import {readFileSync,writeFileSync} from 'node:fs';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createSeed} from '../../shared/seed.mjs';
import {ensureOrderSerials} from '../../shared/domain.mjs';
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../..'),read=p=>readFileSync(join(root,p),'utf8'),safe=s=>s.replace(/<\/script/gi,'<\\/script');
const strip=s=>s.replace(/^import\s+[^\n]*;\s*$/gm,'').replace(/^export\s+/gm,'');
const sources=['shared/plm.mjs','shared/shipping.mjs','shared/domain.mjs','shared/final-master-data.mjs','shared/clean-seed.mjs','web/app.mjs'];
let js=sources.map(p=>'\n// '+p+'\n'+strip(read(p))).join('\n');
js=js.replaceAll('fh-purchase-alpha15-clean-schema7','fh-theme-lab-v1-state').replaceAll('fh-purchase-alpha10-clean-files','fh-theme-lab-v1-files');
// The preview strip supplies the sample-data notice; do not reuse the clean-build seed claim.
js=js.replace(/^function demoStrip\(\)\{.*$/m,"function demoStrip(){return '';}");
// Fresh resets must also use synthetic preview data, never a live endpoint.
js=js.replaceAll('createCleanSeed()','structuredClone(window.FH_PREVIEW_SEED)');
const seed=createSeed('2026-09-12');ensureOrderSerials(seed);
const logo='data:image/png;base64,'+readFileSync(join(root,'web/assets/farming-hub-logo.png')).toString('base64'),template=readFileSync(join(root,'templates/LAE_Item_Master_Upload_Template_v0.1.xlsx')).toString('base64');
const poseManifest=JSON.parse(readFileSync(join(here,'assets/poses.json'),'utf8'));
const poses=Object.fromEntries(Object.entries(poseManifest).map(([name,pose])=>[name,{alt:pose.alt,src:'data:image/png;base64,'+readFileSync(join(here,'assets',pose.file)).toString('base64')}]));
const mascot=poses.welcome.src;
const setup=`window.FH_GUIDE_POSES=${JSON.stringify(poses)};window.FH_MODE='clean';window.FH_LOGO_URL=${JSON.stringify(logo)};window.FH_TEMPLATE_BASE64=${JSON.stringify(template)};window.FH_PREVIEW_SEED=${JSON.stringify(seed)};if(!localStorage.getItem('fh-theme-lab-v1-state')){localStorage.setItem('fh-theme-lab-v1-state',JSON.stringify(window.FH_PREVIEW_SEED));localStorage.setItem('fh-theme-lab-v1-state-user','u-admin');}`;
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Farming Hub - Theme Lab</title><link rel="icon" href="${logo}"><style>${read('web/styles.css')}\n${readFileSync(join(here,'theme.css'),'utf8').replace(/^\uFEFF/,'')}\n${readFileSync(join(here,'support.css'),'utf8')}</style></head><body data-preview-theme="minimal" data-preview-guides="off"><div class="theme-lab" aria-label="Theme preview controls"><div class="theme-lab-title">THEME LAB <span>Local sample data only</span></div><div class="theme-lab-controls"><div class="segmented" aria-label="Compare themes"><button type="button" data-theme="current" aria-pressed="false">Current</button><button type="button" data-theme="minimal" aria-pressed="true">Minimal</button></div><button type="button" class="theme-replay">Replay animation</button><button type="button" class="theme-guide" aria-pressed="false">Show page guides</button></div></div><div id="app"><div class="boot">Loading sample workspace...</div></div><div id="modal-root"></div><div id="toast-root" aria-live="polite"></div><div class="support-dock"><button class="support-launcher" type="button" aria-label="Guide me with Farming Hub" aria-haspopup="dialog" aria-controls="support-tour" aria-expanded="false"><img src="${mascot}" alt=""><span class="support-dock-label"><img src="${logo}" alt=""><span>Guide me</span></span></button></div><dialog id="support-tour" class="support-tour" aria-labelledby="support-title" aria-describedby="support-copy"><div class="support-ring" hidden aria-hidden="true"></div><section class="support-card"><div class="support-top"><div class="support-brand"><img src="${logo}" alt="Farming Hub"><span class="support-name">YOUR PAGE GUIDE</span></div><button type="button" class="support-close" data-support="close" aria-label="Close guide">&times;</button></div><div class="support-intro"><img class="support-mascot" src="${mascot}" alt="Farming Hub elephant mascot"><div aria-live="polite" aria-atomic="true"><p class="support-count"></p><h2 id="support-title"></h2></div></div><p id="support-copy" aria-live="polite"></p><div class="support-actions"><button type="button" class="button" data-support="take">Take me there</button><button type="button" class="button ghost support-skip" data-support="close">Skip tour</button><button type="button" class="button ghost" data-support="back">Back</button><button type="button" class="button primary" data-support="next">Next</button></div></section></dialog><script>${safe(setup)}</script><script>${safe(read('web/jszip.min.js'))}</script><script type="module">${safe(js)}</script><script type="module">${safe(readFileSync(join(here,'theme.mjs'),'utf8'))}</script><script type="module">${safe(readFileSync(join(here,'support.mjs'),'utf8'))}</script></body></html>`;
writeFileSync(join(here,'preview.html.tmp'),html);const {renameSync}=await import('node:fs');renameSync(join(here,'preview.html.tmp'),join(here,'preview.html'));console.log('Built isolated theme preview: '+join(here,'preview.html'));
