/** Local prototype acceptance checks. Does not use .env or production data. */
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
const out=resolve(process.env.FH_TEST_OUTPUT_ROOT||'test-output','theme-preview',new Date().toISOString().replace(/[:.]/g,'-'));mkdirSync(out,{recursive:true});
const {chromium}=await import(pathToFileURL(resolve('test-output/ui-tools/node_modules/playwright/index.mjs')).href),browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),report={checks:[],errors:[],requests:[],out};
await context.tracing.start({screenshots:true,snapshots:true});const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))report.requests.push({url:r.url(),method:r.method()});});
await page.addInitScript(()=>{window.themeAnimations=[];const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){window.themeAnimations.push({duration:options?.duration,element:this.className});return animate.call(this,frames,options);};localStorage.setItem('fh-purchase-alpha15-clean-schema7','normal-review-sentinel');});
const check=(label,ok)=>{assert.ok(ok,label);report.checks.push(label);console.log('PASS '+label);},read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fh-theme-lab-v1-state'))),settle=()=>page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))),shot=async name=>{await settle();await page.screenshot({path:join(out,name+'.png'),fullPage:true});};
try{
 await page.goto('http://127.0.0.1:8137/#/orders');await page.locator('#order-sort').waitFor();await settle();const initial=await read();check('Sample workspace loads eight illustrative orders',initial.orders.length===8);check('Preview has a separate storage key',await page.evaluate(()=>localStorage.getItem('fh-purchase-alpha15-clean-schema7'))==='normal-review-sentinel');check('Minimal theme is initially selected',await page.locator('body').getAttribute('data-preview-theme')==='minimal');
 check('Explanatory page subtitle hidden, heading and actions visible',!(await page.locator('.page-head .subtitle').isVisible())&&await page.getByRole('button',{name:'Create purchase order',exact:true}).isVisible());const minimalText=(await page.locator('#app').innerText()).length;await shot('minimal-pipeline');
 const beforeReplay=await page.evaluate(()=>window.themeAnimations.length);await page.getByRole('button',{name:'Replay animation',exact:true}).click();check('Replay starts visible page motion',await page.evaluate(n=>window.themeAnimations.length>n,beforeReplay));await settle();
 await page.evaluate(()=>{const b=document.querySelector('.theme-replay');b.click();b.click();b.click();});check('Repeated replay replaces motion instead of stacking',await page.locator('main.content').evaluate(e=>e.getAnimations().length)===1);await settle();check('Replay never changes sample data',JSON.stringify(await read())===JSON.stringify(initial));
 check('Show page guides remains visible and enabled in Minimal',await page.getByRole('button',{name:'Show page guides',exact:true}).isVisible()&&await page.getByRole('button',{name:'Show page guides',exact:true}).isEnabled());await page.getByRole('button',{name:'Show page guides',exact:true}).click();check('Guidance is available on demand',await page.locator('.page-head .subtitle').isVisible());await page.getByRole('button',{name:'Hide page guides',exact:true}).click();
 await page.getByRole('button',{name:'Current',exact:true}).click();check('Current theme restores original explanatory text',await page.locator('.page-head .subtitle').isVisible()&&(await page.locator('#app').innerText()).length>minimalText);check('Current comparison disables replay',await page.getByRole('button',{name:'Replay animation',exact:true}).isDisabled());await shot('current-pipeline');await page.getByRole('button',{name:'Minimal',exact:true}).click();check('Theme comparison does not change application data',JSON.stringify(await read())===JSON.stringify(initial));
 await page.locator('#order-sort').selectOption('serial-desc');const rows=await page.locator('tr[data-action=open-order]').evaluateAll(es=>es.map(e=>e.dataset.id));check('Pipeline sorting remains functional',rows[0]===initial.orders.at(-1).id);await page.locator('#order-supplier').selectOption(initial.orders[0].vendorId);check('Supplier filter remains available',await page.locator('#order-supplier').inputValue()===initial.orders[0].vendorId);
 const draft=initial.orders.find(o=>o.status==='DRAFT');await page.goto('http://127.0.0.1:8137/#/order/'+draft.id);await page.locator('.preview-workflow').waitFor();check('Full timeline collapsed while current stage stays visible',!(await page.locator('.preview-workflow').getAttribute('open'))&&await page.locator('.current-stage-card').isVisible());await page.locator('.preview-workflow>summary').focus();await page.keyboard.press('Enter');await settle();check('Keyboard expansion animates workflow content',await page.evaluate(()=>window.themeAnimations.some(a=>String(a.element).includes('progress-track')&&a.duration===220)));check('All original workflow steps can be expanded',await page.locator('.progress-track .step').count()>20&&await page.locator('.progress-track').isVisible());await page.locator('.preview-workflow>summary').click();
 await page.locator('.preview-actions>summary').click();await page.getByRole('button',{name:'Log interaction / correction',exact:true}).click();const dialog=page.getByRole('dialog');check('Working modal keeps required field labels',await dialog.getByLabel(/^Interaction remarks/).getAttribute('required')!==null);await shot('minimal-modal');await dialog.getByRole('button',{name:'Save',exact:true}).click();check('Required field validation still blocks empty submission',(await read()).revision===initial.revision);await dialog.getByLabel(/^Interaction remarks/).fill('Theme preview usability test - local only.');await dialog.getByRole('button',{name:'Save',exact:true}).click();await dialog.waitFor({state:'hidden'});check('Form saves into isolated sample history',(await read()).revision===initial.revision+1&&(await read()).events.some(e=>e.summary?.includes('Theme preview usability test')));await shot('minimal-order');
 await page.goto('http://127.0.0.1:8137/#/orders');await page.locator('[data-order-select="'+draft.id+'"]').check();await page.getByRole('button',{name:'Delete selected (1)',exact:true}).click();check('Deletion warning and explicit confirmation remain visible',await dialog.locator('.note-box.warn').isVisible()&&await dialog.locator('[name=confirm]').isVisible());await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
 for(const view of ['overview','payments','shipments','documents','vendors','items','prices','plm','settings']){await page.locator('.nav-link[data-to="'+view+'"]').click();await page.locator('main h1').waitFor();check(view+' page renders with its functional controls',!!(await page.locator('main h1').innerText()));if(view==='overview')await shot('minimal-overview');}
 await page.getByRole('button',{name:'Manage approval controls',exact:true}).click();check('Approval risk disclosure and all stages remain visible',await dialog.locator('.note-box.warn').isVisible()&&await dialog.locator('fieldset').count()===13);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
 const animations=await page.evaluate(()=>window.themeAnimations);check('Navigation/modal animations are short and actually run',animations.some(a=>String(a.element).includes('modal'))&&animations.some(a=>String(a.element).includes('content'))&&animations.every(a=>a.duration<=280));
 await page.emulateMedia({reducedMotion:'reduce'});check('Reduced motion disables replay',await page.getByRole('button',{name:'Replay animation',exact:true}).isDisabled());const count=await page.evaluate(()=>window.themeAnimations.length);await page.getByRole('button',{name:'Current',exact:true}).click();await page.getByRole('button',{name:'Minimal',exact:true}).click();await page.locator('.nav-link[data-to=orders]').click();await settle();check('Reduced motion disables JS transitions and CSS motion',await page.evaluate(n=>window.themeAnimations.length===n&&getComputedStyle(document.querySelector('.button')).transitionDuration==='0s',count));
 await page.setViewportSize({width:390,height:844});check('Compare controls fit mobile width',(await page.locator('.theme-lab').boundingBox()).width===390);for(const selector of ['#order-sort','#order-supplier']){const b=await page.locator(selector).boundingBox();check(selector+' remains usable on mobile',b.x>=0&&b.x+b.width<=391);}await shot('minimal-mobile');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});check('All preview buttons fit at '+width+'px',await page.locator('.theme-lab button').evaluateAll((buttons,w)=>buttons.every(b=>{const r=b.getBoundingClientRect();return r.left>=0&&r.right<=w&&r.bottom<=document.querySelector('.theme-lab').getBoundingClientRect().bottom;}),width));}
 await page.emulateMedia({reducedMotion:'no-preference'});check('Replay re-enables when reduced motion is off',await page.getByRole('button',{name:'Replay animation',exact:true}).isEnabled());
 check('Preview never calls a live host or business API',report.requests.every(r=>r.url.startsWith('http://127.0.0.1:8137/')&&!r.url.includes('/api/')&&r.method==='GET'));check('No browser runtime errors',report.errors.length===0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e.stack||e);console.error(report.failure);await shot('failure').catch(()=>{});process.exitCode=1;}
finally{await context.tracing.stop({path:join(out,'trace.zip')}).catch(()=>{});await browser.close();writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));console.log('Evidence: '+out);}
