/** Read-only Farming Hub tour acceptance checks in the isolated sample workspace. */
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
const out=resolve(process.env.FH_TEST_OUTPUT_ROOT||'test-output','gaja-guide',new Date().toISOString().replace(/[:.]/g,'-'));mkdirSync(out,{recursive:true});
const {chromium}=await import(pathToFileURL(resolve('test-output/ui-tools/node_modules/playwright/index.mjs')).href);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),report={checks:[],errors:[],requests:[],out};
page.setDefaultTimeout(12000);page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(r.url().startsWith('http'))report.requests.push({url:r.url(),method:r.method()});});await context.tracing.start({screenshots:true,snapshots:true});
const check=(name,ok)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS '+name);},tour=page.locator('.support-tour'),launch=page.getByRole('button',{name:'Guide me with Farming Hub'}),next=tour.getByRole('button',{name:'Next',exact:true}),read=()=>page.evaluate(()=>localStorage.getItem('fh-theme-lab-v1-state')),settle=()=>page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))),shot=async name=>{await settle();await page.screenshot({path:join(out,name+'.png')});};
try{
 await page.goto('http://127.0.0.1:8137/#/orders');await launch.waitFor();const initial=await read();check('Guide is opt-in, not an automatic interruption',!await tour.isVisible());
 await launch.click();await settle();check('Mascot stays visible and clickable during the tour',await launch.isVisible()&&await launch.evaluate(e=>!!e.closest('dialog[open]')));check('Farming Hub mascot loads in the guide',await tour.locator('.support-mascot').evaluate(i=>i.complete&&i.naturalWidth>0));check('First guide step uses the welcoming wave',await tour.locator('.support-mascot').getAttribute('data-pose')==='welcome');check('Launcher uses the green welcome asset',await launch.locator('img').first().evaluate(i=>i.src===window.FH_GUIDE_POSES.welcome.src));check('Three distinct pose assets are bundled',await page.evaluate(()=>Object.keys(window.FH_GUIDE_POSES).length===3&&new Set(Object.values(window.FH_GUIDE_POSES).map(p=>p.src)).size===3));check('Guide header uses the approved Farming Hub logo',await tour.locator('.support-brand img').evaluate(i=>i.complete&&i.naturalWidth>0&&i.src===document.querySelector('.brand-logo').src));check('No old mascot name in guide text or image alternatives',await tour.evaluate(d=>!(/gaja/i.test(d.innerText+' '+[...d.querySelectorAll('[alt]')].map(e=>e.alt).join(' ')))));check('Pipeline starts with seven contextual steps',await tour.locator('.support-count').textContent()==='Step 1 of 7');check('First step cannot go back',await tour.getByRole('button',{name:'Back',exact:true}).isDisabled());await shot('gaja-desktop-intro');
 await next.click();await tour.locator('.support-mascot').evaluate(i=>i.decode());check('Explanations switch to the pointing pose',await tour.locator('.support-mascot').getAttribute('data-pose')==='pointing');check('Next explains search and highlights its control',(await tour.locator('h2').innerText()).includes('Find an order')&&await tour.locator('.support-ring').isVisible());await next.click();check('Supplier explanation is contextual',(await tour.locator('h2').innerText()).includes('Choose a supplier'));await shot('gaja-desktop-supplier');
 await tour.getByRole('button',{name:'Back',exact:true}).click();check('Back returns to the previous step',await tour.locator('.support-count').textContent()==='Step 2 of 7');
 for(let i=0;i<12;i++){await page.keyboard.press('Tab');check('Keyboard focus remains inside guide '+(i+1),await tour.evaluate(d=>d.contains(document.activeElement)));}
 await page.keyboard.press('Escape');check('Escape closes and returns focus',!await tour.isVisible()&&await launch.evaluate(e=>e===document.activeElement));await launch.click();check('Reopen restarts the page guide',await tour.locator('.support-count').textContent()==='Step 1 of 7');check('Reopening restores the welcome pose',await tour.locator('.support-mascot').getAttribute('data-pose')==='welcome');await tour.getByRole('button',{name:'Skip tour',exact:true}).click();check('Skip closes immediately',!await tour.isVisible());
 await launch.click();while(await next.count()){if(!await next.isVisible())break;await next.click();}await tour.locator('.support-mascot').evaluate(i=>i.decode());check('Final step uses thumbs-up without changing order status',await tour.locator('.support-mascot').getAttribute('data-pose')==='ready'&&await read()===initial);await shot('gaja-final-pose');await tour.getByRole('button',{name:'Finish',exact:true}).click();check('Finish exits the complete tour',!await tour.isVisible());check('Full tour leaves purchase state unchanged',await read()===initial);
 await page.getByRole('button',{name:'Current',exact:true}).click();await launch.click();check('Guide also works in Current comparison',await tour.isVisible());await page.keyboard.press('Escape');await page.getByRole('button',{name:'Minimal',exact:true}).click();
 const state=JSON.parse(initial),draft=state.orders.find(o=>o.status==='DRAFT');await page.goto('http://127.0.0.1:8137/#/order/'+draft.id);await page.locator('.preview-workflow').waitFor();await launch.click();check('Order guidance starts with the actual next action',(await tour.locator('h2').innerText()).includes('Submit for approval'));await tour.getByRole('button',{name:'Take me there',exact:true}).click();check('Take me there focuses without submitting',await page.locator('[data-action=submit-po]').evaluate(e=>e===document.activeElement)&&await read()===initial);await launch.click();await next.click();check('Order guide explains actual current-stage checks',(await tour.locator('#support-copy').innerText()).includes('configured controls'));await shot('gaja-order-stage');await page.keyboard.press('Escape');
 await page.locator('.preview-actions>summary').click();await page.getByRole('button',{name:'Log interaction / correction',exact:true}).click();check('Mascot stays available while a business form is open',await launch.isVisible());await launch.click();check('Form guide identifies the missing required field',(await tour.locator('h2').innerText()).includes('Interaction remarks'));await shot('guide-required-field');await tour.getByRole('button',{name:'Take me there',exact:true}).click();const remarks=page.locator('#modal-root').getByLabel(/^Interaction remarks/);check('Take me there focuses the actual form field',await remarks.evaluate(e=>e===document.activeElement));await remarks.fill('Unsaved local draft must remain here.');await launch.click();await page.keyboard.press('Escape');check('Closing guidance keeps the form and unsaved input',await page.locator('#modal-root .modal').isVisible()&&await remarks.inputValue()==='Unsaved local draft must remain here.');await page.locator('#modal-root').getByRole('button',{name:'Cancel',exact:true}).click();await launch.waitFor();check('Launcher returns after the form closes',await launch.isVisible());
 for(const route of ['overview','tasks','payments','shipments','documents','vendors','items','prices','plm','settings','versions']){await page.goto('http://127.0.0.1:8137/#/'+route);await launch.waitFor();await launch.click();check(route+' has a usable page tour',await tour.isVisible()&&!!await tour.locator('h2').innerText());await page.keyboard.press('Escape');}
 await page.goto('http://127.0.0.1:8137/#/orders');await launch.click();await page.evaluate(()=>location.hash='#/overview');await tour.waitFor({state:'hidden'});check('Route changes dismiss stale guidance',!await tour.isVisible());
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.goto('http://127.0.0.1:8137/#/orders');await launch.click();await next.click();await next.click();await settle();const b=await tour.locator('.support-card').boundingBox();check('Guide fits '+width+'px viewport',b.x>=0&&b.x+b.width<=width&&b.y>=0&&b.y+b.height<=844);check('Guide actions visible at '+width+'px',await tour.getByRole('button',{name:'Skip tour',exact:true}).isVisible()&&await next.isVisible());check('Persistent dock fits the mobile viewport '+width,await launch.evaluate(e=>{const b=e.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth&&b.bottom<=innerHeight;}));await shot('gaja-mobile-'+width);await page.keyboard.press('Escape');}
 await page.emulateMedia({reducedMotion:'reduce'});await launch.click();await next.click();check('Reduced motion prevents guide animation',await tour.locator('.support-card').evaluate(e=>e.getAnimations().length===0));await page.keyboard.press('Escape');
 await page.setViewportSize({width:1440,height:1000});const viewer=state.users.find(u=>u.role==='VIEWER');assert.ok(viewer);await page.locator('#demo-role').selectOption(viewer.id);await launch.click();check('Viewer tour omits unavailable create action',!(await tour.innerText()).includes('Create when'));const titles=[];for(let i=0;i<12;i++){titles.push(await tour.locator('h2').innerText());if(await tour.getByRole('button',{name:'Finish',exact:true}).isVisible())break;await next.click();}check('No create instruction anywhere in Viewer tour',!titles.some(t=>t.includes('Create when')));await page.keyboard.press('Escape');
 check('All tours leave saved purchase data unchanged',await read()===initial);check('No runtime errors',report.errors.length===0);check('No live host or business writes',report.requests.every(r=>r.url.startsWith('http://127.0.0.1:8137/')&&!r.url.includes('/api/')&&r.method==='GET'));report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e.stack||e);console.error(report.failure);await shot('failure').catch(()=>{});process.exitCode=1;}
finally{await context.tracing.stop({path:join(out,'trace.zip')}).catch(()=>{});await browser.close();writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));console.log('Evidence: '+out);}
