import test from 'node:test';
import assert from 'node:assert/strict';
import {createSeed} from '../shared/seed.mjs';
import {execute,toMinor,toRate,major} from '../shared/domain.mjs';
import {ARRIVAL_COST_FIELDS,arrivalCostCalculation,arrivalCostingStatus,arrivalInvoiceOptions} from '../shared/arrival-costing.mjs';
import {softwareReference} from '../shared/references.mjs';
const baseline=createSeed('2026-09-11'),now='2026-09-17T12:00:00Z';
function setup(){const state=structuredClone(baseline),o=state.orders.find(o=>o.shipments.some(s=>s.actualArrival)),s=o.shipments.find(s=>s.actualArrival),actor=state.users.find(u=>u.role==='MANAGER'),file=state.files.find(f=>f.orderIds.includes(o.id));const doc=arrivalInvoiceOptions(o,s.id)[0];assert.ok(doc);const lines=s.lines.map(l=>({lineId:l.lineId,quantity:l.quantity,unitPrice:major(o.lines.find(x=>x.id===l.lineId).unitPriceMinor)})),invoiceAmount=major(lines.reduce((n,l)=>n+l.quantity*toMinor(l.unitPrice),0)),payload={orderId:o.id,shipmentId:s.id,invoiceNumber:doc.invoiceNumber,invoiceAmount,boeNumber:'BOE-COST-001',boeDate:'2026-09-11',currencyPerUsd:'7.2',fxDate:'2026-09-11',fxSource:'Supplier invoice agreement',lines,costs:Object.fromEntries(ARRIVAL_COST_FIELDS.map(([k])=>[k,k==='supplierPayment'?'10000':'100'])),gst:'500',boeTotals:{bcd:'100',sws:'100',gst:'500'},boeFileIds:[file.id],supportFileIds:[file.id],allocationNote:'Actual remittance and shipment bills, allocated once to this invoice.'};return {state,o,s,actor,payload,run:(type,p=payload,who=actor,input=state)=>execute(input,{type,payload:p},who,{now})};}
const get=(out,oid)=>out.state.orders.find(o=>o.id===oid).arrivalCostings.at(-1);
test('worksheet method sums nine costs and excludes GST using synthetic values',()=>{const values=['85000','7500','750','2000','500','1000','250','1500','1500'],costs=Object.fromEntries(ARRIVAL_COST_FIELDS.map(([k],i)=>[k,toMinor(values[i])])),c={currencyPerUsd:toRate('1'),costs,gstMinor:toMinor('18000'),lines:[{quantity:10,unitPriceMinor:toMinor('100')}]},r=arrivalCostCalculation(c);assert.equal(r.totalMinor,10000000);assert.equal(r.invoiceUsdMinor,100000);assert.equal(r.costPerUsd,100000000);assert.equal(r.lines[0].landedMinor,r.totalMinor);});
test('allocation conserves paise with multiple quantities; RMB is explicitly converted to USD',()=>{const c={currencyPerUsd:toRate('7.2'),costs:Object.fromEntries(ARRIVAL_COST_FIELDS.map(([k],i)=>[k,i?0:10001])),lines:[{quantity:3,unitPriceMinor:7200},{quantity:7,unitPriceMinor:14400}]},r=arrivalCostCalculation(c);assert.equal(r.invoiceUsdMinor,17000);assert.equal(r.lines.reduce((n,l)=>n+l.landedMinor,0),10001);assert.equal(r.lines.reduce((n,l)=>n+l.usdMinor,0),17000);assert.equal(r.lines[0].landedMinor,1765);});
test('unknown cost remains pending and zero denominator / overflow fail visibly',()=>{const c={currencyPerUsd:1000000,costs:Object.fromEntries(ARRIVAL_COST_FIELDS.map(([k])=>[k,0])),lines:[{quantity:1,unitPriceMinor:100}]};c.costs.insurance=null;assert.equal(arrivalCostCalculation(c).totalMinor,null);assert.deepEqual(arrivalCostCalculation(c).missing,['Insurance']);assert.throws(()=>arrivalCostCalculation({...c,lines:[{quantity:1,unitPriceMinor:0}]}),/positive/);assert.throws(()=>arrivalCostCalculation({...c,lines:[{quantity:2,unitPriceMinor:Number.MAX_SAFE_INTEGER}]}),/precision/);});
test('arrival saves get permanent references and immutable final snapshots survive correction',()=>{const f=setup(),out=f.run('SAVE_ARRIVAL_COSTING'),c=get(out,f.o.id);assert.equal(c.status,'PROVISIONAL');assert.match(softwareReference(out.state,'arrivalCostings',c.id,'orders',f.o.id),/^FH-LC-/);assert.throws(()=>f.run('FINALIZE_ARRIVAL_COSTING',{orderId:f.o.id,costingId:c.id},f.actor,out.state),/Confirm/);const final=f.run('FINALIZE_ARRIVAL_COSTING',{orderId:f.o.id,costingId:c.id,confirmActuals:true},f.actor,out.state),frozen=get(final,f.o.id);assert.equal(frozen.status,'FINAL');assert.throws(()=>f.run('SAVE_ARRIVAL_COSTING',{...f.payload,costingId:c.id},f.actor,final.state),/Reopen/);const reopened=f.run('REOPEN_ARRIVAL_COSTING',{orderId:f.o.id,costingId:c.id,reason:'Correct bill amount'},f.actor,final.state);assert.equal(get(reopened,f.o.id).history[0].calculation.totalMinor,frozen.calculation.totalMinor);assert.equal(get(reopened,f.o.id).status,'PROVISIONAL');assert.equal(reopened.state.orders.find(o=>o.id===f.o.id).costingCompletedAt,undefined);});
test('costing never changes issued PO, payments or existing cost register',()=>{const f=setup(),before=structuredClone(f.state),out=f.run('SAVE_ARRIVAL_COSTING');for(const k of ['payments','costs','items','vendors'])assert.deepEqual(out.state[k],before[k]);assert.deepEqual(out.state.orders.find(o=>o.id===f.o.id).revisions,f.o.revisions);});
test('arrival, invoice identity, order evidence, invoice total and shipment quantities are enforced',()=>{for(const mutate of [p=>p.shipmentId='wrong',p=>p.invoiceNumber='unknown',p=>p.boeFileIds=['missing'],p=>p.invoiceAmount='1',p=>p.lines[0].quantity+=1,p=>p.lines.push(p.lines[0]),p=>p.boeDate='2026-02-30',p=>p.boeDate='2099-01-01']){const f=setup();mutate(f.payload);assert.throws(()=>f.run('SAVE_ARRIVAL_COSTING'));}const f=setup();f.s.actualArrival=null;assert.throws(()=>f.run('SAVE_ARRIVAL_COSTING'),/arrival/);});
test('duplicate invoice costings and shared BOE overallocations cannot be saved',()=>{const f=setup(),out=f.run('SAVE_ARRIVAL_COSTING');assert.throws(()=>f.run('SAVE_ARRIVAL_COSTING',f.payload,f.actor,out.state),/already has/);const second=structuredClone(out.state),o=second.orders.find(o=>o.id===f.o.id),s=o.shipments.find(s=>s.id===f.s.id),existing=o.arrivalCostings[0];existing.lines[0].quantity=1;o.documents.push({...arrivalInvoiceOptions(o,s.id)[0],id:'new-ci-id',invoiceNumber:'SECOND-CI'});const p={...f.payload,invoiceNumber:'SECOND-CI',lines:[{...f.payload.lines[0],quantity:1}],invoiceAmount:f.payload.lines[0].unitPrice};assert.throws(()=>f.run('SAVE_ARRIVAL_COSTING',p,f.actor,second),/exceeds the Bill/);});
test('only actual complete evidence-backed costs can finalize; approver controls and scope remain authoritative',()=>{const f=setup(),out=f.run('SAVE_ARRIVAL_COSTING'),c=get(out,f.o.id),p={orderId:f.o.id,costingId:c.id,confirmActuals:true};for(const change of [x=>x.costs.insurance=null,x=>x.supportFileIds=[],x=>x.boeTotals.gst=null,x=>x.allocationNote='']){const s=structuredClone(out.state);change(s.orders.find(o=>o.id===f.o.id).arrivalCostings[0]);assert.throws(()=>f.run('FINALIZE_ARRIVAL_COSTING',p,f.actor,s));}for(const actor of [{...f.actor,role:'VIEWER'},{...f.actor,role:'EXECUTIVE'},{...f.actor,scopes:[]}])assert.throws(()=>f.run('FINALIZE_ARRIVAL_COSTING',p,actor,out.state));const s=structuredClone(out.state);s.approvalControls={stages:{FINALIZE_ARRIVAL_COSTING:[]}};assert.throws(()=>f.run('FINALIZE_ARRIVAL_COSTING',p,f.actor,s),/approver/);});
test('final stage requires every invoice and complete shipment quantity coverage',()=>{const f=setup();assert.equal(arrivalCostingStatus(f.o).complete,false);const o={lines:[{id:'line',quantity:2}],shipments:[{id:'s',number:'S1',status:'ARRIVED',actualArrival:'2026-09-11',lines:[{lineId:'line',quantity:2}]}],documents:[{type:'COMMERCIAL_INVOICE',shipmentId:'s',invoiceNumber:'CI1'}],arrivalCostings:[{shipmentId:'s',invoiceKey:'CI1',status:'FINAL',lines:[{lineId:'line',quantity:2}]}]};assert.equal(arrivalCostingStatus(o).complete,true);o.arrivalCostings[0].lines[0].quantity=1;assert.equal(arrivalCostingStatus(o).complete,false);});
