import test from 'node:test';
import assert from 'node:assert/strict';
import {createSeed} from '../shared/seed.mjs';
import {execute} from '../shared/domain.mjs';
import {ensureRecordReferences,softwareReference,preserveRecordReferences,referenceKey,integrationSnapshot} from '../shared/references.mjs';

const baseline=createSeed('2026-09-11');
function fixture(){const state=structuredClone(baseline),actor=state.users.find(u=>u.role==='ADMIN'),o=state.orders[0];return {state,actor,command:{type:'CREATE_ORDER',payload:{vendorId:o.vendorId,lines:o.lines,currency:o.currency,priceListCurrency:o.priceListCurrency,productionDays:o.productionDays,productionOverrideReason:'Test supplier commitment'}}};}
const created=out=>out.state.orders.find(o=>o.id===out.result.id);

test('new PO uses its reference and ignores client-supplied numbers and counters',()=>{const f=fixture(),before=structuredClone(f.state),out=execute(f.state,{...f.command,payload:{...f.command.payload,number:'MANUAL-OVERRIDE',serialNumber:1,reference:'FAKE',numberSource:'MANUAL'}},f.actor),o=created(out);assert.equal(o.number,softwareReference(out.state,'orders',o.id));assert.match(o.number,/^FH-LAE-I-PO-[1-9][0-9]*$/);assert.equal(o.numberSource,'SOFTWARE_REFERENCE');assert.deepEqual(f.state,before);assert.equal(integrationSnapshot(out.state).records.find(r=>r.type==='orders'&&r.id===o.id).data.number,o.number);});
test('automatic PO cannot be edited, stripped of its policy or rebound after registry loss',()=>{const f=fixture(),out=execute(f.state,f.command,f.actor),o=created(out);assert.throws(()=>execute(out.state,{type:'EDIT_DRAFT',payload:{orderId:o.id,number:'MANUAL'}},f.actor),/cannot be changed/);const edited=execute(out.state,{type:'EDIT_DRAFT',payload:{orderId:o.id,notes:'Updated notes'}},f.actor);assert.equal(edited.state.orders.find(r=>r.id===o.id).number,o.number);for(const mutate of [n=>n.orders.find(r=>r.id===o.id).number='OTHER',n=>delete n.orders.find(r=>r.id===o.id).numberSource]){const next=structuredClone(out.state);mutate(next);assert.throws(()=>preserveRecordReferences(out.state,next),/cannot change/);}const lost=structuredClone(out.state);delete lost.recordReferences.entries[referenceKey('orders',o.id)];assert.throws(()=>ensureRecordReferences(lost),/restore its registry/);});
test('allocator skips normalized legacy current and historical numbers without rewriting history',()=>{const f=fixture(),legacy=f.state.orders[0],n=f.state.recordReferences.next.orders;delete legacy.numberSource;legacy.number='fh-lae-i-po- '+n;legacy.numberHistory=['FH-LAE-I-PO-'+(n+1)];legacy.revisions[0].snapshot.number='FH-LAE-I-PO-'+(n+2);legacy.deletedAt='2026-09-13';const before=structuredClone(legacy),out=execute(f.state,f.command,f.actor);assert.equal(created(out).number,'FH-LAE-I-PO-'+(n+3));assert.deepEqual(out.state.orders.find(o=>o.id===legacy.id),before);});
test('deletion and display-serial reset do not reuse automatic PO references',()=>{const f=fixture(),first=execute(f.state,f.command,f.actor),o=created(first),removed=execute(first.state,{type:'DELETE_ORDERS',payload:{orderIds:[o.id],remarks:'Synthetic deletion'}},f.actor);removed.state.nextOrderSerial=1;const second=execute(removed.state,f.command,f.actor);assert.notEqual(created(second).number,o.number);assert.equal(softwareReference(second.state,'orders',o.id),o.number);});
test('failed creation consumes no number; old saved drafts remain fixed and blank drafts acquire their existing reference',()=>{const f=fixture(),before=structuredClone(f.state.recordReferences);assert.throws(()=>execute(f.state,{...f.command,payload:{...f.command.payload,lines:[]}},f.actor));assert.deepEqual(f.state.recordReferences,before);const legacy=f.state.orders[0];delete legacy.numberSource;legacy.status='DRAFT';legacy.revisions=[];legacy.number='HISTORICAL-PO';let out=execute(f.state,{type:'EDIT_DRAFT',payload:{orderId:legacy.id,notes:'Updated legacy draft'}},f.actor);assert.equal(out.state.orders[0].number,'HISTORICAL-PO');legacy.number='';out=execute(f.state,{type:'EDIT_DRAFT',payload:{orderId:legacy.id,notes:'Complete blank draft'}},f.actor);assert.equal(out.state.orders[0].number,softwareReference(out.state,'orders',legacy.id));});
