import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Store} from '../server/store.mjs';import {EditVersions} from '../server/concurrency.mjs';import {createSeed} from '../shared/seed.mjs';import {TERMS} from '../shared/domain.mjs';
const fixture=()=>{const store=new Store(join(mkdtempSync(join(tmpdir(),'fh-concurrent-')),'db.sqlite'),createSeed('2026-09-11'));return {store,state:store.read(),close:()=>store.close()};};
const context=(f,id)=>({expected:f.state.revision,token:f.store.editContext(f.state,id)});
const task=(id,title)=>({type:'ADD_FOLLOWUP',payload:{orderId:id,title,due:'2026-10-20'}});
const send=(f,id,c,command,key)=>f.store.transact(command,id,c.expected,key,c.token);
const conflict=fn=>assert.throws(fn,e=>e.code==='CONFLICT');

test('compact saved views are bounded, shared safely, expire and fail closed after eviction',()=>{
 const state=createSeed('2026-09-11');let now=100;const versions=new EditVersions({maxContexts:2,ttlMs:100,clock:()=>now});
 const first=versions.issue(state,'u-admin'),bytes=versions.bytes,second=versions.issue(structuredClone(state),'u-manager');assert.equal(first.length,43);assert.equal(second.length,43);assert.equal(versions.snapshots.size,1);assert.equal(versions.bytes,bytes);
 versions.assert(state,{type:'SAVE_PERSONAL_PREFERENCES'},'u-admin',state.revision,first);versions.issue(state,'u-admin');conflict(()=>versions.read(first,'u-admin',state.revision));assert.ok(versions.read(second,'u-manager',state.revision));now=200;conflict(()=>versions.read(second,'u-manager',state.revision));
 versions.issue(state,'u-admin');assert.equal(versions.contexts.size,1);assert.equal(versions.bytes,bytes);
 const tiny=new EditVersions({maxBytes:1});assert.equal(tiny.issue(state,'u-admin'),null);assert.equal(tiny.bytes,0);const changed={...state,revision:state.revision+1};conflict(()=>tiny.assert(changed,{type:'SAVE_PERSONAL_PREFERENCES'},'u-admin',state.revision,null));
 const bounded=new EditVersions({maxBytes:bytes+100});bounded.issue(state,'u-admin');const modified=structuredClone(state);modified.revision++;modified.orders[0].number+=' modified';bounded.issue(modified,'u-admin');assert.ok(bounded.bytes<=bytes+100);assert.equal(bounded.contexts.size,1);
});

test('two users save different orders from the same original view without losing either change',()=>{const f=fixture();try{const a=context(f,'u-admin'),b=context(f,'u-manager'),[one,two]=f.state.orders;send(f,'u-admin',a,task(one.id,'First user'));send(f,'u-manager',b,task(two.id,'Second user'));const saved=f.store.read();assert.ok(saved.orders.find(o=>o.id===one.id).tasks.some(t=>t.title==='First user'));assert.ok(saved.orders.find(o=>o.id===two.id).tasks.some(t=>t.title==='Second user'));assert.deepEqual(saved.events.slice(0,f.state.events.length),f.state.events);}finally{f.close();}});
test('same-order concurrent writes remain blocked and require a fresh explicitly reviewed view',()=>{const f=fixture();try{const a=context(f,'u-admin'),b=context(f,'u-manager'),id=f.state.orders[0].id;send(f,'u-admin',a,task(id,'First'));const before=f.store.read();conflict(()=>send(f,'u-manager',b,task(id,'Stale')));assert.deepEqual(f.store.read(),before);const fresh={expected:before.revision,token:f.store.editContext(before,'u-manager')};send(f,'u-manager',fresh,task(id,'Reviewed'));assert.ok(f.store.read().orders[0].tasks.some(t=>t.title==='Reviewed'));}finally{f.close();}});
test('evidence upload does not invalidate its own form and cannot refresh away another user conflict',()=>{const f=fixture();try{const a=context(f,'u-admin'),b=context(f,'u-manager'),id=f.state.orders[0].id,actor=f.state.users.find(u=>u.id==='u-manager');send(f,'u-admin',a,task(id,'Concurrent change'));const next=f.store.saveFile({id:'new-proof',name:'proof.txt',orderIds:[id],scope:'LAE_IMPORT'},Buffer.from('proof'),b.expected,actor,'upload-concurrent-1234',b.token);assert.ok(next.files.some(x=>x.id==='new-proof'));conflict(()=>send(f,'u-manager',b,task(id,'Old form')));const other=f.state.orders[1].id;send(f,'u-manager',b,task(other,'Independent form after upload'));}finally{f.close();}});
test('retries return original result without duplicate work even after other users save',()=>{const f=fixture();try{const a=context(f,'u-admin'),b=context(f,'u-manager'),[one,two]=f.state.orders,cmd=task(one.id,'Once');send(f,'u-admin',a,cmd,'concurrent-retry-1234');send(f,'u-manager',b,task(two.id,'Other'));const again=send(f,'u-admin',a,cmd,'concurrent-retry-1234');assert.ok(again.replayed);assert.equal(again.state.orders[0].tasks.filter(x=>x.title==='Once').length,1);}finally{f.close();}});
test('untrusted, wrong-user, mismatched and restarted-server versions fail closed',()=>{const f=fixture();try{const a=context(f,'u-admin'),id=f.state.orders[0].id;conflict(()=>send(f,'u-manager',a,task(id,'Forged actor')));conflict(()=>send(f,'u-admin',{...a,token:a.token.slice(0,-8)+'12345678'},task(id,'Tampered')));conflict(()=>send(f,'u-admin',{...a,expected:a.expected+1},task(id,'Bad revision')));f.store.editVersions=new EditVersions();conflict(()=>send(f,'u-admin',a,task(id,'Restarted')));}finally{f.close();}});
test('changes to supplier dependencies, approval policies and account access do not bypass review',()=>{const f=fixture();try{const b=context(f,'u-manager'),current=f.store.read();current.vendors.find(v=>v.id===current.orders[0].vendorId).name+=' changed';current.revision++;f.store.db.prepare('UPDATE workspace SET payload=?,revision=?').run(JSON.stringify(current),current.revision);conflict(()=>send(f,'u-manager',b,task(current.orders[0].id,'Stale supplier')));current.users.find(u=>u.id==='u-manager').role='VIEWER';current.revision++;f.store.db.prepare('UPDATE workspace SET payload=?,revision=?').run(JSON.stringify(current),current.revision);conflict(()=>send(f,'u-manager',b,task(current.orders[1].id,'Stale access')));}finally{f.close();}});
test('vendor-specific changes permit independent suppliers and reject same supplier',()=>{const f=fixture();try{const a=context(f,'u-admin'),b=context(f,'u-manager'),ids=f.state.vendors.slice(0,2).map(v=>v.id);const cmd=id=>({type:'VMS_SAVE_EVALUATION',payload:{vendorId:id,scores:{},remarks:'Concurrent evaluation'}});send(f,'u-admin',a,cmd(ids[0]));send(f,'u-manager',b,cmd(ids[1]));conflict(()=>send(f,'u-manager',b,cmd(ids[0])));}finally{f.close();}});
test('personal settings are independent between users, global administration remains conservative',()=>{const f=fixture();try{const a=context(f,'u-admin'),b=context(f,'u-manager');send(f,'u-admin',a,{type:'SAVE_PERSONAL_PREFERENCES',payload:{showPageGuides:true}});send(f,'u-manager',b,{type:'SAVE_PERSONAL_PREFERENCES',payload:{showPageGuides:true}});conflict(()=>send(f,'u-admin',a,{type:'ADD_CATEGORY',payload:{name:'OLD-CATALOG'}}));assert.equal(f.store.read().users.filter(u=>u.preferences?.showPageGuides).length,2);}finally{f.close();}});
test('legacy clients retain strict revision checking',()=>{const f=fixture();try{const a=context(f,'u-admin');send(f,'u-admin',a,task(f.state.orders[0].id,'First'));conflict(()=>f.store.transact(task(f.state.orders[1].id,'Legacy'),'u-manager',a.expected));}finally{f.close();}});
test('simultaneous new orders receive unique references and serials from the latest transaction',()=>{const f=fixture();try{const a=context(f,'u-admin'),b=context(f,'u-manager'),item=f.state.items.find(i=>i.code==='GJPW12'),base=f.state.bases.find(x=>x.id===item.baseId);const cmd={type:'CREATE_ORDER',payload:{vendorId:base.vendorId,currency:'USD',paymentTerms:TERMS[0],productionDays:30,productionOverrideReason:'Synthetic order commitment',planningTat:60,routeId:f.state.routes[0].id,requestedPortDate:'2026-12-20',lines:[{itemId:item.id,quantity:10,unitPrice:'100.00',specId:base.specifications[0].id}]}};const x=send(f,'u-admin',a,cmd).result.id,y=send(f,'u-manager',b,cmd).result.id,orders=f.store.read().orders.filter(o=>[x,y].includes(o.id));assert.equal(new Set(orders.map(o=>o.number)).size,2);assert.equal(new Set(orders.map(o=>o.serialNumber)).size,2);assert.ok(orders.every(o=>o.number.startsWith('FH-LAE-I-PO-')));}finally{f.close();}});
test('a payment change on a target order is a conflict even when its order object is unchanged',()=>{const f=fixture();try{const b=context(f,'u-manager'),current=f.store.read(),payment=current.payments.find(p=>p.allocations.length),id=payment.allocations[0].orderId;payment.amountMinor+=1;current.revision++;f.store.db.prepare('UPDATE workspace SET payload=?,revision=?').run(JSON.stringify(current),current.revision);conflict(()=>send(f,'u-manager',b,task(id,'Stale financial context')));send(f,'u-manager',b,task(current.orders.find(o=>!payment.allocations.some(a=>a.orderId===o.id)).id,'Unrelated order'));}finally{f.close();}});
