import test from 'node:test';
import assert from 'node:assert/strict';
import {createSeed} from '../shared/seed.mjs';
import {APPROVAL_STAGES,approvalRoles,APPROVAL_ROLES,canPerformApproval,canApprove,canProductApprove,canEdit,execute,TERMS,orderTotal,orderStatus,financials,paymentSchedule,flagsFor,shipmentTotals,proportionalSlices,toMinor,toRate,convertMinor,previewImport,major,currentApprovedPrice,priceVarianceForLine} from '../shared/domain.mjs';
import {previewTrackingImport,previewRateImport,rateVariance,freightTrendFor,shippingDocReadiness} from '../shared/shipping.mjs';
const TODAY='2026-09-11';

test('admin bulk deletion retains financials, evidence, snapshots and original serials; restoration resumes the same order',()=>{
 const f=fixture(),a=f.draft(),b=f.draft();f.issue(a);f.commercial(a);f.pay(a);const original=structuredClone(f.state),numbers=[f.get(a).serialNumber,f.get(b).serialNumber],finance=financials(f.state,f.get(a));
 f.run('DELETE_ORDERS',{orderIds:[a,b],remarks:'Remove test orders'},f.role('ADMIN'));
 assert.ok(f.get(a).deletedAt&&f.get(b).deletedAt);assert.deepEqual(financials(f.state,f.get(a)),finance);assert.deepEqual(f.state.payments,original.payments);assert.deepEqual(f.state.files,original.files);assert.deepEqual(f.get(a).revisions,original.orders.find(o=>o.id===a).revisions);assert.deepEqual(f.state.events.slice(0,original.events.length),original.events);
 assert.deepEqual([f.get(a).serialNumber,f.get(b).serialNumber],numbers);assert.equal(canEdit(f.role('ADMIN'),f.get(a)),false);
 for(const type of ['ADD_NOTE','APPROVE_PI','AUTHORIZE_PAYMENT'])assert.throws(()=>f.run(type,{orderId:a,remarks:'Blocked'},f.role('ADMIN')),/deleted/i);
 assert.throws(()=>f.run('VOID_PAYMENT',{paymentId:f.state.payments[0].id,remarks:'Blocked'},f.role('ADMIN')),/deleted/i);
 const c=f.draft({serialNumber:1});assert.ok(f.get(c).serialNumber>Math.max(...numbers));
 f.run('RESTORE_ORDERS',{orderIds:[a,b],remarks:'Resume tests'},f.role('ADMIN'));assert.equal(f.get(a).deletedAt,undefined);assert.equal(f.get(a).serialNumber,numbers[0]);assert.deepEqual(financials(f.state,f.get(a)),finance);f.run('ADD_NOTE',{orderId:a,remarks:'Restored order can resume'});
});

test('bulk delete/restore enforces admin, bounded selection, reason and atomic validation',()=>{
 const f=fixture(),a=f.draft(),b=f.draft(),before=structuredClone(f.state),admin=f.role('ADMIN');
 for(const role of ['MANAGER','EXECUTIVE','PRODUCT_MANAGER','VIEWER'])for(const type of ['DELETE_ORDERS','RESTORE_ORDERS'])assert.throws(()=>f.run(type,{orderIds:[a],remarks:'Attempt'},f.role(role)),e=>e.code==='FORBIDDEN');
 for(const payload of [{orderIds:[],remarks:'x'},{orderIds:[a,a],remarks:'x'},{orderIds:[a,'missing'],remarks:'x'},{orderIds:[a],remarks:''},{orderIds:Array(201).fill(a),remarks:'x'}])assert.throws(()=>f.run('DELETE_ORDERS',payload,admin));
 assert.deepEqual(f.state,before);f.run('DELETE_ORDERS',{orderIds:[a],remarks:'Test'},admin);const deleted=structuredClone(f.state);assert.throws(()=>f.run('DELETE_ORDERS',{orderIds:[b,a],remarks:'Mixed'},admin));assert.throws(()=>f.run('RESTORE_ORDERS',{orderIds:[a,b],remarks:'Mixed'},admin));assert.deepEqual(f.state,deleted);
 const ref=f.get(a).number;assert.throws(()=>f.draft({number:ref}),/already exists/i);
});

test('approval roles remain authoritative with no date-based executive delegation',()=>{
 const f=fixture(),u=f.role('EXECUTIVE');for(const [command,role] of Object.entries(APPROVAL_ROLES)){for(const now of ['2026-09-12T10:00:00Z','2026-09-30T18:29:59Z','2026-10-01T00:00:00Z'])assert.equal(canPerformApproval(u,command,'LAE_IMPORT',now),false);assert.equal(canPerformApproval(f.role(role),command),true);assert.equal(canPerformApproval(f.role('ADMIN'),command),true);assert.equal(canPerformApproval(f.role('VIEWER'),command),false);assert.equal(canPerformApproval({...f.role(role),scopes:[]},command),false);}
 const oid=f.draft();f.run('SUBMIT_ORDER',{orderId:oid});for(const type of Object.keys(APPROVAL_ROLES))assert.throws(()=>execute(f.state,{type,payload:{orderId:oid,now:'2026-09-12T10:00:00Z',user:{role:'ADMIN'}}},u,{now:'2026-09-12T10:00:00Z'}),e=>e.code==='FORBIDDEN',type);
 f.run('APPROVE_ORDER',{orderId:oid});assert.ok(f.state.events.filter(e=>e.action==='PO_APPROVED').every(e=>!e.approvalPolicy));
});

test('multiple response attachments share one confirmation and preserve each document',()=>{
 const f=fixture(),oid=f.draft();f.issue(oid);const ids=[f.file([oid]),f.file([oid])];
 f.run('CONFIRM_SUPPLIER',{orderId:oid,channel:'EMAIL',remarks:'Two supplier responses for one acknowledgement.',fileIds:ids});
 assert.deepEqual(f.get(oid).confirmation.fileIds,ids);assert.equal(f.get(oid).confirmation.fileId,ids[0]);
 assert.deepEqual(f.get(oid).documents.filter(d=>d.type==='SUPPLIER_CONFIRMATION').map(d=>d.fileId),ids);
 const piFiles=[f.file([oid]),f.file([oid])];f.run('RECORD_PI',{orderId:oid,number:'MULTI-PI',date:TODAY,currency:'USD',amount:major(orderTotal(f.get(oid))),quantity:100,termsConfirmed:true,commitmentConfirmed:true,fileIds:piFiles});
 assert.deepEqual(f.get(oid).pi.fileIds,piFiles);assert.equal(f.get(oid).pi.status,'RECEIVED');
 const docs=[f.file([oid]),f.file([oid])];f.run('ATTACH_DOCUMENT',{orderId:oid,type:'OTHER',fileIds:docs});
 assert.deepEqual(f.get(oid).documents.filter(d=>d.type==='OTHER').map(d=>d.fileId),docs);
 assert.deepEqual(f.state.events.at(-1).newValue.fileIds,docs);
});

test('every attachment is validated before workflow mutation; single-file clients still work',()=>{
 const f=fixture(),oid=f.draft();f.issue(oid);const valid=f.file([oid]),wrongOrder=f.file([]),wrongScope=f.file([oid]);f.state.files.find(x=>x.id===wrongScope).scope='UTILITY_DOMESTIC';
 for(const bad of [wrongOrder,wrongScope,'missing'])rejects(f,'CONFIRM_SUPPLIER',{orderId:oid,channel:'EMAIL',remarks:'Invalid second attachment',fileIds:[valid,bad]},/evidence|order/i);
 rejects(f,'CONFIRM_SUPPLIER',{orderId:oid,channel:'EMAIL',remarks:'No files',fileIds:[]},/evidence/i);
 f.run('CONFIRM_SUPPLIER',{orderId:oid,channel:'EMAIL',remarks:'Legacy single file',fileId:valid});assert.equal(f.get(oid).confirmation.fileId,valid);
});

test('all remittance proofs must link to every allocation and receipt files stay grouped',()=>{
 const f=fixture(),oid=f.draft();f.issue(oid);f.commercial(oid);f.run('AUTHORIZE_PAYMENT',{orderId:oid,termIndex:0,shipmentId:null});
 const amount=major(paymentSchedule(f.state,f.get(oid))[0].amount),good=f.file([oid]),bad=f.file([]);
 const p={reference:'MULTI-PAY',date:TODAY,currency:'USD',amount,inrRate:'85',fileIds:[good,bad],allocations:[{orderId:oid,termIndex:0,shipmentId:null,amount,invoiceRate:'1'}]};
 rejects(f,'RECORD_PAYMENT',p,/every allocated order/);
 const second=f.file([oid]);p.fileIds=[good,second];const id=f.run('RECORD_PAYMENT',p).id,payment=f.state.payments.find(p=>p.id===id);assert.deepEqual(payment.fileIds,[good,second]);
 const proofs=[f.file([oid]),f.file([oid])];f.run('ACKNOWLEDGE_PAYMENT',{paymentId:id,allocationId:payment.allocations[0].id,realizedAmount:amount,supplierRate:'1',remarks:'Supplier proof bundle',fileIds:proofs});assert.deepEqual(f.state.payments.find(p=>p.id===id).allocations[0].ackFileIds,proofs);
});

test('optional QC and brand artwork retain multiple files without changing approval gates',()=>{
 const f=fixture(),oid=f.draft();f.issue(oid);f.produce(oid);
 // Optional sample evidence is represented by an empty collection when no files are chosen.
 const other=f.draft();f.issue(other);f.commercial(other);f.pay(other);f.run('RECORD_PREPRODUCTION_SAMPLE',{orderId:other,remarks:'Sample without optional evidence',fileIds:[]});assert.equal(f.get(other).preproductionSample.fileId,null);
 const ids=[f.file([]),f.file([])];f.run('SUBMIT_BRAND_ARTWORK',{itemId:f.item.id,remarks:'Two packaging views',fileIds:ids});const art=f.state.items.find(i=>i.id===f.item.id).artworkRevisions.at(-1);assert.deepEqual(art.fileIds,ids);assert.equal(art.status,'PENDING');
});
function fixture(nowDay=TODAY){let state=createSeed(TODAY),serial=0;state={...state,orders:[],payments:[],files:[],events:[],costs:[],imports:[],revision:0};const role=r=>state.users.find(u=>u.role===r),run=(type,payload,user=role('MANAGER'),day=nowDay)=>{const x=execute(state,{type,payload},user,{now:day+'T10:00:00.000Z',id:()=>`test-${++serial}`});state=x.state;return x.result;},file=(ids=[])=>{const id='file-'+(++serial);state.files.push({id,name:'test-evidence.txt',orderIds:ids,scope:'LAE_IMPORT',mime:'text/plain',size:4});return id;};const item=state.items.find(i=>i.code==='GJPW12'),base=state.bases.find(b=>b.id===item.baseId);const get=id=>state.orders.find(o=>o.id===id);
 const draft=(extra={})=>run('CREATE_ORDER',{number:'TEST-'+(++serial),vendorId:base.vendorId,buyerId:role('EXECUTIVE').id,currency:'USD',paymentTerms:TERMS[0],productionDays:30,productionOverrideReason:'Supplier order commitment.',planningTat:60,routeId:state.routes[0].id,requestedPortDate:'2026-10-25',lines:[{itemId:item.id,quantity:100,unitPrice:'100.00',specId:base.specifications[0].id}],...extra}).id;
 const issue=id=>{run('SUBMIT_ORDER',{orderId:id});run('APPROVE_ORDER',{orderId:id});};
 const confirm=id=>run('CONFIRM_SUPPLIER',{orderId:id,channel:'EMAIL',remarks:'Supplier accepted this version.',fileId:file([id])});
 const pi=id=>{if(get(id).confirmation?.revision!==get(id).revision)confirm(id);run('RECORD_PI',{orderId:id,number:'PI-'+(++serial),date:TODAY,currency:get(id).currency,amount:major(orderTotal(get(id))),quantity:shipmentTotals(get(id)).required,termsConfirmed:true,commitmentConfirmed:true,fileId:file([id])});run('VERIFY_PI',{orderId:id});run('APPROVE_PI',{orderId:id});};
 const technical=id=>run('CONFIRM_TECHNICAL',{orderId:id,channel:'EMAIL',remarks:'Supplier confirmed current technical package.',fileId:file([id])});
 const artwork=id=>{run('SUBMIT_ARTWORK',{orderId:id,fileId:file([id]),remarks:'Brand artwork supplied.'});run('APPROVE_ARTWORK',{orderId:id},role('PRODUCT_MANAGER'));run('CONFIRM_ARTWORK',{orderId:id,fileId:file([id]),remarks:'Artwork accepted.'});};
 const commercial=id=>{pi(id);technical(id);artwork(id);};
 const pay=(id,index=0,sid=null)=>{run('AUTHORIZE_PAYMENT',{orderId:id,termIndex:index,shipmentId:sid});const m=paymentSchedule(state,get(id)).find(m=>m.index===index&&m.shipmentId===sid),amount=major(m.amount);return run('RECORD_PAYMENT',{reference:'TX-'+(++serial),date:TODAY,currency:get(id).currency,amount,inrRate:'85.50',fileId:file([id]),allocations:[{orderId:id,termIndex:index,shipmentId:sid,amount,invoiceRate:'1'}]}).id;};
 const completeSample=id=>run('RECORD_PREPRODUCTION_SAMPLE',{orderId:id,remarks:'Supplier completed pre-production sample.',fileId:file([id])});
 const approveSample=id=>{if(!get(id).preproductionSample||get(id).preproductionSample.status==='REJECTED')completeSample(id);return run('APPROVE_PREPRODUCTION_SAMPLE',{orderId:id,result:'APPROVED',remarks:'Purchase approved pre-production sample.'});};
 const produce=id=>{commercial(id);for(const [i,m]of get(id).paymentTerms.steps.entries())if(m.trigger==='PI')pay(id,i);approveSample(id);run('START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Production start acknowledged.'});run('RECORD_BULK_QC',{orderId:id,result:'PASS',remarks:'Bulk-production QC passed.',fileId:file([id])});run('COMPLETE_PRODUCTION',{orderId:id,date:TODAY,remarks:'Inspection-ready batch.'});};
 const shipment=(id,quantity=100)=>run('ADD_SHIPMENT',{orderId:id,number:'SHP-'+(++serial),containerType:'40HC',origin:'NINGBO',destination:'CHENNAI',rateRouteKey:'NINGBO|CHENNAI|1X40HC',etd:TODAY,eta:'2026-09-30',lines:[{lineId:get(id).lines[0].id,quantity}]}).id;
 const bookRelease=(id,sid,freight='3800')=>{run('BOOK_CONTAINER',{orderId:id,shipmentId:sid,forwarderId:state.vendors.find(v=>v.kind==='LOGISTICS'&&v.status==='ACTIVE').id,forwarderRef:'REF-'+(++serial),date:TODAY,freightUsd:freight,rateRouteKey:'NINGBO|CHENNAI|1X40HC',remarks:'Booking confirmed.'});run('RELEASE_CONTAINER',{orderId:id,shipmentId:sid,container:'TEST'+String(++serial).padStart(7,'0'),date:TODAY,remarks:'Container released for loading.'});};
 const ready=(id,sid)=>{const s=get(id).shipments.find(s=>s.id===sid);if(s.bookingStatus==='PLANNED')bookRelease(id,sid);for(const t of ['COMMERCIAL_INVOICE','PACKING_LIST'])run('ATTACH_DOCUMENT',{orderId:id,shipmentId:sid,type:t,fileId:file([id])});for(const m of paymentSchedule(state,get(id)).filter(m=>m.trigger==='SHIPMENT'&&m.shipmentId===sid))pay(id,m.index,sid);};
 const dispatch=(id,sid,day=TODAY)=>run('DISPATCH_SHIPMENT',{orderId:id,shipmentId:sid,date:day,vessel:'TEST VESSEL',voyage:'V001',location:'NINGBO',remarks:'Loaded on vessel.'});
 const postVessel=(id,sid,day=TODAY)=>{run('RECORD_BL',{orderId:id,shipmentId:sid,number:'FINAL-'+(++serial),date:day,fileId:file([id]),remarks:'Final BL verified.'});run('RECORD_INSURANCE',{orderId:id,shipmentId:sid,masterPolicy:'MASTER-TEST',declarationNumber:'INS-'+(++serial),insuredValue:major(orderTotal(get(id))),currency:get(id).currency,date:day,remarks:'Shipment insured after final BL.',fileId:file([id])});};
 return {get state(){return state;},set state(x){state=x;},role,run,file,item,base,get,draft,issue,confirm,pi,technical,artwork,commercial,pay,completeSample,approveSample,produce,shipment,bookRelease,ready,dispatch,postVessel};}
function rejects(f,type,payload,pattern,user){const before=structuredClone(f.state);assert.throws(()=>f.run(type,payload,user),pattern);assert.deepEqual(f.state,before,'failed command must leave the caller state unchanged');}

test('source seed: 153 untouched raw items, six mapped brand SKUs, eight illustrative orders',()=>{const s=createSeed(TODAY);assert.equal(s.items.filter(i=>i.source==='User-supplied demo item master').length,153);assert.equal(s.items.filter(i=>i.baseId).length,6);assert.equal(s.categories.length,22);assert.equal(s.orders.length,8);assert.ok(s.orders.some(o=>orderStatus(o)==='PORT_ARRIVED'&&financials(s,o).balance>0));});
test('money and FX math use bounded integer minor units',()=>{assert.equal(toMinor('123.45'),12345);assert.throws(()=>toMinor('1.234'));assert.throws(()=>toMinor('-3'));assert.equal(convertMinor(10000,toRate('7.1')),71000);assert.equal(convertMinor(101,toRate('1.5')),152);});
test('pro-rata shipment allocations preserve the exact total down to the cent',()=>{assert.deepEqual(proportionalSlices(100,[1,1,1]),[33,34,33]);for(let n=1;n<1000;n++)assert.equal(proportionalSlices(n,[13,19,21,3]).reduce((a,b)=>a+b,0),n);});
test('viewer cannot create or update and executive cannot approve',()=>{const f=fixture();rejects(f,'CREATE_ORDER',{},/permission|access/i,f.role('VIEWER'));const id=f.draft();f.run('SUBMIT_ORDER',{orderId:id});rejects(f,'APPROVE_ORDER',{orderId:id},/Manager/,f.role('EXECUTIVE'));});
test('division assignment and assigned owner enforce edits',()=>{const f=fixture(),id=f.draft();rejects(f,'ADD_NOTE',{orderId:id,remarks:'x'},/assigned|permission|scope/i,{id:'another-exec',name:'Other buyer',role:'EXECUTIVE',scopes:['LAE_IMPORT'],active:true});rejects(f,'ADD_NOTE',{orderId:id,remarks:'x'},/scope|access|assigned division/i,{...f.role('MANAGER'),scopes:['UTILITY_DOMESTIC']});});
test('issue freezes exact technical specification and historical supplier / payment data',()=>{const f=fixture(),id=f.draft();f.issue(id);const snap=structuredClone(f.get(id).revisions[0]);f.state.bases.find(b=>b.id===f.base.id).specifications[0].description='MASTER LATER CHANGE';assert.deepEqual(f.get(id).revisions[0],snap);assert.notEqual(snap.snapshot.lines[0].specification.description,'MASTER LATER CHANGE');});
test('one vendor per base and operational brand mapping cannot be bypassed',()=>{const f=fixture(),raw=f.state.items.find(i=>!i.baseId);assert.throws(()=>f.draft({lines:[{itemId:raw.id,quantity:2,unitPrice:'1'}]}),/brand|mapping|base product/i);assert.throws(()=>f.draft({vendorId:f.state.vendors.find(v=>v.id!==f.base.vendorId&&v.kind==='SUPPLIER').id}),/vendor|supplier/i);});
test('new pending technical revision raises issue gate; previous approved policy never permits pending spec',()=>{const f=fixture(),id=f.draft();f.run('SAVE_SPEC',{baseId:f.base.id,version:'1.2',reason:'Update',description:'Full specification'});rejects(f,'SUBMIT_ORDER',{orderId:id},/pending/);f.run('SAVE_SETTINGS',{allowPreviousApprovedSpec:true},f.role('ADMIN'));f.run('SUBMIT_ORDER',{orderId:id});});
test('missing planning TAT and unapproved spec prevent PO issue',()=>{const f=fixture(),id=f.draft({planningTat:null});rejects(f,'SUBMIT_ORDER',{orderId:id},/TAT/);});
test('supplier blacklist prevents a new PO but existing open order remains readable',()=>{const f=fixture(),id=f.draft();f.issue(id);f.run('SAVE_VENDOR',{...f.state.vendors.find(v=>v.id===f.base.vendorId),status:'BLACKLISTED'});assert.ok(f.get(id));assert.throws(()=>f.draft(),/active/i);});
test('supplier PI quantity / currency / value discrepancies block verification',()=>{const f=fixture(),id=f.draft();f.issue(id);f.confirm(id);f.run('RECORD_PI',{orderId:id,number:'MISMATCH',date:TODAY,currency:'USD',amount:'99.00',quantity:100,termsConfirmed:true,commitmentConfirmed:true,fileId:f.file([id])});rejects(f,'VERIFY_PI',{orderId:id},/value differs/);});
test('PI requires evidence, purchase verification and manager approval in that order',()=>{const f=fixture(),id=f.draft();f.issue(id);f.confirm(id);rejects(f,'APPROVE_PI',{orderId:id},/verification/);rejects(f,'RECORD_PI',{orderId:id,number:'PI',date:TODAY,currency:'USD',amount:'10000',quantity:100},/evidence|attachment/i);});
test('replacing a PI removes prior payment authorizations',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);f.run('AUTHORIZE_PAYMENT',{orderId:id,termIndex:0});assert.equal(f.get(id).paymentAuthorizations.length,1);f.pi(id);assert.equal(f.get(id).paymentAuthorizations.length,0);});
test('unauthorized milestone cannot receive a payment',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);rejects(f,'RECORD_PAYMENT',{reference:'UNAUTH',date:TODAY,currency:'USD',amount:'3000',inrRate:'85',fileId:f.file([id]),allocations:[{orderId:id,termIndex:0,amount:'3000'}]},/authoriz/i);});
test('one bank remittance allocates exactly across multiple original orders',()=>{const f=fixture(),a=f.draft(),b=f.draft();for(const id of[a,b]){f.issue(id);f.commercial(id);f.run('AUTHORIZE_PAYMENT',{orderId:id,termIndex:0});}f.run('RECORD_PAYMENT',{reference:'MULTI',date:TODAY,currency:'USD',amount:'6000',inrRate:'85',fileId:f.file([a,b]),allocations:[{orderId:a,termIndex:0,amount:'3000'},{orderId:b,termIndex:0,amount:'3000'}]});assert.equal(f.state.payments.length,1);assert.equal(financials(f.state,f.get(a)).reported,300000);assert.equal(financials(f.state,f.get(b)).reported,300000);});
test('remittance allocations must exactly equal the bank amount',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);f.run('AUTHORIZE_PAYMENT',{orderId:id,termIndex:0});rejects(f,'RECORD_PAYMENT',{reference:'BAD-SUM',date:TODAY,currency:'USD',amount:'6000',inrRate:'85',fileId:f.file([id]),allocations:[{orderId:id,termIndex:0,amount:'3000'}]},/equal/);});
test('RMB invoice and USD remittance retain supplier-realized shortfall on the original order',()=>{const f=fixture(),id=f.draft({currency:'CNY'});f.issue(id);f.commercial(id);f.run('AUTHORIZE_PAYMENT',{orderId:id,termIndex:0});const p=f.run('RECORD_PAYMENT',{reference:'RMB-USD',date:TODAY,currency:'USD',amount:'500',inrRate:'85',fileId:f.file([id]),allocations:[{orderId:id,termIndex:0,amount:'500',invoiceRate:'6'}]}).id;const a=f.state.payments.find(p0=>p0.id===p).allocations[0];f.run('ACKNOWLEDGE_PAYMENT',{paymentId:p,allocationId:a.id,realizedAmount:'2980',supplierRate:'5.96',fileId:f.file([id]),remarks:'Bank realized shortfall.'});const fin=financials(f.state,f.get(id));assert.equal(fin.reported,300000);assert.equal(fin.realized,298000);assert.equal(fin.balance,702000);});
test('duplicate bank reference is blocked and void is visible, not a bank reversal',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);const p=f.pay(id);const pay=f.state.payments[0];rejects(f,'RECORD_PAYMENT',{reference:pay.reference,date:TODAY,currency:'USD',amount:'1',inrRate:'85',fileId:f.file([id]),allocations:[{orderId:id,termIndex:0,amount:'1'}]},/Duplicate|already exists/i);f.run('VOID_PAYMENT',{paymentId:p,remarks:'Duplicate external report corrected.'});assert.equal(f.state.payments[0].status,'VOID');assert.equal(financials(f.state,f.get(id)).reported,0);assert.ok(f.state.events.some(e=>e.action==='PAYMENT_VOIDED'));});
test('PI cannot be recorded before supplier PO acknowledgement',()=>{const f=fixture(),id=f.draft();f.issue(id);rejects(f,'RECORD_PI',{orderId:id,number:'PI-EARLY',date:TODAY,currency:'USD',amount:'10000',quantity:100,termsConfirmed:true,commitmentConfirmed:true,fileId:f.file([id])},/acknowledgement/i);f.confirm(id);f.pi(id);assert.equal(f.get(id).pi.status,'APPROVED');});
test('technical and artwork confirmation are mandatory before initial payment',()=>{const f=fixture(),id=f.draft();f.issue(id);f.pi(id);rejects(f,'AUTHORIZE_PAYMENT',{orderId:id,termIndex:0},/technical/i);f.technical(id);rejects(f,'AUTHORIZE_PAYMENT',{orderId:id,termIndex:0},/artwork/i);f.artwork(id);f.run('AUTHORIZE_PAYMENT',{orderId:id,termIndex:0});assert.equal(f.get(id).paymentAuthorizations.length,1);});
test('single initial-payment stage stores SWIFT evidence and starts production lead-time clock',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);const m=paymentSchedule(f.state,f.get(id)).find(m=>m.trigger==='PI');f.run('COMPLETE_INITIAL_PAYMENT',{orderId:id,reference:'SWIFT-001',date:TODAY,currency:'USD',amount:major(m.amount),invoiceRate:'1',inrRate:'85.5',bankCharges:'20',remarks:'Advance remitted.',fileId:f.file([id])});assert.equal(f.get(id).productionWindowStartedAt,TODAY);assert.equal(f.get(id).baselineProductionDue,'2026-10-11');assert.ok(f.get(id).documents.some(d=>d.type==='PAYMENT_PROOF'));});
test('pre-production sample completion and approval are separate hard gates before bulk production',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);for(const [i,m]of f.get(id).paymentTerms.steps.entries())if(m.trigger==='PI')f.pay(id,i);rejects(f,'START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Start'},/sample/i);f.completeSample(id);assert.equal(f.get(id).preproductionSample.status,'COMPLETED');rejects(f,'START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Start'},/sample/i);f.run('APPROVE_PREPRODUCTION_SAMPLE',{orderId:id,result:'APPROVED',remarks:'Approved by Purchase.'});f.run('START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Start after approval.'});assert.ok(f.get(id).productionStartedAt);});
test('full-credit production starts after commercial confirmations without inventing an advance',()=>{const f=fixture(),id=f.draft({paymentTerms:TERMS.find(t=>t.id==='credit60')});f.issue(id);f.commercial(id);assert.ok(f.get(id).productionWindowStartedAt);f.approveSample(id);f.run('START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Start on agreed credit.'});assert.equal(f.state.payments.length,0);assert.ok(f.get(id).productionStartedAt);});
test('commitment revisions preserve the initial production baseline',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const baseline=f.get(id).baselineProductionDue;f.get(id).productionCompletedAt=null;f.run('UPDATE_COMMITMENT',{orderId:id,date:'2026-11-01',remarks:'Supplier revised its date.'});assert.equal(f.get(id).baselineProductionDue,baseline);assert.equal(f.get(id).productionDue,'2026-11-01');});
test('artwork requires Product Manager approval and leaves technical/issued PO versions unchanged',()=>{const f=fixture(),id=f.draft();f.issue(id);f.pi(id);f.technical(id);const snap=structuredClone(f.get(id).revisions);f.run('SUBMIT_ARTWORK',{orderId:id,remarks:'New decals',fileId:f.file([id])});rejects(f,'APPROVE_ARTWORK',{orderId:id},/Product Manager/,f.role('EXECUTIVE'));f.run('APPROVE_ARTWORK',{orderId:id},f.role('PRODUCT_MANAGER'));assert.equal(f.get(id).revision,0);assert.deepEqual(f.get(id).revisions,snap);assert.equal(f.get(id).artwork.current.label,'A1');});
test('partial shipments cannot over-allocate PO quantities',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);f.shipment(id,60);assert.throws(()=>f.shipment(id,50),/remaining|unallocated balance/i);assert.equal(shipmentTotals(f.get(id)).allocated,60);});
test('no separate pre-dispatch QC gate remains in the current shipping workflow',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);f.bookRelease(id,sid);assert.deepEqual(shippingDocReadiness(f.get(id),f.get(id).shipments.find(s=>s.id===sid)).sort(),['COMMERCIAL_INVOICE','PACKING_LIST']);});
test('loaded-on-vessel is blocked by missing commercial invoice / packing list, not pre-dispatch QC',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);f.bookRelease(id,sid);rejects(f,'DISPATCH_SHIPMENT',{orderId:id,shipmentId:sid,date:TODAY,vessel:'TEST VESSEL',voyage:'V001',remarks:'Dispatch'},/documents/i);f.ready(id,sid);f.dispatch(id,sid);assert.ok(f.get(id).shipments.find(s=>s.id===sid).actualDeparture);});
test('before-shipment payment is checked only against the allocated shipment obligation',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id,40);f.ready(id,sid);f.dispatch(id,sid);assert.equal(shipmentTotals(f.get(id)).departed,40);assert.equal(financials(f.state,f.get(id)).reported,300000);assert.equal(orderStatus(f.get(id)),'IN_TRANSIT');});
test('final BL date derives the shipment credit due date without changing its original trigger',()=>{const f=fixture(),id=f.draft({paymentTerms:TERMS.find(t=>t.id==='30-70-bl60')});f.issue(id);f.produce(id);const sid=f.shipment(id);f.ready(id,sid);f.dispatch(id,sid);f.run('RECORD_BL',{orderId:id,shipmentId:sid,number:'FINAL-1',date:TODAY,fileId:f.file([id])});assert.equal(paymentSchedule(f.state,f.get(id)).find(m=>m.trigger==='BL').due,'2026-11-10');});
test('port arrival closes physical workflow but not the unpaid financial balance',()=>{const f=fixture(),id=f.draft({paymentTerms:TERMS.find(t=>t.id==='credit60')});f.issue(id);f.produce(id);const sid=f.shipment(id);f.ready(id,sid);f.dispatch(id,sid);f.postVessel(id,sid);f.run('ARRIVE_SHIPMENT',{orderId:id,shipmentId:sid,date:TODAY,remarks:'Port event captured'});assert.equal(orderStatus(f.get(id)),'PORT_ARRIVED');assert.equal(financials(f.state,f.get(id)).status,'UNPAID');assert.ok(f.get(id).operationalClosedAt);});
test('future actual departure / arrival dates cannot fake a completed milestone',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);f.ready(id,sid);rejects(f,'DISPATCH_SHIPMENT',{orderId:id,shipmentId:sid,date:'2026-10-01',vessel:'TEST VESSEL',voyage:'V001',remarks:'Future dispatch'},/future/);});
test('new artwork revision requires renewed supplier artwork confirmation before vessel loading',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);f.ready(id,sid);f.run('SUBMIT_ARTWORK',{orderId:id,fileId:f.file([id]),remarks:'Revised carton.'});f.run('APPROVE_ARTWORK',{orderId:id},f.role('PRODUCT_MANAGER'));assert.equal(f.get(id).artwork.supplierConfirmed,null);rejects(f,'DISPATCH_SHIPMENT',{orderId:id,shipmentId:sid,date:TODAY,vessel:'TEST VESSEL',voyage:'V001',remarks:'Dispatch'},/artwork/i);f.run('CONFIRM_ARTWORK',{orderId:id,fileId:f.file([id]),remarks:'Supplier accepted revised artwork.'});f.dispatch(id,sid);assert.ok(f.get(id).shipments[0].actualDeparture);});
test('PO amendments preserve earlier issue, require renewed confirmation and re-verify PI',()=>{const f=fixture(),id=f.draft();f.issue(id);f.pi(id);f.confirm(id);const snap=structuredClone(f.get(id).revisions[0]);const l=f.get(id).lines[0];f.run('PROPOSE_AMENDMENT',{orderId:id,reason:'Packing improved.',lines:[{...l,artworkNotes:'New brand packing requirement'}]});f.run('APPROVE_AMENDMENT',{orderId:id});assert.equal(f.get(id).revision,1);assert.deepEqual(f.get(id).revisions[0],snap);assert.equal(f.get(id).confirmation,null);assert.equal(f.get(id).pi.status,'REVERIFY');});
test('short close cannot mask unresolved physical shipments and does not write off finance',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);for(const [i,m] of f.get(id).paymentTerms.steps.entries())if(m.trigger==='PI')f.pay(id,i);f.approveSample(id);f.run('START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Started for allocation test.'});const sid=f.shipment(id,60);rejects(f,'SHORT_CLOSE_ORDER',{orderId:id,reason:'Other',remarks:'Cannot finish'},/shipment/);f.run('CANCEL_SHIPMENT',{orderId:id,shipmentId:sid,remarks:'Cancelled allocation for short-closure test.'});f.run('SHORT_CLOSE_ORDER',{orderId:id,reason:'Other',remarks:'Cancelled remaining requirement.'});assert.equal(orderStatus(f.get(id)),'SHORT_CLOSED');assert.ok(financials(f.state,f.get(id)).balance>0);});
test('follow-up closure records outcome, contact, remarks and next weekly occurrence',()=>{const f=fixture(),id=f.draft();f.issue(id);const task=f.get(id).tasks[0];rejects(f,'COMPLETE_FOLLOWUP',{orderId:id,taskId:task.id},/contact|outcome|remarks|communication/i);f.run('COMPLETE_FOLLOWUP',{orderId:id,taskId:task.id,contact:'Supplier contact',method:'Email',outcome:'On schedule',remarks:'Confirmed factory commitment.',nextDue:'2026-09-18'});assert.equal(f.get(id).tasks.filter(t=>!t.completedAt).length,1);assert.ok(f.get(id).tasks.find(t=>t.id===task.id).completedAt);});
test('correction notes link the original event; history cannot be deleted through commands',()=>{const f=fixture(),id=f.draft();f.issue(id);const before=structuredClone(f.state.events);f.run('ADD_NOTE',{orderId:id,remarks:'Correction explanation',correctsEventId:before[0].id});assert.deepEqual(f.state.events.slice(0,before.length),before);assert.equal(f.state.events.at(-1).newValue.correctionOf,before[0].id);rejects(f,'DELETE_EVENT',{orderId:id,eventId:before[0].id},/Unknown|Unsupported/);});
test('legacy headings normalize; missing / invalid vendor mapping is rejected',()=>{const f=fixture(),r={'VENDOR CODE':f.state.vendors[0].code,'ITEM CODE':'NEW-001','ITEM NAME-1':'Demo new item','PRODUCT CATAGORY':'HTP+MOTOR','production days':30};const p=previewImport(f.state,[r])[0];assert.equal(p.normalized.category,'HTP + MOTOR');assert.equal(p.result,'CREATE');assert.ok(p.warnings.length);assert.equal(previewImport(f.state,[{...r,'VENDOR CODE':'UNKNOWN'}])[0].result,'REJECTED');});
test('duplicate import codes reject the batch and no partial rows commit',()=>{const f=fixture(),r={'VENDOR CODE':f.state.vendors[0].code,'ITEM CODE':'NEW-001','ITEM NAME-1':'Item','PRODUCT CATAGORY':'MOTOR'};assert.ok(previewImport(f.state,[r,r]).some(r=>r.result==='REJECTED'));rejects(f,'COMMIT_IMPORT',{rows:[r,r],sourceFileId:f.file(),filename:'demo.csv'},/rejected/);});
test('import commit retains original source, raw row and mapping version',()=>{const f=fixture(),r={'VENDOR CODE':f.state.vendors[0].code,'ITEM CODE':'NEW-001','ITEM NAME-1':'New item','PRODUCT CATAGORY':'MOTOR'},fileId=f.file();f.run('COMMIT_IMPORT',{rows:[r],sourceFileId:fileId,filename:'demo.csv'});assert.equal(f.state.imports.length,1);assert.equal(f.state.imports[0].sourceFileId,fileId);assert.deepEqual(f.state.items.find(i=>i.code==='NEW-001').rawColumns,r);});

test('PLM seed exposes category templates and full product metadata',()=>{const f=fixture();assert.ok(f.state.plmTemplates.length>=5);assert.equal(f.base.category,'POWER WEEDER');assert.ok(f.base.templateId);assert.equal(f.base.lifecycleStatus,'ACTIVE');assert.ok(f.base.productName);});
test('structured PLM revision enforces required template fields and Product Manager approval',()=>{const f=fixture(),tpl=f.state.plmTemplates.find(t=>t.id===f.base.templateId),values=Object.fromEntries(tpl.fields.filter(x=>x.required).map(x=>[x.key,'Confirmed']));rejects(f,'SAVE_SPEC',{baseId:f.base.id,version:'1.2',reason:'Thickness improvement',changeSummary:'Increase critical member thickness',fieldValues:{e20Compatibility:'Required'}},/required/i);f.run('SAVE_SPEC',{baseId:f.base.id,version:'1.2',reason:'Thickness improvement',changeSummary:'Increase critical member thickness',fieldValues:values});const current=()=>f.state.bases.find(b=>b.id===f.base.id);const sp=current().specifications.find(s=>s.version==='1.2');assert.equal(sp.status,'PENDING');rejects(f,'APPROVE_SPEC',{baseId:f.base.id,specId:sp.id},/Product Manager/,f.role('EXECUTIVE'));f.run('APPROVE_SPEC',{baseId:f.base.id,specId:sp.id},f.role('PRODUCT_MANAGER'));assert.equal(current().specifications.find(s=>s.id===sp.id).status,'APPROVED');});
test('Product Manager can reject a pending technical revision with remarks',()=>{const f=fixture();f.run('SAVE_SPEC',{baseId:f.base.id,version:'1.2',reason:'Trial change',description:'Complete trial specification'});const current=()=>f.state.bases.find(b=>b.id===f.base.id);const sp=current().specifications.find(s=>s.version==='1.2');rejects(f,'REJECT_SPEC',{baseId:f.base.id,specId:sp.id,remarks:''},/remarks/,f.role('PRODUCT_MANAGER'));f.run('REJECT_SPEC',{baseId:f.base.id,specId:sp.id,remarks:'Test report is incomplete.'},f.role('PRODUCT_MANAGER'));assert.equal(current().specifications.find(s=>s.id===sp.id).status,'REJECTED');});
test('significant change creates a successor code and preserves lineage',()=>{const f=fixture();const r=f.run('CREATE_SUCCESSOR',{previousBaseId:f.base.id,code:'PW21',productName:'Power weeder successor',vendorId:f.base.vendorId,version:'1.0',reason:'Major engine configuration change.'});const b=f.state.bases.find(b=>b.id===r.id);assert.equal(b.previousBaseId,f.base.id);assert.equal(b.code,'PW21');assert.equal(b.specifications[0].status,'PENDING');assert.deepEqual(b.specifications[0].fieldValues,f.base.specifications[0].fieldValues);});
test('brand-specific change needs Product Manager approval and blocks new PO issue while pending',()=>{const f=fixture(),id=f.draft();f.run('SAVE_BRAND_DELTA',{itemId:f.item.id,branding:f.item.brand,decals:'New decal',packaging:'New carton',labels:'',colourNotes:'',remarks:'Brand refresh'});rejects(f,'SUBMIT_ORDER',{orderId:id},/brand-specific PLM/i);f.run('APPROVE_BRAND_DELTA',{itemId:f.item.id},f.role('PRODUCT_MANAGER'));f.run('SUBMIT_ORDER',{orderId:id});assert.equal(f.get(id).status,'PENDING_APPROVAL');});
test('brand artwork revision does not change technical revision or base product code',()=>{const f=fixture(),before=structuredClone(f.base.specifications),fid=f.file();const r=f.run('SUBMIT_BRAND_ARTWORK',{itemId:f.item.id,fileId:fid,remarks:'Revised carton artwork.'});const art=f.state.items.find(i=>i.id===f.item.id).artworkRevisions.find(a=>a.id===r.id);assert.equal(art.status,'PENDING');f.run('APPROVE_BRAND_ARTWORK',{itemId:f.item.id,artworkId:art.id},f.role('PRODUCT_MANAGER'));assert.equal(f.state.items.find(i=>i.id===f.item.id).artworkRevisions.find(a=>a.id===art.id).status,'APPROVED');assert.deepEqual(f.base.specifications,before);assert.equal(f.base.code,'PW12');});
test('PLM template edits are audited and do not rewrite already approved specifications',()=>{const f=fixture(),tpl=f.state.plmTemplates.find(t=>t.id===f.base.templateId),before=structuredClone(f.base.specifications[0]);f.run('SAVE_TEMPLATE_FIELD',{templateId:tpl.id,key:'noiseLevel',label:'Noise level',group:'Compliance',fieldType:'text',required:false,options:'',active:true},f.role('PRODUCT_MANAGER'));assert.ok(f.state.plmTemplates.find(t=>t.id===tpl.id).fields.some(x=>x.key==='noiseLevel'));assert.deepEqual(f.base.specifications[0],before);assert.ok(f.state.events.some(e=>e.action==='PLM_TEMPLATE_FIELD_SAVED'));});
test('new PLM approval never rewrites a previously issued PO snapshot',()=>{const f=fixture(),id=f.draft();f.issue(id);const snap=structuredClone(f.get(id).revisions[0].snapshot.lines[0].specification);f.run('SAVE_SPEC',{baseId:f.base.id,version:'1.2',reason:'Later master change',description:'New full specification'});const sp=f.state.bases.find(b=>b.id===f.base.id).specifications.find(s=>s.version==='1.2');f.run('APPROVE_SPEC',{baseId:f.base.id,specId:sp.id},f.role('PRODUCT_MANAGER'));assert.deepEqual(f.get(id).revisions[0].snapshot.lines[0].specification,snap);assert.equal(f.get(id).revisions[0].snapshot.lines[0].specification.version,'1.1');});

test('mandatory pre-production sample rejection returns workflow to corrected sample completion',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);for(const [i,m] of f.get(id).paymentTerms.steps.entries())if(m.trigger==='PI')f.pay(id,i);f.completeSample(id);f.run('APPROVE_PREPRODUCTION_SAMPLE',{orderId:id,result:'REJECTED',remarks:'Colour / fitment mismatch.'});rejects(f,'START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Start'},/sample/i);f.approveSample(id);f.run('START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Corrected sample approved; bulk start.'});assert.ok(f.get(id).productionStartedAt);});

test('bulk production cannot complete until bulk QC is PASS',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);for(const [i,m] of f.get(id).paymentTerms.steps.entries())if(m.trigger==='PI')f.pay(id,i);f.approveSample(id);f.run('START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Start'});rejects(f,'COMPLETE_PRODUCTION',{orderId:id,date:TODAY,remarks:'Done'},/QC/i);f.run('RECORD_BULK_QC',{orderId:id,result:'ISSUES',remarks:'Assembly issue found.'});rejects(f,'COMPLETE_PRODUCTION',{orderId:id,date:TODAY,remarks:'Done'},/QC/i);f.run('RECORD_BULK_QC',{orderId:id,result:'PASS',remarks:'Recheck passed.'});f.run('COMPLETE_PRODUCTION',{orderId:id,date:TODAY,remarks:'Production complete after QC.'});assert.ok(f.get(id).productionCompletedAt);});

test('container booking can occur during active production and forwarder Ref is unique',()=>{const f=fixture(),id=f.draft();f.issue(id);f.commercial(id);for(const [i,m] of f.get(id).paymentTerms.steps.entries())if(m.trigger==='PI')f.pay(id,i);f.approveSample(id);f.run('START_PRODUCTION',{orderId:id,date:TODAY,remarks:'Bulk started.'});const a=f.shipment(id,40),b=f.shipment(id,40),forwarder=f.state.vendors.find(v=>v.kind==='LOGISTICS').id;f.run('BOOK_CONTAINER',{orderId:id,shipmentId:a,forwarderId:forwarder,forwarderRef:'1547',date:TODAY,freightUsd:'3800',rateRouteKey:'NINGBO|CHENNAI|1X40HC',remarks:'Advance booking.'});assert.equal(f.get(id).shipments.find(s=>s.id===a).bookingStatus,'BOOKED');rejects(f,'BOOK_CONTAINER',{orderId:id,shipmentId:b,forwarderId:forwarder,forwarderRef:'1547',date:TODAY,freightUsd:'3800',rateRouteKey:'NINGBO|CHENNAI|1X40HC',remarks:'Duplicate ref.'},/already linked/i);});

test('container release is a separate milestone and requires booked container reference',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);rejects(f,'RELEASE_CONTAINER',{orderId:id,shipmentId:sid,container:'C123',date:TODAY,remarks:'Release'},/Booked/i);f.bookRelease(id,sid);const s=f.get(id).shipments.find(s=>s.id===sid);assert.equal(s.bookingStatus,'RELEASED');assert.ok(s.trackingMilestones.some(m=>m.key==='BOOKING'&&m.status==='COMPLETED'));assert.ok(s.trackingMilestones.some(m=>m.key==='RELEASED'&&m.status==='COMPLETED'));});

test('weekly tracking import matches exact forwarder Ref and preserves earliest baseline dates',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);f.bookRelease(id,sid);const s=f.get(id).shipments.find(s=>s.id===sid),baselineEtd=s.baselineEtd,baselineEta=s.baselineEta,ref=s.forwarderRef;const rows=[{'Supplier Name':'Demo supplier','BL NO':'BL-TRACK','ETD':'15.09.2026','ETA':'28.09.2026','Status':'SHIPPER LOADED CARGO','Ref':ref,'Telex Staus':'PENDING'}];const preview=previewTrackingImport(f.state,rows);assert.equal(preview[0].result,'MATCHED');f.run('COMMIT_TRACKING_IMPORT',{rows,filename:'VJ Report test.xlsx',statusDate:'2026-09-12',sourceFileId:f.file()});const after=f.get(id).shipments.find(x=>x.id===sid);assert.equal(after.baselineEtd,baselineEtd);assert.equal(after.baselineEta,baselineEta);assert.equal(after.etd,'2026-09-15');assert.equal(after.eta,'2026-09-28');assert.equal(after.lastForwarderStatus,'SHIPPER LOADED CARGO');assert.ok(after.trackingEvents.some(e=>e.source.includes('Weekly forwarder Excel')));});


test('final BL and insurance are post-vessel gates in that order',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);f.ready(id,sid);rejects(f,'RECORD_BL',{orderId:id,shipmentId:sid,number:'EARLY-BL',date:TODAY,fileId:f.file([id])},/vessel/i);f.dispatch(id,sid);rejects(f,'RECORD_INSURANCE',{orderId:id,shipmentId:sid,masterPolicy:'MASTER',declarationNumber:'INS-EARLY',insuredValue:'10000',currency:'USD',date:TODAY,fileId:f.file([id])},/final BL/i);f.run('RECORD_BL',{orderId:id,shipmentId:sid,number:'FINAL-BL',date:TODAY,fileId:f.file([id]),remarks:'Verified.'});f.run('RECORD_INSURANCE',{orderId:id,shipmentId:sid,masterPolicy:'MASTER',declarationNumber:'INS-OK',insuredValue:'10000',currency:'USD',date:TODAY,fileId:f.file([id]),remarks:'Insured.'});assert.ok(f.get(id).shipments.find(s=>s.id===sid).insurance.insuredAt);});
test('India port arrival cannot close before final BL and insurance',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);f.ready(id,sid);f.dispatch(id,sid);rejects(f,'ARRIVE_SHIPMENT',{orderId:id,shipmentId:sid,date:TODAY,remarks:'Arrived'},/BL|insurance/i);f.postVessel(id,sid);f.run('ARRIVE_SHIPMENT',{orderId:id,shipmentId:sid,date:TODAY,remarks:'India port arrival.'});assert.equal(orderStatus(f.get(id)),'PORT_ARRIVED');});
test('VJ Week 36 freight rows normalize into five distinct route benchmarks',()=>{const f=fixture(),rows=[{'PORT OF LOADING':'Ningbo','PORT OF DISCHARGE':'Chennai','VOLUME':'1X40HC','O/F USD':'USD 3800','SCHEDULE':'ETD NINGBO 11th September'},{'PORT OF LOADING':'Qingdao','PORT OF DISCHARGE':'Chennai','VOLUME':'1X40HC','O/F USD':'USD 3250','SCHEDULE':'ETD QINGDAO 20th September'},{'PORT OF LOADING':'Shenzhen','PORT OF DISCHARGE':'Chennai','VOLUME':'1X40HC','O/F USD':'USD 2500','SCHEDULE':'ETD SHENZHEN 20th September'},{'PORT OF LOADING':'Chongqing via Ningbo','PORT OF DISCHARGE':'Chennai','VOLUME':'1X40HC','O/F USD':'USD 4600','SCHEDULE':'ETD CHONGQING 13th September'},{'PORT OF LOADING':'Chongqing via Nansha','PORT OF DISCHARGE':'Chennai','VOLUME':'1X40HC','O/F USD':'USD 4500','SCHEDULE':'ETD CHONGQING 13th September'}];const p=previewRateImport(f.state,rows,'2026-W37');assert.equal(p.length,5);assert.ok(p.every(r=>r.result==='READY'));assert.equal(p[3].normalized.routeKey,'CHONGQING|VIA NINGBO|CHENNAI|1X40HC');assert.equal(p[4].normalized.rateUsd,4500);});

test('booked freight is compared with final benchmark including agent charge',()=>{const f=fixture(),id=f.draft();f.issue(id);f.produce(id);const sid=f.shipment(id);const forwarder=f.state.vendors.find(v=>v.kind==='LOGISTICS').id;f.run('BOOK_CONTAINER',{orderId:id,shipmentId:sid,forwarderId:forwarder,forwarderRef:'1591',date:TODAY,freightUsd:'3901',rateRouteKey:'NINGBO|CHENNAI|1X40HC',remarks:'Booked rate.'});const s=f.get(id).shipments.find(x=>x.id===sid),v=rateVariance(f.state,s);assert.equal(v.market,3920);assert.equal(v.difference,-19);assert.equal(v.flag,false);});

test('freight history identifies rising weekly rate trend without overwriting earlier week',()=>{const f=fixture(),rows=[{'PORT OF LOADING':'Ningbo','PORT OF DISCHARGE':'Chennai','VOLUME':'1X40HC','O/F USD':'USD 4000','SCHEDULE':'Next sailing'}],fid=f.file();f.run('COMMIT_FREIGHT_RATE_IMPORT',{rows,weekCode:'2026-W37',filename:'Week37.xlsx',sourceFileId:fid});const key='NINGBO|CHENNAI|1X40HC',tr=freightTrendFor(f.state,key);assert.equal(tr.direction,'RISING');assert.equal(tr.recent.at(-1).rateUsd,4000);assert.ok(f.state.freightRates.some(r=>r.weekCode==='2026-W36'&&r.rateUsd===3800));});


test('supplier price list supports independent current RMB/CNY and USD prices for the same SKU',()=>{const f=fixture(),v=f.state.vendors.find(v=>v.id===f.base.vendorId);const cny=currentApprovedPrice(f.state,v.id,f.item.id,'CNY',TODAY),usd=currentApprovedPrice(f.state,v.id,f.item.id,'USD',TODAY);assert.equal(cny.currency,'CNY');assert.equal(cny.unitPriceMinor,168000);assert.equal(usd.currency,'USD');assert.equal(usd.unitPriceMinor,24000);});

test('saving a revised supplier price supersedes only the prior same-currency price and retains history',()=>{const f=fixture(),v=f.state.vendors.find(v=>v.id===f.base.vendorId);const before=currentApprovedPrice(f.state,v.id,f.item.id,'CNY',TODAY);f.run('SAVE_PRICE_LIST',{vendorId:v.id,itemId:f.item.id,currency:'CNY',unitPrice:'1710.00',effectiveDate:TODAY,reference:'Supplier list Sept',remarks:'Supplier revised RMB price.'},f.role('EXECUTIVE'));const after=currentApprovedPrice(f.state,v.id,f.item.id,'CNY',TODAY);assert.notEqual(after.id,before.id);assert.equal(after.unitPriceMinor,171000);assert.equal(f.state.priceLists.find(x=>x.id===before.id).status,'SUPERSEDED');assert.ok(currentApprovedPrice(f.state,v.id,f.item.id,'USD',TODAY));assert.equal(f.state.priceLists.filter(x=>x.vendorId===v.id&&x.itemId===f.item.id&&x.currency==='CNY').length,2);});

test('PO line snapshots matching supplier price list and marks a manual override without blocking issue',()=>{const f=fixture(),v=f.state.vendors.find(v=>v.id===f.base.vendorId),ref=currentApprovedPrice(f.state,v.id,f.item.id,'USD',TODAY);const matched=f.draft({currency:'USD',lines:[{itemId:f.item.id,quantity:10,unitPrice:major(ref.unitPriceMinor),specId:f.base.specifications[0].id}]});assert.equal(f.get(matched).lines[0].priceOverride,false);assert.equal(f.get(matched).lines[0].priceListSnapshot.entryId,ref.id);const override=f.draft({currency:'USD',lines:[{itemId:f.item.id,quantity:10,unitPrice:'250.00',specId:f.base.specifications[0].id}]});assert.equal(f.get(override).lines[0].priceOverride,true);assert.ok(flagsFor(f.state,f.get(override),TODAY).some(x=>/price differs/i.test(x.label)));f.issue(override);assert.equal(f.get(override).status,'ISSUED');});

test('later supplier price-list revision never rewrites an issued PO price or source snapshot',()=>{const f=fixture(),v=f.state.vendors.find(v=>v.id===f.base.vendorId),ref=currentApprovedPrice(f.state,v.id,f.item.id,'USD',TODAY);const id=f.draft({currency:'USD',lines:[{itemId:f.item.id,quantity:10,unitPrice:major(ref.unitPriceMinor),specId:f.base.specifications[0].id}]});f.issue(id);const snap=structuredClone(f.get(id).revisions[0].snapshot.lines[0]);f.run('SAVE_PRICE_LIST',{vendorId:v.id,itemId:f.item.id,currency:'USD',unitPrice:'255.00',effectiveDate:TODAY,reference:'New list',remarks:'Later supplier revision.'});assert.deepEqual(f.get(id).revisions[0].snapshot.lines[0],snap);assert.equal(snap.unitPriceMinor,24000);assert.equal(snap.priceListSnapshot.entryId,ref.id);});

test('TAT override reason is required only when supplier commitment differs from vendor standard',()=>{const f=fixture(),v=f.state.vendors.find(v=>v.id===f.base.vendorId);const same=f.draft({productionDays:v.productionDays,productionOverrideReason:''});assert.ok(f.get(same));rejects(f,'CREATE_ORDER',{number:'TEST-OVERRIDE-MISSING',vendorId:f.base.vendorId,buyerId:f.role('EXECUTIVE').id,currency:'USD',paymentTerms:TERMS[0],productionDays:v.productionDays-1,productionOverrideReason:'',planningTat:60,routeId:f.state.routes[0].id,requestedPortDate:'2026-10-25',lines:[{itemId:f.item.id,quantity:100,unitPrice:'100.00',specId:f.base.specifications[0].id}]},/production-time override/i);const overridden=f.draft({productionDays:v.productionDays-1,productionOverrideReason:'Supplier agreed shorter TAT for this order.'});assert.ok(f.get(overridden));});

const standardApprovalStages=()=>Object.fromEntries(APPROVAL_STAGES.map(s=>[s.command,[...s.roles]]));
test('approval controls require admin, complete validated matrix and confirmation; preserve existing transactions',()=>{
 const f=fixture(),before=structuredClone(f.state),stages=standardApprovalStages();
 for(const user of ['MANAGER','PRODUCT_MANAGER','EXECUTIVE','VIEWER'])assert.throws(()=>f.run('SAVE_APPROVAL_CONTROLS',{stages,remarks:'Test',confirm:true},f.role(user)),/Administrator/);
 for(const payload of [{stages,remarks:'',confirm:true},{stages,remarks:'Test',confirm:false},{stages:{...stages,UNKNOWN:[]},remarks:'Test',confirm:true},{stages:{...stages,APPROVE_ORDER:['VIEWER']},remarks:'Test',confirm:true},{stages:{...stages,APPROVE_ORDER:['MANAGER','MANAGER']},remarks:'Test',confirm:true},{stages:{},remarks:'Test',confirm:true}])assert.throws(()=>f.run('SAVE_APPROVAL_CONTROLS',payload,f.role('ADMIN')));
 assert.deepEqual(f.state,before);stages.APPROVE_ARTWORK.push('MANAGER');f.run('SAVE_APPROVAL_CONTROLS',{stages,remarks:'Temporary artwork coverage',confirm:true},f.role('ADMIN'));
 assert.deepEqual(f.state.orders,before.orders);assert.deepEqual(f.state.users,before.users);assert.deepEqual(f.state.payments,before.payments);assert.equal(f.state.approvalControls.revision,1);assert.equal(f.state.events.at(-1).action,'APPROVAL_CONTROLS_UPDATED');
});
test('all approval controls support role changes, scope/active denial, admin retention and immediate restore',()=>{
 const f=fixture(),stages=standardApprovalStages();for(const s of APPROVAL_STAGES)stages[s.command]=['MANAGER'];f.run('SAVE_APPROVAL_CONTROLS',{stages,remarks:'Manager coverage',confirm:true},f.role('ADMIN'));
 for(const s of APPROVAL_STAGES){assert.equal(canPerformApproval(f.role('MANAGER'),s.command,'LAE_IMPORT',null,f.state),true);assert.equal(canPerformApproval({...f.role('MANAGER'),active:false},s.command,'LAE_IMPORT',null,f.state),false);assert.equal(canPerformApproval({...f.role('MANAGER'),scopes:[]},s.command,'LAE_IMPORT',null,f.state),false);assert.equal(canPerformApproval(f.role('VIEWER'),s.command,'LAE_IMPORT',null,f.state),false);}
 const restricted=Object.fromEntries(APPROVAL_STAGES.map(s=>[s.command,[]]));f.run('SAVE_APPROVAL_CONTROLS',{stages:restricted,remarks:'Admin only',confirm:true},f.role('ADMIN'));for(const s of APPROVAL_STAGES){assert.equal(canPerformApproval(f.role('MANAGER'),s.command,'LAE_IMPORT',null,f.state),false);assert.equal(canPerformApproval(f.role('ADMIN'),s.command,'LAE_IMPORT',null,f.state),true);}
 f.run('SAVE_APPROVAL_CONTROLS',{stages:standardApprovalStages(),remarks:'Restore',confirm:true},f.role('ADMIN'));assert.equal(canPerformApproval(f.role('MANAGER'),'APPROVE_ARTWORK','LAE_IMPORT',null,f.state),false);assert.equal(f.state.events.filter(e=>e.action==='APPROVAL_CONTROLS_UPDATED').length,3);
});
test('configured Manager artwork approval executes with policy revision; restore retains prior approvals',()=>{
 const f=fixture(),id=f.draft();f.issue(id);f.pi(id);f.technical(id);f.run('SUBMIT_ARTWORK',{orderId:id,fileId:f.file([id]),remarks:'Artwork'});assert.throws(()=>f.run('APPROVE_ARTWORK',{orderId:id}),/Product Manager/);
 const stages=standardApprovalStages();stages.APPROVE_ARTWORK.push('MANAGER');f.run('SAVE_APPROVAL_CONTROLS',{stages,remarks:'Temporary cover',confirm:true},f.role('ADMIN'));f.run('APPROVE_ARTWORK',{orderId:id});const approved=structuredClone(f.get(id).artwork.current);assert.equal(f.state.events.at(-1).approvalControl.revision,1);
 f.run('SAVE_APPROVAL_CONTROLS',{stages:standardApprovalStages(),remarks:'Restore standard',confirm:true},f.role('ADMIN'));assert.deepEqual(f.get(id).artwork.current,approved);f.run('SUBMIT_ARTWORK',{orderId:id,fileId:f.file([id]),remarks:'Revision'});assert.throws(()=>f.run('APPROVE_ARTWORK',{orderId:id}),/Product Manager/);
});
test('sample and initial-payment controls cannot be bypassed by existing editor rights',()=>{
 const f=fixture(),id=f.draft(),stages=standardApprovalStages();for(const cmd of ['APPROVE_PREPRODUCTION_SAMPLE','COMPLETE_INITIAL_PAYMENT']){assert.equal(canPerformApproval(f.role('EXECUTIVE'),cmd,'LAE_IMPORT',null,f.state,f.get(id)),true);assert.equal(canPerformApproval({...f.role('EXECUTIVE'),id:'unassigned'},cmd,'LAE_IMPORT',null,f.state,f.get(id)),false);stages[cmd]=[];}
 f.run('SAVE_APPROVAL_CONTROLS',{stages,remarks:'Restrict shortcuts',confirm:true},f.role('ADMIN'));for(const cmd of ['APPROVE_PREPRODUCTION_SAMPLE','COMPLETE_INITIAL_PAYMENT'])for(const role of ['MANAGER','EXECUTIVE'])assert.throws(()=>f.run(cmd,{orderId:id},f.role(role)),/not allowed/);
});
