import test from 'node:test';import assert from 'node:assert/strict';
import {execute} from '../shared/domain.mjs';import {scopedState} from '../server/index.mjs';import {assemblyComparisonFixture} from './domestic-assembly-fixture.mjs';
function fixture(){const f=assemblyComparisonFixture(),state=f.state,manager=state.users.find(u=>u.role==='MANAGER'),executive=state.users.find(u=>u.role==='EXECUTIVE'),bom=state.domesticBoms.find(b=>b.id===f.assemblyId),vendor=state.vendors.find(v=>v.code==='DEMO-A');const payload={bomId:bom.id,bomRevision:bom.revision,vendorId:vendor.id,assemblyQuantity:'10',lines:bom.lines.map((l,i)=>({itemId:l.itemId,rate:i?'12':'1000'})),deliveryDate:'2026-12-30',billingAddress:'Billing office, Chennai 600001',deliveryAddress:'Local test address',paymentTerms:'As agreed in local test',taxTerms:'GST extra as agreed',freightTerms:'Supplier delivery included',reason:'Local test order'};return {...f,state,manager,executive,bom,vendor,payload};}
const save=f=>execute(f.state,{type:'DOMESTIC_PO_SAVE',payload:f.payload},f.executive).state;
const run=(s,type,payload,u)=>execute(s,{type,payload},u).state;
test('executive saves derived BOM quantities/photos/prices with automatic immutable Domestic PO identity',()=>{const f=fixture();f.payload.number='FAKE';f.payload.lines[0].quantityMilli=1;f.payload.lines[0].description='FAKE';const s=save(f),o=s.domesticOrders[0];assert.equal(o.number,'FH-LAE-D-PO-1');assert.equal(o.totalMinor,1048000);assert.equal(o.lines[0].quantityMilli,10000);assert.equal(o.lines[1].quantityMilli,40000);assert.equal(o.lines[0].description,f.bom.lines[0].description);assert.equal(o.lines[0].imageAsset,f.bom.lines[0].imageAsset);assert.equal(o.status,'DRAFT');assert.equal(s.events.at(-1).action,'DOMESTIC_PO_CREATED');assert.deepEqual(f.state.domesticOrders,undefined);});
test('manager issues a frozen snapshot; executive cannot issue or cancel; cancelled order stays retained',()=>{const f=fixture(),s=save(f),o=s.domesticOrders[0],p={orderId:o.id,revision:o.revision,reason:'Reviewed local test',confirm:true};assert.throws(()=>run(s,'DOMESTIC_PO_ISSUE',p,f.executive),/Manager/);let issued=run(s,'DOMESTIC_PO_ISSUE',p,f.manager),io=issued.domesticOrders[0];assert.equal(io.status,'ISSUED');assert.equal(io.issuedSnapshot.totalMinor,1048000);assert.throws(()=>run(issued,'DOMESTIC_PO_SAVE',{...f.payload,orderId:o.id,revision:io.revision},f.manager),/cannot be edited/);const snap=structuredClone(io.issuedSnapshot);const cancelled=run(issued,'DOMESTIC_PO_CANCEL',{orderId:o.id,revision:io.revision,reason:'Supplier notified separately'},f.manager);assert.equal(cancelled.domesticOrders[0].status,'CANCELLED');assert.deepEqual(cancelled.domesticOrders[0].issuedSnapshot,snap);assert.equal(cancelled.domesticOrders[0].history.length,3);});
test('duplicate/missing/non-BOM/inactive parts, invalid amounts and quantities fail atomically',()=>{for(const mutate of [p=>p.lines=[],p=>p.lines.push(p.lines[0]),p=>p.lines[0].itemId='missing',p=>p.lines[0].rate='',p=>p.lines[0].rate='-1',p=>p.lines[0].rate='1.001',p=>p.lines[0].rate='999999999999999999999999',p=>p.assemblyQuantity='1.5',p=>p.assemblyQuantity='0',p=>p.assemblyQuantity='10001',p=>p.vendorId='missing',p=>p.deliveryDate='2026-02-30',p=>p.paymentTerms='',p=>p.taxTerms='',p=>p.freightTerms='',p=>p.reason='']){const f=fixture(),before=structuredClone(f.state);mutate(f.payload);assert.throws(()=>save(f));assert.deepEqual(f.state,before);}});
test('unconfirmed/changed BOM and changed item units cannot be ordered',()=>{let f=fixture();f.bom.compositionConfirmed=false;assert.throws(()=>save(f),/confirm/);f=fixture();f.payload.bomRevision--;assert.throws(()=>save(f),/changed/);f=fixture();f.state.domesticItems.find(i=>i.id===f.bom.lines[0].itemId).uom='SET';assert.throws(()=>save(f),/UOM changed/);f=fixture();f.bom.lines[0].quantityMilli=null;assert.throws(()=>save(f),/quantities/);});
test('quote associations are supplier/unit/price validated, manual and zero rates remain explicit',()=>{const f=fixture();f.payload.lines[0].quoteId=f.state.domesticPriceLists.find(q=>q.quoteReference==='SAMPLE-A-NEW').id;assert.ok(save(f).domesticOrders[0].lines[0].quotation);f.payload.lines[0].rate='999';assert.throws(()=>save(f),/does not match/);f.payload.lines[0].quoteId=null;f.payload.lines[0].rate='0';assert.equal(save(f).domesticOrders[0].totalMinor,48000);});
test('draft edits append history, stale saves fail and new orders never reuse numbers',()=>{const f=fixture(),s=save(f),o=s.domesticOrders[0];let t=run(s,'DOMESTIC_PO_SAVE',{...f.payload,orderId:o.id,revision:o.revision,assemblyQuantity:'5'},f.executive);assert.equal(t.domesticOrders[0].totalMinor,524000);assert.equal(t.domesticOrders[0].history[1].previous.totalMinor,1048000);assert.equal(t.domesticOrders[0].number,o.number);assert.throws(()=>run(t,'DOMESTIC_PO_SAVE',{...f.payload,orderId:o.id,revision:1},f.executive),/changed/);t=run(t,'DOMESTIC_PO_SAVE',f.payload,f.executive);assert.equal(t.domesticOrders[1].number,'FH-LAE-D-PO-2');});
test('issue requires explicit confirmation, unchanged BOM, active supplier and nonpast delivery',()=>{for(const mutate of [f=>f.confirm=false,f=>f.s.domesticBoms.find(b=>b.id===f.bom.id).revision++,f=>f.s.vendors.find(v=>v.id===f.vendor.id).status='INACTIVE',f=>f.s.domesticOrders[0].deliveryDate='2020-01-01']){const f=fixture();f.s=save(f);f.confirm=true;mutate(f);const o=f.s.domesticOrders[0];assert.throws(()=>run(f.s,'DOMESTIC_PO_ISSUE',{orderId:o.id,revision:o.revision,reason:'Approve',confirm:f.confirm},f.manager));}});
test('Domestic order read/write access never leaks to other divisions or Viewer write access',()=>{const f=fixture(),s=save(f),other={...f.executive,scopes:['LAE_IMPORT']};assert.throws(()=>run(s,'DOMESTIC_PO_SAVE',f.payload,other),/access/);assert.throws(()=>run(s,'DOMESTIC_PO_SAVE',f.payload,f.state.users.find(u=>u.role==='VIEWER')),/access/);assert.equal(scopedState(s,other).domesticOrders.length,0);assert.equal(scopedState(s,f.manager).domesticOrders.length,1);assert.ok(!JSON.stringify(scopedState(s,other).recordReferences).includes('FH-LAE-D-PO-1'));});
test('Bill to and Ship to are required, same-address resolves server-side, and legacy drafts need review',()=>{const f=fixture();f.payload.shipToSameAsBillTo=true;f.payload.deliveryAddress='Ignored client shipping text';let s=save(f),o=s.domesticOrders[0];assert.equal(o.deliveryAddress,o.billingAddress);assert.equal(o.shipToSameAsBillTo,true);f.payload.billingAddress='';assert.throws(()=>save(f),/Bill to/);f.payload.billingAddress='Billing office';f.payload.shipToSameAsBillTo=false;f.payload.deliveryAddress='';assert.throws(()=>save(f),/Ship to/);delete o.billingAddress;assert.throws(()=>run(s,'DOMESTIC_PO_ISSUE',{orderId:o.id,revision:o.revision,reason:'Issue',confirm:true},f.manager),/Bill to and Ship to/);});
test('supplier PIN and mobile are frozen with the issued PO',()=>{const f=fixture();f.vendor.pinCode='600001';f.vendor.phone='+91 9876543210';let s=save(f),o=s.domesticOrders[0];s=run(s,'DOMESTIC_PO_ISSUE',{orderId:o.id,revision:o.revision,reason:'Issue',confirm:true},f.manager);s.vendors.find(v=>v.id===f.vendor.id).phone='9999999999';assert.equal(s.domesticOrders[0].issuedSnapshot.vendor.phone,'+91 9876543210');assert.equal(s.domesticOrders[0].issuedSnapshot.vendor.pinCode,'600001');});
