import test from 'node:test';
import assert from 'node:assert/strict';
import {compareDomesticAssemblySuppliers as compare} from '../shared/domestic.mjs';
const line=(itemId,quantityMilli=1000,uom='PCS')=>({itemId,code:itemId,description:itemId,quantityMilli,uom,rateMinor:999999});
const quote=(id,vendorId,quoteDate,lines)=>({id,vendorId,vendorCode:vendorId,quoteDate,quoteReference:id,currency:'INR',lines:lines.map(([itemId,rateMinor,uom='PCS'])=>({itemId,rateMinor,uom}))});
function fixture(){return {domesticBoms:[{id:'frame',scope:'LAE_DOMESTIC',kind:'ASSEMBLY',code:'FRAME1',revision:3,compositionConfirmed:true,lines:[line('frame'),line('bush',4000)]}],domesticPriceLists:[quote('old-a','A','2026-09-20',[['frame',90000],['bush',1200]]),quote('new-a','A','2026-09-24',[['frame',100000]]),quote('b','B','2026-09-23',[['frame',95000],['bush',1500]])]};}
test('same saved assembly quantities produce exact supplier totals and reference differences without writes',()=>{const s=fixture(),before=structuredClone(s),r=compare(s,'frame',['A','B','A'],'A');assert.equal(r.cells.length,2);assert.deepEqual(r.cells.map(c=>c.totalMinor),[104800,101000]);assert.equal(r.cells[1].deltaMinor,-3800);assert.equal(r.cells[1].percentText,'-3.63%');assert.equal(r.cells[1].lowest,true);assert.equal(r.cells[0].lowest,false);assert.equal(r.rows[1].cells[0].quote.quoteReference,'old-a');assert.equal(r.rows[1].cells[0].amountMinor,4800);assert.deepEqual(s,before);assert.equal(compare(s,'frame',['B','A'],'B').cells[1].deltaMinor,3800);});
test('incomplete quote shows only priced subtotal and cannot win or supply a comparison baseline',()=>{const s=fixture();s.domesticPriceLists[2].lines.pop();const r=compare(s,'frame',['A','B'],'B');assert.equal(r.cells[1].totalMinor,null);assert.equal(r.cells[1].knownMinor,95000);assert.equal(r.cells[1].pricedParts,1);assert.equal(r.rows[1].cells[1].issue,'Not quoted');assert.ok(r.cells.every(c=>!c.lowest&&c.deltaMinor===null));});
test('unconfirmed composition, unknown quantities and empty assemblies never claim a full cost',()=>{const s=fixture();s.domesticBoms[0].compositionConfirmed=false;assert.ok(compare(s,'frame',['A','B']).cells.every(c=>!c.complete));s.domesticBoms[0].compositionConfirmed=true;s.domesticBoms[0].lines[0].quantityMilli=null;let r=compare(s,'frame',['A']);assert.equal(r.cells[0].knownMinor,4800);assert.equal(r.cells[0].totalMinor,null);assert.match(r.rows[0].cells[0].issue,/quantity/);s.domesticBoms[0].lines=[];r=compare(s,'frame',['A']);assert.equal(r.cells[0].totalMinor,null);assert.match(r.issues[0],/Add assembly parts/);});
test('units are exact and incompatible quotes do not use stale BOM rates or old matching quotes',()=>{const s=fixture();s.domesticPriceLists.push(quote('a-unit','A','2026-09-24',[['frame',1,'SET']]));const r=compare(s,'frame',['A','B'],'A');assert.equal(r.rows[0].cells[0].issue,'Different UOM');assert.equal(r.cells[0].totalMinor,null);assert.equal(r.cells[0].knownMinor,4800);assert.equal(r.cells[1].deltaMinor,null);});
test('fractional metre quantities round each part half up to paise before summing',()=>{const s=fixture();s.domesticBoms[0].lines=[line('tube',500,'Metre'),line('rope',500,'Metre')];s.domesticPriceLists=[quote('q','A','2026-09-24',[['tube',101,'Metre'],['rope',101,'Metre']])];const r=compare(s,'frame',['A']);assert.deepEqual(r.rows.map(r=>r.cells[0].amountMinor),[51,51]);assert.equal(r.cells[0].totalMinor,102);});
test('zero quotes remain real rates, equal complete totals tie and zero baseline has no percentage',()=>{const s=fixture();s.domesticPriceLists=[quote('a','A','2026-09-24',[['frame',0],['bush',0]]),quote('b','B','2026-09-24',[['frame',0],['bush',0]])];let r=compare(s,'frame',['A','B'],'A');assert.ok(r.cells.every(c=>c.complete&&c.lowest&&c.totalMinor===0&&c.percentText===null));s.domesticPriceLists[1].lines[0].rateMinor=100;r=compare(s,'frame',['A','B'],'A');assert.equal(r.cells[1].deltaMinor,100);assert.equal(r.cells[1].percentText,null);});
test('invalid rates, quantities, currencies, nested parts, duplicate parts and overflow stay incomplete',()=>{for(const rate of [null,-1,1.5,Number.MAX_SAFE_INTEGER+1]){const s=fixture();s.domesticPriceLists[1].lines[0].rateMinor=rate;assert.equal(compare(s,'frame',['A']).cells[0].complete,false);}for(const qty of [0,-1000,500,1000000001]){const s=fixture();s.domesticBoms[0].lines[0].quantityMilli=qty;assert.equal(compare(s,'frame',['A']).cells[0].complete,false);}const s=fixture();s.domesticPriceLists[1].currency='USD';assert.match(compare(s,'frame',['A']).rows[0].cells[0].issue,/INR/);s.domesticPriceLists[1].currency='INR';s.domesticPriceLists[1].lines[0].rateMinor=Number.MAX_SAFE_INTEGER;let r=compare(s,'frame',['A']);assert.equal(r.cells[0].totalMinor,null);assert.equal(r.cells[0].knownMinor,null);assert.match(r.cells[0].issue,/too large/);s.domesticBoms[0].lines[0].quantityMilli=2000;assert.match(compare(s,'frame',['A']).rows[0].cells[0].issue,/too large/);s.domesticBoms[0].lines[0].assemblyId='other';assert.match(compare(s,'frame',['A']).rows[0].cells[0].issue,/purchased parts/);s.domesticBoms[0].lines.push(line('bush'));assert.match(compare(s,'frame',['A']).issues.join(' '),/duplicate/);});
test('invalid assembly/scope/model selection rejected; empty and duplicate supplier selection safe',()=>{const s=fixture();assert.throws(()=>compare(s,'missing',['A']),/saved assembly/);s.domesticBoms[0].kind='MODEL';assert.throws(()=>compare(s,'frame',['A']),/saved assembly/);s.domesticBoms[0].kind='ASSEMBLY';s.domesticBoms[0].scope='LAE_IMPORT';assert.throws(()=>compare(s,'frame',['A']),/saved assembly/);s.domesticBoms[0].scope='LAE_DOMESTIC';assert.equal(compare(s,'frame',[]).cells.length,0);assert.equal(compare(s,'frame',['A','A'],'absent').baselineVendorId,'A');});
test('same-day last saved price wins while later upload of earlier dated quote stays historical',()=>{const s=fixture();s.domesticPriceLists.push(quote('same-day','A','2026-09-24',[['frame',80000]]),quote('late-old','A','2026-09-01',[['frame',1]]));const r=compare(s,'frame',['A']);assert.equal(r.cells[0].totalMinor,84800);assert.equal(r.rows[0].cells[0].quote.quoteReference,'same-day');});
