import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createSeed} from '../shared/seed.mjs';
import {execute,referenceConflict,documentReferenceKey,orderTotal,toMinor,convertMinor,toRate} from '../shared/domain.mjs';
import {ensureRecordReferences,referenceKey,softwareReference,integrationSnapshot} from '../shared/references.mjs';
import {orderProgress} from '../shared/order-progress.mjs';
import {Store} from '../server/store.mjs';
const setup=()=>{const state=createSeed('2026-09-11');return {state,actor:state.users.find(u=>u.role==='ADMIN')};};
const draft=(s,number)=>{const o=s.orders[0];return {type:'CREATE_ORDER',payload:{number,vendorId:o.vendorId,lines:o.lines,currency:o.currency,priceListCurrency:o.priceListCurrency,productionDays:o.productionDays,productionOverrideReason:'Test supplier commitment'}};};

test('legacy PO numbers normalize and remain reserved in current, renamed and issued history',()=>{const {state}=setup(),o=state.orders[0];delete o.numberSource;o.number='REF902';o.numberHistory=['REF 901'];o.deletedAt='2026-09-13';assert.equal(referenceConflict(state,{kind:'PO',number:'ＲＥＦ​９０１'}),true);assert.equal(referenceConflict(state,{kind:'PO',number:'ref902'}),true);assert.notEqual(documentReferenceKey('REF-901'),documentReferenceKey('REF901'));});

test('PI and invoice uniqueness is supplier-scoped and retains document history',()=>{const {state,actor}=setup(),o=state.orders.find(o=>o.pi),other=structuredClone(o);other.id='other-order';delete other.numberSource;delete other.serialNumber;other.number='OTHER-ORDER';other.pi=null;other.piHistory=[];other.documents=[];state.orders.push(other);assert.throws(()=>execute(state,{type:'RECORD_PI',payload:{orderId:other.id,number:o.pi.number}},actor),/reserved/);assert.equal(referenceConflict(state,{kind:'PI',number:o.pi.number,vendorId:'different-supplier',orderId:other.id}),false);const ship=o.shipments[0];o.documents.push({id:'invoice-history',type:'COMMERCIAL_INVOICE',shipmentId:ship?.id||null,invoiceNumber:'INV 401',invoiceDate:'2026-09-11'});assert.equal(referenceConflict(state,{kind:'INVOICE',number:'inv401',vendorId:o.vendorId,orderId:other.id}),true);assert.equal(referenceConflict(state,{kind:'INVOICE',number:'inv401',vendorId:o.vendorId,orderId:o.id,shipmentId:ship?.id||null}),false);assert.equal(referenceConflict(state,{kind:'PI',number:'INV401',vendorId:o.vendorId,orderId:other.id}),false);});

test('commercial invoice evidence requires identifiable number/date on every attachment',()=>{const {state,actor}=setup(),o=state.orders.find(o=>o.shipments.length),file=state.files.find(f=>f.orderIds.includes(o.id)),base={type:'ATTACH_DOCUMENT',payload:{orderId:o.id,shipmentId:o.shipments[0].id,type:'COMMERCIAL_INVOICE',fileId:file.id}};assert.throws(()=>execute(state,base,actor),/invoice number/);assert.throws(()=>execute(state,{...base,payload:{...base.payload,invoiceNumber:'NEW-CI',invoiceDate:'2026-02-30'}},actor),/valid/);const out=execute(state,{...base,payload:{...base.payload,invoiceNumber:'NEW-CI',invoiceDate:'2026-09-11'}},actor);const saved=out.state.orders.find(r=>r.id===o.id).documents.at(-1);assert.equal(saved.invoiceNumber,'NEW-CI');assert.ok(softwareReference(out.state,'orderDocuments',saved.id,'orders',o.id));});

test('reference registry rejects numeric alias collisions and invalid persisted mappings',()=>{const {state}=setup(),entries=Object.values(state.recordReferences.entries).filter(e=>e.type==='orders'),a=entries[0],b=entries[1];b.reference='FH-PO-'+a.reference.split('-').at(-1).padStart(6,'0');assert.throws(()=>ensureRecordReferences(state),/duplicate/);const clean=setup().state;clean.recordReferences.links.push({recordKey:'missing',system:'TALLY',companyKey:'company',externalId:'external'});assert.throws(()=>ensureRecordReferences(clean),/Invalid ERP link/);});

test('current and historical supplier PIs have stable linked software references',()=>{const {state}=setup(),o=state.orders.find(o=>o.pi),old=structuredClone(o.pi);o.piHistory.push(old);o.pi={...old,id:'replacement-pi',number:'REPLACEMENT-PI'};ensureRecordReferences(state);const first=softwareReference(state,'proformas',old.id,'orders',o.id),second=softwareReference(state,'proformas',o.pi.id,'orders',o.id);assert.ok(first&&second&&first!==second);const exported=integrationSnapshot(state).records.find(r=>r.type==='proformas'&&r.id===old.id);assert.equal(exported.parent.id,o.id);assert.equal(exported.reference,first);});

test('simultaneous stale claims consume nothing; refreshed creation allocates a distinct automatic PO',()=>{const {state,actor}=setup(),path=join(mkdtempSync(join(tmpdir(),'fh-claims-')),'db.sqlite'),one=new Store(path,state),two=new Store(path);try{const before=one.read(),out=one.transact(draft(before,'CONCURRENT-1'),actor.id,before.revision,'concurrent-request-one'),next=out.state.recordReferences.next.orders;assert.throws(()=>two.transact(draft(before,'CONCURRENT-1'),actor.id,before.revision,'concurrent-request-two'),/Another user/);assert.equal(two.read().recordReferences.next.orders,next);const current=two.read(),second=two.transact(draft(current,'CONCURRENT-1'),actor.id,current.revision,'concurrent-request-three');assert.notEqual(softwareReference(out.state,'orders',out.result.id),softwareReference(second.state,'orders',second.result.id));for(const id of [out.result.id,second.result.id])assert.equal(second.state.orders.find(o=>o.id===id).number,softwareReference(second.state,'orders',id));}finally{one.close();two.close();}});

test('lost-response command replay survives restart without duplicate PO, event or reference',()=>{const {state,actor}=setup(),path=join(mkdtempSync(join(tmpdir(),'fh-replay-')),'db.sqlite');let store=new Store(path,state);const before=store.read(),cmd=draft(before,'REPLAY-1'),first=store.transact(cmd,actor.id,before.revision,'saved-request-12345'),count=first.state.events.length;store.close();store=new Store(path);try{const retry=store.transact(cmd,actor.id,before.revision,'saved-request-12345');assert.equal(retry.replayed,true);assert.equal(retry.result.id,first.result.id);assert.equal(retry.state.events.length,count);assert.deepEqual(retry.state.recordReferences,first.state.recordReferences);assert.throws(()=>store.transact(draft(before,'CHANGED-RETRY'),actor.id,before.revision,'saved-request-12345'),/different content/);}finally{store.close();}});

test('guide prevents an executive from being directed past pending PO approval',()=>{const {state}=setup(),o=state.orders[0],executive=state.users.find(u=>u.role==='EXECUTIVE');o.status='PENDING_APPROVAL';o.revisions=[];o.pi=null;o.buyerId=executive.id;const step=orderProgress(state,o,executive);assert.equal(step.action,null);assert.equal(step.blocked,true);assert.match(step.reason,/Purchase Manager/);assert.equal(step.step,2);});

test('guide distinguishes port arrival from financial settlement and gives concrete checks',()=>{const {state,actor}=setup(),o=state.orders.find(o=>o.shipments.some(s=>s.actualArrival));assert.ok(o);for(const s of o.shipments){s.actualArrival='2026-09-11';s.status='ARRIVED';}for(const p of state.payments)for(const a of p.allocations.filter(a=>a.orderId===o.id))a.realizedMinor=null;const next=orderProgress(state,o,actor);assert.equal(next.step,12);assert.equal(next.action,'tab');assert.equal(next.complete,false);assert.match(next.checks.join(' '),/actually received/);});

test('300 crore annual aggregate and INR conversions preserve exact integer minor units',()=>{const perOrder=toMinor('300000'),annual=Array.from({length:10000},()=>orderTotal({lines:[{quantity:1,unitPriceMinor:perOrder}]})).reduce((a,b)=>a+b,0);assert.equal(annual,300000000000);assert.ok(Number.isSafeInteger(annual));assert.equal(convertMinor(annual,toRate('1')),annual);assert.equal(convertMinor(toMinor('1000000'),toRate('83.123456')),8312345600);assert.throws(()=>toMinor('300000.001'),/two decimals/);assert.throws(()=>toMinor('-1'),/non-negative/);});

test('upload retry returns one retained evidence body and software reference',()=>{const {state,actor}=setup(),path=join(mkdtempSync(join(tmpdir(),'fh-upload-replay-')),'db.sqlite'),store=new Store(path,state);try{const before=store.read(),meta={id:'upload-one',name:'proof.txt',mime:'text/plain',size:5,orderIds:[before.orders[0].id],scope:'LAE_IMPORT'},first=store.saveFile(meta,Buffer.from('proof'),before.revision,actor,'upload-retry-12345'),again={...meta,id:'upload-two'};const retry=store.saveFile(again,Buffer.from('proof'),before.revision,actor,'upload-retry-12345');assert.equal(again.id,'upload-one');assert.equal(retry.revision,first.revision);assert.deepEqual(retry.recordReferences,first.recordReferences);assert.equal(store.db.prepare('SELECT count(*) n FROM file_bodies WHERE id IN (?,?)').get('upload-one','upload-two').n,1);assert.throws(()=>store.saveFile({...meta,id:'changed'},Buffer.from('other'),retry.revision,actor,'upload-retry-12345'),/different content/);}finally{store.close();}});

test('registry rejects arrays that would lose reference properties on JSON persistence',()=>{for(const field of ['entries','next']){const {state}=setup();state.recordReferences[field]=[];assert.throws(()=>ensureRecordReferences(state),/Invalid software reference registry/);}});

test('initial INR payment cannot invent an INR-to-INR exchange gain',()=>{const {state,actor}=setup(),o=state.orders.find(o=>o.pi?.status==='APPROVED'&&o.technicalConfirmation&&o.artwork?.supplierConfirmed&&o.paymentTerms.steps.some(s=>s.trigger==='PI'));assert.ok(o);assert.throws(()=>execute(state,{type:'COMPLETE_INITIAL_PAYMENT',payload:{orderId:o.id,reference:'INR-RATE-TEST',date:'2026-09-11',currency:'INR',amount:'100',inrRate:'2'}},actor,{now:'2026-09-13T00:00:00Z'}),/INR-to-INR rate must be 1/);});
