import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../server/store.mjs';
import {emptyState} from '../server/index.mjs';
import {ImplementsStore} from '../server/implements-store.mjs';
import {blankState,ensureMonthly,createOrders} from '../shared/implements/domain.mjs';
import {applyOrderEvent,orderProgress,incomingPurchaseSummary,addSupplierQuote,compareQuotes,validateProcurementTransition} from '../shared/implements/procurement.mjs';
import {backwardCost,marginIncludingGst,compareSalesCosts} from '../shared/implements/sales-pricing.mjs';
const admin=emptyState().users.find(u=>u.id==='admin'),actor={id:admin.id,name:admin.name,role:admin.role},today=new Date().toISOString().slice(0,10);
function fixture(){const s=ensureMonthly(blankState({version:'test',parts:[{id:'bolt',code:'IMP-1',name:'Bolt',rate:10,supplier:'a',uom:'pcs'}],suppliers:[{id:'a',name:'A'},{id:'b',name:'B'}],models:[{id:'S2.V58',series:'Leader',revision:1,history:[],bomAvailable:true,lines:[{partId:'bolt',ppm:4}],fabrication:[{partId:'f',name:'Patta',ppm:4,weight:2}],fabricationSupplier:'a',costs:{}}]}));s.settings.fabricationRate=125;s.plan={'S2.V58':5};s.orders=createOrders(s,['bolt'],{date:today});return s;}
const event=(s,type,extra={})=>applyOrderEvent(s,{id:randomUUID(),poId:s.orders[0].id,type,date:today,reason:'Checked',...extra},{actor});
test('PO approval, issue, partial acknowledgment, completion and closure preserve snapshots and never over-receive',()=>{const s=fixture(),snapshot=structuredClone(s.orders);assert.throws(()=>event(s,'ACKNOWLEDGE',{reference:'D1',lines:[{key:'bolt',qty:1}]}),/Issue/);event(s,'APPROVE');event(s,'ISSUE');const before=structuredClone(s);event(s,'ACKNOWLEDGE',{reference:'D1',lines:[{key:'bolt',qty:5}]});assert.equal(s.stock.bolt.qty,5);assert.equal(incomingPurchaseSummary(s).bolt.qty,17);assert.equal(orderProgress(s,s.orders[0].id).status,'PART_DELIVERED');assert.equal(orderProgress(s,s.orders[0].id).lines[0].outstanding,17);validateProcurementTransition(before,s,actor);assert.throws(()=>event(s,'ACKNOWLEDGE',{reference:'D1',lines:[{key:'bolt',qty:1}]}),/already/);assert.throws(()=>event(s,'ACKNOWLEDGE',{reference:'D2',lines:[{key:'bolt',qty:18}]}),/outstanding/);assert.throws(()=>event(s,'CANCEL'),/Delivered/);event(s,'ACKNOWLEDGE',{reference:'D2',lines:[{key:'bolt',qty:17}]});event(s,'CLOSE');assert.equal(orderProgress(s,s.orders[0].id).status,'CLOSED');assert.equal(s.stock.bolt.qty,22);assert.deepEqual(s.orders,snapshot);});
test('authoritative acknowledgment guards actor, immutable history, exact stock and retry receipts',()=>{const dir=mkdtempSync(join(tmpdir(),'fh-procurement-'));let store;try{const initial=emptyState();store=new Store(join(dir,'db.sqlite'),initial);const mod=new ImplementsStore(store);let s=fixture();mod.save({state:s,expectedRevision:0,requestId:randomUUID(),message:'Fixture'},'admin');for(const type of ['APPROVE','ISSUE']){s=mod.read();event(s,type);mod.save({state:s,expectedRevision:s.revision,requestId:randomUUID(),message:type},'admin');}const previous=mod.read();s=structuredClone(previous);event(s,'ACKNOWLEDGE',{reference:'D1',lines:[{key:'bolt',qty:5}]});s.stock.bolt.qty=6;assert.throws(()=>mod.save({state:s,expectedRevision:previous.revision,requestId:randomUUID(),message:'Tampered'},'admin'),/exactly/);assert.equal(mod.read().stock.bolt,undefined);s=structuredClone(previous);event(s,'ACKNOWLEDGE',{reference:'D1',lines:[{key:'bolt',qty:5}]});const input={state:s,expectedRevision:previous.revision,requestId:randomUUID(),message:'Delivery'};mod.save(input,'admin');mod.save(input,'admin');assert.equal(mod.read().stock.bolt.qty,5);s=mod.read();s.procurement.events[0].reason='Edited';assert.throws(()=>mod.save({state:s,expectedRevision:s.revision,requestId:randomUUID(),message:'Tamper'},'admin'),/rewritten/);}finally{store?.close();rmSync(dir,{recursive:true,force:true});}});
test('quotes compare transport once, respect latest quote date, expiry and MOQ, and history cannot be replaced',()=>{const s=fixture();const add=(supplierId,rate,extra={})=>addSupplierQuote(s,{id:randomUUID(),key:'bolt',supplierId,reference:randomUUID(),date:'2026-01-01',validUntil:'2027-01-01',rate,transportPercent:5,transportPerUnit:1,moq:10,leadDays:7,...extra},{by:actor});const a=add('a',100),b=add('b',99);assert.equal(a.landed,106);let rows=compareQuotes(s,'bolt',{qty:20,date:'2026-10-01'});assert.equal(rows[0].id,b.id);assert.equal(rows[0].total,2099);assert.equal(compareQuotes(s,'bolt',{qty:5,date:'2026-10-01'})[0].eligible,false);add('a',90,{date:'2026-02-01',validUntil:'2026-03-01'});rows=compareQuotes(s,'bolt',{qty:20,date:'2026-10-01'});assert.equal(rows.find(r=>r.supplierId==='a').expired,true);assert.throws(()=>addSupplierQuote(s,{id:'q',key:'missing',supplierId:'a'}),/Choose/);});
test('backward target cost and user GST denominator differ from markup and saved historical costs remain distinct',()=>{assert.equal(backwardCost(100000,{factor:1.25}),80000);assert.equal(backwardCost(100000,{marginPercent:20,gstPercent:5}),79000);assert.equal(marginIncludingGst(100000,79000,5),20);assert.equal(marginIncludingGst(100000,null,5),null);assert.equal(backwardCost(100000,{marginPercent:20}),null);assert.throws(()=>backwardCost(100,{marginPercent:99,gstPercent:100}),/exceeds/);const s=fixture();s.sales={lists:[{id:'old',rows:[{modelId:'S2.V58',price:100,cost:70,partsCost:30,fabricationCost:35,otherCost:5}]},{id:'new',rows:[{modelId:'S2.V58',price:110,cost:75,partsCost:34,fabricationCost:36,otherCost:5}]}]};const r=compareSalesCosts(s,'old','new')[0];assert.equal(r.costChange,5);assert.equal(r.partsChange+r.fabricationChange+r.otherChange,r.costChange);assert.equal(r.priceChange,10);});

test('approval requires a manager, canceled drafts never enter incoming coverage, and quote histories reject tampering',()=>{const s=fixture(),input={id:randomUUID(),poId:s.orders[0].id,type:'APPROVE',date:today,reason:'Reviewed'};assert.throws(()=>applyOrderEvent(s,input,{actor:{id:'operator',name:'Operator',role:'OPERATOR'}}),/manager/);event(s,'CANCEL');assert.deepEqual(incomingPurchaseSummary(s),{});const before=structuredClone(s);addSupplierQuote(s,{id:randomUUID(),key:'bolt',supplierId:'a',reference:'Q1',date:today,validUntil:today,rate:100,transportPercent:5,transportPerUnit:0,moq:1,leadDays:7},{by:actor});validateProcurementTransition(before,s,actor);const old=structuredClone(s);s.procurement.quotes[0].rate=1;assert.throws(()=>validateProcurementTransition(old,s,actor),/rewritten/);});
