import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {buildLandingPricesXlsx,buildLandingPricesPdf} from '../server/landing-price-exports.mjs';
import {queryLandingPrices} from '../shared/landing-prices.mjs';
const python=process.env.FH_PYTHON||'python3',available=spawnSync(python,['-c','import openpyxl,reportlab'],{windowsHide:true,stdio:'ignore'}).status===0;
const row=(id,overrides={})=>({id:'row-'+id,ro:'TEST-'+id,inwardDate:'2026-09-19',vendorName:'=1+1',itemName:'Synthetic machine '+id,masterCode:'PW8',brandCode:'GJ-PW8',brand:'GAJA',usdUnit:20,aiInrPerUsd:110,inrUnitBeforeGst:2200,quantity:10,unit:'PCS',status:'Provisional reference',invoice:'CI-TEST-'+id,...overrides});
function report(){return queryLandingPrices([row('2',{itemName:'Long description '.repeat(30)}),row('1',{usdUnit:null,aiInrPerUsd:null,inrUnitBeforeGst:null,quantity:7}),row('3',{unit:'SETS',quantity:2}),row('4',{usdUnit:0,inrUnitBeforeGst:0,quantity:1})],{page:'2',pageSize:'1',sort:'ro',direction:'asc',year:'2026'},{totalRos:4},{exportAll:true});}
const inspectXlsx=bytes=>{
 const result=spawnSync(python,['-c',`import sys,io,json,openpyxl\nw=openpyxl.load_workbook(io.BytesIO(sys.stdin.buffer.read()),data_only=False);s=w.active\nprint(json.dumps({'rows':[[str(c.value) if getattr(c,'is_date',False) else c.value for c in r] for r in s.iter_rows()], 'formulaCells':[c.coordinate for r in s for c in r if c.data_type=='f'], 'types':[[c.data_type for c in r] for r in s.iter_rows(min_row=7,max_row=10)],'formats':[[c.number_format for c in r] for r in s.iter_rows(min_row=7,max_row=10)],'heights':{str(i):s.row_dimensions[i].height for i in range(7,11)},'freeze':s.freeze_panes,'table':list(s.tables.values())[0].ref,'links':[s.cell(i,1).hyperlink.target for i in range(7,11)]}))`],{input:bytes,windowsHide:true,maxBuffer:2e6});assert.equal(result.status,0,result.stderr.toString());return JSON.parse(result.stdout.toString());
};
test('download builders reject a page-only payload before starting work',async()=>{const r=report();r.rows=r.rows.slice(0,1);await assert.rejects(buildLandingPricesXlsx(r),/complete filtered result/);await assert.rejects(buildLandingPricesPdf(r),/complete filtered result/);});
test('Excel download contains all selected sorted lines, numeric amounts, pending values and safe literal source text',{skip:!available},async()=>{
 const r=report(),bytes=await buildLandingPricesXlsx(r);assert.equal(bytes.subarray(0,2).toString(),'PK');const result=inspectXlsx(bytes),body=result.rows.slice(6,10);
 assert.deepEqual(body.map(values=>values[0]),['TEST-1','TEST-2','TEST-3','TEST-4']);assert.equal(body[0][7],'Pending');assert.equal(body[0][8],'Pending');assert.equal(body[0][9],'Pending');assert.equal(body[1][7],20);assert.equal(body[1][8],110);assert.equal(body[1][9],2200);assert.equal(body[3][7],0);assert.equal(body[3][9],0);
 assert.deepEqual(result.formulaCells,[]);assert.equal(body[1][2],'=1+1');assert.equal(result.types[1][2],'s');assert.equal(result.types[1][7],'n');assert.equal(result.formats[1][8],'#,##0.0000');assert.equal(result.table,'A6:N10');assert.equal(result.freeze,'D7');assert.ok(result.heights['8']>100);assert.match(result.links[0],/#\/ro-costings\/TEST-1$/);
 const pcs=result.rows.find(values=>values[0]==='pcs'),sets=result.rows.find(values=>values[0]==='sets');assert.equal(pcs[2],18);assert.equal(pcs[3],11);assert.equal(pcs[4],7);assert.ok(Math.abs(pcs[5]-200/11)<1e-10);assert.equal(pcs[6],110);assert.ok(Math.abs(pcs[7]-22000/11)<1e-10);assert.equal(sets[2],2);assert.equal(sets[5],20);
});
test('PDF download generates full sorted report and separate unit summary',{skip:!available},async()=>{const r=report(),bytes=await buildLandingPricesPdf(r);assert.equal(bytes.subarray(0,5).toString(),'%PDF-');assert.ok(bytes.length>5000);const text=bytes.toString('latin1');assert.match(text,/LAE Landing Prices/);assert.match(text,/\/Type \/Page/);});
