import test from 'node:test';
import assert from 'node:assert/strict';
import {createSeed} from '../shared/seed.mjs';
import {execute} from '../shared/domain.mjs';
import {pendingLoadingRows} from '../shared/shipping.mjs';

function fixture(){const s=createSeed('2026-09-11');s.orders=s.orders.slice(0,3);s.payments=[];const [a,b,c]=s.orders;b.vendorId=a.vendorId;c.vendorId=s.vendors.find(v=>v.kind==='SUPPLIER'&&v.id!==a.vendorId).id;for(const o of s.orders){o.pi={...o.pi,status:'APPROVED'};o.productionStartedAt='2026-09-01';o.manualClosed=false;o.shipments=[];}const u=s.users.find(u=>u.role==='MANAGER'),p={loadingMode:'SINGLE_ORDER',vendorId:a.vendorId,orderId:a.id,etd:'2026-10-01',eta:'2026-10-20',origin:'CHINA',destination:'CHENNAI',remarks:'Loading test',orders:[{orderId:a.id,lines:[{lineId:a.lines[0].id,quantity:2}]}]};let n=0;const run=(type,payload,state=s,user=u)=>execute(state,{type,payload},user,{now:'2026-09-26T16:00:00Z',id:()=>`lp-${++n}`});return {s,a,b,c,p,u,run};}
test('plan reserves checked quantities before separate RO assignment; original finance unchanged',()=>{const {s,a,p,run}=fixture(),r=run('PLAN_LOADING',p),o=r.state.orders[0],ship=o.shipments[0];assert.equal(ship.lines[0].quantity,2);assert.equal(ship.roGroupId,undefined);assert.equal(ship.forwarderRef,'');assert.deepEqual(o.lines,a.lines);assert.deepEqual(o.pi,a.pi);assert.deepEqual(r.state.payments,s.payments);assert.equal(pendingLoadingRows(r.state.orders)[0].unallocated,a.lines[0].quantity-2);const linked=run('PLAN_RO_LOADING',{roNumber:'RO-1',remarks:'Single plan',orders:[{orderId:a.id,shipmentId:ship.id}]},r.state);assert.equal(linked.state.orders[0].shipments.length,1);assert.equal(linked.state.orders[0].shipments[0].roNumber,'RO-1');});
test('loading modes enforce supplier/order selection and reject cross-scope hidden selections',()=>{const {a,b,c,p,run}=fixture(),entry=o=>({orderId:o.id,lines:[{lineId:o.lines[0].id,quantity:1}]});assert.throws(()=>run('PLAN_LOADING',{...p,orders:[entry(a),entry(c)]}),/Single-order/);assert.throws(()=>run('PLAN_LOADING',{...p,loadingMode:'MULTIPLE_ORDERS'}),/at least two/);assert.throws(()=>run('PLAN_LOADING',{...p,loadingMode:'MULTIPLE_ORDERS',orders:[entry(a),entry(c)]}),/selected supplier/);assert.equal(run('PLAN_LOADING',{...p,loadingMode:'MULTIPLE_ORDERS',orders:[entry(a),entry(b)]}).result.members.length,2);assert.throws(()=>run('PLAN_LOADING',{...p,loadingMode:'MULTIPLE_SUPPLIERS',orders:[entry(a),entry(b)]}),/at least two suppliers/);assert.equal(run('PLAN_LOADING',{...p,loadingMode:'MULTIPLE_SUPPLIERS',orders:[entry(a),entry(c)]}).result.members.length,2);});
test('invalid quantity, duplicate line/order, closed or ineligible order and unauthorized user do not save',()=>{const {s,a,p,run}=fixture(),before=structuredClone(s);for(const q of [0,-1,1.5,999999])assert.throws(()=>run('PLAN_LOADING',{...p,orders:[{orderId:a.id,lines:[{lineId:a.lines[0].id,quantity:q}]}]}));assert.throws(()=>run('PLAN_LOADING',{...p,orders:[p.orders[0],p.orders[0]]}));assert.throws(()=>run('PLAN_LOADING',{...p,orders:[{...p.orders[0],lines:[p.orders[0].lines[0],p.orders[0].lines[0]]}]}));for(const patch of [{pi:{status:'RECEIVED'}},{productionStartedAt:null},{manualClosed:true}]){const x=structuredClone(s);Object.assign(x.orders[0],patch);assert.throws(()=>run('PLAN_LOADING',p,x));}assert.throws(()=>run('PLAN_LOADING',p,s,s.users.find(u=>u.role==='VIEWER')),/access/);assert.deepEqual(s,before);});
test('multiple saved partial plans from one PO can share an RO without double allocation',()=>{const {a,p,run}=fixture(),first=run('PLAN_LOADING',p).state,second=run('PLAN_LOADING',p,first).state,orders=second.orders[0].shipments.map(s=>({orderId:a.id,shipmentId:s.id})),linked=run('PLAN_RO_LOADING',{roNumber:'RO-SPLIT',remarks:'Combine saved partials',orders},second).state;assert.equal(linked.orders[0].shipments.length,2);assert.equal(new Set(linked.orders[0].shipments.map(s=>s.roGroupId)).size,1);assert.equal(pendingLoadingRows(linked.orders)[0].allocated,4);assert.throws(()=>run('PLAN_RO_LOADING',{roNumber:'RO-DUP',remarks:'Duplicate',orders:[orders[0],orders[0]]},second),/Duplicate/);});
test('available, reserved, loaded and departed quantities remain disjoint; remarks do not fake departure',()=>{const {a,p,run}=fixture(),s=run('PLAN_LOADING',p).state,o=s.orders[0],ship=o.shipments[0];ship.bookingStatus='RELEASED';ship.trackingMilestones=[{key:'RELEASED',status:'COMPLETED',actualDate:'2026-09-24',remarks:'Loading completed'}];let r=pendingLoadingRows([o])[0];assert.equal(r.reserved,2);assert.equal(r.containerLoaded,0);ship.trackingMilestones.push({key:'FACTORY_LOADING',status:'COMPLETED',actualDate:'2026-09-25'});r=pendingLoadingRows([o])[0];assert.equal(r.reserved,0);assert.equal(r.containerLoaded,2);ship.actualDeparture='2026-09-26';r=pendingLoadingRows([o])[0];assert.equal(r.containerLoaded,0);assert.equal(r.departed,2);assert.equal(r.unallocated+r.reserved+r.containerLoaded+r.departed,a.lines[0].quantity);ship.status='CANCELLED';r=pendingLoadingRows([o])[0];assert.equal(r.allocated,0);assert.equal(r.unallocated,a.lines[0].quantity);});
