/** Synthetic accounts only. Browser mutations in native and standalone modes. */
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Store} from '../server/store.mjs';
import {makeServer} from '../server/index.mjs';
import {createSeed} from '../shared/seed.mjs';
import {APPROVAL_STAGES} from '../shared/domain.mjs';
const out=resolve('test-output','manager-setup',new Date().toISOString().replace(/[:.]/g,'-'));mkdirSync(out,{recursive:true});
const seed=createSeed('2026-09-13'),manager=seed.users.find(u=>u.role==='MANAGER');seed.users.push({...manager,id:'u-second-manager',name:'Second isolated Manager'});
const base=seed.bases.find(b=>b.specifications?.length);for(const suffix of ['first','second'])base.specifications.push({...base.specifications[0],id:'reject-'+suffix,version:'QA-'+suffix,status:'PENDING'});
const booking=seed.orders.find(o=>o.shipments.length);booking.productionStartedAt='2026-09-13';const ship=booking.shipments[0];Object.assign(ship,{status:'PLANNED',bookingStatus:'PLANNED',actualDeparture:null,actualArrival:null,origin:'QA ORIGIN',via:'',destination:'QA DESTINATION',containerType:'1X20GP',rateRouteKey:''});
const password='Isolated-manager-setup-1234',store=new Store(join(out,'test.sqlite'),seed),server=makeServer(store);for(const id of ['u-admin',manager.id,'u-second-manager'])store.addAccount(id,id+'@example.test',password);
const report={checks:[],errors:[],out};let browser,context,page;
const check=(name,ok)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS '+name);};
try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const {chromium}=await import(pathToFileURL(resolve('test-output/ui-tools/node_modules/playwright/index.mjs')).href);browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 for(const mode of ['server','review']){
  context=await browser.newContext({viewport:{width:1440,height:1000}});await context.tracing.start({screenshots:true,snapshots:true});page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.errors.push(e.message));
  const root=mode==='server'?'http://127.0.0.1:'+server.address().port:pathToFileURL(resolve('Farming_Hub_Purchase_Management_Clean_Review.html')).href;
  await page.goto(root+'#/settings');if(mode==='review'){await page.evaluate(s=>{localStorage.setItem('fh-purchase-alpha15-clean-schema7',JSON.stringify(s));localStorage.setItem('fh-purchase-alpha15-clean-schema7-user','u-admin');},seed);await page.reload();}
  const read=async()=>mode==='server'?store.read():page.evaluate(()=>JSON.parse(localStorage.getItem('fh-purchase-alpha15-clean-schema7')));
  const login=async id=>{if(mode==='review'){await page.locator('#demo-role').selectOption(id);return;}if(await page.getByRole('button',{name:'Sign out',exact:true}).count())await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByLabel(/^Email/).fill(id+'@example.test');await page.getByLabel(/^Password/).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('.sidebar').waitFor();};
  const fill=async(name,value)=>page.locator('#dialog-form [name="'+name+'"]').fill(String(value));
  const submit=async()=>{await page.locator('#dialog-form button[type=submit]').click();await page.getByRole('dialog').waitFor({state:'hidden'});};
  const upload=async(selector,filename,content)=>page.locator(selector).setInputFiles({name:filename,mimeType:'text/csv',buffer:Buffer.from(content)});
  if(mode==='server')await login('u-admin');await page.getByRole('button',{name:'Manage approval controls',exact:true}).click();await page.getByRole('button',{name:'Enable independent Manager workflow',exact:true}).click();
  for(const stage of APPROVAL_STAGES)assert.ok(await page.locator('[name=approval-'+stage.command+'][value=MANAGER]').isChecked());
  check(mode+': preset includes all 13 Manager stages without saving',!(await read()).approvalControls);await page.locator('[name=confirm]').check();await submit();check(mode+': Admin saves auditable coverage',(await read()).approvalControls.revision===1);
  for(const [id,suffix] of [[manager.id,'first'],['u-second-manager','second']]){
   await login(id);await page.goto(root+'#/settings');check(mode+': '+id+' sees all allowed stages',await page.locator('.panel').filter({hasText:'Your workflow access'}).locator('tbody tr').count()===13 && !(await page.locator('.panel').filter({hasText:'Your workflow access'}).innerText()).includes('Not assigned'));
   check(mode+': '+id+' cannot change users or policy',await page.locator('[data-action=approval-controls],[data-action=create-user],[data-action=change-role]').count()===0);
   await page.goto(root+'#/product/'+base.id);await page.locator('[data-action=reject-spec][data-spec=reject-'+suffix+']').click();await fill('remarks','Synthetic correction test: manager can return technical revision');await submit();check(mode+': '+id+' rejects technical revision with own audit',(await read()).events.some(e=>e.action==='SPEC_REJECTED'&&e.actorId===id));
  }
  await page.goto(root+'#/vendors');await page.getByRole('button',{name:'Upload vendors',exact:true}).click();
  const vendorCsv='code,vendorSerial,fixedSupplierCode,name,kind,status,defaultTerms,defaultPriceListCurrency,defaultBillingCurrency,defaultPaymentMethod,productionDays\nV99,Q99,QATM,Invalid,SUPPLIER,ACTIVE,30-70,CNY,USD,TT,60';
  await upload('#master-import-file','invalid.csv',vendorCsv);await page.getByText('code must match vendorSerial-fixedSupplierCode',{exact:false}).waitFor();check(mode+': rejected vendor preview disables commit',await page.locator('#dialog-form [type=submit]').isDisabled());
  await upload('#master-import-file','vendors.csv',vendorCsv.replace('V99,Q99,QATM,Invalid','V99-QATM,V99,QATM,QA synthetic supplier'));await page.locator('#dialog-form [type=submit]:enabled').waitFor();await submit();
  const v=(await read()).vendors.find(v=>v.code==='V99-QATM');check(mode+': Manager imports vendor',!!v);await page.locator('[data-action=vendor-view][data-vendor="'+v.id+'"]').click();await page.getByText('Change history',{exact:true}).waitFor();await page.locator('.timeline-event summary').click();check(mode+': vendor exposes actor and before/after',(await page.getByRole('dialog').innerText()).includes('Second isolated Manager')&&(await page.getByRole('dialog').innerText()).includes('previous'));await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.goto(root+'#/items');await page.getByRole('button',{name:'Upload item master',exact:true}).click();const category=seed.categories.find(c=>c.active).name;
  await upload('#item-import-file','items.csv','ITEM CODE,ITEM NAME,VENDOR CODE,PRODUCT CATEGORY,PRODUCTION DAYS\nGJ-QAMASTER,QA imported item,V99-QATM,'+category+',60');await page.locator('#dialog-form [type=submit]:enabled').waitFor();await submit();await page.locator('.tab[data-value=items]').click();await page.locator('#view-search').fill('GJ-QAMASTER');check(mode+': imported unmapped item has setup control',await page.getByRole('button',{name:'Set up item',exact:true}).count()===1);
  await page.getByRole('button',{name:'Set up item',exact:true}).click();await page.getByRole('button',{name:'Create base product first',exact:true}).click();
  await fill('code','QAMASTER');await fill('productName','QA new product');await fill('family','QA series');await fill('creationReason','Synthetic independent Manager setup');await page.locator('[name=category]').selectOption(category);await page.locator('[name=vendorId]').selectOption(v.id);const template=seed.plmTemplates.find(t=>t.category==='*');await page.locator('[name=templateId]').selectOption(template.id);await submit();
  const newBase=(await read()).bases.find(b=>b.code==='QAMASTER');await page.goto(root+'#/items');await page.locator('.tab[data-value=items]').click();await page.locator('#view-search').fill('GJ-QAMASTER');await page.getByRole('button',{name:'Set up item',exact:true}).click();await page.locator('[name=baseId]').selectOption(newBase.id);await page.locator('[name=brand]').selectOption(seed.brands.find(b=>b.prefix==='GJ').name);await submit();
  const newItem=(await read()).items.find(i=>i.code==='GJ-QAMASTER');await page.goto(root+'#/product/'+newBase.id);await page.locator('[data-action=approve-brand-delta][data-item="'+newItem.id+'"]').first().click();await page.locator('[data-action=approve-brand-delta][data-item="'+newItem.id+'"]').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'New technical revision',exact:true}).click();await fill('version','1.0');await fill('changeSummary','QA initial specification');await fill('reason','Synthetic new product workflow');for(const field of template.fields.filter(f=>f.active!==false&&f.required)){if(field.type==='select')await page.locator('[name="plmfield-'+field.key+'"]').selectOption(field.options[0]);else await fill('plmfield-'+field.key,'QA '+field.label);}await submit();await page.locator('[data-action=approve-spec]').first().click();await page.locator('[data-action=approve-spec]').waitFor({state:'hidden'});
  await page.locator('[data-action=brand-artwork][data-item="'+newItem.id+'"]').first().click();await fill('remarks','Synthetic brand artwork');await upload('#dialog-form [name=file]','artwork.txt','QA artwork');await submit();await page.locator('[data-action=approve-brand-artwork][data-item="'+newItem.id+'"]').first().click();await page.locator('[data-action=approve-brand-artwork][data-item="'+newItem.id+'"]').waitFor({state:'hidden'});
  const mapped=(await read()).items.find(i=>i.id===newItem.id);check(mode+': new supplier to ERP to technical/brand/artwork approvals needs no role handoff',mapped.baseId===newBase.id&&mapped.brandDeltaStatus==='APPROVED'&&mapped.artworkRevisions.at(-1).status==='APPROVED'&&(await read()).bases.find(b=>b.id===newBase.id).specifications.at(-1).status==='APPROVED');
  await page.goto(root+'#/prices');await page.getByRole('button',{name:'Upload prices',exact:true}).click();const supplier=seed.vendors.find(v=>v.id===base.vendorId);
  await upload('#master-import-file','prices.csv','vendorCode,baseItemCode,currency,unitPrice,effectiveDate\n'+supplier.code+','+base.code+',USD,12.34,2026-09-13');await page.locator('#dialog-form [type=submit]:enabled').waitFor();await submit();check(mode+': price append and source retained',(await read()).priceImports.at(-1).sourceFileId&&(await read()).priceLists.at(-1).unitPriceMinor===1234);
  await page.goto(root+'#/order/'+booking.id);await page.locator('.tab[data-value=shipments]').click();await page.locator('.ship-actions [data-action=container-book][data-shipment="'+ship.id+'"]').click();await page.getByRole('button',{name:'Add supplied benchmark',exact:true}).click();await fill('oceanFreight','2000');await fill('schedule','QA supplied quote only');await upload('#dialog-form [name=file]','quote.txt','Synthetic freight quote');await page.locator('#dialog-form [type=submit]').click();await page.getByRole('heading',{name:'Container booking',exact:true}).waitFor();
  const rate=(await read()).freightRates.at(-1);check(mode+': missing benchmark recovery uses supplied quote and existing charge',rate.benchmarkUsd===2060&&rate.containerType==='1X20GP'&&!!rate.sourceFileId);check(mode+': new benchmark selectable after returning to booking',await page.locator('[name=rateRouteKey] option[value="'+rate.routeKey+'"]').count()===1);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(out,mode+'-booking-mobile.png'),fullPage:true});await context.tracing.stop({path:join(out,mode+'-trace.zip')});await context.close();context=null;
 }
 check('No browser runtime errors',report.errors.length===0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e.stack||e);console.error(report.failure);if(page){await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});writeFileSync(join(out,'failure-page.txt'),await page.locator('body').innerText().catch(()=>''));}process.exitCode=1;}
finally{await context?.tracing.stop({path:join(out,'failure-trace.zip')}).catch(()=>{});await browser?.close();await new Promise(r=>server.close(r));store.close();writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));console.log('Evidence: '+out);}
