import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../server/store.mjs';
import {makeServer} from '../server/index.mjs';
import {createSeed} from '../shared/seed.mjs';
const oldPassword='Test-only-password-0123',newPassword='Replacement-test-only-0123';
const input=(f,extra={})=>({userId:'u-product',password:newPassword,confirmPassword:newPassword,remarks:'Isolated account recovery',confirm:true,expectedRevision:f.store.read().revision,requestId:crypto.randomUUID(),...extra});
async function serverFixture(){const dir=mkdtempSync(join(tmpdir(),'fh-test-')),s=createSeed('2026-09-11');s.users.push({id:'u-utility',name:'Utility-only test viewer',role:'VIEWER',scopes:['UTILITY_DOMESTIC'],active:true});const store=new Store(join(dir,'test.sqlite'),s);for(const id of['u-admin','u-manager','u-exec','u-product','u-viewer','u-utility'])store.addAccount(id,id+'@example.test','Test-only-password-0123');const server=makeServer(store);await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;async function req(path,{method='GET',payload,token,csrf,originHeader=origin}={}){const res=await fetch(origin+path,{method,headers:{'Content-Type':'application/json',...(method!=='GET'?{Origin:originHeader}:{}),...(token?{Cookie:'fh_session='+token}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},...(payload!==undefined?{body:JSON.stringify(payload)}:{})});const text=await res.text();let data;try{data=JSON.parse(text);}catch{data=text;}return {status:res.status,data,headers:res.headers};}async function login(id='u-manager'){const r=await req('/api/login',{method:'POST',payload:{email:id+'@example.test',password:'Test-only-password-0123'}});const token=r.headers.get('set-cookie').match(/fh_session=([^;]+)/)[1],b=await req('/api/bootstrap',{token});return {token,csrf:b.data.csrf,state:b.data.state,user:b.data.user,cookie:r.headers.get('set-cookie')};}return{store,req,login,origin,close:async()=>{await new Promise(r=>server.close(r));store.close();rmSync(dir,{recursive:true,force:true});}};}
test('admin password reset revokes only target sessions, retains identity and business records, and safely replays',async()=>{
 const f=await serverFixture();try{const admin=await f.login('u-admin'),target=await f.login('u-product');await f.login('u-product');const before=f.store.read(),payload=input(f),out=await f.req('/api/users/reset-password',{method:'POST',...admin,payload});assert.equal(out.status,200,JSON.stringify(out.data));assert.equal(out.data.result.sessionsRevoked,2);assert.equal(out.data.result.reauthRequired,false);assert.equal(f.store.session(target.token),null);assert.ok(f.store.session(admin.token));assert.equal(f.store.login('u-product@example.test',oldPassword),null);assert.ok(f.store.login('u-product@example.test',newPassword));const after=f.store.read();assert.deepEqual(after.users,before.users);for(const key of Object.keys(before).filter(k=>!['revision','events'].includes(k)))assert.deepEqual(after[key],before[key],key);assert.equal(after.revision,before.revision+1);assert.equal(after.events.at(-1).action,'USER_PASSWORD_RESET');const receipts=f.store.db.prepare('SELECT * FROM request_receipts').all();for(const value of [out.data,after,receipts])for(const secret of [newPassword,oldPassword,'password_hash'])assert.ok(!JSON.stringify(value).includes(secret));const replay=await f.req('/api/users/reset-password',{method:'POST',...admin,payload});assert.equal(replay.status,200);assert.deepEqual(f.store.read(),after);assert.equal(f.store.db.prepare('SELECT count(*) n FROM sessions WHERE account_id=?').get('u-product').n,1);assert.equal((await f.req('/api/users/reset-password',{method:'POST',...admin,payload:{...payload,password:'Different-test-only-0123',confirmPassword:'Different-test-only-0123'}})).status,409);assert.equal((await f.req('/api/users/reset-password',{method:'POST',...admin,payload:{...payload,remarks:'Changed reason'}})).status,409);
 const later=input(f,{password:'Later-test-only-0123',confirmPassword:'Later-test-only-0123'});assert.equal((await f.req('/api/users/reset-password',{method:'POST',...admin,payload:later})).status,200);assert.equal((await f.req('/api/users/reset-password',{method:'POST',...admin,payload})).status,409);assert.ok(f.store.login('u-product@example.test','Later-test-only-0123'));
 }finally{await f.close();}
});
test('password reset rejects invalid, stale and unauthorized requests without changing credentials or sessions',async()=>{
 const f=await serverFixture();try{const admin=await f.login('u-admin'),target=await f.login('u-product'),before=f.store.read(),hash=f.store.db.prepare('SELECT password_hash FROM accounts WHERE id=?').get('u-product').password_hash;
 for(const extra of [{password:'short',confirmPassword:'short'},{confirmPassword:'mismatch'},{confirm:false},{remarks:''},{remarks:newPassword},{expectedRevision:before.revision-1},{password_hash:'injected'},{userId:'missing'}]){assert.throws(()=>f.store.resetUserPassword(input(f,extra),'u-admin'));assert.deepEqual(f.store.read(),before);assert.equal(f.store.db.prepare('SELECT password_hash FROM accounts WHERE id=?').get('u-product').password_hash,hash);assert.ok(f.store.session(target.token));}
 for(const id of ['u-manager','u-product','u-viewer']){const actor=await f.login(id);assert.equal((await f.req('/api/users/reset-password',{method:'POST',...actor,payload:input(f)})).status,403);}
 assert.equal((await f.req('/api/users/reset-password',{method:'POST',token:admin.token,payload:input(f)})).status,403);assert.equal((await f.req('/api/users/reset-password',{method:'POST',...admin,originHeader:'https://evil.test',payload:input(f)})).status,403);assert.equal((await f.req('/api/users/reset-password',{method:'POST',payload:input(f)})).status,401);assert.deepEqual(f.store.read(),before);
 }finally{await f.close();}
});
test('self password change requires current password and clears the authenticated cookie',async()=>{
 const f=await serverFixture();try{const admin=await f.login('u-admin');let payload=input(f,{userId:'u-admin'});assert.equal((await f.req('/api/users/reset-password',{method:'POST',...admin,payload})).status,400);const out=await f.req('/api/users/reset-password',{method:'POST',...admin,payload:{...payload,currentPassword:oldPassword}});assert.equal(out.status,200);assert.equal(out.data.result.reauthRequired,true);assert.match(out.headers.get('set-cookie'),/Max-Age=0/);assert.equal((await f.req('/api/bootstrap',admin)).status,401);assert.ok(f.store.login('u-admin@example.test',newPassword));}finally{await f.close();}
});
test('credential and session changes roll back if audit commit fails; profile-only users cannot be reset',async()=>{
 const f=await serverFixture();try{const target=await f.login('u-product'),before=f.store.read(),hash=f.store.db.prepare('SELECT password_hash FROM accounts WHERE id=?').get('u-product').password_hash;f.store.db.exec("CREATE TRIGGER fail_password_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'isolated audit failure'); END;");assert.throws(()=>f.store.resetUserPassword(input(f),'u-admin'),/audit failure/);assert.deepEqual(f.store.read(),before);assert.equal(f.store.db.prepare('SELECT password_hash FROM accounts WHERE id=?').get('u-product').password_hash,hash);assert.ok(f.store.session(target.token));f.store.db.exec('DROP TRIGGER fail_password_audit');f.store.db.prepare('DELETE FROM sessions WHERE account_id=?').run('u-viewer');f.store.db.prepare('DELETE FROM accounts WHERE id=?').run('u-viewer');assert.throws(()=>f.store.resetUserPassword(input(f,{userId:'u-viewer'}),'u-admin'),/no sign-in/);}finally{await f.close();}
});
test('password reset endpoint limits repeated attempts',async()=>{const f=await serverFixture();try{const admin=await f.login('u-admin');for(let i=0;i<10;i++)assert.equal((await f.req('/api/users/reset-password',{method:'POST',...admin,payload:input(f,{confirm:false})})).status,400);assert.equal((await f.req('/api/users/reset-password',{method:'POST',...admin,payload:input(f)})).status,429);}finally{await f.close();}});
