import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createSeed} from '../shared/seed.mjs';
import {Store} from '../server/store.mjs';
import {makeServer} from '../server/index.mjs';
import {financials} from '../shared/domain.mjs';
const out=resolve(process.env.FH_TEST_OUTPUT_ROOT||'test-output','payment-rates',new Date().toISOString().replace(/[:.]/g,'-'));mkdirSync(out,{recursive:true});
const seed=createSeed('2026-09-12'),o=structuredClone(seed.orders.find(o=>o.pi?.status==='APPROVED'&&o.artwork.current));
Object.assign(o,{currency:'USD',status:'ISSUED',shipments:[],manualClosed:null,preproductionSample:null,productionWindowStartedAt:null,productionStartedAt:null,productionCompletedAt:null});o.pi.currency='USD';o.confirmation={revision:o.revision};o.technicalConfirmation={revision:o.revision};o.artwork.pending=null;o.artwork.supplierConfirmed={artworkId:o.artwork.current.id};
seed.orders=[o];seed.payments=[];seed.events=[];seed.files=[];seed.costs=[];
const store=new Store(join(out,'test.sqlite'),seed);store.addAccount('u-manager','rates@example.test','Rates-browser-test-1234');const server=makeServer(store),report={checks:[],errors:[],out};let browser,context,page;
const check=(label,ok=true)=>{assert.ok(ok,label);report.checks.push(label);console.log('PASS '+label);};
try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const {chromium}=await import(pathToFileURL(resolve('test-output/ui-tools/node_modules/playwright/index.mjs')).href);browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 for(const mode of ['server','review']){
  context=await browser.newContext({viewport:{width:1440,height:1000}});await context.tracing.start({screenshots:true,snapshots:true});page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>report.errors.push(e.message));
  const root=mode==='server'?'http://127.0.0.1:'+server.address().port:pathToFileURL(resolve('Farming_Hub_Purchase_Management_Clean_Review.html')).href;
  await page.goto(root+'#/order/'+o.id);
  if(mode==='server'){await page.getByLabel(/^Email/).fill('rates@example.test');await page.getByLabel(/^Password/).fill('Rates-browser-test-1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();}
  else{await page.evaluate(s=>{localStorage.setItem('fh-purchase-alpha15-clean-schema7',JSON.stringify(s));localStorage.setItem('fh-purchase-alpha15-clean-schema7-user','u-manager');},seed);await page.reload();}
  const read=()=>mode==='server'?store.read():page.evaluate(()=>JSON.parse(localStorage.getItem('fh-purchase-alpha15-clean-schema7')));
  const proof=async()=>page.locator('#dialog-form input[type=file]').setInputFiles({name:'bank-proof.txt',mimeType:'text/plain',buffer:Buffer.from('Isolated rate test evidence')});
  const save=async()=>{await page.locator('#dialog-form button[type=submit]').click();await page.locator('#dialog-form').waitFor({state:'detached'});};
  await page.locator('.head-actions [data-action=initial-payment]').click();check(mode+': initial payment uses Indian bank label',await page.getByLabel(/^USD to INR \(Indian bank\)/).isVisible());
  await page.locator('[name=currency]').selectOption('CNY');check(mode+': initial labels follow RMB remittance currency',await page.getByLabel(/^RMB to INR \(Indian bank\)/).isVisible()&&!await page.locator('[name=bocUsdRmbRate]').isVisible());await page.locator('[name=currency]').selectOption('USD');check(mode+': BOC remains optional',!await page.locator('[name=bocUsdRmbRate]').evaluate(e=>e.required));
  await page.locator('[name=reference]').fill('RATES-INITIAL');await page.locator('[name=inrRate]').fill('85');await proof();await save();let s=await read();check(mode+': blank BOC initial payment saves without supplier realization',s.payments[0].bocUsdRmbRate===null&&s.payments[0].allocations.every(a=>a.realizedMinor===null));
  await page.goto(root+'#/payments');await page.getByRole('button',{name:'Record payment',exact:true}).click();await page.locator('[name=currency]').selectOption('USD');check(mode+': remittance uses plain currency labels',await page.getByLabel(/^USD to INR \(Indian bank\)/).isVisible()&&!(await page.locator('#dialog-form').innerText()).includes('per remittance unit'));
  await page.locator('[name=reference]').fill('RATES-BOC');await page.locator('[name=amount]').fill('1');await page.locator('[name=inrRate]').fill('85.123456');await page.locator('[name=bocUsdRmbRate]').fill('7.123456');await page.locator('[name=aamount-0]').fill('1');await proof();await save();s=await read();const p=s.payments.find(p=>p.reference==='RATES-BOC');check(mode+': BOC reference saves with six decimals',p.bocUsdRmbRate===7123456&&p.inrRate===85123456&&p.allocations[0].expectedMinor===100);check(mode+': register shows BOC reference column',await page.getByRole('columnheader',{name:'USD to RMB (BOC)',exact:true}).isVisible()&&(await page.locator('tr').filter({hasText:'RATES-BOC'}).innerText()).includes('7.123456'));
  await page.goto(root+'#/order/'+o.id);await page.locator('.tab[data-value=finance]').click();const row=page.locator('tr').filter({hasText:'RATES-BOC'});await row.getByRole('button',{name:'Record receipt',exact:true}).click();check(mode+': receipt inherits optional BOC reference',await page.locator('[name=bocUsdRmbRate]').inputValue()==='7.123456');await page.locator('[name=realizedAmount]').fill('0.9');await page.locator('[name=bocUsdRmbRate]').fill('7.2');await proof();await save();s=await read();let a=s.payments.find(x=>x.id===p.id).allocations[0];
  check(mode+': manual actual receipt stays separate',a.realizedMinor===90&&a.bocUsdRmbRate===7200000&&financials(s,s.orders[0]).realized===90);
  await page.locator('tr').filter({hasText:'RATES-BOC'}).getByRole('button',{name:'Correct receipt',exact:true}).click();await page.locator('[name=bocUsdRmbRate]').fill('');await page.locator('[name=remarks]').fill('Remove optional reference only');await proof();await save();s=await read();a=s.payments.find(x=>x.id===p.id).allocations[0];check(mode+': clearing receipt reference preserves actual amount',a.bocUsdRmbRate===null&&a.realizedMinor===90);
  await page.goto(root+'#/payments');await page.getByRole('button',{name:'Record payment',exact:true}).click();await page.locator('[name=currency]').selectOption('USD');await page.locator('[name=bocUsdRmbRate]').fill('7.1');await page.locator('[name=currency]').selectOption('INR');check(mode+': non-USD hides BOC and has correct bank label',!await page.locator('[name=bocUsdRmbRate]').isVisible()&&await page.getByLabel(/^INR to INR \(Indian bank\)/).isVisible());await page.locator('[name=currency]').selectOption('USD');check(mode+': currency changes clear stale BOC rate',await page.locator('[name=bocUsdRmbRate]').inputValue()==='');
  await page.setViewportSize({width:390,height:844});check(mode+': rate fields fit mobile',await page.locator('[name=bocUsdRmbRate]').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}));check(mode+': modal title is not covered by appearance toolbar',await page.locator('#modal-title').evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return r.top>=0&&hit?.closest('.modal')===e.closest('.modal');}));check(mode+': notification clears mascot dock',await page.locator('.toast').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().bottom<=document.querySelector('.support-dock').getBoundingClientRect().top)));await page.screenshot({path:join(out,mode+'-mobile.png'),fullPage:true});await context.tracing.stop({path:join(out,mode+'-trace.zip')});await context.close();context=null;
 }
 check('No browser runtime errors',report.errors.length===0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e.stack||e);console.error(report.failure);await page?.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{await context?.tracing.stop({path:join(out,'failure-trace.zip')}).catch(()=>{});await browser?.close();await new Promise(r=>server.close(r));store.close();writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));console.log('Evidence: '+out);}
