/** Excel-style pipeline sorting/filtering: isolated native and standalone review modes. */
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Store} from '../server/store.mjs';
import {makeServer} from '../server/index.mjs';
import {createSeed} from '../shared/seed.mjs';
const out=resolve(process.env.FH_TEST_OUTPUT_ROOT||'test-output','pipeline-sort',new Date().toISOString().replace(/[:.]/g,'-'));mkdirSync(out,{recursive:true});
const seed=createSeed('2026-09-11'),template=seed.orders.find(o=>o.status==='DRAFT'),vendor=seed.vendors.find(v=>v.kind==='SUPPLIER');
seed.vendors=[['sort-alpha','Alpha Tools','A01'],['sort-beta','beta Tools','B02'],['sort-alpha2','Alpha Tools','A03']].map(([id,name,code])=>({...structuredClone(vendor),id,name,code}));
seed.orders=Array.from({length:27},(_,i)=>({...structuredClone(template),id:'sort-po-'+i,number:'PO-'+((i*7)%27+1),serialNumber:i<25?(i*7)%25+1:i+1,vendorId:seed.vendors[i%3].id,createdAt:'2026-09-11T10:00:00Z',...(i>=25?{deletedAt:'2026-09-11T12:00:00Z',deletedBy:'Test admin',deletionReason:'Isolated fixture'}:{})}));seed.payments=[];seed.costs=[];seed.events=[];seed.nextOrderSerial=28;
const store=new Store(join(out,'test.sqlite'),seed),password='Isolated-sort-test-1234';for(const id of ['u-admin','u-manager'])store.addAccount(id,id+'@example.test',password);
const server=makeServer(store),report={checks:[],errors:[],writes:[],out};let browser,context,page;
const check=(label,ok=true)=>{assert.ok(ok,label);report.checks.push(label);console.log('PASS '+label);};
const active=seed.orders.filter(o=>!o.deletedAt),serialAsc=[...active].sort((a,b)=>a.serialNumber-b.serialNumber);
try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const {chromium}=await import(process.env.FH_PLAYWRIGHT_MODULE||pathToFileURL(resolve('test-output/ui-tools/node_modules/playwright/index.mjs')).href);browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 for(const mode of ['server','review']){
  context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.tracing.start({screenshots:true,snapshots:true});page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET'&&/\/api\/(commands|users|files)/.test(r.url()))report.writes.push(r.url());});
  const root=mode==='server'?'http://127.0.0.1:'+server.address().port:pathToFileURL(resolve('Farming_Hub_Purchase_Management_Clean_Review.html')).href;await page.goto(root+'#/orders');
  const login=async id=>{if(await page.getByRole('button',{name:'Sign out',exact:true}).count())await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByLabel(/^Email/).fill(id+'@example.test');await page.getByLabel(/^Password/).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('.sidebar').waitFor();};
  if(mode==='server')await login('u-admin');else{await page.evaluate(s=>{localStorage.setItem('fh-purchase-alpha15-clean-schema7',JSON.stringify(s));localStorage.setItem('fh-purchase-alpha15-clean-schema7-user','u-admin');},seed);await page.reload();}
  await page.locator('#order-sort').waitFor();const read=()=>mode==='server'?store.read():page.evaluate(()=>JSON.parse(localStorage.getItem('fh-purchase-alpha15-clean-schema7')));const initial=await read();
  const ids=()=>page.locator('tr[data-action=open-order]').evaluateAll(es=>es.map(e=>e.dataset.id));const expectRows=async(os,label)=>check(mode+': '+label,JSON.stringify(await ids())===JSON.stringify(os.map(o=>o.id)));
  await expectRows(active.slice(0,12),'default preserves original order');check(mode+': supplier filter includes name and code for duplicate names',await page.locator('#order-supplier option').count()===4&&(await page.locator('#order-supplier').innerText()).includes('Alpha Tools / A03'));
  await page.getByRole('button',{name:'Sort by S.No.',exact:true}).click();await expectRows(serialAsc.slice(0,12),'serial sorts numerically across the full dataset');check(mode+': header exposes ascending state',await page.locator('th[aria-sort=ascending]').count()===1);await page.getByRole('button',{name:'Next',exact:true}).click();await expectRows(serialAsc.slice(12,24),'second page continues global numeric order');
  await page.getByRole('button',{name:'Sort by S.No.',exact:true}).click();await expectRows([...serialAsc].reverse().slice(0,12),'descending resets to first page');check(mode+': keyboard focus survives sorting',await page.getByRole('button',{name:'Sort by S.No.',exact:true}).evaluate(el=>el===document.activeElement));
  await page.getByRole('button',{name:'Sort by Supplier / item',exact:true}).click();const supplierAsc=[...active].sort((a,b)=>{const av=seed.vendors.find(v=>v.id===a.vendorId).name.toLowerCase(),bv=seed.vendors.find(v=>v.id===b.vendorId).name.toLowerCase();return av<bv?-1:av>bv?1:a.serialNumber-b.serialNumber;});await expectRows(supplierAsc.slice(0,12),'supplier names sort case-insensitively with serial tie-break');await page.locator('#order-sort').selectOption('supplier-desc');const supplierDesc=[...active].sort((a,b)=>{const av=seed.vendors.find(v=>v.id===a.vendorId).name.toLowerCase(),bv=seed.vendors.find(v=>v.id===b.vendorId).name.toLowerCase();return av>bv?-1:av<bv?1:a.serialNumber-b.serialNumber;});await expectRows(supplierDesc.slice(0,12),'supplier descending keeps numeric serial order within names');
  await page.getByLabel('Select all orders on this page',{exact:true}).check();await page.locator('#order-supplier').selectOption('sort-alpha2');const supplierRows=active.filter(o=>o.vendorId==='sort-alpha2').sort((a,b)=>a.serialNumber-b.serialNumber);await expectRows(supplierRows,'supplier filter uses exact ID despite duplicate names');check(mode+': supplier change clears hidden bulk selection',await page.locator('[data-action=delete-orders]').count()===0);
  await page.locator('#status-filter').selectOption('DRAFT');await expectRows(supplierRows,'supplier and stage filters compose');await page.locator('#view-search').fill('A03');await expectRows(supplierRows,'search matches supplier code');await page.locator('#order-sort').selectOption('serial-desc');
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();const d=await download;const csvPath=join(out,mode+'-filtered.csv');await d.saveAs(csvPath);const lines=readFileSync(csvPath,'utf8').replace(/^\uFEFF/,'').trim().split(/\r?\n/);check(mode+': export includes all filtered sorted rows and supplier name',lines.length===supplierRows.length+1&&lines[0].includes('Supplier name')&&JSON.stringify(lines.slice(1).map(l=>Number(l.split(',')[0].replaceAll('"',''))))===JSON.stringify([...supplierRows].reverse().map(o=>o.serialNumber))&&lines.slice(1).every(l=>l.includes('Alpha Tools')));
  await page.locator('#view-search').fill('NO-MATCH');check(mode+': empty filtered view is explicit',await page.getByText('No matching orders',{exact:true}).count()===1);await page.getByRole('button',{name:'Reset view',exact:true}).click();await expectRows(active.slice(0,12),'reset restores default order and clears filters');
  await page.locator('[data-order-select="'+active[0].id+'"]').check();await page.locator('#order-sort').selectOption('number-asc');check(mode+': sorting clears bulk selection',await page.locator('[data-action=delete-orders]').count()===0);const poAsc=[...active].sort((a,b)=>Number(a.number.slice(3))-Number(b.number.slice(3)));await expectRows(poAsc.slice(0,12),'PO reference uses natural numeric text order');
  await page.locator('#order-visibility').selectOption('deleted');await page.locator('#order-sort').selectOption('serial-desc');await expectRows([...seed.orders.filter(o=>o.deletedAt)].reverse(),'deleted view supports serial sorting');await page.locator('#order-supplier').selectOption(seed.orders[26].vendorId);await expectRows([seed.orders[26]],'deleted view supplier filter works');
  await page.locator('#order-visibility').selectOption('active');await page.locator('#order-supplier').selectOption('sort-beta');await page.locator('[data-action=layout][data-value=board]').click();check(mode+': board respects supplier filter',await page.locator('.board-card').count()===active.filter(o=>o.vendorId==='sort-beta').length);await page.locator('[data-action=layout][data-value=table]').click();
  await page.setViewportSize({width:390,height:844});for(const id of ['order-supplier','order-sort']){const box=await page.locator('#'+id).boundingBox();check(mode+': '+id+' fits mobile',box.x>=0&&box.x+box.width<=391);}await page.screenshot({path:join(out,mode+'-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});
  check(mode+': sorting and filtering leave every stored record unchanged',JSON.stringify(await read())===JSON.stringify(initial));
  if(mode==='server')await login('u-manager');else await page.locator('#demo-role').selectOption('u-manager');await page.locator('#order-sort').selectOption('serial-asc');check(mode+': Purchase Manager can sort without admin deletion controls',await page.locator('[data-order-select]').count()===0&&await page.locator('#order-supplier').count()===1);await page.screenshot({path:join(out,mode+'-desktop.png'),fullPage:true});
  await context.tracing.stop({path:join(out,mode+'-trace.zip')});await context.close();context=null;
 }
 check('No browser runtime errors',report.errors.length===0);check('No business-write requests',report.writes.length===0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e.stack||e);console.error(report.failure);if(page)await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{await context?.tracing.stop({path:join(out,'failure-trace.zip')}).catch(()=>{});await browser?.close();await new Promise(r=>server.close(r));store.close();writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));console.log('Evidence: '+out);}
