import test from 'node:test';
import assert from 'node:assert/strict';
import {createSeed} from '../shared/seed.mjs';
import {execute,priceListConversion,priceListInvoiceMinor,priceVarianceForLine,orderTotal} from '../shared/domain.mjs';

function fixture(){let state=createSeed('2026-09-13'),n=0;const actor=state.users.find(u=>u.role==='MANAGER'),item=state.items.find(i=>i.code==='GJPW12'),base=state.bases.find(b=>b.id===item.baseId);state.priceLists=[{id:'rmb-price',vendorId:base.vendorId,baseId:base.id,currency:'CNY',unitPriceMinor:72000,effectiveDate:'2026-09-01',status:'APPROVED',revision:1}];const run=(type,payload)=>{const out=execute(state,{type,payload},actor,{now:'2026-09-13T12:00:00Z',id:()=>`fx-${++n}`});state=out.state;return out.result;};const payload={number:'RMB-USD-TEST',vendorId:base.vendorId,currency:'USD',priceListCurrency:'CNY',priceListFxRate:'7.2',priceListFxDate:'2026-09-13',planningTat:90,requestedPortDate:'2026-12-15',routeId:state.routes[0].id,lines:[{itemId:item.id,quantity:10,unitPrice:'100.00',specId:base.specifications[0].id}]};return {get state(){return state;},run,payload};}

test('RMB supplier prices divide by the entered RMB per USD rate, preserving source and date',()=>{const f=fixture(),id=f.run('CREATE_ORDER',f.payload).id,o=f.state.orders.find(o=>o.id===id),l=o.lines[0];assert.equal(l.priceListSnapshot.currency,'CNY');assert.equal(l.priceListSnapshot.unitPriceMinor,72000);assert.equal(l.priceListSnapshot.invoiceUnitPriceMinor,10000);assert.equal(l.priceListSnapshot.conversion.quote,'USD_CNY');assert.equal(l.priceListSnapshot.conversion.rate,7200000);assert.equal(l.priceListSnapshot.conversion.date,'2026-09-13');assert.equal(l.priceOverride,false);assert.equal(orderTotal(o),100000);assert.equal(priceVarianceForLine(f.state,o,l).differenceMinor,0);});

test('FX validation rejects missing, zero, negative, excess precision, invalid date and wrong direction atomically',()=>{for(const change of [{priceListFxRate:undefined},{priceListFxRate:''},{priceListFxRate:'0'},{priceListFxRate:'-7.2'},{priceListFxRate:'7.1234567'},{priceListFxDate:undefined},{priceListFxDate:'2026-02-30'},{priceListFxQuote:'INVERT'}]){const f=fixture(),before=structuredClone(f.state);assert.throws(()=>f.run('CREATE_ORDER',{...f.payload,...change}),/rate|date|decimal|direction/i);assert.deepEqual(f.state,before);}});

test('Unit conversion rounds half up once without rounding a reciprocal rate',()=>{const order={currency:'USD',priceConversion:priceListConversion('CNY','USD','7.2','2026-09-13')};assert.equal(priceListInvoiceMinor({currency:'CNY',unitPriceMinor:72001},order),10000);assert.equal(priceListInvoiceMinor({currency:'CNY',unitPriceMinor:72004},order),10001);order.priceConversion=priceListConversion('CNY','USD','2','2026-09-13');assert.equal(priceListInvoiceMinor({currency:'CNY',unitPriceMinor:1},order),1);order.priceConversion=priceListConversion('CNY','USD','7.123456','2026-09-13');assert.equal(priceListInvoiceMinor({currency:'CNY',unitPriceMinor:71234560},order),10000000);assert.equal(priceListInvoiceMinor({currency:'CNY',unitPriceMinor:0},order),0);});

test('USD source to RMB invoice multiplies the same quote; equal currency requires no rate',()=>{const o={currency:'CNY',priceConversion:priceListConversion('USD','CNY','7.2','2026-09-13')};assert.equal(priceListInvoiceMinor({currency:'USD',unitPriceMinor:10000},o),72000);assert.equal(priceListConversion('CNY','CNY',undefined,undefined),null);assert.equal(priceListInvoiceMinor({currency:'CNY',unitPriceMinor:72000},{currency:'CNY'}),72000);assert.equal(priceListInvoiceMinor({currency:'CNY',unitPriceMinor:72000},{currency:'USD'}),null);});

test('Draft FX updates compare invoice prices and preserve manual overrides',()=>{const f=fixture(),id=f.run('CREATE_ORDER',f.payload).id;f.run('EDIT_DRAFT',{orderId:id,priceListFxRate:'7.5'});const o=f.state.orders.find(o=>o.id===id);assert.equal(o.lines[0].unitPriceMinor,10000);assert.equal(o.lines[0].priceListSnapshot.invoiceUnitPriceMinor,9600);assert.equal(o.lines[0].priceOverride,true);assert.equal(priceVarianceForLine(f.state,o,o.lines[0]).differenceMinor,400);});

test('Issued snapshots stay immutable while amendments record a new rate',()=>{const f=fixture(),id=f.run('CREATE_ORDER',f.payload).id;f.run('SUBMIT_ORDER',{orderId:id});f.run('APPROVE_ORDER',{orderId:id});const original=structuredClone(f.state.orders.find(o=>o.id===id).revisions[0]);f.run('PROPOSE_AMENDMENT',{orderId:id,reason:'Current negotiated exchange rate',priceListFxRate:'7.5',priceListFxDate:'2026-09-13'});f.run('APPROVE_AMENDMENT',{orderId:id});const o=f.state.orders.find(o=>o.id===id);assert.deepEqual(o.revisions[0],original);assert.equal(o.revisions[1].snapshot.priceConversion.rate,7500000);assert.equal(o.lines[0].priceListSnapshot.invoiceUnitPriceMinor,9600);});

test('Legacy cross-currency draft cannot proceed without an explicitly recorded exchange rate',()=>{const f=fixture(),id=f.run('CREATE_ORDER',f.payload).id;delete f.state.orders.find(o=>o.id===id).priceConversion;const before=structuredClone(f.state);assert.throws(()=>f.run('SUBMIT_ORDER',{orderId:id}),/exchange rate/i);assert.deepEqual(f.state,before);f.run('EDIT_DRAFT',{orderId:id,priceListFxRate:'7.2',priceListFxDate:'2026-09-13'});assert.doesNotThrow(()=>f.run('SUBMIT_ORDER',{orderId:id}));});

test('Existing direct historical quotes retain their interpretation',()=>{const fx={from:'CNY',to:'USD',rate:140000,date:'2026-09-13'};assert.equal(priceListInvoiceMinor({currency:'CNY',unitPriceMinor:10000},{currency:'USD',priceConversion:fx}),1400);});
