/** Isolated manual USD/RMB conversion checks in server and standalone review modes. */
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Store} from '../server/store.mjs';
import {makeServer} from '../server/index.mjs';
import {createCleanSeed} from '../shared/clean-seed.mjs';
const root=resolve('test-output');mkdirSync(root,{recursive:true});const dir=mkdtempSync(join(root,'po-currency-')),seed=createCleanSeed(),base=seed.bases.find(b=>b.id==='base-bs20');
seed.priceLists=seed.priceLists.filter(p=>p.baseId!==base.id);
for(const [currency,unitPriceMinor]of [['CNY',72000],['USD',10000]])seed.priceLists.push({id:'fx-'+currency,vendorId:base.vendorId,baseId:base.id,currency,unitPriceMinor,effectiveDate:'2026-09-12',status:'APPROVED',revision:1});
const store=new Store(join(dir,'test.sqlite'),seed),server=makeServer(store),password='Isolated-currency-test-1234';store.addAccount('u-manager','currency@example.test',password);
const report={checks:[],errors:[]};let browser,page;
const check=(name,ok)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS '+name);};
try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const {chromium}=await import(pathToFileURL(resolve('test-output/ui-tools/node_modules/playwright/index.mjs')));browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 for(const mode of ['server','review']){
  const context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.setDefaultTimeout(12000);page.on('dialog',d=>d.accept());
  const url=mode==='server'?'http://127.0.0.1:'+server.address().port:pathToFileURL(resolve('Farming_Hub_Purchase_Management_Clean_Review.html')).href;await page.goto(url+'#/orders');
  if(mode==='server'){await page.locator('#login-form [name=email]').fill('currency@example.test');await page.locator('#login-form [name=password]').fill(password);await page.locator('#login-form [type=submit]').click();}else{await page.evaluate(seed=>{localStorage.setItem('fh-purchase-alpha15-clean-schema7',JSON.stringify(seed));localStorage.setItem('fh-purchase-alpha15-clean-schema7-user','u-manager');},seed);await page.reload();}
  const input=n=>page.locator('#dialog-form [name="'+n+'"]'),read=()=>mode==='server'?Promise.resolve(store.read()):page.evaluate(()=>JSON.parse(localStorage.getItem('fh-purchase-alpha15-clean-schema7')));
  await page.locator('[data-action=new-order]').first().click();await input('vendorId').selectOption(base.vendorId);await input('priceListCurrency').selectOption('CNY');await input('currency').selectOption('USD');
  check(mode+': explicit USD to RMB quote and required date',await page.getByLabel('USD to RMB',{exact:false}).isVisible()&&await input('priceListFxRate').evaluate(e=>e.required)&&await input('priceListFxDate').evaluate(e=>e.required));
  check(mode+': source selector says RMB',await input('priceListCurrency').locator('option:checked').innerText()==='RMB');
  await page.locator('[data-action=pick-po-item][data-base="'+base.id+'"]').click();await input('qty-0-GJ').fill('2');
  check(mode+': no unconverted USD price before rate',await input('baseprice-0').inputValue()===''&&(await page.locator('[data-po-total]').innerText())==='Check entries');
  check(mode+': original RMB catalogue amount retained',(await page.locator('[data-po-catalog-row]').filter({has:page.locator('[data-base="'+base.id+'"]')}).innerText()).includes('720.00'));
  await input('priceListFxRate').fill('7.2');await input('priceListFxDate').fill('2026-09-13');check(mode+': RMB 720 converts to USD 100',await input('baseprice-0').inputValue()==='100.00');check(mode+': total is USD 200',(await page.locator('[data-po-total]').innerText()).includes('200.00'));
  await input('priceListFxRate').fill('');check(mode+': clearing required rate clears computed price',await input('baseprice-0').inputValue()==='');await input('priceListFxRate').fill('7.2');await input('number').fill('FX-RMB-'+mode);await page.locator('.po-terms>summary').click();await input('planningTat').fill('90');if(await input('productionOverrideReason').count())await input('productionOverrideReason').fill('Synthetic supplier agreement');await page.locator('.po-terms>summary').click();
  await page.screenshot({path:join(dir,mode+'-desktop.png')});await page.setViewportSize({width:390,height:844});check(mode+': mobile quote remains visible',await input('priceListFxRate').isVisible()&&await page.locator('.modal').evaluate(e=>e.getBoundingClientRect().right<=innerWidth+1));await page.screenshot({path:join(dir,mode+'-mobile.png')});await page.setViewportSize({width:1440,height:1000});
  await page.locator('#dialog-form [type=submit]').click();await page.locator('#dialog-form').waitFor({state:'hidden'});let saved=(await read()).orders.find(o=>o.number==='FX-RMB-'+mode);check(mode+': source, quote and invoice price persist',saved.priceConversion.rate===7200000&&saved.priceConversion.quote==='USD_CNY'&&saved.lines[0].priceListSnapshot.unitPriceMinor===72000&&saved.lines[0].unitPriceMinor===10000);
  await page.evaluate(()=>{window.print=()=>{};});const print=page.locator('[data-action=print]').first();await print.evaluate(e=>{for(let p=e.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;});await print.click();check(mode+': printable quote retains USD to RMB direction',(await page.locator('.print-sheet').textContent()).includes('1 USD = 7.2 RMB'));
  await page.locator('[data-action=edit-draft]').first().click();check(mode+': edit restores rate and date',await input('priceListFxRate').inputValue()==='7.2'&&await input('priceListFxDate').inputValue()==='2026-09-13');await input('priceListFxRate').fill('7.5');check(mode+': matched draft price follows new rate',await input('baseprice-0').inputValue()==='96.00');await input('baseprice-0').fill('97.00');await input('priceListFxRate').fill('8');check(mode+': manual override remains and warns',await input('baseprice-0').inputValue()==='97.00'&&(await page.locator('[data-po-price-warning="0"]').innerText()).includes('differs'));await page.locator('#dialog-form [type=submit]').click();await page.locator('#dialog-form').waitFor({state:'hidden'});saved=(await read()).orders.find(o=>o.id===saved.id);check(mode+': saved override compares with converted reference',saved.lines[0].priceOverride&&saved.lines[0].unitPriceMinor===9700&&saved.lines[0].priceListSnapshot.invoiceUnitPriceMinor===9000);
  await page.goto(url+'#/orders');await page.locator('[data-theme=current]').click();await page.locator('[data-action=new-order]').first().click();await input('vendorId').selectOption(base.vendorId);await input('priceListCurrency').selectOption('USD');await input('currency').selectOption('CNY');await input('base-0').selectOption(base.id);await input('priceListFxRate').fill('7.2');check(mode+': reverse direction multiplies USD 100 to RMB 720 in Current',await input('baseprice-0').inputValue()==='720.00');await input('currency').selectOption('USD');check(mode+': same currency hides FX and uses original USD 100',await input('priceListFxRate').count()===0&&await input('baseprice-0').inputValue()==='100.00');
  await context.close();
 }
 check('No browser runtime errors',report.errors.length===0);
}catch(e){report.failure=e.message;await page?.screenshot({path:join(dir,'failure.png')}).catch(()=>{});throw e;}finally{writeFileSync(join(dir,'report.json'),JSON.stringify(report,null,2));await browser?.close();await new Promise(r=>server.close(r));store.close();console.log('Report '+dir);}
