/** Isolated supplier worksheet acceptance checks; no .env or live data. */
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Store} from '../server/store.mjs';
import {makeServer} from '../server/index.mjs';
import {createCleanSeed} from '../shared/clean-seed.mjs';
import {orderTotal} from '../shared/domain.mjs';
const root=resolve('test-output');mkdirSync(root,{recursive:true});const dir=mkdtempSync(join(root,'po-worksheet-')),seed=createCleanSeed(),a=seed.bases.find(b=>b.id==='base-bs20'),b=seed.bases.find(b=>b.id==='base-bs21');
seed.items=seed.items.filter(i=>!(i.baseId===b.id&&i.brandPrefix==='TT'));
seed.priceLists=seed.priceLists.filter(p=>![a.id,b.id].includes(p.baseId));
for(const [i,base]of[a,b].entries())seed.priceLists.push({id:'worksheet-price-'+i,vendorId:a.vendorId,baseId:base.id,currency:'USD',unitPriceMinor:i?5000:10000,effectiveDate:'2026-09-12',status:'APPROVED',revision:1});
const store=new Store(join(dir,'test.sqlite'),seed),server=makeServer(store),password='Isolated-worksheet-test-1234';store.addAccount('u-manager','worksheet@example.test',password);
const report={checks:[],errors:[],environment:'Isolated server and private standalone review'};let browser,page;
const check=(name,condition=true)=>{assert.ok(condition,name);report.checks.push(name);console.log('PASS '+name);};
try{await new Promise(r=>server.listen(0,'127.0.0.1',r));const {chromium}=await import(pathToFileURL(resolve('test-output/ui-tools/node_modules/playwright/index.mjs')));browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 for(const mode of ['server','review']){const context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>report.errors.push(e.message));page.on('dialog',d=>d.accept());const url=mode==='server'?'http://127.0.0.1:'+server.address().port:pathToFileURL(resolve('Farming_Hub_Purchase_Management_Clean_Review.html')).href;
  await page.goto(url+'#/orders');if(mode==='server'){await page.locator('#login-form [name=email]').fill('worksheet@example.test');await page.locator('#login-form [name=password]').fill(password);await page.locator('#login-form [type=submit]').click();}else{await page.evaluate(seed=>{localStorage.setItem('fh-purchase-alpha15-clean-schema7',JSON.stringify(seed));localStorage.setItem('fh-purchase-alpha15-clean-schema7-user','u-manager');},seed);await page.reload();}
  const input=n=>page.locator('#dialog-form [name="'+n+'"]'),read=()=>mode==='server'?Promise.resolve(store.read()):page.evaluate(()=>JSON.parse(localStorage.getItem('fh-purchase-alpha15-clean-schema7')));
  await page.locator('[data-action=new-order]').first().click();await input('vendorId').selectOption(a.vendorId);await input('priceListCurrency').selectOption('USD');await input('currency').selectOption('USD');
  check(mode+': terms start collapsed and worksheet visible',!await page.locator('.po-terms').evaluate(e=>e.open)&&await page.locator('.po-item-sheet').isVisible());
  await page.locator('#po-item-search').fill('bs20');check(mode+': supplier search narrows visible list',await page.locator('[data-po-catalog-row]:visible').evaluateAll(rows=>rows.length>0&&rows.every(r=>r.dataset.search.includes('bs20'))));await page.locator('[data-action=pick-po-item][data-base="'+a.id+'"]').click();check(mode+': catalogue fills first row with supplier price',await input('base-0').inputValue()===a.id&&await input('baseprice-0').inputValue()==='100.00');check(mode+': duplicate selection is disabled',await page.locator('[data-action=pick-po-item][data-base="'+a.id+'"]').isDisabled());
  await input('qty-0-GJ').fill('10');await input('qty-0-KD').fill('2');await input('baseprice-0').fill('101.25');check(mode+': row amount updates while typing',(await page.locator('[data-po-amount="0"]').innerText()).includes('1,215.00'));check(mode+': price override warning remains visible',await page.locator('[data-po-price-warning="0"]').innerText()==='Price differs from supplier list');
  await page.locator('#po-item-search').fill('BS21');await page.keyboard.press('Enter');check(mode+': Enter in search adds item without submitting form',await input('base-1').inputValue()===b.id);await input('qty-1-GJ').fill('3');check(mode+': unavailable brand cannot receive quantity',await input('qty-1-TT').isDisabled());check(mode+': adding another item retains first row',await input('baseprice-0').inputValue()==='101.25'&&await input('qty-0-GJ').inputValue()==='10');check(mode+': total uses existing minor-unit calculations',(await page.locator('[data-po-total]').innerText()).includes('1,365.00'));
  await input('qty-0-GJ').focus();await page.keyboard.press('ArrowDown');check(mode+': down arrow moves to same quantity column',await input('qty-1-GJ').evaluate(e=>e===document.activeElement));await page.keyboard.press('Enter');check(mode+': Enter moves to next cell without saving',await input('qty-1-KD').evaluate(e=>e===document.activeElement)&&await page.locator('#dialog-form').isVisible());
  await page.locator('.po-terms>summary').click();await input('planningTat').fill('90');if(await input('productionOverrideReason').count())await input('productionOverrideReason').fill('Synthetic supplier commitment');await page.locator('.po-terms>summary').click();await input('number').fill('WORKSHEET-'+mode.toUpperCase());
  await page.locator('.modal').evaluate(async e=>await Promise.all(e.getAnimations().map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:join(dir,mode+'-desktop.png')});await page.setViewportSize({width:390,height:844});check(mode+': narrow view contains horizontal scrolling within worksheet',await page.locator('.modal').evaluate(e=>e.getBoundingClientRect().right<=innerWidth+1)&&await page.locator('.po-sheet-scroll').evaluate(e=>e.scrollWidth>e.clientWidth));await page.screenshot({path:join(dir,mode+'-mobile.png')});await page.setViewportSize({width:1440,height:1000});
  await page.locator('#dialog-form [type=submit]').click();await page.locator('#dialog-form').waitFor({state:'hidden'});let saved=(await read()).orders.find(o=>o.number==='WORKSHEET-'+mode.toUpperCase());check(mode+': saving creates only nonzero brand lines with unchanged total',saved.lines.length===3&&orderTotal(saved)===136500);
  await page.locator('[data-theme=current]').click();await page.locator('[data-action=edit-draft]').first().click();check(mode+': Current theme retains worksheet and entries',await page.locator('.po-item-sheet').isVisible()&&await input('qty-0-GJ').inputValue()==='10');check(mode+': editing restores both items and quantities',await input('base-1').inputValue()===b.id&&await input('qty-0-KD').inputValue()==='2');await page.locator('[data-action=remove-base-plan][data-index="1"]').click();check(mode+': removing a row updates totals without losing other entries',(await page.locator('[data-po-total]').innerText()).includes('1,215.00')&&await input('baseprice-0').inputValue()==='101.25');await page.locator('#dialog-form [type=submit]').click();await page.locator('#dialog-form').waitFor({state:'hidden'});saved=(await read()).orders.find(o=>o.id===saved.id);check(mode+': edit persists remaining brand lines',saved.lines.length===2&&orderTotal(saved)===121500);
  await context.close();
 }
 check('No browser runtime errors',report.errors.length===0);
}catch(e){report.failure=e.message;await page?.screenshot({path:join(dir,'failure.png')}).catch(()=>{});throw e;}finally{writeFileSync(join(dir,'report.json'),JSON.stringify(report,null,2));await browser?.close();await new Promise(r=>server.close(r));store.close();console.log('Report '+dir);}
