import test from 'node:test';
import assert from 'node:assert/strict';
import {createSeed} from '../shared/seed.mjs';
import {execute,paymentSchedule,major} from '../shared/domain.mjs';
import {processGateAllowed,activeProcessExemptions,pendingProcessExemptions} from '../shared/process-exemptions.mjs';
import {orderProgress} from '../shared/order-progress.mjs';
const now='2026-09-17T12:00:00Z';
function fixture(){let state=createSeed('2026-09-11');const o=state.orders.find(o=>o.pi?.status==='APPROVED'&&paymentSchedule(state,o).some(m=>m.trigger==='PI'));state.payments=state.payments.filter(p=>!p.allocations.some(a=>a.orderId===o.id));o.artwork={current:null,pending:null,history:[],supplierConfirmed:null};o.paymentAuthorizations=[];o.productionWindowStartedAt=null;o.productionStartedAt=null;o.productionCompletedAt=null;o.preproductionSample=null;delete o.processExemptionCutoffAt;o.bulkQc=null;o.shipments=[];o.processExemptions=[];const actor=state.users.find(u=>u.role==='MANAGER'),file=state.files.find(f=>f.orderIds.includes(o.id));return {state,o,actor,file,run(type,p={},who=actor,input=state){return execute(input,{type,payload:{orderId:o.id,...p}},who,{now});},grant(stage='ARTWORK',actions=['PAYMENT']){return {stage,actions,reason:'Supplier artwork pending; advance authorized separately.',ownerId:actor.id,due:'2026-09-18',confirm:true};},payment(){const amount=paymentSchedule(state,o).filter(m=>m.trigger==='PI').reduce((n,m)=>n+m.amount,0);return {date:'2026-09-17',currency:o.currency,amount:major(amount),invoiceRate:'1',inrRate:'90',reference:'EXEMPTION-TEST-PAYMENT',fileIds:[file.id],remarks:'Isolated actual-payment fixture'};}};}
const get=(f,r)=>r.state.orders.find(o=>o.id===f.o.id);
test('artwork payment exception preserves pending artwork and does not authorize production',()=>{const f=fixture();assert.throws(()=>f.run('COMPLETE_INITIAL_PAYMENT',f.payment()),/artwork/);const g=f.run('APPROVE_PROCESS_EXEMPTION',f.grant()),o=get(f,g);assert.equal(o.artwork.current,null);assert.equal(processGateAllowed(o,'ARTWORK','PAYMENT'),true);assert.equal(processGateAllowed(o,'ARTWORK','PRODUCTION'),false);assert.equal(orderProgress(g.state,o,f.actor).action,'initial-payment');const paid=f.run('COMPLETE_INITIAL_PAYMENT',f.payment(),f.actor,g.state),p=get(f,paid);assert.ok(p.productionWindowStartedAt);assert.equal(p.artwork.current,null);assert.equal(activeProcessExemptions(p).length,1);assert.ok(paid.state.events.some(e=>e.action==='PROCESS_EXEMPTION_USED'&&e.newValue?.command==='COMPLETE_INITIAL_PAYMENT')||paid.state.events.some(e=>e.action==='PROCESS_EXEMPTION_USED'));assert.throws(()=>f.run('START_PRODUCTION',{date:'2026-09-17',remarks:'Must not proceed'},f.actor,paid.state),/production-specific/);});
test('only Manager/Admin may approve or revoke; scope, active profile and confirmation apply',()=>{const f=fixture();for(const role of ['EXECUTIVE','PRODUCT_MANAGER','VIEWER'])assert.throws(()=>f.run('APPROVE_PROCESS_EXEMPTION',f.grant(),{...f.actor,role}),e=>e.code==='FORBIDDEN');for(const actor of [{...f.actor,scopes:[]},{...f.actor,active:false}])assert.throws(()=>f.run('APPROVE_PROCESS_EXEMPTION',f.grant(),actor));for(const change of [p=>p.confirm=false,p=>p.reason='',p=>p.due='2026-09-01',p=>p.ownerId='missing',p=>p.actions=['DISPATCH','unknown'],p=>p.actions=[],p=>p.actions=['PAYMENT','PAYMENT'],p=>p.stage='PAYMENT',p=>p.stage='PI',p=>p.stage='COSTING',p=>p.stage='__proto__']){const p=f.grant();change(p);assert.throws(()=>f.run('APPROVE_PROCESS_EXEMPTION',p));}});
test('payment proof, exact advance amount, PI approval and duplicate bank references remain required',()=>{const f=fixture(),g=f.run('APPROVE_PROCESS_EXEMPTION',f.grant());for(const change of [p=>p.amount='1',p=>p.fileIds=[],p=>p.reference='']){const p=f.payment();change(p);assert.throws(()=>f.run('COMPLETE_INITIAL_PAYMENT',p,f.actor,g.state));}const missing=structuredClone(g.state);missing.orders.find(o=>o.id===f.o.id).pi.status='VERIFIED';assert.throws(()=>f.run('COMPLETE_INITIAL_PAYMENT',f.payment(),f.actor,missing),/PI/);const duplicate=structuredClone(g.state);duplicate.payments.push({id:'reserved-payment',reference:f.payment().reference,status:'VOID',allocations:[]});assert.throws(()=>f.run('COMPLETE_INITIAL_PAYMENT',f.payment(),f.actor,duplicate),/already exists/);});
test('revocation and PO revision changes invalidate future bypass without rewriting payments',()=>{const f=fixture(),g=f.run('APPROVE_PROCESS_EXEMPTION',f.grant()),x=get(f,g).processExemptions[0];assert.throws(()=>f.run('APPROVE_PROCESS_EXEMPTION',f.grant(),f.actor,g.state),/already exists/);const revoke=f.run('REVOKE_PROCESS_EXEMPTION',{exemptionId:x.id,reason:'Supplier no longer needs early payment'},f.actor,g.state);assert.equal(processGateAllowed(get(f,revoke),'ARTWORK','PAYMENT'),false);assert.deepEqual(revoke.state.payments,g.state.payments);const changed=structuredClone(g.state);changed.orders.find(o=>o.id===f.o.id).revision++;assert.equal(processGateAllowed(changed.orders.find(o=>o.id===f.o.id),'ARTWORK','PAYMENT'),false);const touched=f.run('ADD_NOTE',{remarks:'Revision changed'},f.actor,changed);assert.equal(get(f,touched).processExemptions[0].status,'SUPERSEDED');});
test('actual artwork completion fulfils exemption; a later artwork change cannot reuse it',()=>{const f=fixture(),g=f.run('APPROVE_PROCESS_EXEMPTION',f.grant()),o=get(f,g);o.artwork.current={id:'actual-artwork'};const r=f.run('CONFIRM_ARTWORK',{fileIds:[f.file.id],remarks:'Actual supplier reply'},f.actor,g.state);assert.equal(get(f,r).processExemptions[0].status,'FULFILLED');assert.equal(activeProcessExemptions(get(f,r)).length,0);get(f,r).artwork.pending={id:'new-art'};assert.equal(processGateAllowed(get(f,r),'ARTWORK','PAYMENT'),false);});

test('acknowledgement exception can permit PI recording without skipping PI verification',()=>{const f=fixture(),pi=structuredClone(f.o.pi);f.o.confirmation=null;f.o.pi=null;const g=f.run('APPROVE_PROCESS_EXEMPTION',f.grant('CONFIRM',['PI_RECORD']));assert.equal(orderProgress(g.state,get(f,g),f.actor).action,'pi');const r=f.run('RECORD_PI',{number:pi.number,date:pi.date,currency:pi.currency,amount:major(pi.amountMinor),quantity:pi.quantity,termsConfirmed:true,commitmentConfirmed:true,fileIds:[f.file.id]},f.actor,g.state);assert.equal(get(f,r).pi.status,'RECEIVED');assert.equal(get(f,r).confirmation,null);assert.throws(()=>f.run('APPROVE_PI',{},f.actor,r.state),/verification/);});


test('sample QC and every later exemption stage and action are forbidden',()=>{const f=fixture();for(const stage of ['SAMPLE','BULK_QC','READY','BL','INSURANCE','PRODUCTION','PORT','COSTING'])assert.throws(()=>f.run('APPROVE_PROCESS_EXEMPTION',f.grant(stage,['PRODUCTION'])),/cannot be bypassed/);for(const action of ['PRODUCTION','DISPATCH','COMPLETE_PRODUCTION','ARRIVAL'])assert.throws(()=>f.run('APPROVE_PROCESS_EXEMPTION',f.grant('ARTWORK',[action])),/allowed next/);});
test('sample QC approval requires real early confirmations; rejection closes the exemption window permanently',()=>{const f=fixture(),g=f.run('APPROVE_PROCESS_EXEMPTION',f.grant()),paid=f.run('COMPLETE_INITIAL_PAYMENT',f.payment(),f.actor,g.state),sample=f.run('RECORD_PREPRODUCTION_SAMPLE',{remarks:'Actual sample ready for inspection'},f.actor,paid.state);assert.equal(orderProgress(sample.state,get(f,sample),f.actor).label,'Open pending processes');assert.throws(()=>f.run('APPROVE_PREPRODUCTION_SAMPLE',{result:'APPROVED',remarks:'Cannot carry artwork deferral past QC'},f.actor,sample.state),/Complete deferred/);const rejected=f.run('APPROVE_PREPRODUCTION_SAMPLE',{result:'REJECTED',remarks:'Record the actual inspection result'},f.actor,sample.state);assert.ok(get(f,rejected).processExemptionCutoffAt);assert.equal(get(f,rejected).processExemptions[0].status,'BOUNDARY_CLOSED');assert.equal(activeProcessExemptions(get(f,rejected)).length,0);assert.equal(pendingProcessExemptions(get(f,rejected)).length,1);const corrected=f.run('RECORD_PREPRODUCTION_SAMPLE',{remarks:'Corrected sample recorded honestly'},f.actor,rejected.state);assert.throws(()=>f.run('APPROVE_PROCESS_EXEMPTION',f.grant(),f.actor,corrected.state),/only before/);});
test('legacy approved QC or later actual events close all early bypasses, including stale approved records',()=>{for(const mark of [o=>o.preproductionSample={status:'APPROVED'},o=>o.productionStartedAt='2026-09-17',o=>o.productionCompletedAt='2026-09-17',o=>o.shipments=[{id:'s1',actualDeparture:'2026-09-17',lines:[]}]]){const f=fixture(),g=f.run('APPROVE_PROCESS_EXEMPTION',f.grant());mark(get(f,g));assert.equal(processGateAllowed(get(f,g),'ARTWORK','PAYMENT'),false);assert.throws(()=>f.run('APPROVE_PROCESS_EXEMPTION',f.grant(),f.actor,g.state),/only before/);}});
