import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {createSeed} from '../shared/seed.mjs';
import {execute} from '../shared/domain.mjs';
import {ensureRecordReferences,softwareReference,referenceKey,referenceRecords,preserveRecordReferences,integrationSnapshot} from '../shared/references.mjs';
import {Store} from '../server/store.mjs';
import {scopedState,makeServer} from '../server/index.mjs';
const seed=()=>{const s=createSeed('2026-09-11');delete s.recordReferences;for(const o of s.orders)delete o.numberSource;return s;};
test('backfill is permanent and leaves every business record and issued snapshot unchanged',()=>{const s=seed(),before=structuredClone(s);assert.ok(ensureRecordReferences(s));assert.equal(ensureRecordReferences(s),false);const refs=structuredClone(s.recordReferences);for(const k of Object.keys(before))assert.deepEqual(s[k],before[k]);s.orders.reverse();s.vendors.reverse();ensureRecordReferences(s);assert.deepEqual(s.recordReferences,refs);assert.ok(softwareReference(s,'orders',s.orders[0].id).startsWith('FH-LAE-I-PO-'));});
test('references survive removal, serial reset, restoration and nested duplicate IDs',()=>{const s=seed();s.orders=[{id:'old',serialNumber:1,lines:[{id:'same'}]},{id:'other',serialNumber:2,lines:[{id:'same'}]}];ensureRecordReferences(s);const old=softwareReference(s,'orders','old'),line1=softwareReference(s,'orderLines','same','orders','old'),line2=softwareReference(s,'orderLines','same','orders','other');assert.notEqual(line1,line2);s.orders=[];s.nextOrderSerial=1;s.orders.push({id:'new',serialNumber:1});ensureRecordReferences(s);assert.equal(softwareReference(s,'orders','new'),'FH-PO-3');s.orders.push({id:'old'});ensureRecordReferences(s);assert.equal(softwareReference(s,'orders','old'),old);});
test('registry identity, existing links and counters cannot be rewritten at persistence boundary',()=>{const s=seed();ensureRecordReferences(s);for(const change of [n=>n.recordReferences.namespace=crypto.randomUUID(),n=>n.recordReferences.next.orders=1,n=>delete n.recordReferences.entries[Object.keys(n.recordReferences.entries)[0]]]){const n=structuredClone(s);change(n);assert.throws(()=>preserveRecordReferences(s,n));}const n=structuredClone(s),entries=Object.values(n.recordReferences.entries).filter(e=>e.type==='orders');entries[1].reference=entries[0].reference;assert.throws(()=>ensureRecordReferences(n),/duplicate/);});
test('ERP links enforce Admin, company identity, duplicate prevention and exact retry',()=>{let s=seed();ensureRecordReferences(s);const admin=s.users.find(u=>u.role==='ADMIN'),manager=s.users.find(u=>u.role==='MANAGER'),recordKey=referenceKey('items',s.items[0].id),p={recordKey,system:'TALLY',companyKey:'company-guid',externalId:'stock-guid',masterId:'12'};assert.throws(()=>execute(s,{type:'LINK_EXTERNAL_REFERENCE',payload:p},manager),/Administrator/);s=execute(s,{type:'LINK_EXTERNAL_REFERENCE',payload:p},admin).state;const eventCount=s.events.length,again=execute(s,{type:'LINK_EXTERNAL_REFERENCE',payload:p},admin);assert.equal(again.result.alreadyLinked,true);assert.equal(again.state.events.length,eventCount);assert.equal(again.state.recordReferences.links.length,1);assert.throws(()=>execute(s,{type:'LINK_EXTERNAL_REFERENCE',payload:{...p,externalId:'other'}},admin),/different link/);assert.throws(()=>execute(s,{type:'LINK_EXTERNAL_REFERENCE',payload:{...p,recordKey:referenceKey('items',s.items[1].id)}},admin),/already linked/);const secondCompany=execute(s,{type:'LINK_EXTERNAL_REFERENCE',payload:{...p,recordKey:referenceKey('items',s.items[1].id),companyKey:'another-company'}},admin);assert.equal(secondCompany.state.recordReferences.links.length,2);});
test('scoped reference projection cannot disclose hidden orders or their nested records',()=>{const s=seed();s.orders.push({id:'hidden',scope:'UTILITY',lines:[{id:'secret-line'}]});ensureRecordReferences(s);const u={id:'limited',role:'MANAGER',scopes:['LAE_IMPORT'],active:true},out=scopedState(s,u);assert.equal(Object.values(out.recordReferences.entries).some(e=>e.id==='hidden'||e.id==='secret-line'),false);assert.throws(()=>execute(s,{type:'LINK_EXTERNAL_REFERENCE',payload:{recordKey:referenceKey('orders','hidden'),system:'ERP',companyKey:'c',externalId:'x'}},u),/Administrator/);const snapshot=integrationSnapshot(out);assert.equal(snapshot.records.some(r=>r.id==='hidden'),false);assert.ok(snapshot.records.every(r=>r.integrationKey.startsWith(snapshot.workspaceNamespace+':FH-')));});
test('legacy SQLite migration backs up once, survives reopen and preserves masters and financials',()=>{const dir=mkdtempSync(join(tmpdir(),'fh-refs-')),file=join(dir,'data.sqlite'),s=seed(),db=new DatabaseSync(file);db.exec('CREATE TABLE workspace(id INTEGER PRIMARY KEY,revision INTEGER,payload TEXT)');db.prepare('INSERT INTO workspace VALUES(1,?,?)').run(s.revision,JSON.stringify(s));db.close();let store=new Store(file);const a=store.read();assert.ok(a.recordReferences);for(const k of ['orders','payments','items','vendors'])assert.deepEqual(a[k],s[k]);const backups=readdirSync(dir).filter(x=>x.includes('before-record-references'));assert.equal(backups.length,1);const revision=a.revision,namespace=a.recordReferences.namespace;store.close();store=new Store(file);assert.equal(store.read().revision,revision);assert.equal(store.read().recordReferences.namespace,namespace);store.close();});
test('new records receive references in their existing transaction; rejected commands consume none',()=>{let s=seed();ensureRecordReferences(s);const u=s.users.find(u=>u.role==='MANAGER'),item=s.items[0],before=structuredClone(s.recordReferences);item.baseId='complaint-base';s.bases.push({id:'complaint-base',code:'CMP',scope:item.scope});assert.throws(()=>execute(s,{type:'ADD_COMPLAINT',payload:{itemId:item.id,severity:'UNKNOWN',summary:'bad'}},u));assert.deepEqual(s.recordReferences,before);s=execute(s,{type:'ADD_COMPLAINT',payload:{itemId:item.id,severity:'MINOR',summary:'Reference fixture'}},u).state;assert.equal(softwareReference(s,'complaints',s.complaints.at(-1).id),'FH-CMP-1');});
test('snapshot endpoint requires Admin and preserves IDs, relationships and integer amounts',async()=>{const dir=mkdtempSync(join(tmpdir(),'fh-ref-api-')),store=new Store(join(dir,'db.sqlite'),seed());store.addAccount('u-admin','admin@example.test','testing-only-12345');store.addAccount('u-manager','manager@example.test','testing-only-12345');const server=makeServer(store);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{assert.equal((await fetch(base+'/api/integration/v1/snapshot')).status,401);for(const [email,status] of [['admin@example.test',200],['manager@example.test',403]]){const login=await fetch(base+'/api/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({email,password:'testing-only-12345'})});const r=await fetch(base+'/api/integration/v1/snapshot',{headers:{Cookie:login.headers.get('set-cookie').split(';')[0]}});assert.equal(r.status,status);if(status===200){const data=await r.json(),order=data.records.find(r=>r.type==='orders');assert.ok(order.relations.vendorId.reference);assert.equal(data.version,1);assert.equal(data.connectionStatus,'Not connected');assert.deepEqual(order.data,store.read().orders.find(o=>o.id===order.id));}}}finally{await new Promise(r=>server.close(r));store.close();}});


test('LAE Import PO prefix preserves assigned references, counters and other divisions',()=>{const s=seed();s.orders=[{id:'legacy',scope:'LAE_IMPORT'}];ensureRecordReferences(s);const key=referenceKey('orders','legacy');s.recordReferences.entries[key].reference='FH-PO-000001';const previous=structuredClone(s);s.orders.push({id:'import',scope:'LAE_IMPORT'},{id:'domestic',scope:'LAE_DOMESTIC'});ensureRecordReferences(s);assert.equal(softwareReference(s,'orders','legacy'),'FH-PO-000001');assert.equal(softwareReference(s,'orders','import'),'FH-LAE-I-PO-2');assert.equal(softwareReference(s,'orders','domestic'),'FH-PO-3');preserveRecordReferences(previous,s);const exported=integrationSnapshot(s).records.find(r=>r.id==='import');assert.equal(exported.reference,'FH-LAE-I-PO-2');assert.ok(exported.integrationKey.endsWith(':FH-LAE-I-PO-2'));s.orders.find(r=>r.id==='import').scope='LAE_DOMESTIC';assert.equal(ensureRecordReferences(s),false);assert.equal(softwareReference(s,'orders','import'),'FH-LAE-I-PO-2');});
