import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {Store} from '../server/store.mjs';
import {emptyState,makeServer} from '../server/index.mjs';
import {RoCostingStore} from '../server/ro-costing-store.mjs';
import {validateRoRecord,calculateRoCosting} from '../shared/ro-costing.mjs';
import {importantRoDocuments} from '../shared/ro-documents.mjs';
const record=(ro='1605-A')=>validateRoRecord({ro,supplier:'Joint suppliers',invoices:[{supplier:'A',invoice:'CI-1',currency:'USD',goods:100,extras:10,face:110},{supplier:'B',invoice:'CI-2',currency:'USD',goods:200,extras:0,face:200}],customsFx:86,actuals:{supplierInr:27900,bankNet:100,forwarderNet:1000,otherNet:0,bcd:900,sws:90,sureshRate:99,expenseCoverage:'Complete',currencyConfirmed:true,confirmation:'Payments, net bills and nil other expenses checked.'}});
test('important documents distinguish actual forwarding-agent issuers from overseas and shipping-line bills',()=>{
 const files=[{id:'ci',name:'original.pdf',kind:'Commercial invoice',sha256:'matched'},{id:'scan',name:'scan.pdf',kind:'Commercial invoice (visually reviewed scan)'},{id:'inward',name:'375923814092026INNPK6.pdf',kind:'Assessed BOE'},{id:'dta',name:'391167721092026INNPK6.pdf',kind:'Assessed BOE'},{id:'draft',name:'3759238-draft.pdf',kind:'Preliminary BOE checklist'},{id:'forwarder',name:'invoice.pdf',kind:'Forwarder proforma (provisional)'}];
 files.push({id:'future',name:'1547 proforma.pdf',kind:'Forwarding agent proforma (provisional) — Future Consol'},{id:'yasuda',name:'bill.pdf',kind:'Forwarding agent invoice — Yasuda'},{id:'world',name:'bill.pdf',kind:'Forwarding agent invoice — World Gates'},{id:'overseas',name:'Future Consol debit.pdf',kind:'Overseas agent debit note'},{id:'line',name:'Future Consol tax.pdf',kind:'Shipping-line invoice'},{id:'generic',name:'World Gates invoice.pdf',kind:'Supporting document'});
 const roles=importantRoDocuments({boe:'3759238',invoices:[{sha256:'matched'}]},files);assert.deepEqual(roles.commercialInvoices.map(f=>f.id),['ci','scan']);assert.deepEqual(roles.inwardBoe.map(f=>f.id),['inward']);assert.deepEqual(roles.otherBoe.map(f=>f.id),['dta']);assert.deepEqual(roles.forwarderInvoices.map(f=>f.id),['future','yasuda','world']);assert.equal(roles.forwarderInvoices[0].agent,'Future Consol');assert.equal(importantRoDocuments({boe:''},files).inwardBoe.length,0);
});
test('joint loading uses unique goods USD, includes payment extras once, excludes reference GST/customs FX',()=>{
 const r=record();r.expenses=[{currency:'INR',net:1000,gst:180,gross:1180,component:'Reference',provisional:true}];const c=calculateRoCosting(r);assert.equal(c.goodsUsd,300);assert.equal(c.faceUsd,310);assert.equal(c.enteredTotal,29990);assert.equal(c.rate,29990/300);r.customsFx=96;assert.equal(calculateRoCosting(r).rate,c.rate);r.invoices.push(r.invoices[0]);assert.throws(()=>calculateRoCosting(r),/unique/);
});
test('missing actuals, missing invoices, currency conflicts and unconfirmed completeness never become final',()=>{
 const r=record();for(const k of ['supplierInr','bankNet','forwarderNet','otherNet','bcd','sws']){const bad=structuredClone(r);bad.actuals[k]=null;assert.equal(calculateRoCosting(bad).rate,null);}
 r.actuals.expenseCoverage='Pending';assert.equal(calculateRoCosting(r).rate,null);r.actuals.expenseCoverage='Complete';r.invoices[0].currency='CONFLICT';assert.equal(calculateRoCosting(r).rate,null);r.invoices=[];r.boeGoodsUsd=300;assert.equal(calculateRoCosting(r).goodsUsd,300);assert.equal(calculateRoCosting(r).rate,null);
 assert.throws(()=>validateRoRecord({...record(),ro:'../1605'}),/exact RO/);assert.throws(()=>validateRoRecord({...record(),actuals:{expenseCoverage:'Complete'}}),/Explain/);
 assert.equal(calculateRoCosting({ro:'MISSING',actuals:{}}).goodsUsd,null);
 const boeOnly=record();boeOnly.invoices[0].basis='BOE invoice face; original supplier CI not located';assert.equal(calculateRoCosting(boeOnly).rate,null);
 assert.equal(validateRoRecord({...record(),customsFx:96.42857143}).customsFx,96.428571);
 assert.throws(()=>validateRoRecord({...record(),boeDate:'2026-02-31'}),/valid YYYY/);
});
test('RO transaction preserves main state, blocks stale/partial imports, retries safely and retains immutable history',()=>{
 const dir=mkdtempSync(join(tmpdir(),'fh-ro-')),store=new Store(join(dir,'test.sqlite'),emptyState()),module=new RoCostingStore(store);
 try{const baseline=store.read(),r=record(),input={records:[{record:r,expectedRevision:0}],reason:'Reviewed initial record'},id=randomUUID();module.import('admin',input,id);module.import('admin',input,id);assert.equal(module.detail('admin',r.ro).revision,1);assert.throws(()=>module.import('admin',{...input,reason:'Different'},id),/different content/);
 assert.throws(()=>module.import('admin',{records:[{record:record('NEW'),expectedRevision:0},{record:r,expectedRevision:0}],reason:'Atomic batch'},randomUUID()),/changed/);assert.throws(()=>module.detail('admin','NEW'),/not found/);
 const update=record();update.actuals.supplierInr=30000;module.save('admin',{record:update,expectedRevision:1,reason:'Correct payment'},randomUUID());assert.equal(module.detail('admin',r.ro).revision,2);assert.equal(module.detail('admin',r.ro).history.length,2);assert.throws(()=>store.db.exec('DELETE FROM ro_costing_events'),/append-only/);assert.deepEqual(store.read(),baseline);
 const doc={ro:r.ro,name:'invoice.xls',base64:Buffer.from('isolated test').toString('base64')};const file=module.upload('admin',doc,randomUUID());assert.equal(module.upload('admin',doc,randomUUID()).id,file.id);assert.equal(Buffer.from(module.download('admin',file.id).body).toString(),'isolated test');assert.throws(()=>module.upload('admin',{...doc,name:'../invoice.pdf'},randomUUID()),/filename/);
 }finally{store.close();rmSync(dir,{recursive:true,force:true});}
});
test('authenticated RO APIs enforce scope, role, CSRF and document privacy with bounded pagination',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'fh-ro-http-')),s=emptyState();s.users.push({id:'viewer',name:'Viewer',role:'VIEWER',scopes:['LAE_IMPORT']},{id:'other',name:'Other',role:'MANAGER',scopes:['LAE_DOMESTIC']});const store=new Store(join(dir,'test.sqlite'),s);for(const u of s.users)store.addAccount(u.id,u.id+'@example.test','Isolated-test-password');const server=makeServer(store,{log:()=>{}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const call=async(path,session={},data)=>{const res=await fetch(base+path,{method:data?'POST':'GET',headers:{Origin:base,Cookie:session.cookie||'','X-CSRF-Token':session.csrf||'','Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};};
 const login=async id=>{const r=await call('/api/login',{}, {email:id+'@example.test',password:'Isolated-test-password'});return {cookie:r.cookie,csrf:(await call('/api/bootstrap',{cookie:r.cookie})).data.csrf};};
 try{const admin=await login('admin'),viewer=await login('viewer'),other=await login('other'),p={records:[{record:record(),expectedRevision:0}],reason:'Checked'};assert.equal((await call('/api/ro-costings')).status,401);assert.equal((await call('/api/ro-costings',other)).status,403);assert.equal((await call('/api/ro-costings/import',viewer,p)).status,403);assert.equal((await call('/api/ro-costings/import',{cookie:admin.cookie},p)).status,403);assert.equal((await call('/api/ro-costings/import',admin,p)).status,200);assert.equal((await call('/api/ro-costings',viewer)).data.total,1);assert.equal((await call('/api/ro-costings?offset=-1',admin)).status,400);assert.equal((await call('/api/ro-costings/files/unknown')).status,401);assert.equal((await call('/api/ro-costings/files/unknown',other)).status,403);
  const uploaded=await call('/api/ro-costings/files',admin,{ro:'1605-A',name:'commercial.pdf',kind:'Commercial invoice',base64:Buffer.from('%PDF-1.4\nIsolated fixture').toString('base64')});assert.equal(uploaded.status,201);const detail=await call('/api/ro-costings/record?ro=1605-A',admin);assert.equal(detail.data.importantDocuments.commercialInvoices.length,1);const view=await fetch(base+'/api/ro-costings/files/'+uploaded.data.id+'?view=1',{headers:{Cookie:admin.cookie}});assert.equal(view.headers.get('content-type'),'application/pdf');assert.match(view.headers.get('content-disposition'),/^inline;/);
  const agent=await call('/api/ro-costings/files',admin,{ro:'1605-A',name:'agent.pdf',kind:'Forwarder proforma (provisional)',base64:Buffer.from('%PDF-1.4\nVerified issuer fixture').toString('base64')});const source=moduleDocument(store,agent.data.id),classification={id:agent.data.id,sha256:source.sha256,kind:'Forwarding agent proforma (provisional) — Future Consol',reason:'Issuer and billed customer checked.',expectedSequence:0};
  assert.equal((await call('/api/ro-costings/document-classification',viewer,classification)).status,403);assert.equal((await call('/api/ro-costings/document-classification',other,classification)).status,403);assert.equal((await call('/api/ro-costings/document-classification',{cookie:admin.cookie},classification)).status,403);assert.equal((await call('/api/ro-costings/document-classification',admin,{...classification,sha256:'wrong'})).status,400);
  const classifyResponse=await fetch(base+'/api/ro-costings/document-classification',{method:'POST',headers:{Origin:base,Cookie:admin.cookie,'X-CSRF-Token':admin.csrf,'Content-Type':'application/json','Idempotency-Key':'agent-classification-replay'},body:JSON.stringify(classification)});assert.equal(classifyResponse.status,200);const saved=await classifyResponse.json();const retry=await fetch(base+'/api/ro-costings/document-classification',{method:'POST',headers:{Origin:base,Cookie:admin.cookie,'X-CSRF-Token':admin.csrf,'Content-Type':'application/json','Idempotency-Key':'agent-classification-replay'},body:JSON.stringify(classification)});assert.deepEqual(await retry.json(),saved);
  assert.equal((await call('/api/ro-costings/document-classification',admin,classification)).status,409);const verified=await call('/api/ro-costings/record?ro=1605-A',admin);assert.equal(verified.data.importantDocuments.forwarderInvoices[0].agent,'Future Consol');assert.equal(verified.data.revision,1);assert.deepEqual(moduleDocument(store,agent.data.id),source);assert.throws(()=>store.db.exec('DELETE FROM ro_document_classifications'),/append-only/);assert.throws(()=>store.db.exec("UPDATE ro_document_classifications SET reason='overwrite'"),/append-only/);
 }finally{await new Promise(r=>server.close(r));store.close();rmSync(dir,{recursive:true,force:true});}
});
function moduleDocument(store,id){const row=store.db.prepare('SELECT * FROM ro_costing_documents WHERE id=?').get(id);return {...row,body:Buffer.from(row.body).toString('base64')};}
