import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../server/store.mjs';
import {makeServer,scopedState} from '../server/index.mjs';
import {createSeed} from '../shared/seed.mjs';
async function serverFixture(){const dir=mkdtempSync(join(tmpdir(),'fh-test-')),s=createSeed('2026-09-11');s.users.push({id:'u-utility',name:'Utility-only test viewer',role:'VIEWER',scopes:['UTILITY_DOMESTIC'],active:true});const store=new Store(join(dir,'test.sqlite'),s);for(const id of['u-admin','u-manager','u-exec','u-product','u-viewer','u-utility'])store.addAccount(id,id+'@example.test','Test-only-password-0123');const server=makeServer(store);await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;async function req(path,{method='GET',payload,token,csrf,originHeader=origin}={}){const res=await fetch(origin+path,{method,headers:{'Content-Type':'application/json',...(method!=='GET'?{Origin:originHeader}:{}),...(token?{Cookie:'fh_session='+token}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},...(payload!==undefined?{body:JSON.stringify(payload)}:{})});const text=await res.text();let data;try{data=JSON.parse(text);}catch{data=text;}return {status:res.status,data,headers:res.headers};}async function login(id='u-manager'){const r=await req('/api/login',{method:'POST',payload:{email:id+'@example.test',password:'Test-only-password-0123'}});const token=r.headers.get('set-cookie').match(/fh_session=([^;]+)/)[1],b=await req('/api/bootstrap',{token});return {token,csrf:b.data.csrf,state:b.data.state,user:b.data.user,cookie:r.headers.get('set-cookie')};}return{store,req,login,origin,close:async()=>{await new Promise(r=>server.close(r));store.close();rmSync(dir,{recursive:true,force:true});}};}

test('unauthenticated state and evidence access return 401',async()=>{const f=await serverFixture();try{assert.equal((await f.req('/api/bootstrap')).status,401);assert.equal((await f.req('/api/files/anything')).status,401);}finally{await f.close();}});
test('successful local authentication uses HttpOnly SameSite cookie; invalid login is generic',async()=>{const f=await serverFixture();try{const a=await f.login();assert.match(a.cookie,/HttpOnly/);assert.match(a.cookie,/SameSite=Strict/);assert.equal(a.state.orders.length,8);const bad=await f.req('/api/login',{method:'POST',payload:{email:'missing@example.test',password:'not-a-real-password'}});assert.equal(bad.status,401);assert.equal(bad.data.error,'Invalid credentials or inactive account.');}finally{await f.close();}});
test('role is taken from the authenticated server account, not from client payload',async()=>{const f=await serverFixture();try{const a=await f.login('u-exec'),o=a.state.orders.find(o=>o.status==='PENDING_APPROVAL');const r=await f.req('/api/commands',{method:'POST',...a,payload:{type:'APPROVE_ORDER',payload:{orderId:o.id,user:{role:'ADMIN'}},expectedRevision:a.state.revision}});assert.equal(r.status,403);assert.equal(f.store.read().orders.find(x=>x.id===o.id).status,'PENDING_APPROVAL');}finally{await f.close();}});
test('state records are scoped to allowed divisions, including evidence and vendors',async()=>{const f=await serverFixture();try{const a=await f.login('u-utility');assert.equal(a.state.orders.length,0);assert.equal(a.state.items.length,0);assert.equal(a.state.vendors.length,0);assert.equal(a.state.files.length,0);assert.equal(a.state.payments.length,0);}finally{await f.close();}});
test('CSRF and cross-origin writes are rejected',async()=>{const f=await serverFixture();try{const a=await f.login(),o=a.state.orders[0],payload={type:'ADD_NOTE',payload:{orderId:o.id,remarks:'Must not save'},expectedRevision:a.state.revision};assert.equal((await f.req('/api/commands',{method:'POST',token:a.token,payload})).status,403);assert.equal((await f.req('/api/commands',{method:'POST',...a,originHeader:'https://untrusted.invalid',payload})).status,403);}finally{await f.close();}});
test('optimistic revision check prevents lost updates from stale browser state',async()=>{const f=await serverFixture();try{const a=await f.login(),o=a.state.orders[0],payload={type:'ADD_NOTE',payload:{orderId:o.id,remarks:'First update'},expectedRevision:a.state.revision};const r=await f.req('/api/commands',{method:'POST',...a,payload});assert.equal(r.status,200);assert.equal((await f.req('/api/commands',{method:'POST',...a,payload})).status,409);assert.equal(f.store.read().events.filter(e=>e.summary==='First update').length,1);}finally{await f.close();}});
test('SQLite audit events cannot be updated or deleted',async()=>{const f=await serverFixture();try{assert.throws(()=>f.store.db.exec("UPDATE audit_events SET payload='{}'"),/append-only/);assert.throws(()=>f.store.db.exec('DELETE FROM audit_events'),/append-only/);}finally{await f.close();}});
test('uploaded document bytes persist with order scope and safe download headers',async()=>{const f=await serverFixture();try{const a=await f.login(),o=a.state.orders[0],text='Actual test upload body';const r=await f.req('/api/files',{method:'POST',...a,payload:{name:'receipt.txt',base64:Buffer.from(text).toString('base64'),orderIds:[o.id],expectedRevision:a.state.revision}});assert.equal(r.status,201);const out=await f.req('/api/files/'+r.data.id,{token:a.token});assert.equal(out.status,200);assert.equal(out.data,text);assert.match(out.headers.get('content-disposition'),/attachment/);const other=await f.login('u-utility');assert.equal((await f.req('/api/files/'+r.data.id,{token:other.token})).status,404);}finally{await f.close();}});
test('executable/HTML evidence and path traversal are rejected',async()=>{const f=await serverFixture();try{const a=await f.login();assert.equal((await f.req('/api/files',{method:'POST',...a,payload:{name:'file.html',base64:Buffer.from('<script>1</script>').toString('base64'),orderIds:[],expectedRevision:a.state.revision}})).status,400);assert.equal((await f.req('/server/store.mjs')).status,404);assert.equal((await f.req('/data/purchase-pilot.sqlite')).status,404);}finally{await f.close();}});
test('upload permission cannot be gained merely by owning a login',async()=>{const f=await serverFixture();try{const a=await f.login('u-viewer');assert.equal((await f.req('/api/files',{method:'POST',...a,payload:{name:'test.txt',base64:'dGVzdA==',orderIds:[],expectedRevision:a.state.revision}})).status,403);}finally{await f.close();}});
test('logging out invalidates the server session',async()=>{const f=await serverFixture();try{const a=await f.login();assert.equal((await f.req('/api/logout',{method:'POST',...a,payload:{}})).status,200);assert.equal((await f.req('/api/bootstrap',{token:a.token})).status,401);}finally{await f.close();}});
test('business data persists when the local store is reopened',async()=>{const dir=mkdtempSync(join(tmpdir(),'fh-persist-'));try{const path=join(dir,'p.sqlite'),s=new Store(path,createSeed('2026-09-11')),state=s.read(),id=state.orders[0].id;s.transact({type:'ADD_NOTE',payload:{orderId:id,remarks:'Persisted test note'}},'u-manager',state.revision);s.close();const next=new Store(path);assert.ok(next.read().events.some(e=>e.summary==='Persisted test note'));next.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test('local account utility commits profile and hashed credential together',async()=>{const f=await serverFixture();try{const profile={id:'new-pilot-user',name:'New pilot user',role:'EXECUTIVE',scopes:['LAE_IMPORT']};f.store.createLocalAccount(profile,'new-user@example.test','Test-only-new-password-1234');assert.ok(f.store.login('new-user@example.test','Test-only-new-password-1234'));assert.equal(f.store.read().users.filter(u=>u.id===profile.id).length,1);assert.ok(f.store.read().events.some(e=>e.action==='USER_PROFILE_CREATED'&&e.entityId===profile.id));assert.ok(!JSON.stringify(f.store.read()).includes('Test-only-new-password'));}finally{await f.close();}});
test('duplicate account creation rolls back the new profile and audit entries',async()=>{const f=await serverFixture();try{const before=structuredClone(f.store.read());assert.throws(()=>f.store.createLocalAccount({id:'must-not-exist',name:'Duplicate account test',role:'VIEWER',scopes:['LAE_IMPORT']},'u-manager@example.test','Test-only-new-password-1234'),/already exists/);assert.deepEqual(f.store.read(),before);assert.throws(()=>f.store.createLocalAccount({id:'bad-scope',name:'Bad scope',role:'EXECUTIVE',scopes:['UNKNOWN']},'invalid@example.test','Test-only-new-password-1234'),/scopes/);}finally{await f.close();}});
