import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createSeed} from '../shared/seed.mjs';
import {execute} from '../shared/domain.mjs';
import {vmsConfig,vmsProfileSnapshot,vmsAnalytics} from '../shared/vms.mjs';
function fixture(){let state=createSeed('2026-09-11');const actor=state.users.find(u=>u.role==='MANAGER'),vendorId=state.vendors.find(v=>v.scopes.includes('LAE_IMPORT')).id;const run=(type,p={},user=actor)=>{const result=execute(state,{type,payload:{vendorId,...p}},user,{now:'2026-09-13T12:00:00Z',id:randomUUID});state=result.state;return result.result;};return {get state(){return state;},get vendor(){return state.vendors.find(v=>v.id===vendorId);},actor,run,vendorId};}
test('existing VMS configuration gains empty catalogues without losing IDs',()=>{const old={products:[{id:'p',name:'Engine'}]};const cfg=vmsConfig({vms:old});assert.equal(cfg.products[0].id,'p');for(const k of ['groups','classifications','countries','regions','districts','currencies'])assert.deepEqual(cfg[k],[]);assert.deepEqual(old,{products:[{id:'p',name:'Engine'}]});});
test('product groups and analytics retain scoped vendor counts, including zero coverage',()=>{const f=fixture(),group=f.run('VMS_SAVE_CATALOG',{kind:'groups',name:'Farm machinery'}).id,product=f.run('VMS_SAVE_CATALOG',{kind:'products',name:'Engine',groupId:group}).id;f.run('VMS_SAVE_CATALOG',{kind:'products',name:'Pump'});f.run('VMS_SAVE_PROFILE',{...vmsProfileSnapshot(f.vendor),products:[product]});const report=vmsAnalytics([f.vendor],vmsConfig(f.state));assert.deepEqual(report.products.map(t=>t.count),[1,0]);assert.equal(report.products[0].groupId,group);assert.equal(report.vendors[0].products,1);assert.throws(()=>f.run('VMS_SAVE_CATALOG',{kind:'products',name:'Bad',groupId:'missing'}),/valid product group/);f.run('VMS_SAVE_CATALOG',{kind:'groups',id:group,name:'Farm machinery',active:false});assert.equal(f.vendor.crm.products[0],product);});
test('location hierarchy rejects wrong parents and preserves free-text legacy location',()=>{const f=fixture(),country=f.run('VMS_SAVE_CATALOG',{kind:'countries',name:'China'}).id,other=f.run('VMS_SAVE_CATALOG',{kind:'countries',name:'India'}).id,region=f.run('VMS_SAVE_CATALOG',{kind:'regions',name:'Zhejiang',parentId:country}).id,district=f.run('VMS_SAVE_CATALOG',{kind:'districts',name:'Ningbo',parentId:region}).id;assert.throws(()=>f.run('VMS_SAVE_PROFILE',{...vmsProfileSnapshot(f.vendor),countryId:other,regionId:region}),/Region does not belong/);f.run('VMS_SAVE_PROFILE',{...vmsProfileSnapshot(f.vendor),countryId:country,regionId:region,districtId:district});assert.equal(f.vendor.city,'Ningbo');assert.equal(f.vendor.country,'China');f.run('VMS_SAVE_PROFILE',{...vmsProfileSnapshot(f.vendor),countryId:'',regionId:'',districtId:'',city:'Legacy city'});assert.equal(f.vendor.city,'Legacy city');});
test('manual VMS currency references are precise, dated and never change financials',()=>{const f=fixture(),before=JSON.stringify({orders:f.state.orders,prices:f.state.priceLists,payments:f.state.payments});const input={kind:'currencies',name:'US Dollar',code:'USD',inrPerUnit:'83.123456',rateDate:'2026-09-13'};f.run('VMS_SAVE_CATALOG',input);assert.equal(vmsConfig(f.state).currencies[0].inrPerUnit,'83.123456');assert.throws(()=>f.run('VMS_SAVE_CATALOG',{...input,name:'Duplicate'}),/already exists/);assert.throws(()=>f.run('VMS_SAVE_CATALOG',{...input,name:'RMB',code:'CNY',inrPerUnit:'-1'}),/positive/);assert.throws(()=>f.run('VMS_SAVE_CATALOG',{...input,name:'RMB',code:'CNY',rateDate:'2026-02-30'}),/valid/);assert.equal(JSON.stringify({orders:f.state.orders,prices:f.state.priceLists,payments:f.state.payments}),before);});
test('offline profile sync merges unrelated changes and replays only once after lost acknowledgement',()=>{const f=fixture(),base=vmsProfileSnapshot(f.vendor);f.run('VMS_SAVE_PROFILE',{...base,website:'https://supplier.example.test'});const input={requestId:randomUUID(),commandType:'VMS_SAVE_PROFILE',base,payload:{...base,remarks:'Offline notes'}};f.run('VMS_SYNC_EDIT',input);assert.equal(f.vendor.crm.website,'https://supplier.example.test');assert.equal(f.vendor.crm.remarks,'Offline notes');const n=f.state.events.length;assert.equal(f.run('VMS_SYNC_EDIT',input).alreadySynced,true);assert.equal(f.state.events.length,n);assert.throws(()=>f.run('VMS_SYNC_EDIT',{...input,payload:{...input.payload,remarks:'Changed request'}}),e=>e.code==='CONFLICT');});
test('overlapping offline edits stop for review; rejected edits are atomic',()=>{const f=fixture(),base=vmsProfileSnapshot(f.vendor);f.run('VMS_SAVE_PROFILE',{...base,remarks:'Another manager'});const before=JSON.stringify(f.state);assert.throws(()=>f.run('VMS_SYNC_EDIT',{requestId:randomUUID(),commandType:'VMS_SAVE_PROFILE',base,payload:{...base,remarks:'My offline edit'}}),e=>e.code==='CONFLICT');assert.equal(JSON.stringify(f.state),before);});
test('queued actions recheck role, scope, validation and reject financial or attachment replay',()=>{const f=fixture(),base=vmsProfileSnapshot(f.vendor),viewer=f.state.users.find(u=>u.role==='VIEWER'),executive=f.state.users.find(u=>u.role==='EXECUTIVE'),sync={requestId:randomUUID(),commandType:'VMS_SAVE_PROFILE',base,payload:{...base,remarks:'Offline'}};assert.throws(()=>f.run('VMS_SYNC_EDIT',sync,viewer),e=>e.code==='FORBIDDEN');assert.throws(()=>f.run('VMS_SYNC_EDIT',sync,{...f.actor,scopes:['UTILITY_DOMESTIC']}),e=>e.code==='FORBIDDEN');assert.throws(()=>f.run('VMS_SYNC_EDIT',{...sync,commandType:'APPROVE_ORDER'}),/online/);assert.throws(()=>f.run('VMS_SYNC_EDIT',{...sync,payload:{...base,contacts:[{name:'Contact',email:'bad'}]}}),/email/);const interaction={requestId:randomUUID(),commandType:'VMS_ADD_INTERACTION',base:null,payload:{type:'NOTE',notes:'Offline expo notes',occurredAt:'2026-09-13',nextFollowUpAt:'2026-09-14',fileIds:[]}};f.run('VMS_SYNC_EDIT',interaction,executive);const n=f.vendor.crm.interactions.length;f.run('VMS_SYNC_EDIT',interaction,executive);assert.equal(f.vendor.crm.interactions.length,n);assert.throws(()=>f.run('VMS_SYNC_EDIT',{...interaction,requestId:randomUUID(),payload:{...interaction.payload,fileIds:['file']}}),/online/);});
