import {downloadRecovery} from './recovery.mjs';
import {RoCostingStore} from './ro-costing-store.mjs';
import {ImplementsStore,assertImplementsAccess,canWriteImplements} from './implements-store.mjs';
import {implementsAssets,implementsExport} from './implements-files.mjs';
import {BomManagementStore,assertBomAccess} from './bom-management-store.mjs';
import {bomAssets,exportTechnical} from './bom-management-files.mjs';
import {ProductionStore,assertProductionAccess} from './production-store.mjs';
import {productionAssets,productionCsv} from './production-files.mjs';
import {PlanningStore,assertPlanningAccess} from './planning-store.mjs';
import {planningAssets} from './planning-files.mjs';
import {domesticImageAsset} from '../shared/domestic.mjs';
import {scopedRecordReferences,integrationSnapshot} from '../shared/references.mjs';
/** Isolated local alpha. Never point it at the live VMS/ERP database.
 * The bundled native SQLite store is a review/pilot adapter, not the final shared schema.
 */
import http from 'node:http';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {randomBytes,randomUUID} from 'node:crypto';
import {Store} from './store.mjs';
import {createCleanSeed} from '../shared/clean-seed.mjs';
import {APP_VERSION,MAX_UPLOAD_BYTES,UPLOAD_EXTENSIONS,RuleError,scopeAllowed,canEdit,canCreate,canProductApprove} from '../shared/domain.mjs';
const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'..');
export function scopedState(state,actor){if(actor.role==='PLAN_OPERATOR'){const clean=createCleanSeed();for(const [key,value] of Object.entries(clean)){if(Array.isArray(value))clean[key]=[];else if(value&&typeof value==='object'&&key!=='settings')clean[key]={};}clean.users=[structuredClone(actor)];clean.revision=state.revision;return clean;}const out=structuredClone(state),ids=new Set(out.orders.filter(o=>scopeAllowed(actor,o.scope)).map(o=>o.id));out.orders=out.orders.filter(o=>ids.has(o.id));out.items=out.items.filter(i=>scopeAllowed(actor,i.scope));out.bases=out.bases.filter(b=>scopeAllowed(actor,b.scope));out.vendors=out.vendors.filter(v=>v.scopes.some(s=>scopeAllowed(actor,s)));const vs=new Set(out.vendors.map(v=>v.id)),bs=new Set(out.bases.map(b=>b.id)),is=new Set(out.items.map(i=>i.id));out.payments=out.payments.filter(p=>p.allocations.every(a=>ids.has(a.orderId)));out.costs=out.costs.filter(c=>ids.has(c.orderId));out.files=out.files.filter(f=>scopeAllowed(actor,f.scope)&&f.orderIds.every(id=>ids.has(id)));const fs=new Set(out.files.map(f=>f.id));out.events=out.events.filter(e=>e.entityType==='domestic'?scopeAllowed(actor,'LAE_DOMESTIC'):e.entityType==='order'?ids.has(e.entityId):e.entityType==='vendor'?vs.has(e.entityId):e.entityType==='base'?bs.has(e.entityId):e.entityType==='item'?is.has(e.entityId):e.entityType==='file'?fs.has(e.entityId):actor.role==='ADMIN');out.imports=scopeAllowed(actor,'LAE_IMPORT')?out.imports:[];out.vendorRequests=out.vendorRequests.filter(r=>vs.has(r.vendorId));out.priceLists=(out.priceLists||[]).filter(p=>vs.has(p.vendorId)&&(!p.baseId||bs.has(p.baseId))&&(!p.itemId||is.has(p.itemId)));out.complaints=(out.complaints||[]).filter(c=>is.has(c.itemId)&&bs.has(c.baseId));if(actor.role!=='ADMIN')out.users=out.users.filter(u=>u.id===actor.id||u.scopes.some(s=>scopeAllowed(actor,s)));if(!scopeAllowed(actor,'LAE_IMPORT')){delete out.vms;out.routes=[];out.categories=[];out.brands=[];out.plmTemplates=[];out.freightRates=[];out.freightImports=[];out.shippingImports=[];out.vendorImports=[];out.priceImports=[];}if(!scopeAllowed(actor,'LAE_DOMESTIC')){out.domesticOrders=[];out.domesticPriceLists=[];out.domesticItems=[];out.domesticModels=[];out.domesticBoms=[];delete out.domesticImports;}out.domesticPriceLists=(out.domesticPriceLists||[]).filter(p=>vs.has(p.vendorId));if(out.recordReferences)out.recordReferences=scopedRecordReferences(out,out.recordReferences);return out;}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function body(req,maxBytes=12*1024*1024){let n=0;const parts=[];for await(const p of req){n+=p.length;if(n>maxBytes)throw new RuleError('Request too large.');parts.push(p);}try{return JSON.parse(Buffer.concat(parts).toString('utf8')||'{}');}catch{throw new RuleError('Invalid JSON request.');}}
const cookie=req=>String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('fh_session='))?.slice(11)||null;
const ext=s=>'.'+s.split('.').at(-1).toLowerCase();
const MIME={'.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.html':'text/html; charset=utf-8','.pdf':'application/pdf','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.txt':'text/plain','.csv':'text/csv','.eml':'message/rfc822','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};
export function makeServer(store,{origin=null,secureCookie=false,releaseSha=process.env.SOURCE_COMMIT||process.env.FH_RELEASE_SHA||null,log=event=>console.log(JSON.stringify(event))}={}){let roCostingStore;const getRoCostings=()=>roCostingStore||(roCostingStore=new RoCostingStore(store));let implementsStore;const getImplements=()=>implementsStore||(implementsStore=new ImplementsStore(store));let bomStore;const getBom=()=>bomStore||(bomStore=new BomManagementStore(store,getImplements()));let productionStore;const getProduction=()=>productionStore||(productionStore=new ProductionStore(store,getImplements()));let planningStore;const getPlanning=()=>planningStore||(planningStore=new PlanningStore(store,getImplements()));const attempts=new Map(),release=/^[a-f0-9]{7,64}$/i.test(releaseSha||'')?releaseSha:null;return http.createServer(async(req,res)=>{
 const started=performance.now(),requestId=randomUUID();let route='static';
 res.setHeader('X-Request-ID',requestId);
 res.once('finish',()=>{const durationMs=Math.round(performance.now()-started);if(res.statusCode>=500||durationMs>=1000){try{log({event:'http_request',requestId,method:req.method,route,status:res.statusCode,durationMs});}catch{/* Logging failures must not affect a completed request. */}}});
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; frame-src 'self' https://drive.google.com; frame-ancestors 'self'; base-uri 'none'; form-action 'self'");
 try{const url=new URL(req.url,'http://localhost'),path=url.pathname;route=path.startsWith('/api/')?(['/api/health','/api/bootstrap','/api/revision','/api/login','/api/logout','/api/commands','/api/users','/api/files','/api/integration/v1/snapshot'].includes(path)?path:path.startsWith('/api/files/')?'/api/files/:id':path.startsWith('/api/requests/')?'/api/requests/:id':'/api/other'):'static';
 if(path==='/api/health'&&req.method==='GET'){try{if(!Number.isSafeInteger(store.revision()))throw Error();return json(res,200,{status:'ok',version:APP_VERSION,storage:'sqlite',releaseSha:release});}catch{return json(res,503,{status:'unavailable',version:APP_VERSION,storage:'sqlite',releaseSha:release});}}
 if(path.startsWith('/api/')){
  const write=!['GET','HEAD'].includes(req.method);if(write){if(req.headers.origin!==(origin||`http://${req.headers.host}`))throw new RuleError('Request origin is not permitted.','FORBIDDEN');}
  if(path==='/api/login'&&req.method==='POST'){const ip=req.socket.remoteAddress;let a=attempts.get(ip)||{count:0,since:Date.now()};if(Date.now()-a.since>60000)a={count:0,since:Date.now()};if(a.count>=10)return json(res,429,{error:'Too many attempts. Wait a minute before signing in.'});const p=await body(req);if(typeof p.email!=='string'||typeof p.password!=='string'||p.email.length>254||p.password.length>256)throw new RuleError('Invalid login request.');const s=store.login(p.email,p.password);if(!s){a.count++;attempts.set(ip,a);return json(res,401,{error:'Invalid credentials or inactive account.'});}attempts.delete(ip);res.setHeader('Set-Cookie',`fh_session=${s.token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${secureCookie?'; Secure':''}`);return json(res,200,{user:s.user});}
  const session=store.session(cookie(req));if(!session)return json(res,401,{error:'Sign in to the local pilot workspace.'});if(write&&req.headers['x-csrf-token']!==session.csrf)throw new RuleError('Session request token is missing or invalid.','FORBIDDEN');
  if(path==='/api/admin/recovery'&&req.method==='POST'){if(session.user.role!=='ADMIN')throw new RuleError('Administrator access is required.','FORBIDDEN');await downloadRecovery(store,res);return;}
  if(path.startsWith('/api/planning/')){
   assertPlanningAccess(session.user);const module=getPlanning(),id=session.user.id;
   if(path==='/api/planning/workspace'&&req.method==='GET')return json(res,200,{...module.read(id,{month:url.searchParams.get('month')||'',status:url.searchParams.get('status')||'',before:url.searchParams.has('before')?Number(url.searchParams.get('before')):null}),csrf:session.csrf});
   if(path==='/api/planning/request'&&req.method==='GET')return json(res,200,{record:module.detail(id,url.searchParams.get('id'))});
   if(path==='/api/planning/commands'&&req.method==='POST')return json(res,200,module.command(id,await body(req,200000)));
   return json(res,404,{error:'Not found.'});
  }
  if(path.startsWith('/api/production/')){
   assertProductionAccess(session.user);const module=getProduction(),id=session.user.id;
   if(path==='/api/production/workspace'&&req.method==='GET')return json(res,200,{...module.read(id),csrf:session.csrf});
   const filters={kind:url.searchParams.get('kind')||'batches',query:url.searchParams.get('query')||'',status:url.searchParams.get('status')||'',key:url.searchParams.get('key')||'',before:url.searchParams.has('before')?Number(url.searchParams.get('before')):null,batchId:url.searchParams.has('batchId')?Number(url.searchParams.get('batchId')):null};
   if(path==='/api/production/records'&&req.method==='GET')return json(res,200,module.page(id,filters));
   if(path==='/api/production/batch'&&req.method==='GET')return json(res,200,module.detail(id,Number(url.searchParams.get('id'))));
   if(path==='/api/production/unit'&&req.method==='GET')return json(res,200,module.unit(id,url.searchParams.get('serial')));
   if(path==='/api/production/requirements'&&req.method==='GET')return json(res,200,module.requirements(id,url.searchParams.get('modelId'),url.searchParams.get('quantity')));
   if(path==='/api/production/pick-list'&&req.method==='GET')return json(res,200,module.pickList(id,Object.fromEntries(url.searchParams)));
   if(path==='/api/production/commands'&&req.method==='POST')return json(res,200,module.command(id,await body(req,2*1024*1024)));
   if(path==='/api/production/export'&&req.method==='POST'){
    const data=await body(req,10000);let headers,rows;
    if(data.kind==='pick-list'){const report=module.pickList(id,{date:data.date,mode:data.mode,modelId:data.modelId,segment:data.segment});headers=['Pick date','View','Segment','Item code','Supplier part code','Item name','Unit','Confirmed quantity','Pending quantities','Stock now','Shortage','Batch','Model','Batch item quantity','Shared shortage across segments','Reversed'];rows=report.rows.flatMap(r=>r.batches.map(b=>[report.date,report.mode,r.segment,r.code,r.supplierPartCode,r.name,r.unit,r.confirmedQty,r.pendingQuantities,r.stock,r.shortage,b.reference,b.modelId,b.qty,r.sharedShortage?'Yes':'No',b.reversed?'Yes':'No']));}
    else if(data.kind==='stock'){if(typeof (data.query??'')!=='string'||(data.query||'').length>120||!['','Component','Fabricated set'].includes(data.type||''))throw new RuleError('Invalid stock filter.');const search=(data.query||'').toLowerCase();headers=['Item code','Item name','Type','Unit','Current stock'];rows=module.read(id).items.filter(p=>(!search||[p.code,p.name].join(' ').toLowerCase().includes(search))&&(!data.type||p.kind===data.type)).map(p=>[p.code,p.name,p.kind,p.unit,p.qty]);}
    else {const page=module.page(id,data);if(page.kind==='batches'){headers=['Batch','Model','Quantity','Status','Production date','Planning month','Issue date','Completed date','BOM revision','Machines completed','Machines remaining'];rows=page.rows.map(r=>[r.reference,r.modelId,r.quantity,r.status,r.date,r.month,r.issueDate,r.completedDate,r.model.revision,r.completedQuantity||(r.status==='COMPLETED'?r.quantity:0),r.quantity-(r.completedQuantity||(r.status==='COMPLETED'?r.quantity:0))]);}
     else if(page.kind==='units'){headers=['Serial','Model','Batch ID','Configuration','Completed date','Status','Dispatch date'];rows=page.rows.map(r=>[r.serial,r.modelId,r.batchId,r.configuration,r.completedDate,r.status,r.dispatchDate]);}
     else{headers=['Item','Date','Type','Reference','Change','Before','After','By','Reason'];rows=page.rows.map(r=>[r.key,r.date,r.type,r.reference,r.delta,r.before,r.after,r.by.name,r.reason]);}}
    res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="Production_'+String(data.kind).replace(/[^a-z]/g,'')+'.csv"','Cache-Control':'no-store'});return res.end(productionCsv(headers,rows));
   }
   return json(res,404,{error:'Not found.'});
  }
  if(path.startsWith('/api/bom-management/')){
   assertBomAccess(session.user);const module=getBom();
   if(path==='/api/bom-management/workspace'&&req.method==='GET')return json(res,200,{...module.read(session.user.id),csrf:session.csrf});
   if(path==='/api/bom-management/reviews'&&req.method==='GET')return json(res,200,module.reviewPage(session.user.id,{modelId:url.searchParams.get('modelId')||'',status:url.searchParams.get('status')||'',before:url.searchParams.has('before')?Number(url.searchParams.get('before')):null}));
   if(path==='/api/bom-management/commands'&&req.method==='POST')return json(res,200,module.command(session.user.id,await body(req,2*1024*1024)));
   if(path.startsWith('/api/bom-management/export/')&&req.method==='POST'){const out=exportTechnical(module.read(session.user.id),await body(req,100000),path.split('/').at(-1));res.writeHead(200,{'Content-Type':out.type,'Content-Disposition':'attachment; filename="'+out.name+'"','Cache-Control':'no-store'});return res.end(out.bytes);}
   return json(res,404,{error:'Not found.'});
  }
  if(path.startsWith('/api/ro-costings')){
   const module=getRoCostings(),actorId=session.user.id;
   if(path==='/api/ro-costings'&&req.method==='GET')return json(res,200,module.list(actorId,{q:url.searchParams.get('q')||'',status:url.searchParams.get('status')||'',offset:Number(url.searchParams.get('offset')||0)}));
   if(path==='/api/ro-costings/record'&&req.method==='GET')return json(res,200,module.detail(actorId,url.searchParams.get('ro')));
   if(path==='/api/ro-costings/documents'&&req.method==='GET')return json(res,200,module.documents(actorId,url.searchParams.get('ro'),Number(url.searchParams.get('offset')||0)));
   if(path==='/api/ro-costings/source-library'&&req.method==='GET')return json(res,200,{sourceLibrary:module.sourceLibrary(actorId)});
   if(path==='/api/ro-costings/source-library'&&req.method==='POST')return json(res,200,module.saveSourceLibrary(actorId,await body(req,10000),req.headers['idempotency-key']));
   if(path==='/api/ro-costings/drive-documents'&&req.method==='POST')return json(res,201,module.linkDriveDocument(actorId,await body(req,10000),req.headers['idempotency-key']));
   if(path.startsWith('/api/ro-costings/files/')&&req.method==='GET'){const doc=module.download(actorId,decodeURIComponent(path.slice('/api/ro-costings/files/'.length)));const preview=url.searchParams.get('view')==='1'&&/\.pdf$/i.test(doc.name)&&Buffer.from(doc.body).subarray(0,5).toString()==='%PDF-';res.writeHead(200,{'Content-Type':preview?'application/pdf':'application/octet-stream','Content-Length':doc.body.length,'Content-Disposition':`${preview?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(doc.name)}`,'Cache-Control':'private, no-store'});return res.end(Buffer.from(doc.body));}
   if(path==='/api/ro-costings/import'&&req.method==='POST')return json(res,200,{saved:module.import(actorId,await body(req,5*1024*1024),req.headers['idempotency-key'])});
   if(path==='/api/ro-costings/files'&&req.method==='POST')return json(res,201,module.upload(actorId,await body(req,Math.ceil(MAX_UPLOAD_BYTES/3)*4+1024*1024),req.headers['idempotency-key']));
   if(path==='/api/ro-costings/document-classification'&&req.method==='POST')return json(res,200,module.classify(actorId,await body(req,10000),req.headers['idempotency-key']));
   return json(res,404,{error:'Not found.'});
  }
  if(path.startsWith('/api/implements/')){
   assertImplementsAccess(session.user);
   if(path==='/api/implements/workspace'&&req.method==='GET')return json(res,200,{state:getImplements().read(),csrf:session.csrf,user:session.user,canWrite:canWriteImplements(session.user)});
   if(req.method!=='POST')return json(res,404,{error:'Not found.'});
   const input=await body(req);if(JSON.stringify(input).length>20e6)throw new RuleError('Maximum request size is 20 MB.');
   if(path==='/api/implements/workspace')return json(res,200,{state:getImplements().save(input,session.user.id)});
   if(!['/api/implements/read-stock','/api/implements/export/pdf','/api/implements/export/xlsx','/api/implements/export/items','/api/implements/export/costing'].includes(path))return json(res,404,{error:'Not found.'});
   const out=await implementsExport(path,input,getImplements().read());res.setHeader('Content-Type',out.type);if(out.name)res.setHeader('Content-Disposition','attachment; filename="'+out.name.replace(/[^A-Za-z0-9._-]/g,'_')+'"');res.end(out.bytes);return;
  }
  if(path==='/api/integration/v1/snapshot'&&req.method==='GET'){if(session.user.role!=='ADMIN')throw new RuleError('Administrator access required for integration export.','FORBIDDEN');return json(res,200,integrationSnapshot(scopedState(store.read(),session.user)));}
  if(path==='/api/revision'&&req.method==='GET')return json(res,200,{revision:store.revision()});
  if(path==='/api/bootstrap'&&req.method==='GET'){const state=store.read();return json(res,200,{state:scopedState(state,session.user),user:session.user,csrf:session.csrf,editContext:store.editContext(state,session.user.id)});}
  if(path==='/api/users/reset-password'&&req.method==='POST'){
   if(session.user.role!=='ADMIN')throw new RuleError('Administrator access is required to reset passwords.','FORBIDDEN');
   const key='password:'+session.user.id,now=Date.now(),prior=attempts.get(key);const limit=prior&&now-prior.since<60000?prior:{count:0,since:now};
   if(limit.count>=10)return json(res,429,{error:'Too many password reset attempts. Wait a minute before trying again.'});limit.count++;attempts.set(key,limit);
   const out=store.resetUserPassword(await body(req,12000),session.user.id);
   if(out.result.reauthRequired)res.setHeader('Set-Cookie',`fh_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${secureCookie?'; Secure':''}`);
   return json(res,200,{state:scopedState(out.state,session.user),result:out.result,users:store.listAccounts(),editContext:store.editContext(out.state,session.user.id)});
  }
  if(path==='/api/users'&&['GET','POST'].includes(req.method)){
   if(session.user.role!=='ADMIN')throw new RuleError('Administrator access is required to manage users.','FORBIDDEN');
   if(req.method==='GET')return json(res,200,{users:store.listAccounts()});
   const p=await body(req);
   if(!p||!Number.isSafeInteger(p.expectedRevision))throw new RuleError('Expected workspace revision is required.');
   if(typeof p.email!=='string')throw new RuleError('A valid email is required.');
   const created=store.createLocalAccount({id:randomUUID(),name:p.name,role:p.role,scopes:p.scopes},p.email,p.password,{actorId:session.user.id,expectedRevision:p.expectedRevision,editContext:p.editContext});
   return json(res,201,{user:created,users:store.listAccounts(),state:scopedState(store.read(),session.user),editContext:store.editContext(store.read(),session.user.id)});
  }
  if(path==='/api/logout'&&req.method==='POST'){store.logout(cookie(req));res.setHeader('Set-Cookie',`fh_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${secureCookie?'; Secure':''}`);return json(res,200,{ok:true});}
  if(path.startsWith('/api/requests/')&&req.method==='GET'){const receipt=store.requestReceipt(session.user.id,decodeURIComponent(path.slice(14)));return json(res,200,{committed:!!receipt,result:receipt?JSON.parse(receipt.result):null});}
  if(path==='/api/commands'&&req.method==='POST'){const p=await body(req);if(typeof p.type!=='string'||!Number.isSafeInteger(p.expectedRevision))throw new RuleError('Command type and expected revision are required.');const out=store.transact({type:p.type,payload:p.payload},session.user.id,p.expectedRevision,req.headers['idempotency-key'],p.editContext),u=out.state.users.find(u=>u.id===session.user.id);return json(res,200,{state:scopedState(out.state,u),result:out.result,editContext:store.editContext(out.state,u.id)});}
  if(path==='/api/files'&&req.method==='POST'){const p=await body(req,Math.ceil(MAX_UPLOAD_BYTES/3)*4+1024*1024),state=store.read(),actor=state.users.find(u=>u.id===session.user.id);const uploadScope=p.scope||'LAE_IMPORT';if(!['LAE_IMPORT','LAE_DOMESTIC'].includes(uploadScope)||!scopeAllowed(actor,uploadScope)||uploadScope==='LAE_DOMESTIC'&&p.orderIds?.length)throw new RuleError('Upload division is not permitted.','FORBIDDEN');if(!canCreate(actor,uploadScope)&&!(uploadScope==='LAE_IMPORT'&&canProductApprove(actor)))throw new RuleError('No upload permission.','FORBIDDEN');if(!Array.isArray(p.orderIds)||p.orderIds.some(id=>!state.orders.some(o=>o.id===id&&!o.deletedAt&&scopeAllowed(actor,o.scope)&&(canEdit(actor,o)||canProductApprove(actor)))))throw new RuleError('An order file link is not permitted.','FORBIDDEN');if(typeof p.name!=='string'||p.name.length>200||/[\x00-\x1f\\/]/.test(p.name))throw new RuleError('Invalid filename.');if(!UPLOAD_EXTENSIONS.includes(ext(p.name).slice(1)))throw new RuleError('Unsupported file type.');if(typeof p.base64!=='string'||!/^[A-Za-z0-9+/]*={0,2}$/.test(p.base64))throw new RuleError('Invalid file encoding.');const bytes=Buffer.from(p.base64,'base64');if(!bytes.length||bytes.length>MAX_UPLOAD_BYTES)throw new RuleError('Evidence must be non-empty and at most 50 MB per file.');const meta={id:randomUUID(),name:p.name,mime:MIME[ext(p.name)],size:bytes.length,orderIds:[...new Set(p.orderIds)],scope:uploadScope,uploadedAt:new Date().toISOString(),uploadedBy:actor.name};const next=store.saveFile(meta,bytes,p.expectedRevision,actor,req.headers['idempotency-key'],p.editContext);return json(res,201,{id:meta.id,state:scopedState(next,actor),editContext:store.editContext(next,actor.id)});}
  if(path.startsWith('/api/files/')&&req.method==='GET'){const id=decodeURIComponent(path.slice(11)),state=store.read(),f=scopedState(state,session.user).files.find(f=>f.id===id);if(!f)throw new RuleError('File unavailable.','NOT_FOUND');const bytes=f.demoContent?Buffer.from(f.demoContent):store.fileBytes(id);if(!bytes)throw new RuleError('Evidence body unavailable.','NOT_FOUND');res.writeHead(200,{'Content-Type':f.mime,'Content-Length':bytes.length,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'no-store'});return res.end(Buffer.from(bytes));}
  return json(res,404,{error:'API route not found.'});
 }
 if(!['GET','HEAD'].includes(req.method))return json(res,405,{error:'Method not allowed.'});
 if(path==='/mode.js'){res.writeHead(200,{'Content-Type':'text/javascript','Cache-Control':'no-store'});return res.end("window.FH_MODE='server';");}
 if(path==='/production'||path.startsWith('/production/')){
  const session=store.session(cookie(req));if(!session){if(path==='/production'||path==='/production/'){res.writeHead(303,{Location:'/#/home'});return res.end();}return json(res,401,{error:'Sign in to view production.'});}
  assertProductionAccess(session.user);if(path==='/production'){res.writeHead(303,{Location:'/production/'});return res.end();}
  const asset=productionAssets.get(path);if(!asset)return json(res,404,{error:'Not found.'});res.writeHead(200,{'Content-Type':asset.type,'Cache-Control':'private, no-store'});return res.end(req.method==='HEAD'?undefined:readFileSync(asset.file));
 }
 if(path==='/bom'||path.startsWith('/bom/')||path==='/shared/bom-management.mjs'){
  const session=store.session(cookie(req));if(!session){if(path==='/bom'||path==='/bom/'){res.writeHead(303,{Location:'/#/home'});return res.end();}return json(res,401,{error:'Sign in to view BOM & Syntax.'});}
  assertBomAccess(session.user);if(path==='/bom'){res.writeHead(303,{Location:'/bom/'});return res.end();}
  const asset=bomAssets.get(path);if(!asset||!['GET','HEAD'].includes(req.method))return json(res,404,{error:'Not found.'});res.writeHead(200,{'Content-Type':asset.type,'Cache-Control':'private, no-store'});return res.end(req.method==='HEAD'?undefined:readFileSync(asset.file));
 }
 if(path==='/planning'||path.startsWith('/planning/')){
  const session=store.session(cookie(req));if(!session){if(path==='/planning'||path==='/planning/'){res.writeHead(303,{Location:'/#/home'});return res.end();}return json(res,401,{error:'Sign in to use monthly plan entry.'});}
  assertPlanningAccess(session.user);if(path==='/planning'){res.writeHead(303,{Location:'/planning/'});return res.end();}
  const asset=planningAssets.get(path);if(!asset||!['GET','HEAD'].includes(req.method))return json(res,404,{error:'Not found.'});res.writeHead(200,{'Content-Type':asset.type,'Cache-Control':'private, no-store'});return res.end(req.method==='HEAD'?undefined:readFileSync(asset.file));
 }
 if(path==='/implements'||path.startsWith('/implements/')||path.startsWith('/shared/implements/')){
  const session=store.session(cookie(req));if(!session){if(path==='/implements'||path==='/implements/'){res.writeHead(303,{Location:'/#/order-management/implements'});return res.end();}return json(res,401,{error:'Sign in to view Implements.'});}
  assertImplementsAccess(session.user);if(path==='/implements'){res.writeHead(303,{Location:'/implements/'});return res.end();}
  const asset=implementsAssets.get(path);if(!asset||!['GET','HEAD'].includes(req.method))return json(res,404,{error:'Not found.'});
  res.writeHead(200,{'Content-Type':asset.type,'Cache-Control':'private, no-store'});return res.end(req.method==='HEAD'?undefined:readFileSync(asset.file));
 }
 if(path.startsWith('/assets/domestic-bom/')){const s=store.session(cookie(req));if(!s)return json(res,401,{error:'Sign in to view item pictures.'});if(!scopeAllowed(s.user,'LAE_DOMESTIC'))throw new RuleError('LAE Domestic access is required.','FORBIDDEN');const name=path.slice('/assets/domestic-bom/'.length);if(!domesticImageAsset(name))return json(res,404,{error:'Picture unavailable.'});const bytes=readFileSync(join(ROOT,'web/assets/domestic-bom',name));res.writeHead(200,{'Content-Type':'image/png','Cache-Control':'private, no-store'});return res.end(req.method==='HEAD'?undefined:bytes);}
 const staticFiles={'/shared/ro-documents.mjs':'shared/ro-documents.mjs','/ro-costing.mjs':'web/ro-costing.mjs','/shared/ro-costing.mjs':'shared/ro-costing.mjs','/vendor/gsap-3.15.0.min.js':'web/vendor/gsap-3.15.0.min.js','/tasks.mjs':'web/tasks.mjs','/shared/task-reporting.mjs':'shared/task-reporting.mjs','/loading.mjs':'web/loading.mjs','/domestic-orders.mjs':'web/domestic-orders.mjs','/shared/domestic-orders.mjs':'shared/domestic-orders.mjs','/templates/Domestic_Price_List_Template.xlsx':'templates/Domestic_Price_List_Template.xlsx','/domestic-prices.mjs':'web/domestic-prices.mjs','/domestic-price-comparison.mjs':'web/domestic-price-comparison.mjs','/shared/domestic-prices.mjs':'shared/domestic-prices.mjs','/domestic.mjs':'web/domestic.mjs','/shared/domestic.mjs':'shared/domestic.mjs','/domestic.css':'web/domestic.css','/concurrency.mjs':'web/concurrency.mjs','/process-exemptions.mjs':'web/process-exemptions.mjs','/shared/process-exemptions.mjs':'shared/process-exemptions.mjs','/arrival-costing.mjs':'web/arrival-costing.mjs','/shared/arrival-costing.mjs':'shared/arrival-costing.mjs','/references.mjs':'web/references.mjs','/shared/order-progress.mjs':'shared/order-progress.mjs','/shared/references.mjs':'shared/references.mjs','/navigation.mjs':'web/navigation.mjs','/vms-outbox.mjs':'web/vms-outbox.mjs','/vms-pages.mjs':'web/vms-pages.mjs','/manifest.webmanifest':'web/manifest.webmanifest','/app-icon.svg':'web/app-icon.svg','/service-worker.js':'web/service-worker.js','/offline.html':'web/offline.html','/vms.mjs':'web/vms.mjs','/shared/vms.mjs':'shared/vms.mjs','/guide-poses.mjs':'web/guide-poses.mjs',"/theme.mjs":"web/theme.mjs","/support.mjs":"web/support.mjs","/experience.mjs":"web/experience.mjs","/theme.css":"web/theme.css","/support.css":"web/support.css","/assets/guide/farminghub-welcome.png":"web/assets/guide/farminghub-welcome.png","/assets/guide/farminghub-pointing.png":"web/assets/guide/farminghub-pointing.png","/assets/guide/farminghub-ready.png":"web/assets/guide/farminghub-ready.png",'/':'web/index.html','/index.html':'web/index.html','/styles.css':'web/styles.css','/app.mjs':'web/app.mjs','/jszip.min.js':'web/jszip.min.js','/shared/plm.mjs':'shared/plm.mjs','/shared/shipping.mjs':'shared/shipping.mjs','/shared/domain.mjs':'shared/domain.mjs','/shared/clean-seed.mjs':'shared/clean-seed.mjs','/shared/final-master-data.mjs':'shared/final-master-data.mjs','/templates/LAE_Item_Master_Upload_Template_v0.1.xlsx':'templates/LAE_Item_Master_Upload_Template_v0.1.xlsx','/assets/farming-hub-logo.png':'web/assets/farming-hub-logo.png'};const f=staticFiles[path];if(!f)return json(res,404,{error:'Not found.'});const bytes=readFileSync(join(ROOT,f));res.writeHead(200,{'Content-Type':MIME[ext(f)]||'application/octet-stream','Cache-Control':'no-store'});res.end(req.method==='HEAD'?undefined:bytes);
 }catch(e){if(res.headersSent){res.end();return;}const code=e.code==='FORBIDDEN'?403:e.code==='NOT_FOUND'?404:e.code==='CONFLICT'?409:e instanceof RuleError?400:500;json(res,code,{error:code===500?'Request could not be completed; no partial transaction was saved.':e.message});if(code===500){try{log({event:'request_error',requestId,route,code:/^(ERR_|SQLITE_)[A-Z0-9_]{1,50}$/.test(e.code||'')?e.code:'UNEXPECTED_ERROR'});}catch{}}}
 });}
export function emptyState(){const s=createCleanSeed();return {...s,demo:false,clean:true,revision:0,users:[{id:'admin',name:process.env.FH_ADMIN_NAME||'Purchase Administrator',role:'ADMIN',scopes:['LAE_IMPORT'],active:true}],seededEventCount:0};}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const dataDir=resolve(process.env.FH_DATA_DIR||join(ROOT,'data'));mkdirSync(dataDir,{recursive:true});const file=join(dataDir,'purchase-pilot.sqlite'),first=!existsSync(file);if(first&&(!process.env.FH_ADMIN_EMAIL||!process.env.FH_ADMIN_PASSWORD)){console.error('First run: set FH_ADMIN_EMAIL and FH_ADMIN_PASSWORD (12+ characters). This clean build does not seed sample business data.');process.exit(1);}if(first&&process.env.FH_ADMIN_PASSWORD.length<12){console.error('FH_ADMIN_PASSWORD needs at least 12 characters.');process.exit(1);}const store=new Store(file,emptyState());if(first)store.addAccount('admin',process.env.FH_ADMIN_EMAIL,process.env.FH_ADMIN_PASSWORD);const host=process.env.HOST||'127.0.0.1',port=Number(process.env.PORT||8000),server=makeServer(store,{origin:process.env.FH_ORIGIN||null,secureCookie:process.env.FH_SECURE_COOKIE==='true'});server.listen(port,host,()=>console.log(`Farming Hub Purchase Management ${APP_VERSION}\nClean local pilot: http://${host}:${port}\nStorage: ${file}\nNo sample suppliers, items, orders, payments, shipments or freight rates are preloaded.`));for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>server.close(()=>{store.close();process.exit(0);}));}
