import {createNavigation,moduleDestination} from '/navigation.mjs';
const app=document.querySelector('#app'),guard=document.querySelector('#guard');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v==null?'Not entered':Number(v).toLocaleString('en-IN',{maximumFractionDigits:3});
const label=s=>String(s||'').replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase());
const chip=s=>`<span class="chip status-chip ${['DRAFT','MATERIAL_ISSUED','PART_COMPLETED'].includes(s)?'warning':''}">${esc(label(s))}</span>`;
const icon=()=>'<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M4 4h16v16H4z M8 8h8 M8 12h8 M8 16h4"/></svg>';
const button=(name,action,attrs='',primary=false)=>`<button class="button ${primary?'primary':'ghost'}" type="button" data-action="${action}" ${attrs}>${name}</button>`;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Calcutta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const options=(rows,value)=>rows.map(([v,name])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(name)}</option>`).join('');
const field=(name,title,value='',type='text',attrs='')=>`<label class="field">${title}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
const table=(headers,rows,title)=>`<div class="table-wrap" tabindex="0" role="region" aria-label="${esc(title)}"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">No records yet. Use the action above to get started.</td></tr>`}</tbody></table></div>`;
const sections=[['dashboard','Dashboard','grid'],['batches','Production batches','box'],['stock','Component stock','box'],['units','Finished stock & serials','orders'],['movements','Stock movements','history']];
let state,csrf='',view='dashboard',query=new URLSearchParams(),page=null,detail=null,requirements=null,busy=false,dirty=false,previousHash='',pendingLeave=null,lastRequest=null;
const api=async(path,options={})=>{const r=await fetch('/api/production/'+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...options.headers}});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed.');return data;};
const item=key=>state.items.find(p=>p.key===key);
const model=id=>state.models.find(m=>m.id===id);
function toast(message){document.querySelector('#toast-root').innerHTML=`<div class="toast">${esc(message)}</div>`;setTimeout(()=>document.querySelector('#toast-root').replaceChildren(),5000);}
const stat=(name,value,sub,url)=>`<a class="stat-card" href="${url}"><span>${name} →</span><strong>${fmt(value)}</strong><small>${sub}</small></a>`;
const head=(title,description,actions='')=>`<div class="page-head"><div><div class="eyebrow">Factory workspace</div><h1>${title}</h1><p>${description}</p></div><div class="actions">${actions}</div></div>`;
const newBatch=()=>state.canWrite?'<a class="button primary" href="#/entry">New production batch</a>':'';
function dashboard(){return head('Production & Stock','Issue materials, record completed machines and track each serial number.',newBatch())+`<div class="stats">${stat('Draft batches',state.counts.DRAFT||0,'Review before posting','#/batches?status=DRAFT')}${stat('In production',(state.counts.MATERIAL_ISSUED||0)+(state.counts.PART_COMPLETED||0),'Issued or partly completed','#/batches?status=IN_PRODUCTION')}${stat('Finished machines',state.unitCounts.AVAILABLE||0,'Available for dispatch','#/units?status=AVAILABLE')}${stat('Dispatched machines',state.unitCounts.DISPATCHED||0,'Open serial history','#/units?status=DISPATCHED')}</div><section class="panel entry-form"><h2>Production workflow</h2><p>Create a draft → verify BOM consumption and stock → issue materials → complete with serial numbers → dispatch finished machines.</p><p>Complete a draft in parts or as a whole. Direct partial completion deducts only its material share. If materials were issued for the whole batch first, later partial completions do not deduct again.</p><div class="actions"><a class="button ghost" href="#/stock">Receive / verify component stock</a>${state.user.role==='ADMIN'||state.user.scopes.includes('BOM_MANAGEMENT')?'<a class="button ghost" href="/bom/">Check BOM & syntax</a>':''}</div></section>`;}
function filters(kind){return `<section class="panel stock-filter"><label>Find ${kind==='units'?'serial or model':'batch / model'}<input data-filter="query" value="${esc(query.get('query')||'')}" placeholder="${kind==='units'?'Serial number or S2.V58':'S2.V58 or FH-PROD…'}"></label><label>Status<select data-filter="status">${options([['','All statuses'],...(kind==='units'?['AVAILABLE','DISPATCHED','VOID']:['IN_PRODUCTION','DRAFT','MATERIAL_ISSUED','PART_COMPLETED','COMPLETED','CANCELLED','REVERSED']).map(s=>[s,label(s)])],query.get('status')||'')}</select></label>${button('Apply filters','filter')}${button('Reset','reset')}</section>`;}
function historyList(kind){const rows=page?.rows||[];return head(kind==='units'?'Finished stock & serials':kind==='movements'?'Stock movements':'Production batches',kind==='movements'?'Every receipt, issue, return and stock count correction remains in the ledger.':'Open a record to review its production and stock history.',kind==='batches'?newBatch():button('Download latest 100','download',`data-kind="${kind}"`))+(kind==='movements'?`<section class="panel stock-filter"><label>Item<select id="movement-item">${options([['','All stock items'],...state.items.map(p=>[p.key,(p.code||p.key)+' · '+p.name])],query.get('key')||'')}</select></label>${button('Apply filters','filter')}</section>`:filters(kind))+`<div class="result-count"><span>${page?.total||0} records · showing ${rows.length}</span>${kind==='batches'?button('Download latest 100','download','data-kind="batches"'):''}</div><section class="panel">`+(kind==='batches'?table(['Batch','Model','Machines','Date / plan month','Status','BOM revision'],rows.map(b=>`<tr><td><a class="unit-link" href="#/batch?id=${b.id}">${esc(b.reference)}</a></td><td>${esc(b.modelId)}</td><td>${fmt(b.quantity)} planned<small>${fmt(b.completedQuantity||(b.status==='COMPLETED'?b.quantity:0))} completed</small></td><td>${esc(b.date)}<br><small>${esc(b.month)}</small></td><td>${chip(b.status)}</td><td>${b.model.revision}</td></tr>`),'Production batches'):kind==='units'?table(['Serial','Model','Completed','Status','Batch','Action'],rows.map(u=>`<tr><td><a class="unit-link" href="#/serial?serial=${encodeURIComponent(u.serial)}">${esc(u.serial)}</a></td><td>${esc(u.modelId)}</td><td>${esc(u.completedDate)}</td><td>${chip(u.status)}</td><td><a href="#/batch?id=${u.batchId}">${u.batchId}</a></td><td>${state.canWrite&&u.status==='AVAILABLE'?`<a class="button ghost" href="#/dispatch?serial=${encodeURIComponent(u.serial)}">Dispatch</a>`:state.canManage&&u.status==='DISPATCHED'?`<a class="button ghost" href="#/dispatch?serial=${encodeURIComponent(u.serial)}&return=yes">Record return</a>`:''}</td></tr>`),'Finished machines'):table(['Date','Item','Reference','Movement','Before','After','Recorded by'],rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(item(r.key)?.code||r.key)}<br><small>${esc(item(r.key)?.name||r.name||'')}</small></td><td>${r.batchId?`<a href="#/batch?id=${r.batchId}">${esc(r.reference)}</a>`:esc(r.reference)}<br><small>${esc(label(r.type))}</small></td><td>${r.delta>0?'+':''}${fmt(r.delta)}</td><td>${fmt(r.before)}</td><td>${fmt(r.after)}</td><td>${esc(r.by.name)}<br><small>${esc(r.reason)}</small></td></tr>`),'Stock movements'))+`</section><div class="actions">${page?.next?button('Load more','more',`data-before="${page.next}"`):''}</div>`;}
function stock(){const q=(query.get('query')||'').toLowerCase(),kind=query.get('type')||'',rows=state.items.filter(p=>(!q||[p.code,p.name].join(' ').toLowerCase().includes(q))&&(!kind||p.kind===kind));return head('Component stock','Shared quantities feed purchasing MRP. Fabrication is stocked as one model subassembly set per machine.',`${state.canWrite?'<a class="button primary" href="#/stock-entry">Receive stock</a>':''}${button('Download stock','download','data-kind="stock"')}`)+`<section class="panel stock-filter"><label>Find item<input data-filter="query" value="${esc(query.get('query')||'')}" placeholder="Item code or name"></label><label>Type<select data-filter="type">${options([['','All items'],['Component','Components'],['Fabricated set','Fabricated sets']],kind)}</select></label>${button('Apply filters','filter')}${button('Reset','reset')}</section><div class="result-count">${rows.length} items</div><section class="panel">${table(['Item code','Item','Type','Unit','Current stock','Action'],rows.map(p=>`<tr><td>${esc(p.code||'Code pending')}</td><td><a href="#/movements?key=${encodeURIComponent(p.key)}">${esc(p.name)}</a></td><td>${esc(p.kind)}</td><td>${p.unit}</td><td>${fmt(p.qty)}</td><td>${state.canWrite?`<a class="button ghost" href="#/stock-entry?key=${encodeURIComponent(p.key)}">Receive</a>`:''}${state.canManage?` <a class="button ghost" href="#/stock-entry?key=${encodeURIComponent(p.key)}&adjust=yes">Count adjustment</a>`:''}</td></tr>`),'Component balances')}</section>`;}
const reasonField=()=>`<label class="field full">Reason / production note<input name="reason" required maxlength="1200"></label>`;
function materialsTable(rows,editable=false,overrides=[]){const map=new Map(overrides.map(r=>[r.key,r.qty]));return table(['Item','Unit','BOM PPM','BOM × machines','Consumption','Stock now'],rows.map(r=>{const value=map.has(r.key)?map.get(r.key):r.qty??r.required,available=item(r.key)?.qty;return `<tr><td>${esc(r.code||'Code pending')}<br>${esc(r.name)}</td><td>${r.unit}</td><td>${r.ppm==null?'<span class="stock-low">PPM pending</span>':fmt(r.ppm)}</td><td>${r.required==null?'Confirm for this batch':fmt(r.required)}</td><td>${editable?`<input aria-label="Consumption ${esc(r.name)}" data-material-key="${esc(r.key)}" type="number" min="0" max="100000000" step="${r.unit==='pcs'?'1':'.001'}" value="${value??''}">`:fmt(value)}</td><td data-stock-key="${esc(r.key)}" class="${value>available?'stock-low':''}">${fmt(available)}</td></tr>`;}),'Batch material consumption');}
function entry(){const b=detail?.batch,selected=b?.modelId||query.get('model')||'',models=state.models.filter(m=>m.bomAvailable);return head(b?'Edit draft '+esc(b.reference):'New production batch','Drafts do not change stock. Preview the BOM and confirm any missing consumption quantities.')+`<form id="entry-form" data-form="batch" class="panel entry-form"><div class="form-grid"><label class="field full">Model<select name="modelId" required>${options([['','Select model'],...models.map(m=>[m.id,m.id+' · '+m.series+' · '+m.size])],selected)}</select></label>${field('quantity','Machines',b?.quantity||1,'number','required min="1" max="1000" step="1"')}${field('date','Production date',b?.date||today(),'date',`required max="${today()}"`)}${field('month','Planning month',b?.month||state.activeMonth||today().slice(0,7),'month','required')}<label class="field full">Serial numbers — optional, one per machine<textarea name="serials" placeholder="Leave blank for automatic numbering">${esc(b?.serials.join('\n')||'')}</textarea><small>Serial numbers are assigned on completion. They remain unique, including reversed batches.</small></label>${reasonField()}</div><div class="actions">${button('Preview material requirements','preview','','true')}<button class="button primary" type="submit">Save draft</button><a class="button ghost" href="#/batches">Cancel</a></div><p class="form-error" role="alert" tabindex="-1"></p><div class="actions">${button("Refresh stock balances (keep entries)","refresh")}</div><p id="planning-summary" class="batch-note">Production consumption is linked to the selected planning month.</p><div id="material-preview">${b?materialsTable(b.materials,true,b.overrides):''}</div></form>`;}
function batchPage(){const b=detail.batch;return head(esc(b.reference)+' · '+esc(b.modelId),`${fmt(b.quantity)} planned · ${fmt(b.completedQuantity||(b.status==='COMPLETED'?b.quantity:0))} completed · ${esc(b.date)} · planning ${esc(b.month)} · BOM revision ${b.model.revision}`,`<a class="button ghost" href="#/batches">All batches</a>`)+`<section class="panel entry-form"><div class="flex justify-between">${chip(b.status)}${state.user.role==='ADMIN'||state.user.scopes.includes('BOM_MANAGEMENT')?`<a href="/bom/#/model/${encodeURIComponent(b.modelId)}/bom">View current model BOM</a>`:''}</div><p>${esc(b.model.configuration)}</p><p>${esc(b.reason)}</p><div class="batch-note">${b.status==='DRAFT'?'Stock has not been deducted. Confirm consumption, then issue materials or complete the batch directly.':b.status==='PART_COMPLETED'?'Production is partly completed. Record the remaining machines; finished serials are already available.':b.status==='MATERIAL_ISSUED'?'Materials have been deducted. Complete production to add finished machines; no second deduction occurs.':b.status==='COMPLETED'?'Finished serials are in stock. Open a serial to dispatch it or view its history.':'This batch is closed; its history is retained.'}</div>${materialsTable(b.issued||b.materials,false,b.overrides)}<div class="actions">${state.canWrite&&b.status==='DRAFT'?`<a class="button ghost" href="#/entry?id=${b.id}">Edit draft & quantities</a><a class="button ghost" href="#/stage?id=${b.id}&type=ISSUE_MATERIAL">Issue materials — reduce stock</a><a class="button primary" href="#/stage?id=${b.id}&type=COMPLETE_BATCH">Complete production</a><a class="button ghost" href="#/stage?id=${b.id}&type=CANCEL_BATCH">Cancel draft</a>`:''}${state.canWrite&&['MATERIAL_ISSUED','PART_COMPLETED'].includes(b.status)?`<a class="button primary" href="#/stage?id=${b.id}&type=COMPLETE_BATCH">Complete production</a>`:''}${state.canManage&&['MATERIAL_ISSUED','PART_COMPLETED','COMPLETED'].includes(b.status)?`<a class="button ghost" href="#/stage?id=${b.id}&type=REVERSE_BATCH">Reverse batch & return materials</a>`:''}</div></section>${detail.units.length?`<section class="panel"><h2 class="panel-title">Finished serials</h2>${table(['Serial','Status','Completed'],detail.units.map(u=>`<tr><td><a class="unit-link" href="#/serial?serial=${encodeURIComponent(u.serial)}">${esc(u.serial)}</a></td><td>${chip(u.status)}</td><td>${u.completedDate}</td></tr>`),'Batch serials')}</section>`:''}`;}
function batchHistory(){return '<section class="panel"><h2 class="panel-title">Stage history · latest 100</h2>'+table(['Recorded at','Stage','By','Reason'],(detail.history||[]).map(h=>'<tr><td>'+esc(h.at)+'</td><td>'+esc(label(h.type))+'</td><td>'+esc(h.by.name)+'</td><td>'+esc(h.reason)+'</td></tr>'),'Batch stage history')+'</section>';}
function stage(){const b=detail.batch,type=query.get('type'),editable=b.status==='DRAFT'&&['ISSUE_MATERIAL','COMPLETE_BATCH'].includes(type);return head(label(type)+' · '+esc(b.reference),type==='COMPLETE_BATCH'?'One unique serial per finished machine. Enter only the machines completed now and their serials. Materials are deducted for this quantity only, unless the full batch was already issued.':type==='REVERSE_BATCH'?'A manager reversal returns the exact issued quantities and voids the finished serials.':'Review quantities and stock before posting.')+`<form data-form="stage" class="panel entry-form"><div class="form-grid">${field('date','Posting date',today(),'date',`required min="${b.issueDate||b.date}" max="${today()}"`)}${reasonField()}${type==='COMPLETE_BATCH'?`${field('completeQuantity','Machines completed now',b.quantity-(b.completedQuantity||0),'number',`required min="1" max="${b.quantity-(b.completedQuantity||0)}" step="1"`)}<label class="field full">Serial numbers — blank for automatic numbering<textarea name="serials">${esc((b.serials||[]).slice(b.completedQuantity||0).join('\n'))}</textarea></label>`:''}</div>${type==='COMPLETE_BATCH'?'<p class="batch-note">The table shows the full batch material basis. A direct partial completion deducts only the proportional share for machines completed now. An already-issued batch needs no further deduction.</p>':''}${['ISSUE_MATERIAL','COMPLETE_BATCH'].includes(type)?materialsTable(b.issued||b.materials,editable,b.overrides):''}<div class="actions"><button class="button primary" type="submit">${type==='COMPLETE_BATCH'?'Complete & add finished stock':type==='ISSUE_MATERIAL'?'Post material issue':type==='REVERSE_BATCH'?'Post reversal':'Cancel draft'}</button><a class="button ghost" href="#/batch?id=${b.id}">Keep batch unchanged</a></div><p class="form-error" role="alert"></p></form>`;}
function stockEntry(){const adjust=query.get('adjust')==='yes',selected=query.get('key')||state.items[0]?.key,p=item(selected);return head(adjust?'Stock count adjustment':'Receive component stock',adjust?'Manager action: replace the current balance with a verified physical count. The difference remains in the ledger.':'Enter a physical receipt. A purchase order alone does not add stock.')+`<form data-form="stock" class="panel entry-form"><div class="form-grid"><label class="field full">Item<select name="key" required>${options(state.items.map(i=>[i.key,(i.code||i.key)+' · '+i.name+' ('+i.unit+')']),selected)}</select></label>${field('qty',adjust?'Physical count':'Quantity received',adjust?p?.qty??'':'','number','required min="0" max="100000000" step=".001"')}${field('date','Receipt / count date',today(),'date',`required max="${today()}"`)}${field('reference','Delivery / count reference','','text','required maxlength="120"')}${reasonField()}</div><p id="stock-entry-hint">Current stock: ${fmt(p?.qty)} ${p?.unit||''}. Whole pieces; kg and litres allow three decimals.</p><div class="actions"><button class="button primary" type="submit">${adjust?'Post count adjustment':'Post stock receipt'}</button><a class="button ghost" href="#/stock">Cancel</a></div><p class="form-error" role="alert"></p></form>`;}
function serialPage(){const u=page?.rows.find(r=>r.serial===query.get('serial'));if(!u)return head('Serial not found','Search the finished stock register.')+'<a class="button primary" href="#/units">Finished stock</a>';const returning=query.get('return')==='yes';if(view==='dispatch')return head((returning?'Return ':'Dispatch ')+esc(u.serial),esc(u.modelId)+' · '+label(u.status))+`<form data-form="dispatch" class="panel entry-form"><div class="form-grid">${field('date',returning?'Return date':'Dispatch date',today(),'date',`required min="${u.completedDate}" max="${today()}"`)}${field('reference',returning?'Return reference':'Delivery / dispatch reference','','text','required maxlength="120"')}${reasonField()}</div><div class="actions"><button class="button primary" type="submit">${returning?'Return to finished stock':'Dispatch this serial'}</button><a class="button ghost" href="#/serial?serial=${encodeURIComponent(u.serial)}">Cancel</a></div><p class="form-error" role="alert"></p></form>`;
 return head(esc(u.serial),esc(u.modelId)+' · '+esc(u.configuration))+`<section class="panel entry-form">${chip(u.status)}<p>Completed ${esc(u.completedDate)} · BOM revision ${u.modelRevision}</p><div class="actions"><a class="button ghost" href="#/batch?id=${u.batchId}">Production batch & material issue</a>${state.canWrite&&u.status==='AVAILABLE'?`<a class="button primary" href="#/dispatch?serial=${encodeURIComponent(u.serial)}">Dispatch</a>`:''}${state.canManage&&u.status==='DISPATCHED'?`<a class="button ghost" href="#/dispatch?serial=${encodeURIComponent(u.serial)}&return=yes">Record return</a>`:''}</div></section><section class="panel">${table(['Date','Movement','Reference','Recorded by','Reason'],u.history.map(h=>`<tr><td>${h.date}</td><td>${esc(label(h.type))}</td><td>${esc(h.reference)}</td><td>${esc(h.by.name)}</td><td>${esc(h.reason)}</td></tr>`),'Serial movements')}</section>`;}
function setDrawer(open){const side=document.querySelector('.module-sidebar'),workspace=document.querySelector('.workspace'),toggle=document.querySelector('[data-action=mobile]');side.classList.toggle('open',open);side.inert=!open&&matchMedia('(max-width:760px)').matches;workspace.inert=open;toggle?.setAttribute('aria-expanded',String(open));if(open)side.querySelector('.nav-link')?.focus();else toggle?.focus();}
function render(){const nav=createNavigation({icon,esc,logo:'/assets/farming-hub-logo.png',context:()=>({user:state.user,ui:{view:'production-stock',orderId:sections.some(([s])=>s===view)?view:['stock-entry'].includes(view)?'stock':['serial','dispatch'].includes(view)?'units':'batches'}}),productionSections:sections});app.className='bom-app production-app';app.innerHTML=`<div class="layout">${nav.sidebar().replace('</aside>','<button class="icon-button drawer-close" type="button" data-action="close-navigation" aria-label="Close navigation">×</button></aside>')}<button class="nav-scrim" type="button" data-action="close-navigation" aria-label="Close navigation backdrop"></button><div class="workspace"><header class="topbar"><div class="flex"><button type="button" class="icon-button mobile-toggle" data-action="mobile" aria-label="Open navigation" aria-expanded="false">☰</button>${nav.breadcrumb(sections.find(([id])=>id===view)?.[1]||'Production & Stock')}</div><div class="top-tools"><span class="technical-tag">PRODUCTION</span><span>${esc(state.user.name)}</span>${button('Sign out','logout')}</div></header><main class="content" id="main-content">${!state.canWrite?'<div class="batch-note">Read-only production access.</div>':''}${view==='dashboard'?dashboard():view==='stock'?stock():['batches','units','movements'].includes(view)?historyList(view):view==='entry'?entry():view==='batch'?batchPage()+batchHistory():view==='stage'?stage():view==='stock-entry'?stockEntry():serialPage()}</main></div></div>`;if(matchMedia('(max-width:760px)').matches)document.querySelector('.module-sidebar').inert=true;}
async function load(){const [path='',search='']=location.hash.replace(/^#\/?/,'').split('?');view=path||'dashboard';query=new URLSearchParams(search);if(!['dashboard','batches','stock','units','movements','entry','batch','stage','stock-entry','serial','dispatch'].includes(view))view='dashboard';detail=null;requirements=null;page=null;
 if(['batches','units','movements'].includes(view))page=await api('records?'+new URLSearchParams({kind:view,...Object.fromEntries(query)}));
 if(['batch','stage'].includes(view)||view==='entry'&&query.has('id'))detail=await api('batch?id='+query.get('id'));
 if(['serial','dispatch'].includes(view))page=await api('records?'+new URLSearchParams({kind:'units',query:query.get('serial')||''}));render();previousHash=location.hash;window.scrollTo(0,0);}
const quantities=root=>[...root.querySelectorAll('[data-material-key]')].filter(el=>el.value!=='').map(el=>({key:el.dataset.materialKey,qty:el.value}));
async function command(payload){const next={...payload,expectedRevision:state.revision,expectedProductionRevision:state.productionRevision},identity=JSON.stringify(next);if(lastRequest?.identity!==identity)lastRequest={identity,payload:{...next,requestId:crypto.randomUUID()}};const response=await api('commands',{method:'POST',body:JSON.stringify(lastRequest.payload)});lastRequest=null;state=response;dirty=false;}
function protect(action){if(!dirty)return action();pendingLeave=action;guard.showModal();guard.querySelector('[data-action=keep]').focus();}
document.addEventListener('input',event=>{if(event.target.closest('form'))dirty=true;});
document.addEventListener('change',event=>{if(['modelId','month'].includes(event.target.name)&&document.querySelector('#planning-summary')){const form=event.target.form,id=form.elements.modelId.value,month=form.elements.month.value,planned=state.plans[month]?.[id]||0,issued=state.consumed[month]?.[id]||0;document.querySelector('#planning-summary').textContent='Plan: '+fmt(planned)+' machines · materials issued: '+fmt(issued)+' · remaining plan: '+fmt(Math.max(0,planned-issued))+' for '+month;} if(event.target.closest('form'))dirty=true;if(event.target.name==='key'){const p=item(event.target.value);document.querySelector('#stock-entry-hint').textContent='Current stock: '+fmt(p.qty)+' '+p.unit;if(query.get('adjust')==='yes')document.querySelector('[name=qty]').value=p.qty??'';}if(event.target.id==='module-select')protect(()=>{location.href=event.target.value==='production-stock'?'#/dashboard':moduleDestination(event.target.value);});});
document.addEventListener('click',async event=>{const anchor=event.target.closest('a');if(anchor&&dirty&&!anchor.getAttribute('href')?.startsWith('#')){event.preventDefault();protect(()=>{location.href=anchor.href;});return;}const el=event.target.closest('[data-action]');if(!el||busy)return;const action=el.dataset.action;try{
 if(action==='keep'){guard.close();pendingLeave=null;return;}if(action==='discard'){dirty=false;guard.close();const leave=pendingLeave;pendingLeave=null;leave?.();return;}
 if(action==='nav'){const to=el.dataset.to;protect(()=>{location.href=to.startsWith('production-stock/')?'#/'+to.slice(17):moduleDestination(to);});return;}
 if(action==='mobile'){setDrawer(true);return;}if(action==='close-navigation'){setDrawer(false);return;}
 if(action==='refresh'){state=await api('workspace');csrf=state.csrf;for(const cell of document.querySelectorAll('[data-stock-key]'))cell.textContent=fmt(item(cell.dataset.stockKey)?.qty);toast('Current stock loaded. Your entries are retained.');return;}
 if(action==='reset'){location.hash='#/'+view;return;}if(action==='filter'){const values={};for(const input of document.querySelectorAll('[data-filter]'))if(input.value)values[input.dataset.filter]=input.value;const selected=document.querySelector('#movement-item')?.value;if(selected)values.key=selected;location.hash='#/'+view+'?'+new URLSearchParams(values);return;}
 if(action==='preview'){const form=document.querySelector('#entry-form'),data=new FormData(form);requirements=await api('requirements?'+new URLSearchParams({modelId:data.get('modelId'),quantity:data.get('quantity')}));document.querySelector('#material-preview').innerHTML='<h2>Material requirements</h2><p>Missing PPM must be confirmed for this batch before stock is posted. Changes here do not change the master BOM.</p>'+materialsTable(requirements.materials,true);return;}
 if(action==='more'){const next=await api('records?'+new URLSearchParams({kind:view,...Object.fromEntries(query),before:el.dataset.before}));page={...next,rows:[...page.rows,...next.rows]};render();return;}
 if(action==='download'){const kind=el.dataset.kind,response=await fetch('/api/production/export',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({kind,...Object.fromEntries(query)})});if(!response.ok)throw Error((await response.json()).error);const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download='Production_'+kind+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);return;}
 if(action==='logout')protect(async()=>{const r=await fetch('/api/logout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:'{}'});if(!r.ok)throw Error('Sign-out failed.');dirty=false;location.href='/';});
 }catch(error){const box=document.querySelector('.form-error');if(box)box.textContent=error.message;else toast(error.message);}});
document.addEventListener('submit',async event=>{const form=event.target;if(!form.dataset.form)return;event.preventDefault();if(busy)return;busy=true;const submit=form.querySelector('[type=submit]');submit.disabled=true;form.querySelector('.form-error').textContent='';try{const data=Object.fromEntries(new FormData(form)),type=form.dataset.form;let destination='#/'+view;
  if(type==='batch'){await command({type:detail?'UPDATE_BATCH':'CREATE_BATCH',...(detail?{batchId:detail.batch.id}:{}),...data,materials:quantities(form)});destination='#/batches';}
  if(type==='stage'){await command({type:query.get('type'),batchId:detail.batch.id,...data,...(detail.batch.status==='DRAFT'&&['ISSUE_MATERIAL','COMPLETE_BATCH'].includes(query.get('type'))?{materials:quantities(form)}:{})});destination='#/batch?id='+detail.batch.id;}
  if(type==='stock'){await command({type:query.get('adjust')==='yes'?'ADJUST_STOCK':'RECEIVE_STOCK',...data});destination='#/stock';}
  if(type==='dispatch'){await command({type:query.get('return')==='yes'?'RETURN_UNIT':'DISPATCH_UNIT',serial:query.get('serial'),...data});destination='#/serial?serial='+encodeURIComponent(query.get('serial'));}
  toast('Saved. Stock and history are up to date.');if(location.hash===destination)await load();else location.hash=destination;
 }catch(error){form.querySelector('.form-error').textContent=error.message;form.querySelector('.form-error').focus();}finally{busy=false;submit.disabled=false;}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
window.addEventListener('hashchange',()=>{if(dirty){const target=location.hash;history.replaceState(null,'',previousHash);protect(()=>{location.hash=target;});return;}load().catch(error=>toast(error.message));});
guard.addEventListener('cancel',()=>{pendingLeave=null;});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!guard.open){setDrawer(false);}});
try{state=await api('workspace');csrf=state.csrf;await load();}catch(error){app.className='bom-app';app.innerHTML=`<div class="shell-error"><h1>Production & Stock</h1><p>${esc(error.message)}</p><a class="button primary" href="/#/home">Return to Farming Hub</a></div>`;}

matchMedia('(max-width:760px)').addEventListener('change',()=>{const side=document.querySelector('.module-sidebar');if(side)side.inert=matchMedia('(max-width:760px)').matches&&!side.classList.contains('open');});
 document.addEventListener('keydown',event=>{const side=document.querySelector('.module-sidebar');if(event.key!=='Tab'||!side?.classList.contains('open'))return;const targets=[...side.querySelectorAll('button,a,select')].filter(el=>!el.disabled&&el.getClientRects().length),first=targets[0],last=targets.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
