export function pickingView(report,{esc,fmt,head,table,button,options,models,items,canWrite,query,today}){
 const pending=report.mode==='pending',segments=[...new Set([...items.map(p=>p.category||'Other components'),...report.segments])].sort();
 const actions=button('Refresh pick list','refresh-pick')+button('Print pick list','print-pick')+button('Download Excel CSV','download','data-kind="pick-list"');
 const filters=`<section class="panel stock-filter pick-controls"><label>Pick date<input type="date" data-filter="date" value="${esc(report.date)}" required></label><label>View<select data-filter="mode">${options([['pending','To issue · due batches'],['issued','Issued on this date']],report.mode)}</select></label><label>Model<select data-filter="modelId">${options([['','All models'],...models.filter(m=>m.bomAvailable).map(m=>[m.id,m.id+' · '+m.series])],report.modelId)}</select></label><label>Segment<select data-filter="segment">${options([['','All segments'],...segments.map(s=>[s,s])],report.segment)}</select></label>${button('Apply filters','filter')}${button('Reset','reset')}</section>`;
 const cards=`<div class="pick-summary" role="status"><strong>${report.batchCount} batches</strong><span>${report.itemCount} items</span><span>${report.segments.length} segments</span><span>${report.shortageItems} shortage items</span><span>${report.pendingQuantities} quantities to confirm</span></div>`;
 const queue=`<section class="panel pick-queue"><h2 class="panel-title">${pending?'Material issue queue':'Issued batch references'}</h2>${table(['Batch / model','Machines','Status','Segments','Next step'],report.batches.map(b=>`<tr><td><a class="unit-link" href="#/batch?id=${b.id}">${esc(b.reference)}</a><small>${esc(b.modelId)} · planned ${esc(b.date)}</small></td><td>${fmt(b.quantity)}</td><td>${esc(b.status.replaceAll('_',' ').toLowerCase())}${b.stale?'<small class="stock-low">BOM changed · review draft</small>':''}${b.pendingQuantities?'<small class="stock-low">Consumption pending</small>':''}${b.shortages?'<small class="stock-low">Stock shortage</small>':''}</td><td>${b.segments.map(s=>`<span class="chip">${esc(s)}</span>`).join(' ')}</td><td>${pending&&canWrite?b.stale?`<a class="button ghost" href="#/entry?id=${b.id}">Review draft</a>`:b.segments.map(s=>`<a class="button ghost" href="#/stage?id=${b.id}&type=ISSUE_SEGMENT&segment=${encodeURIComponent(s)}">Issue ${esc(s)}</a>`).join(' '):`<a href="#/batch?id=${b.id}">View history</a>`}</td></tr>`),'Material issue queue')}</section>`;
 const groups=report.segments.map(segment=>{const rows=report.rows.filter(r=>r.segment===segment);return `<section class="panel pick-segment"><h2 class="panel-title">${esc(segment)} <small>${rows.length} items</small></h2>${table(['Item / supplier part code','Unit',pending?'To pick':'Issued quantity','Stock now',pending?'Shortage':'Status','Batch allocation'],rows.map(r=>`<tr><td><div class="pick-item">${r.image?`<img src="${esc(r.image)}" alt="${esc(r.name)}" loading="lazy">`:''}<div><strong>${esc(r.code||'Code pending')}</strong><br>${esc(r.name)}${r.supplierPartCode?`<small>Supplier code: ${esc(r.supplierPartCode)}</small>`:''}</div></div></td><td>${esc(r.unit)}</td><td>${fmt(r.confirmedQty)}${r.pendingQuantities?`<small class="stock-low">+ ${r.pendingQuantities} quantities pending</small>`:''}</td><td>${fmt(r.stock)}</td><td>${pending?r.shortage?`<span class="stock-low">${fmt(r.shortage)} ${esc(r.unit)} ${r.sharedShortage?'shared shortage':'short'}</span>`:'Available for known quantity':r.batches.some(b=>b.reversed)?'Includes reversed issue':'Posted'}</td><td>${r.batches.map(b=>`<div><a href="#/batch?id=${b.id}">${esc(b.reference)}</a> · ${esc(b.modelId)}<small>${b.qty==null?'Quantity pending':fmt(b.qty)+' '+esc(r.unit)}${b.stale?' · draft needs review':''}${b.reversed?' · reversed':''}</small></div>`).join('')}</td></tr>`),segment+' pick list')}</section>`;}).join('');
 return head('Stores · daily pick list','Pick by segment, review each batch and post its material issue. '+esc(report.date),actions)+filters+cards+`<p class="batch-note">${pending?'Includes unissued material for drafts due on or before the pick date. Quantities combine all matching batches; stock is shared. Pending quantities must be confirmed before issue.':'Shows actual issues posted on the selected date. Reversed issues remain identified in history.'} Picking or printing does not reduce stock. Fabrication is one stocked subassembly set per model and machine.</p>`+queue+(groups||'<section class="panel entry-form"><h2>No matching material</h2><p>Change the date or filters, or create a production draft first.</p><a class="button primary" href="#/entry">New production batch</a></section>');
}
