import {apiFetch} from './online.mjs';
import {activeSalesList,salesState,salesRows,forwardPrice,netMargin,saveSalesList,activateSalesList,previewSalesImport} from './sales-pricing.mjs';
import {currentMonth} from './domain.mjs';

// A scoped feature module; saved state and dialogs retain the workspace's write guards.
export function createSalesUI(host){
 const {esc,fmt,money,btn,table,field,option,showDialog,commit,download,toast}=host,$=s=>document.querySelector(s);
 let view='current',listId='',search='',series='',status='',draft=null,upload=null,preview=null,readVersion=0;
 const pct=v=>v==null?'Pending':fmt(v,2)+'%',amount=v=>v==null?'Pending':money(v);
 const button=(label,action,attrs='',kind='')=>btn(label,'sales-'+action,attrs,kind);
 const s=()=>host.state(),active=()=>activeSalesList(s());
 const card=(label,value,target,note)=>`<button class="stat cost-stat" data-action="sales-view" data-view="${target}"><span>${label} →</span><strong>${esc(value)}</strong><small>${note}</small></button>`;
 function render(id='',params=new URLSearchParams()){
  if(id)listId=id;else listId='';view=params.get('view')||'current';
  const current=active(),all=salesRows(s()),x=salesState(s());
  if(listId){const list=x.lists.find(l=>l.id===listId);return list?detail(list):`<div class="empty"><h1>Price list not found</h1><a href="#/sales">Return to sales price lists</a></div>`;}
  return `<div class="page-head"><div><div class="eyebrow">Sales pricing</div><h1>Price with a clear margin.</h1><p>Compare today's model cost with current prices. Build the next list and retain every monthly revision.</p></div><div class="actions">${button('Download model template','template')}${button('Add current price list','new','data-kind="current"')}${button('Build new price list','new','data-kind="proposal"','primary')}</div></div>
  <div class="stats">${card('Current price list',current?current.month:'Not set','current',current?esc(current.name)+' · v'+current.version:'Add prices, then set the list as current')}${card('Current model prices',current?.rows.length||0,'current','Selling prices before GST')}${card('Costs ready',all.filter(r=>r.cost!=null).length,'ready','Full BOM and all additional costs entered')}${card('Saved price lists',x.lists.length,'history','Monthly revisions remain unchanged')}</div>
  <div class="notice">Forward price = total model cost × multiplier (for example 1.25). Net margin on entered costs = (selling price − model cost) ÷ selling price × 100. Prices are before GST. Item transport percentages remain reference values; fabrication transport/kg is included.</div>
  <nav class="section-tabs" aria-label="Sales pricing views"><a href="#/price-analysis">Forward / backward & history comparison</a><a href="#/sales?view=current" class="${view==='current'?'active':''}">Current prices & margins</a><a href="#/sales?view=ready" class="${view==='ready'?'active':''}">Cost readiness</a><a href="#/sales?view=history" class="${view==='history'?'active':''}">Monthly history (${x.lists.length})</a></nav>
  ${view==='history'?history():`<section class="panel"><div class="panel-head"><div><h2>${view==='ready'?'Prepare model costs':current?esc(current.name):'No current sales price list yet'}</h2><small>${current?'Current margins below use today’s costs; saved history keeps the original cost snapshot.':'Enter or upload existing selling prices. Costs may remain pending.'}</small></div>${current?`<a class="button" href="#/sales/${esc(current.id)}">View saved list</a>`:''}</div><div class="toolbar"><label class="search">Find sales model<input id="sales-search" type="search" value="${esc(search)}" placeholder="S2.V58, Leader…"></label><label>Series<select id="sales-series">${option('','All series',series)}${[...new Set(all.map(r=>r.series))].map(v=>option(v,v,series)).join('')}</select></label><label>Show models<select id="sales-status">${option('','Models with BOM or price',status)}${option('confirmed','Confirmed for sales',status)}${option('pending','Cost pending',status)}${option('ready','Cost ready',status)}${option('all','All models',status)}</select></label>${button('Download comparison CSV','compare-csv')}</div><div id="sales-results">${results()}</div></section>`}`;
 }
 function filtered(){return salesRows(s()).filter(r=>(!search||`${r.modelId} ${r.series} ${r.size}`.toLowerCase().includes(search.toLowerCase()))&&(!series||r.series===series)&&(status==='all'||status==='confirmed'?status==='all'||r.salesConfirmed:status==='ready'?r.cost!=null:status==='pending'?r.cost==null:r.bomAvailable||r.currentPrice!=null)).sort((a,b)=>a.modelId.localeCompare(b.modelId,undefined,{numeric:true}));}
 function results(){const rows=filtered();return `<div class="panel-body sub">${rows.length} models · margins use today's complete model costs.</div>${rows.length?table(['Model / series','Current price ₹','Today’s cost ₹','Profit ₹','Net margin / sale %','Cost status','Action'],rows.map(r=>`<tr><td><strong>${esc(r.modelId)}</strong><small class="sub">${esc(r.series)} · ${esc(r.size)}</small></td><td class="num">${amount(r.currentPrice)}</td><td class="num">${amount(r.cost)}</td><td class="num">${amount(r.cost==null||r.currentPrice==null?null:r.currentPrice-r.cost)}</td><td class="num ${r.margin!=null&&r.margin<0?'error-inline':''}">${pct(r.margin)}</td><td>${r.cost==null?`${r.pending} cost entries pending`:'Complete'}${r.savedCost!=null&&r.savedCost!==r.cost?'<small class="sub">Cost changed since saved list</small>':''}</td><td><a class="button small" href="#/costing/${esc(r.modelId)}">Review cost</a></td></tr>`).join(''),'Current sales margins','sales-table'):'<div class="empty">No models match these filters.</div>'}`;}
 function history(){const x=salesState(s()),months=[...new Set(x.lists.map(l=>l.month))].sort().reverse();return months.length?months.map(month=>`<section class="panel"><div class="panel-head"><h2>${month}</h2></div>${x.lists.filter(l=>l.month===month).slice().reverse().map(l=>`<div class="po-card"><div><h3><a href="#/sales/${esc(l.id)}">${esc(l.name)}</a></h3><small>Revision ${l.version} · ${l.rows.length} models · ${l.kind==='proposal'?'Calculated prices':'Entered prices'} · ${esc(l.createdAt.slice(0,10))}</small></div><div class="actions">${x.currentId===l.id?'<span class="badge green">Current</span>':button('Set as current','activate',`data-id="${esc(l.id)}"`)}<a class="button" href="#/sales/${esc(l.id)}">Review list</a></div></div>`).join('')}</section>`).join('')+`<details class="panel panel-body"><summary>Current price list changes</summary>${x.activationHistory.slice().reverse().map(a=>`<p>${esc(a.at)} · ${esc(x.lists.find(l=>l.id===a.id)?.name)} · ${esc(a.reason)}</p>`).join('')||'<p>No current list selected yet.</p>'}</details>`:'<section class="empty panel"><h2>Your monthly history starts here</h2><p>Add current prices or build a proposed list. Each save creates a retained monthly revision.</p>'+button('Add current prices','new','data-kind="current"','primary')+'</section>';}
 function detail(l){return `<a class="back" href="#/sales?view=history">← Monthly price history</a><div class="page-head"><div><div class="eyebrow">${esc(l.month)} · Revision ${l.version} · ${l.kind==='proposal'?'Calculated':'Entered'} prices</div><h1>${esc(l.name)}</h1><p>Saved ${esc(l.createdAt.slice(0,10))} · ${l.rows.length} models · ${active()?.id===l.id?'Current price list':'Retained price list'}</p></div><div class="actions">${button('Customer price CSV','customer-csv',`data-id="${esc(l.id)}"`)}${button('Cost & margin CSV','internal-csv',`data-id="${esc(l.id)}"`)}${active()?.id!==l.id?button('Set as current','activate',`data-id="${esc(l.id)}"`,'primary'):''}</div></div><div class="notice">This saved list uses costs at the time it was created. Later BOM or purchase-price changes do not alter it. <a href="#/sales">Check margins using current costs</a>.</div><section class="panel">${table(['Model','Sale price ₹','Net margin %','Cost ₹','Multiplier','Calculated ₹','Round off ₹','Previous price ₹','Previous margin %','Profit ₹'],l.rows.map(r=>`<tr><td><b>${esc(r.modelId)}</b><small class="sub">${esc(r.series)}</small></td><td class="num current-cell"><strong>${amount(r.price)}</strong></td><td class="num current-cell"><strong>${pct(r.margin)}</strong></td><td class="num">${amount(r.cost)}</td><td class="num">${r.factor==null?'—':fmt(r.factor)}</td><td class="num">${r.calculated==null?'—':amount(r.calculated)}</td><td class="num">${amount(r.roundOff)}</td><td class="num">${amount(r.previousPrice)}</td><td class="num">${pct(r.previousMargin)}</td><td class="num">${amount(r.profit)}</td></tr>`).join(''),'Saved sales price list','sales-table')}<div class="panel-body"><p class="help">${esc(l.basis)}</p><p>${esc(l.notes)}</p>${l.excludedRows?.length?`<details><summary>${l.excludedRows.length} excluded import rows retained</summary>${l.excludedRows.map(e=>`<p>Row ${e.row} · ${esc(e.modelId)} · ${esc(e.message)}</p>`).join('')}</details>`:''}</div></section>`;}
 function newList(kind){const all=salesRows(s());draft={kind,factor:1.25,increment:100,rounding:'up',rows:all.filter(r=>r.bomAvailable||r.currentPrice!=null).map(r=>({...r,include:kind==='proposal'?r.cost!=null:r.currentPrice!=null,price:r.currentPrice??'',factor:1.25,adjustment:null}))};upload=null;preview=null;readVersion++;
  showDialog(kind==='proposal'?'Build new sales price list':'Add current selling prices',`<div class="forms">${field('listName','Price list name',kind==='proposal'?'Proposed sales prices':'Current sales prices','text','required maxlength="150"')}${field('listMonth','Price list month',currentMonth(),'month','required min="2000-01" max="2100-12"')}</div>${kind==='proposal'?`<div class="forms three">${field('factor','Default cost multiplier',1.25,'number','id="sales-factor" min="0.01" max="10" step="0.01"')}<label>Round to ₹<select id="sales-increment">${[0,1,10,50,100,500,1000].map(v=>option(v,v||'No automatic rounding',100)).join('')}</select></label><label>Rounding method<select id="sales-rounding">${option('up','Round up','up')}${option('nearest','Nearest','up')}${option('down','Round down','up')}</select></label></div><div class="actions">${button('Apply multiplier & rounding to all','apply-rule')}</div><p class="help">1.25 means cost × 1.25. Change a model's multiplier or its round-off amount below. The final margin reflects all rounding.</p>`:`<details><summary>Upload Excel / CSV, or paste prices</summary><label>Sales price file<input type="file" id="sales-file" accept=".xlsx,.csv"></label><label>Paste model and price columns, including headers<textarea id="sales-paste" placeholder="Model&#9;Sale price"></textarea></label>${button('Read pasted prices','read-paste')}<div id="sales-import"></div></details>`}
  <div class="notice">${kind==='proposal'?'Only models with complete costs can be included.':'Enter prices in INR per machine before GST. Select the models to include. A blank price stays pending. Imports update matched draft rows; other existing prices stay as shown.'} Saving adds a new history revision. Use “Set as current” after reviewing it.</div><div class="actions"><label>Model to add<select id="sales-add-model">${option('','Choose a model','')}${all.map(r=>option(r.modelId,`${r.modelId} · ${r.series}`,'')).join('')}</select></label>${button('Add model','add-model')}${button('Select eligible models','select-eligible')}</div><div id="sales-draft">${draftTable()}</div><label>Notes / reason<textarea name="notes" maxlength="2000"></textarea></label>`,async fd=>{
   if(draft.kind==='proposal'&&(Number($('#sales-factor').value)!==draft.factor||Number($('#sales-increment').value)!==draft.increment||$('#sales-rounding').value!==draft.rounding))throw Error('Click Apply multiplier & rounding to all to apply the changed defaults before saving.');
   const id='sales-'+crypto.randomUUID();await commit('Sales price list saved. Review before setting it as current.',state=>saveSalesList(state,{...draft,name:fd.get('listName'),month:fd.get('listMonth'),notes:fd.get('notes'),excludedRows:draft.excludedRows||[],rows:draft.rows.filter(r=>r.include)}, {id}));location.hash='#/sales/'+id;
  },'Save price list to history',true,'Saved monthly revisions cannot be overwritten.');
 }
 function calc(r){return draft.kind==='proposal'?forwardPrice(r.cost,r.factor,draft.increment,draft.rounding,r.adjustment):{price:r.price===''?null:Number(r.price),margin:netMargin(r.price===''?null:Number(r.price),r.cost),roundOff:0,calculated:null};}
 function cells(r){try{const p=calc(r);return `<span>${amount(p.price)}</span><small class="sub">Margin ${pct(p.margin)}</small>`;}catch{return '<span class="error-inline">Check multiplier / round off</span>';}}
 function draftTable(){return table(['Include','Model / cost','Current price / margin',...(draft.kind==='proposal'?['Multiplier','Calculated ₹','Round off ₹','New price / margin']:['Selling price ₹','Margin %'])],draft.rows.map((r,i)=>`<tr><td><input aria-label="Include ${esc(r.modelId)}" type="checkbox" data-sales-row="${i}" data-sales-field="include" ${r.include?'checked':''} ${draft.kind==='proposal'&&r.cost==null?'disabled':''}></td><td><b>${esc(r.modelId)}</b><small class="sub">${esc(r.series)} · Cost ${amount(r.cost)}</small>${r.cost==null?`<small class="sub">Complete costs in Price calculation</small>`:''}</td><td class="num">${amount(r.currentPrice)}<small class="sub">${pct(r.margin)}</small></td>${draft.kind==='proposal'?`<td><input aria-label="Multiplier ${esc(r.modelId)}" type="number" min="0.01" max="10" step="0.01" data-sales-row="${i}" data-sales-field="factor" value="${r.factor}"></td><td class="num" id="sales-calculated-${i}">${r.cost==null?'Pending':amount(r.cost*r.factor)}</td><td><input aria-label="Round off ${esc(r.modelId)}" type="number" step="0.01" data-sales-row="${i}" data-sales-field="adjustment" value="${r.adjustment??''}" placeholder="${r.cost==null?'Pending':forwardPrice(r.cost,r.factor,draft.increment,draft.rounding).roundOff}" title="Blank uses automatic rounding; zero means no rounding adjustment"></td><td class="num" id="sales-computed-${i}">${cells(r)}</td>`:`<td><input aria-label="Selling price ${esc(r.modelId)}" type="number" min="0.01" max="100000000" step="0.01" data-sales-row="${i}" data-sales-field="price" value="${r.price}"></td><td class="num" id="sales-computed-${i}">${pct(netMargin(r.price===''?null:Number(r.price),r.cost))}</td>`}</tr>`).join(''),'Edit sales prices','sales-edit-table');}
 function csv(name,rows){const cell=v=>{let t=String(v??'');if(typeof v==='string'&&/^[\s]*[=+@-]/.test(t))t="'"+t;return '"'+t.replaceAll('"','""')+'"';};download(name+'.csv','\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');toast('Price list CSV downloaded.');}
 async function readFile(file){const version=++readVersion;upload=null;preview=null;$('#sales-import').innerHTML='<p role="status">Reading prices…</p>';if(file.size>10*1024*1024)throw Error('Maximum upload is 10 MB.');const res=await apiFetch('/api/implements/read-stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,data:await host.fileBase64(file)})}),data=await res.json();if(!res.ok)throw Error(data.error);if(version!==readVersion||!$('#sales-import'))return;upload=data;$('#sales-import').innerHTML=`<label>Sheet<select id="sales-sheet">${data.sheets.map((sheet,i)=>option(i,sheet.name,0)).join('')}</select></label><div id="sales-columns"></div><div id="sales-import-preview"></div>`;columns();}
 function columns(){preview=null;const h=upload.sheets[Number($('#sales-sheet').value)].rows[0]||[];$('#sales-columns').innerHTML=`<div class="forms"><label>Model number column<select id="sales-code">${h.map((v,i)=>option(i,v,Math.max(0,h.findIndex(v=>/model/i.test(v))))).join('')}</select></label><label>Selling price column<select id="sales-price">${h.map((v,i)=>option(i,v,Math.max(1,h.findIndex(v=>/price|rate/i.test(v))))).join('')}</select></label></div>${button('Preview sales matches','preview-import')}`;$('#sales-import-preview').innerHTML='';}
 async function action(a,d){a=a.replace(/^sales-/,'');
  if(a==='view'){if(d.view==='ready')status='ready';else if(d.view==='current')status='';view=d.view;location.hash='#/sales?view='+view;host.render();}
  if(a==='new')newList(d.kind);
  if(a==='template')csv('Sales_price_model_template',[['Model','Sale price','Series','Size'],...salesRows(s()).map(r=>[r.modelId,r.currentPrice,r.series,r.size])]);
  if(a==='add-model'){const id=$('#sales-add-model').value;if(!id)throw Error('Choose a model.');if(draft.rows.some(r=>r.modelId===id))throw Error('This model is already in the list.');const r=salesRows(s()).find(r=>r.modelId===id);draft.rows.push({...r,include:false,price:r.currentPrice??'',factor:draft.factor,adjustment:null});host.dirty();$('#sales-draft').innerHTML=draftTable();}
  if(a==='select-eligible'){draft.rows.forEach(r=>r.include=draft.kind==='proposal'?r.cost!=null:r.price!==''&&Number(r.price)>0);host.dirty();$('#sales-draft').innerHTML=draftTable();}
  if(a==='apply-rule'){const factor=Number($('#sales-factor').value),increment=Number($('#sales-increment').value),rounding=$('#sales-rounding').value;forwardPrice(100,factor,increment,rounding);Object.assign(draft,{factor,increment,rounding});draft.rows.forEach(r=>{r.factor=factor;r.adjustment=null;});host.dirty();$('#sales-draft').innerHTML=draftTable();}
  if(a==='activate'){const l=salesState(s()).lists.find(l=>l.id===d.id);showDialog('Set this list as current',`<p><b>${esc(l.name)}</b> · ${esc(l.month)} · ${l.rows.length} models</p><div class="notice">This replaces the current sales list. Models not included will have no current sales price. All earlier lists remain in history.</div>${field('reason','Reason for changing current list','','text','required maxlength="1000"')}`,async fd=>await commit('Current sales price list updated.',state=>activateSalesList(state,l.id,fd.get('reason'))),'Set as current');}
  if(a==='compare-csv')csv('Current_sales_margin_comparison',[['Model','Series','Current price INR before GST','Today model cost INR','Profit INR','Net margin on sale %','Pending cost entries'],...filtered().map(r=>[r.modelId,r.series,r.currentPrice,r.cost,r.currentPrice==null||r.cost==null?null:r.currentPrice-r.cost,r.margin,r.pending])]);
  if(a==='customer-csv'||a==='internal-csv'){const l=salesState(s()).lists.find(l=>l.id===d.id);const internal=a==='internal-csv';csv(l.name+'_'+l.month+'_v'+l.version+(internal?'_INTERNAL_cost_margin':'_CUSTOMER_prices'),[internal?['Model','Series','Cost INR','Previous price INR','Previous margin %','Cost multiplier','Calculated price INR','Round off INR','Selling price INR before GST','Profit INR','Net margin %']:['Model','Series','Size','Selling price INR before GST','Effective month','List revision'],...l.rows.map(r=>internal?[r.modelId,r.series,r.cost,r.previousPrice,r.previousMargin,r.factor,r.calculated,r.roundOff,r.price,r.profit,r.margin]:[r.modelId,r.series,r.size,r.price,l.month,l.version])]);}
  if(a==='read-paste'){const text=$('#sales-paste').value;if(!text.trim())throw Error('Paste model numbers and selling prices with headers.');await readFile(new File([text],'Pasted sales prices.csv',{type:'text/csv'}));}
  if(a==='preview-import'){preview=previewSalesImport(s(),upload.sheets[Number($('#sales-sheet').value)].rows,Number($('#sales-code').value),Number($('#sales-price').value));$('#sales-import-preview').innerHTML=`<div class="notice">${preview.matched.length} matched · ${preview.errors.length} excluded</div>${table(['Model','Sale price ₹'],preview.matched.map(r=>`<tr><td>${esc(r.modelId)}</td><td>${amount(r.price)}</td></tr>`).join(''),'Sales price import preview')}${preview.errors.map(e=>`<p>Row ${e.row} · ${esc(e.modelId)} · ${esc(e.message)}</p>`).join('')}${preview.errors.length?'<label class="check"><input type="checkbox" id="sales-accept-excluded"> Keep excluded rows out of this import</label>':''}${button('Use matched prices in draft','use-import')}`;}
  if(a==='use-import'){if(!preview?.matched.length)throw Error('Preview matched prices first.');if(preview.errors.length&&!$('#sales-accept-excluded')?.checked)throw Error('Acknowledge excluded rows first.');for(const p of preview.matched){let r=draft.rows.find(r=>r.modelId===p.modelId);if(!r){r={...salesRows(s()).find(r=>r.modelId===p.modelId),factor:1.25,adjustment:null};draft.rows.push(r);}Object.assign(r,{price:p.price,include:true});}draft.excludedRows=preview.errors;host.dirty();$('#sales-draft').innerHTML=draftTable();toast('Matched prices added to draft. Save the price list to retain them.');}
 }
 function input(el){if(el.id==='sales-search'){search=el.value;$('#sales-results').innerHTML=results();}if(el.dataset.salesRow!=null){const i=Number(el.dataset.salesRow),r=draft.rows[i],key=el.dataset.salesField;r[key]=key==='include'?el.checked:key==='adjustment'?(el.value===''?null:Number(el.value)):el.value;const calculated=$('#sales-calculated-'+i);if(calculated)calculated.textContent=amount(r.cost==null?null:r.cost*Number(r.factor));$('#sales-computed-'+i).innerHTML=draft.kind==='proposal'?cells(r):pct(netMargin(r.price===''?null:Number(r.price),r.cost));}}
 async function change(el){if(el.id==='sales-series'||el.id==='sales-status'){if(el.id==='sales-series')series=el.value;else status=el.value;$('#sales-results').innerHTML=results();}if(el.id==='sales-file'&&el.files[0])await readFile(el.files[0]);if(el.id==='sales-sheet')columns();if(['sales-code','sales-price'].includes(el.id)){preview=null;$('#sales-import-preview').innerHTML='';}}
 return {render,action,input,change};
}
