import {isoDay,SCHEMA_VERSION,PAYMENT_METHODS,PORTS} from './domain.mjs';
import {PLM_TEMPLATES} from './plm.mjs';
import {applyFinalMasterData} from './final-master-data.mjs';

const LAE_CATEGORIES = [
  'CHAFF CUTTER','POWER WEEDER','BRUSH CUTTER','KNAPSACK SPRAYER','WOODCHIPPER','SEEDER',
  'BATTERY SPRAYER','HOSE','HTP+ENGINE','CHAIN SAW','PORTABLE SPRAYER','WATER PUMP','ENGINE',
  'HTP + MOTOR','HTP','EARTH AUGER','HEDGE TRIMMER','MINI WEEDER','MANUAL SPRAYER','FLAIL MOWER',
  'MOTOR','BLADES'
];

/**
 * Clean transaction review workspace.
 * Loads the approved Vendor Master, final Base Item Master, generated ERP Item Codes,
 * filtered supplier price lists and freight-rate history, but no demo PO/payment/shipment/complaint transactions.
 */
export function createCleanSeed(today=isoDay()){
  const state = {
    schemaVersion: SCHEMA_VERSION,
    revision: 0,
    demo: false,
    clean: true,
    seedDate: today,
    settings: {
      warningDays: 3,
      bookingLeadDays: 10,
      freightWarningUsd: 100,
      allowPreviousApprovedSpec: false,
      closurePoint: 'DESTINATION_PORT',
      insuranceMasterPolicy: ''
    },
    users: [
      {id:'u-admin',name:'Administrator',role:'ADMIN',scopes:['LAE_IMPORT'],active:true},
      {id:'u-manager',name:'Purchase Manager',role:'MANAGER',scopes:['LAE_IMPORT'],active:true},
      {id:'u-exec',name:'Purchase Executive',role:'EXECUTIVE',scopes:['LAE_IMPORT'],active:true},
      {id:'u-product',name:'Product Manager',role:'PRODUCT_MANAGER',scopes:['LAE_IMPORT'],active:true},
      {id:'u-viewer',name:'Viewer',role:'VIEWER',scopes:['LAE_IMPORT'],active:true}
    ],
    vendors: [
      {
            "id": "vendor-v01",
            "vendorSerial": "V01",
            "fixedSupplierCode": "SWAC",
            "fullReference": "V01-SWAC",
            "code": "V01-SWAC",
            "name": "CHONGQING SENCI WUGU AGRICULTURAL MACHINERY IMPORT&EXPORT CO LTD",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 45,
            "productionDaysIsReference": true,
            "defaultTerms": "10-20-70-bl120",
            "paymentTermsText": "10% ADVANCE FOR ORDER CONFIRMATION, 20% BEFORE SHIPMENT, 70% BEFORE 120 DAYS FROM LOADING BL",
            "contact": "45",
            "email": "45",
            "phone": "45",
            "wechat": "45",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v02",
            "vendorSerial": "V02",
            "fixedSupplierCode": "YPMC",
            "fullReference": "V02-YPMC",
            "code": "V02-YPMC",
            "name": "CHONGQING YAOHU POWER MACHINE CO LTD",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "20-80-bl120",
            "paymentTermsText": "20% ADVANCE - 80% BEFORE 120 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v03",
            "vendorSerial": "V03",
            "fixedSupplierCode": "HMMC",
            "fullReference": "V03-HMMC",
            "code": "V03-HMMC",
            "name": "CHONGQING HAOFA MACHINERY MANUFACTURING COMPANY LTD",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v04",
            "vendorSerial": "V04",
            "fixedSupplierCode": "SAMC",
            "fullReference": "V04-SAMC",
            "code": "V04-SAMC",
            "name": "CHONGQING SHINERAY AGRICULTURAL MACHINERY CO LTD",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v05",
            "vendorSerial": "V05",
            "fixedSupplierCode": "FCLX",
            "fullReference": "V05-FCLX",
            "code": "V05-FCLX",
            "name": "FUSITE CO LTD",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 45,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v06",
            "vendorSerial": "V06",
            "fixedSupplierCode": "DEMH",
            "fullReference": "V06-DEMH",
            "code": "V06-DEMH",
            "name": "HUNAN DONGFANGHONG ELECTROMECHANICAL MANUFACTURING CO LTD",
            "city": "LOUDI",
            "defaultExportPort": "SHENZHEN",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl60",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v07",
            "vendorSerial": "V07",
            "fixedSupplierCode": "JMCH",
            "fullReference": "V07-JMCH",
            "code": "V07-JMCH",
            "name": "HUNAN JINSONG MACHINERY CO LTD",
            "city": "",
            "defaultExportPort": "",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v08",
            "vendorSerial": "V08",
            "fixedSupplierCode": "FPPL",
            "fullReference": "V08-FPPL",
            "code": "V08-FPPL",
            "name": "LINYI FENGURI PLANT PROTECTION ELECTRONIC EQUIPMENT CO LTD",
            "city": "",
            "defaultExportPort": "",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v09",
            "vendorSerial": "V09",
            "fixedSupplierCode": "XMMS",
            "fullReference": "V09-XMMS",
            "code": "V09-XMMS",
            "name": "SHUANGFENG XIANGDONG MACHINERY MANUFACTURING CO",
            "city": "",
            "defaultExportPort": "",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v10",
            "vendorSerial": "V10",
            "fixedSupplierCode": "SXMX",
            "fullReference": "V10-SXMX",
            "code": "V10-SXMX",
            "name": "SHUNANG XIANGDONG MACHINERY",
            "city": "LOUDI",
            "defaultExportPort": "SHENZHEN",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl60",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v11",
            "vendorSerial": "V11",
            "fixedSupplierCode": "SSAS",
            "fullReference": "V11-SSAS",
            "code": "V11-SSAS",
            "name": "SICHUAN SUITONG SCIENCE AND TECHNOLOGY",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v12",
            "vendorSerial": "V12",
            "fixedSupplierCode": "XMMS",
            "fullReference": "V12-XMMS",
            "code": "V12-XMMS",
            "name": "SICHUAN XUDONG MACHINERY MANUFACTURE CO LTD",
            "city": "LESHAN",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 60,
            "productionDaysIsReference": true,
            "defaultTerms": "20-80",
            "paymentTermsText": "20% Advance - 80% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v13",
            "vendorSerial": "V13",
            "fixedSupplierCode": "DTCT",
            "fullReference": "V13-DTCT",
            "code": "V13-DTCT",
            "name": "TAIZHOU DONGFENG TECHNOLOGY CO LTD",
            "city": "",
            "defaultExportPort": "",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v14",
            "vendorSerial": "V14",
            "fixedSupplierCode": "HICT",
            "fullReference": "V14-HICT",
            "code": "V14-HICT",
            "name": "TAIZHOU HAODING IMPORT&EXPORT CO.,LTD",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 25,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl60",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v15",
            "vendorSerial": "V15",
            "fixedSupplierCode": "OI&T",
            "fullReference": "V15-OI&T",
            "code": "V15-OI&T",
            "name": "TAIZHOU ORDER IMPORT & EXPORT CO LTD",
            "city": "",
            "defaultExportPort": "",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v16",
            "vendorSerial": "V16",
            "fixedSupplierCode": "QMCT",
            "fullReference": "V16-QMCT",
            "code": "V16-QMCT",
            "name": "TAIZHOU QINGFENG MACHINERY CO LTD",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 35,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl60",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v17",
            "vendorSerial": "V17",
            "fixedSupplierCode": "WAMX",
            "fullReference": "V17-WAMX",
            "code": "V17-WAMX",
            "name": "WEIMA AGRICULTURAL MACHINERY CO LTD",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v18",
            "vendorSerial": "V18",
            "fixedSupplierCode": "MTYX",
            "fullReference": "V18-MTYX",
            "code": "V18-MTYX",
            "name": "YONGKANG MAXPOWER TECHNOLOGY",
            "city": "",
            "defaultExportPort": "",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v19",
            "vendorSerial": "V19",
            "fixedSupplierCode": "UMYX",
            "fullReference": "V19-UMYX",
            "code": "V19-UMYX",
            "name": "YONGKANG UNITED MACHANIC",
            "city": "",
            "defaultExportPort": "",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v20",
            "vendorSerial": "V20",
            "fixedSupplierCode": "ZMCY",
            "fullReference": "V20-ZMCY",
            "code": "V20-ZMCY",
            "name": "YONGKANG ZHANLI MACHINERY CO LTD",
            "city": "YONGKANG",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 60,
            "productionDaysIsReference": true,
            "defaultTerms": "credit60",
            "paymentTermsText": "100% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v21",
            "vendorSerial": "V21",
            "fixedSupplierCode": "JMZX",
            "fullReference": "V21-JMZX",
            "code": "V21-JMZX",
            "name": "ZHEJIANG JIARUI MACHINERY",
            "city": "YONGKANG",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 45,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl60",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v22",
            "vendorSerial": "V22",
            "fixedSupplierCode": "OMZX",
            "fullReference": "V22-OMZX",
            "code": "V22-OMZX",
            "name": "ZHEJIANG OUSEN MACHINERY",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 35,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v23",
            "vendorSerial": "V23",
            "fixedSupplierCode": "WMEZ",
            "fullReference": "V23-WMEZ",
            "code": "V23-WMEZ",
            "name": "ZHEJIANG WENXIN MECHANICAL ELECTRICAL CO",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 35,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v24",
            "vendorSerial": "V24",
            "fixedSupplierCode": "RMCE",
            "fullReference": "V24-RMCE",
            "code": "V24-RMCE",
            "name": "CHONGQING REHOGA MACHINERY EQUIPMENT CO., LTD",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v25",
            "vendorSerial": "V25",
            "fixedSupplierCode": "FCMC",
            "fullReference": "V25-FCMC",
            "code": "V25-FCMC",
            "name": "Chongqing Finest Machinery Co.,Ltd",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl120",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 120 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v26",
            "vendorSerial": "V26",
            "fixedSupplierCode": "XHEM",
            "fullReference": "V26-XHEM",
            "code": "V26-XHEM",
            "name": "Hunan Xiangyou Mechanical and Electrical Co., Ltd.",
            "city": "LOUDI",
            "defaultExportPort": "SHENZHEN",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v27",
            "vendorSerial": "V27",
            "fixedSupplierCode": "ZHEB",
            "fullReference": "V27-ZHEB",
            "code": "V27-ZHEB",
            "name": "CHONGQING BAINUODA IMPORT AND EXPORT TRADING CO., LTD.",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 60,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v28",
            "vendorSerial": "V28",
            "fixedSupplierCode": "WDME",
            "fullReference": "V28-WDME",
            "code": "V28-WDME",
            "name": "Dandong Wellgain Machinery Equipment Co.,Ltd",
            "city": "DANDONG",
            "defaultExportPort": "",
            "country": "China",
            "status": "INACTIVE",
            "stage": "Inactive Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl60",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v29",
            "vendorSerial": "V29",
            "fixedSupplierCode": "FEIT",
            "fullReference": "V29-FEIT",
            "code": "V29-FEIT",
            "name": "TAIZHOU FOURNINE IMPORT AND EXPORT CO., LTD",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v30",
            "vendorSerial": "V30",
            "fixedSupplierCode": "DMTA",
            "fullReference": "V30-DMTA",
            "code": "V30-DMTA",
            "name": "TAIZHOU DOMIRO AGRICULTURAL MACHINERY CO., LTD",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 25,
            "productionDaysIsReference": true,
            "defaultTerms": "credit60",
            "paymentTermsText": "100% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v31",
            "vendorSerial": "V31",
            "fixedSupplierCode": "TCSE",
            "fullReference": "V31-TCSE",
            "code": "V31-TCSE",
            "name": "CHONGQING TENGLONG SHINES ELECTROMECHANICS CO.,LTD.",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v32",
            "vendorSerial": "V32",
            "fixedSupplierCode": "WMCM",
            "fullReference": "V32-WMCM",
            "code": "V32-WMCM",
            "name": "Chongqing Weiwang Machinery Manufacturing Co., Ltd",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v33",
            "vendorSerial": "V33",
            "fixedSupplierCode": "HTCM",
            "fullReference": "V33-HTCM",
            "code": "V33-HTCM",
            "name": "CHONGQING HUA TIAN HAO LI MACHINERY LLC",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl120",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 120 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v34",
            "vendorSerial": "V34",
            "fixedSupplierCode": "MTCL",
            "fullReference": "V34-MTCL",
            "code": "V34-MTCL",
            "name": "TAIZHOU MENGHUA MACHINERY CO.,LTD",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "USD",
            "defaultPaymentMethod": "TT",
            "productionDays": 35,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70-bl60",
            "paymentTermsText": "30% ADVANCE AND 70% BEFORE 60 DAYS FROM LOADING BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v35",
            "vendorSerial": "V35",
            "fixedSupplierCode": "CYEI",
            "fullReference": "V35-CYEI",
            "code": "V35-CYEI",
            "name": "YIWU CANFLY IMPORT AND EXPORT CO.,LTD",
            "city": "TAIZHOU",
            "defaultExportPort": "NINGBO",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 60,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v36",
            "vendorSerial": "V36",
            "fixedSupplierCode": "BMCM",
            "fullReference": "V36-BMCM",
            "code": "V36-BMCM",
            "name": "CHONGQING BASEWIN MACHINERY MANUFACTURING CO., LTD.",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 30,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      },
      {
            "id": "vendor-v37",
            "vendorSerial": "V37",
            "fixedSupplierCode": "SMLC",
            "fullReference": "V37-SMLC",
            "code": "V37-SMLC",
            "name": "CHONGQING SBOSEN MACHINERY CO., LTD",
            "city": "Chongqing",
            "defaultExportPort": "Chongqing",
            "country": "China",
            "status": "ACTIVE",
            "stage": "Active Vendor",
            "kind": "SUPPLIER",
            "scopes": [
                  "LAE_IMPORT"
            ],
            "currency": "USD",
            "defaultBillingCurrency": "USD",
            "defaultPriceListCurrency": "CNY",
            "defaultPaymentMethod": "TT",
            "productionDays": 15,
            "productionDaysIsReference": true,
            "defaultTerms": "30-70",
            "paymentTermsText": "30% Advance - 70% AGAINST TELEX BL",
            "contact": "",
            "email": "",
            "phone": "",
            "wechat": "",
            "remarks": "",
            "source": "Supplier Master Update workbook 2026-09-12",
            "codeLocked": true,
            "evaluation": {}
      }
],
    items: [],
    bases: [],
    plmTemplates: structuredClone(PLM_TEMPLATES),
    categories: LAE_CATEGORIES.map((name,i)=>({id:'cat-'+i,name,active:true})),
    brands: [
      {name:'Gaja Hi-Tech Agro',prefix:'GJ',active:true},
      {name:'Kisan Dost',prefix:'KD',active:true},
      {name:'Titan Agri',prefix:'TT',active:true},
      {name:'Stinger',prefix:'',active:false},
      {name:'Suraksha Gold',prefix:'',active:false}
    ],
    paymentMethods: structuredClone(PAYMENT_METHODS),
    ports: structuredClone(PORTS),
    routes: [
      {
            "id": "route-chongqing-chennai",
            "name": "Chongqing → Chennai",
            "origin": "CHONGQING",
            "destination": "CHENNAI",
            "transitDays": 1,
            "rateRouteKey": "CHONGQING|CHENNAI|1X40HC",
            "source": "Route master created from Supplier Master export port. Transit days are placeholder only; manual planning TAT remains explicit."
      },
      {
            "id": "route-ningbo-chennai",
            "name": "Ningbo → Chennai",
            "origin": "NINGBO",
            "destination": "CHENNAI",
            "transitDays": 1,
            "rateRouteKey": "NINGBO|CHENNAI|1X40HC",
            "source": "Route master created from Supplier Master export port. Transit days are placeholder only; manual planning TAT remains explicit."
      },
      {
            "id": "route-shenzhen-chennai",
            "name": "Shenzhen → Chennai",
            "origin": "SHENZHEN",
            "destination": "CHENNAI",
            "transitDays": 1,
            "rateRouteKey": "SHENZHEN|CHENNAI|1X40HC",
            "source": "Route master created from Supplier Master export port. Transit days are placeholder only; manual planning TAT remains explicit."
      }
],
    orders: [],
    payments: [],
    files: [],
    events: [],
    costs: [],
    imports: [],
    vendorImports: [{id:'vendor-import-final-002',filename:'Farming_Hub_Supplier_Master_Update_Template_v1.xlsx',templateVersion:'Supplier Master Commercial v2',mappingVersion:'vendor-reference-plus-commercial-defaults',at: today,by:'System import from user-updated supplier master',count:37,source:'docs/reference/Supplier_Master_Updated_v0.5.3-alpha.14.xlsx',notes:'Payment terms, default payment method, price-list currency, billing currency, reference production days and export port imported from the workbook. Vendor serial + fixed supplier code remain the stable reference.'}],
    vendorRequests: [],
    priceLists: [],
    shippingImports: [],
    freightImports: [],
    freightRates: [],
    seededEventCount: 0
  };
  return applyFinalMasterData(state,today);
}
