/** Permanent application identity, separate from editable business/document numbers. */
export const REFERENCE_TYPES={orders:{prefix:'PO',label:'Purchase orders'},vendors:{prefix:'VEN',label:'Vendors'},bases:{prefix:'BAS',label:'Base products'},items:{prefix:'ITM',label:'Items'},priceLists:{prefix:'PRC',label:'Supplier prices'},payments:{prefix:'PAY',label:'Payments'},complaints:{prefix:'CMP',label:'Complaints'},files:{prefix:'DOC',label:'Documents'},costs:{prefix:'CST',label:'Order costs'},shipments:{prefix:'SHP',label:'Shipments'},orderLines:{prefix:'POL',label:'PO lines'},allocations:{prefix:'PAL',label:'Payment allocations'},tasks:{prefix:'TSK',label:'Order tasks'},interactions:{prefix:'VIS',label:'Vendor interactions'},samples:{prefix:'SMP',label:'Vendor samples'}};
const refCheck=(ok,message)=>{if(!ok)throw new Error(message);};
export const referenceKey=(type,id,parentType='',parentId='')=>JSON.stringify([type,parentType,parentId,id]);
export function referenceRecords(state){const rows=[],add=(type,record,parentType='',parentId='')=>{if(typeof record?.id==='string'&&record.id)rows.push({type,id:record.id,parentType,parentId,key:referenceKey(type,record.id,parentType,parentId),record});};
 for(const type of ['orders','vendors','bases','items','priceLists','payments','complaints','files','costs'])for(const r of state[type]||[])add(type,r);
 for(const o of state.orders||[])for(const [type,field] of [['shipments','shipments'],['orderLines','lines'],['tasks','tasks']])for(const r of o[field]||[])add(type,r,'orders',o.id);
 for(const p of state.payments||[])for(const r of p.allocations||[])add('allocations',r,'payments',p.id);
 for(const v of state.vendors||[])for(const [type,field] of [['interactions','interactions'],['samples','samples']])for(const r of v.crm?.[field]||[])add(type,r,'vendors',v.id);
 return rows;
}
export function ensureRecordReferences(state){let changed=false;if(!state.recordReferences){state.recordReferences={version:1,namespace:crypto.randomUUID(),next:{},entries:{},links:[]};changed=true;}
 const registry=state.recordReferences;refCheck(registry.version===1&&typeof registry.namespace==='string'&&/^[0-9a-f-]{36}$/i.test(registry.namespace)&&registry.next&&registry.entries&&Array.isArray(registry.links),'Invalid software reference registry.');
 const used=new Set(),minimum={};for(const [key,e] of Object.entries(registry.entries)){const def=REFERENCE_TYPES[e.type];refCheck(def&&key===referenceKey(e.type,e.id,e.parentType,e.parentId),'Invalid software reference identity.');const match=new RegExp('^FH-'+def.prefix+'-([0-9]{6,})$').exec(e.reference);const n=match?Number(match[1]):0;refCheck(Number.isSafeInteger(n)&&n>0&&!used.has(e.reference),'Invalid or duplicate software reference.');used.add(e.reference);minimum[e.type]=Math.max(minimum[e.type]||1,n+1);}
 for(const type of Object.keys(REFERENCE_TYPES)){const old=registry.next[type];refCheck(old===undefined||Number.isSafeInteger(old)&&old>0,'Invalid software reference counter.');const next=Math.max(old||1,minimum[type]||1);if(old!==next){registry.next[type]=next;changed=true;}}
 const keys=new Set();for(const row of referenceRecords(state)){refCheck(!keys.has(row.key),'Duplicate record identity; references cannot be assigned.');keys.add(row.key);if(registry.entries[row.key])continue;const n=registry.next[row.type];refCheck(n<Number.MAX_SAFE_INTEGER,'Software reference capacity reached.');registry.next[row.type]++;registry.entries[row.key]={type:row.type,id:row.id,parentType:row.parentType,parentId:row.parentId,reference:'FH-'+REFERENCE_TYPES[row.type].prefix+'-'+String(n).padStart(6,'0')};changed=true;}
 return changed;
}
export function softwareReference(state,type,id,parentType='',parentId=''){return state.recordReferences?.entries?.[referenceKey(type,id,parentType,parentId)]?.reference||'';}
export function preserveRecordReferences(previous,next){if(!previous.recordReferences)return;const a=previous.recordReferences,b=next.recordReferences;refCheck(b&&b.namespace===a.namespace,'Software reference namespace cannot change.');for(const [key,e] of Object.entries(a.entries))refCheck(JSON.stringify(b.entries[key])===JSON.stringify(e),'Assigned software references cannot change or disappear.');for(const [type,n] of Object.entries(a.next))refCheck(b.next[type]>=n,'Software reference counters cannot move backwards.');for(const link of a.links)refCheck(b.links.some(x=>JSON.stringify(x)===JSON.stringify(link)),'Existing ERP links cannot be overwritten.');}
export function scopedRecordReferences(state,registry){if(!registry)return undefined;const keys=new Set(referenceRecords(state).map(r=>r.key));return {...registry,entries:Object.fromEntries(Object.entries(registry.entries).filter(([k])=>keys.has(k))),links:registry.links.filter(l=>keys.has(l.recordKey))};}
export function linkExternalReference(state,payload){const p=payload||{},allowed=['recordKey','system','companyKey','externalId','masterId','alterId','voucherNumber'];refCheck(Object.keys(p).every(k=>allowed.includes(k)),'Unsupported ERP link field.');refCheck(['ERP','TALLY'].includes(p.system),'Select ERP or Tally.');refCheck(referenceRecords(state).some(r=>r.key===p.recordKey),'Select an available software reference.');const clean={recordKey:p.recordKey,system:p.system};for(const k of ['companyKey','externalId','masterId','alterId','voucherNumber']){refCheck(p[k]===undefined||typeof p[k]==='string','ERP identifiers must be text.');const value=(p[k]||'').trim();refCheck(value.length<=200&&!/[\x00-\x1f\x7f]/.test(value),'Invalid ERP identifier.');clean[k]=value;}refCheck(clean.companyKey&&clean.externalId,'Company key and external ID / GUID are required.');const links=state.recordReferences.links,entry=state.recordReferences.entries[p.recordKey];
 const existing=links.find(l=>l.recordKey===p.recordKey&&l.system===p.system&&l.companyKey===clean.companyKey);if(existing){refCheck(JSON.stringify(existing)===JSON.stringify(clean),'This record already has a different link; reassignment requires a controlled correction.');return false;}
 refCheck(!links.some(l=>l.system===clean.system&&l.companyKey===clean.companyKey&&l.externalId===clean.externalId&&state.recordReferences.entries[l.recordKey]?.type===entry.type),'External ID is already linked to another record of this type in this company.');links.push(clean);return true;
}
export function integrationSnapshot(state){refCheck(state.recordReferences,'Software references have not been initialized.');const registry=state.recordReferences,identity=(type,id,parentType='',parentId='')=>{const key=referenceKey(type,id,parentType,parentId),e=registry.entries[key];return e?{type,id,reference:e.reference,recordKey:key,integrationKey:registry.namespace+':'+e.reference}:null;};
 return {schema:'farminghub.integration.snapshot',version:1,workspaceNamespace:registry.namespace,workspaceRevision:state.revision,mode:'snapshot-only',connectionStatus:'Not connected',money:{amounts:'Integer minor units unless the field is explicitly a rate or quantity',currency:'ISO codes; CNY is displayed as RMB'},records:referenceRecords(state).map(r=>({...identity(r.type,r.id,r.parentType,r.parentId),parent:r.parentId?identity(r.parentType,r.parentId):null,deleted:!!r.record.deletedAt,externalLinks:registry.links.filter(l=>l.recordKey===r.key).map(({recordKey,...link})=>link),relations:Object.fromEntries([['vendorId','vendors'],['baseId','bases'],['itemId','items'],['orderId','orders']].filter(([field])=>r.record[field]).map(([field,type])=>[field,identity(type,r.record[field])])),data:structuredClone(r.record)}))};
}
