/** Native VMS adapter. CRM records extend the existing supplier identity. */
export const VMS_CRITERIA=[['evalProductQuality','Product quality',20],['evalQualityControl','Quality control',15],['evalReliability','Reliability',12],['evalFinancialStrength','Financial strength',10],['evalProductionVolume','Production volume',8],['evalCredibility','Credibility',8],['evalPricingSupport','Pricing support',8],['evalCommunication','Communication',6],['evalWillingness','Willingness',5],['evalCreditSupport','Credit support',4],['evalMarketExposure','Market exposure',4]];
export const VMS_SAMPLE_STATUSES=['NONE','REQUESTED','RECEIVED','APPROVED','REJECTED'];
export const VMS_INTERACTION_TYPES=['NOTE','CALL','MEETING','VISIT','ONLINE','DOCUMENT'];
export function syncVmsPrimaryContact(v){
 if(!v.crm)return;
 const primary={...(v.crm.contacts?.[0]||{}),name:v.contact||'',phone:v.phone||'',email:v.email||'',wechat:v.wechat||''};
 v.crm.contacts=[primary,...(v.crm.contacts||[]).slice(1)].filter(c=>Object.values(c).some(Boolean));
 // A master-text edit invalidates the old hierarchy selection, not the new text.
 if((v.crm.country||'')!==(v.country||'')){v.crm.countryId='';v.crm.regionId='';v.crm.districtId='';v.crm.region='';}
 if((v.crm.city||'')!==(v.city||'')){v.crm.districtId='';v.crm.regionId='';v.crm.region='';}
 v.crm.city=v.city||'';v.crm.country=v.country||'';
}
export function vmsConfig(state){return {groups:[],classifications:[],countries:[],regions:[],districts:[],currencies:[],stages:['New Lead','Potential','Approved','Active','On Hold','Inactive','Blacklisted'].map((name,i)=>({id:'stage-'+i,name,active:true,countsInSourcing:[1,2,3].includes(i)})),expos:[],products:[],components:[],photoTypes:['Product','Booth','Online'].map((name,i)=>({id:'photo-'+i,name,active:true})),...(state.vms||{})};}
export function vmsEvaluation(scores={}){let sum=0,weight=0,count=0;for(const [k,,w] of VMS_CRITERIA){const n=Number(scores[k]);if(Number.isInteger(n)&&n>=1&&n<=5){sum+=n*w;weight+=w;count++;}}if(!weight)return {score:null,percentage:null,grade:null,status:'Not evaluated',count:0};const score=Math.round(sum/weight*100)/100;const [grade,status]=score>=4.5?['A+','Preferred Supplier']:score>=4?['A','Approved']:score>=3.5?['B','Approved with Monitoring']:score>=3?['C','Conditional Approval']:['D','Not Approved'];return {score,percentage:Math.round(score/5*1000)/10,grade,status,count};}
export function vmsBusinessDay(now=new Date().toISOString()){
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(now));
 const value=type=>parts.find(p=>p.type===type).value;return value('year')+'-'+value('month')+'-'+value('day');
}
export function vmsInteractionDates(payload,now=new Date().toISOString()){
 const valid=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;
 const occurredAt=payload.occurredAt,nextFollowUpAt=payload.nextFollowUpAt??'';
 if(!valid(occurredAt))throw Error('Enter a valid interaction date.');
 if(occurredAt>vmsBusinessDay(now))throw Error('Interaction date cannot be in the future.');
 if(typeof nextFollowUpAt!=='string'||nextFollowUpAt&&!valid(nextFollowUpAt))throw Error('Enter a valid next follow-up date.');
 if(nextFollowUpAt&&nextFollowUpAt<occurredAt)throw Error('Follow-up cannot precede the interaction.');
 return {occurredAt,nextFollowUpAt};
}
export function vmsFollowups(vendors,today){
 const rank=['Overdue','Today','Upcoming','Completed'];
 return vendors.flatMap(v=>(v.crm?.interactions||[]).filter(i=>i.nextFollowUpAt&&!i.voidedAt).map(i=>({vendor:v,interaction:i,status:i.completedAt?'Completed':i.nextFollowUpAt<today?'Overdue':i.nextFollowUpAt===today?'Today':'Upcoming'})))
 .sort((a,b)=>rank.indexOf(a.status)-rank.indexOf(b.status)||a.interaction.nextFollowUpAt.localeCompare(b.interaction.nextFollowUpAt)||a.vendor.code.localeCompare(b.vendor.code)||a.interaction.id.localeCompare(b.interaction.id));
}
export function vmsInteractionHistory(interactions=[]){return interactions.filter(i=>!i.voidedAt).slice().sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)||b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));}
export function vmsConcentration(vendors,config,kind='products'){return config[kind].map(tag=>{const all=vendors.filter(v=>(v.crm?.[kind]||[]).includes(tag.id)&&(kind!=='components'||!v.crm?.stageId||config.stages?.some(s=>s.id===v.crm.stageId&&s.countsInSourcing))),active=all.filter(v=>v.status==='ACTIVE'),n=all.length;return {id:tag.id,name:tag.name,total:n,active:active.length,preferred:all.filter(v=>vmsEvaluation(v.crm?.scores).grade==='A+').length,risk:kind==='components'?(n<=1?'HIGH':n===2?'MEDIUM':'LOW'):(!n||!active.length||n===1?'CRITICAL':n===2?'HIGH':n===3?'MEDIUM':'LOW'),equalShare:n?Math.round(100/n):100};});}
export function applyVmsCommand(state,type,p,ctx,{ensure,scopeAllowed,canApprove,canCreate,toMinor,event}){
 const {user,now,id}=ctx;ensure(scopeAllowed(user,'LAE_IMPORT'),'VMS is outside your assigned division.','FORBIDDEN');
 const manager=canApprove(user),writer=canCreate(user);const cfg=structuredClone(vmsConfig(state));
 const str=(v,max=2000)=>{ensure(v==null||typeof v==='string','Expected text.');const s=String(v??'').trim();ensure(s.length<=max,'Text is too long.');return s;};
 const date=(v,label,required=false)=>{const s=str(v,10);ensure((!required&&!s)||(/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s),'Enter a valid '+label+'.');return s;};
 const refs=(values,kind)=>{ensure(Array.isArray(values)&&values.length<=100,'Invalid selection.');const ids=[...new Set(values)];ensure(ids.every(x=>cfg[kind].some(t=>t.id===x)),'Unknown '+kind+' selection.');return ids;};
 if(type==='VMS_SAVE_CATALOG'){
  ensure(manager,'Purchase Manager access required.','FORBIDDEN');ensure(['stages','expos','products','groups','classifications','components','photoTypes','countries','regions','districts','currencies'].includes(p.kind),'Invalid VMS catalogue.');const rows=cfg[p.kind];let row=rows.find(x=>x.id===p.id);ensure(!p.id||row,'Catalogue entry not found.');const old=row?structuredClone(row):null;const name=str(p.name,160);ensure(name,'Name is required.');const edition=str(p.edition,60),year=str(p.year,4);if(p.kind==='expos')ensure(!year||/^\d{4}$/.test(year),'Enter a four-digit expo year.');ensure(!rows.some(x=>x.id!==p.id&&x.name.toLowerCase()===name.toLowerCase()&&(!['regions','districts'].includes(p.kind)||x.parentId===p.parentId)&&(p.kind!=='expos'||(x.edition===edition&&x.year===year))),'This catalogue entry already exists.');const update={name,active:p.active!==false};
  if(p.kind==='products'){update.groupId=str(p.groupId,120);ensure(!update.groupId||cfg.groups.some(g=>g.id===update.groupId),'Choose a valid product group.');update.description=str(p.description);}
  if(['regions','districts'].includes(p.kind)){update.parentId=str(p.parentId,120);ensure(cfg[p.kind==='regions'?'countries':'regions'].some(x=>x.id===update.parentId),'Select a valid parent location.');}
  if(p.kind==='currencies'){update.code=str(p.code,3);ensure(['USD','CNY','INR'].includes(update.code),'Choose USD, RMB or INR.');ensure(!rows.some(x=>x.id!==p.id&&x.code===update.code),'Currency reference already exists.');const rate=str(p.inrPerUnit,24);ensure(/^\d+(?:\.\d{1,6})?$/.test(rate)&&Number(rate)>0&&Number(rate)<=1000000,'Enter a positive reference rate with at most six decimals.');ensure(update.code!=='INR'||Number(rate)===1,'INR reference must be 1.');update.inrPerUnit=rate;update.rateDate=date(p.rateDate,'reference rate date',true);}
if(p.kind==='stages')update.countsInSourcing=p.countsInSourcing===true;if(p.kind==='expos'){Object.assign(update,{edition,year,city:str(p.city,100),country:str(p.country,100),startDate:date(p.startDate,'start date'),endDate:date(p.endDate,'end date'),notes:str(p.notes)});ensure(!update.startDate||!update.endDate||update.startDate<=update.endDate,'Expo end date precedes start date.');}if(row)Object.assign(row,update);else{row={id:id(),...update};rows.push(row);}state.vms=cfg;event('settings','vms','VMS_CATALOG_SAVED','VMS catalogue saved; linked records retained.',old,{kind:p.kind,...row});return {id:row.id};
 }
 const v=state.vendors.find(x=>x.id===p.vendorId);ensure(v&&v.scopes?.some(s=>scopeAllowed(user,s))&&v.scopes.includes('LAE_IMPORT'),'Vendor unavailable.','FORBIDDEN');
 if(type==='VMS_SYNC_EDIT'){
  ensure(['VMS_SAVE_PROFILE','VMS_ADD_INTERACTION'].includes(p.commandType),'This action must be completed online.');
  ensure(p.commandType==='VMS_SAVE_PROFILE'?manager:writer,'Purchase access required.','FORBIDDEN');
  ensure(typeof p.requestId==='string'&&/^[a-zA-Z0-9-]{16,80}$/.test(p.requestId),'Invalid sync request.');
  ensure(p.payload&&typeof p.payload==='object'&&!Array.isArray(p.payload),'Invalid queued edit.');
  const receiptKey=user.id+':'+p.requestId,receipt=v.crm?.syncReceipts?.[receiptKey];
  const signature=JSON.stringify({commandType:p.commandType,base:p.base,payload:p.payload});ensure(signature.length<=100000,'Queued edit is too large.');
  if(receipt){ensure(receipt.signature===signature,'Sync request ID already used with different content.','CONFLICT');return {id:v.id,alreadySynced:true};}
  const payload={...p.payload,vendorId:v.id};
  if(p.commandType==='VMS_SAVE_PROFILE'){
   const current=vmsProfileSnapshot(v);ensure(p.base&&Object.keys(current).every(k=>Object.hasOwn(p.base,k)),'Original profile is required for conflict checking.');
   for(const k of Object.keys(current)){const proposed=payload[k]??current[k],base=p.base[k];if(JSON.stringify(proposed)===JSON.stringify(base)){payload[k]=current[k];continue;}ensure(JSON.stringify(current[k])===JSON.stringify(base)||JSON.stringify(current[k])===JSON.stringify(proposed),'Another user changed '+k+'. Review this edit in Pending Sync.','CONFLICT');}
  }else ensure(!(payload.fileIds||[]).length,'Upload attachments online before adding evidence.');
  const result=applyVmsCommand(state,p.commandType,payload,ctx,{ensure,scopeAllowed,canApprove,canCreate,toMinor,event});
  v.crm.syncReceipts={...(v.crm.syncReceipts||{}),[receiptKey]:{signature,at:now}};
  return result;
 }
 const previous=structuredClone(v.crm||{}),primaryBefore=Object.fromEntries(['contact','email','phone','wechat','city','country'].map(k=>[k,v[k]??''])),crm=v.crm||{};const files=()=>{ensure(Array.isArray(p.fileIds||[])&&(p.fileIds||[]).length<=20,'Select at most 20 attachments.');return [...new Set(p.fileIds||[])].map(fid=>{const f=state.files.find(x=>x.id===fid);ensure(f&&v.scopes.includes(f.scope)&&scopeAllowed(user,f.scope)&&f.orderIds.length===0,'Attachment is unavailable or belongs to an order.');return fid;});};
 if(type==='VMS_SAVE_PROFILE'){
  ensure(manager,'Purchase Manager access required to edit vendor profiles.','FORBIDDEN');const stageId=str(p.stageId,120),expoId=str(p.expoId,120),assignedToId=str(p.assignedToId,120);ensure(!stageId||cfg.stages.some(x=>x.id===stageId),'Select a valid sourcing stage.');ensure(!expoId||cfg.expos.some(x=>x.id===expoId),'Select a valid expo.');ensure(!assignedToId||state.users.some(u=>u.id===assignedToId&&u.active!==false&&['ADMIN','MANAGER','EXECUTIVE'].includes(u.role)&&scopeAllowed(u,'LAE_IMPORT')),'Choose an active Purchase owner.');ensure(Array.isArray(p.contacts)&&p.contacts.length<=20,'Use at most 20 contacts.');const contacts=p.contacts.map(c=>({name:str(c.name,120),designation:str(c.designation,100),phone:str(c.phone,80),email:str(c.email,254),wechat:str(c.wechat,100)}));ensure(contacts.every(c=>c.name),'Every contact needs a name.');ensure(contacts.every(c=>!c.email||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.email)),'Enter valid contact email addresses.');const annualVolume=str(p.annualVolume,20);ensure(!annualVolume||(/^\d+$/.test(annualVolume)&&Number.isSafeInteger(Number(annualVolume))),'Annual production volume must be a non-negative whole number.');const website=str(p.website,500);ensure(!website||/^https?:\/\//i.test(website),'Website must start with https:// or http://.');const classificationId=str(p.classificationId,120);ensure(!classificationId||cfg.classifications.some(x=>x.id===classificationId),'Choose a valid product classification.');
  let countryId=str(p.countryId,120),regionId=str(p.regionId,120),districtId=str(p.districtId,120),regionText=str(p.region,100);
  ensure(!countryId||cfg.countries.some(x=>x.id===countryId),'Choose a valid country.');ensure(!regionId||cfg.regions.some(x=>x.id===regionId&&x.parentId===countryId),'Region does not belong to the selected country.');ensure(!districtId||cfg.districts.some(x=>x.id===districtId&&x.parentId===regionId),'District does not belong to the selected region.');
  // Reconcile already-stale hierarchy links only when that saved location was not edited.
  if(countryId&&countryId===crm.countryId&&p.country===crm.country&&crm.country===v.country&&crm.country!==cfg.countries.find(x=>x.id===countryId).name){countryId='';regionId='';districtId='';regionText='';}
  if(districtId&&districtId===crm.districtId&&p.city===crm.city&&crm.city===v.city&&crm.city!==cfg.districts.find(x=>x.id===districtId).name){regionId='';districtId='';regionText='';}
  Object.assign(crm,{classificationId,countryId,regionId,districtId,stageId,expoId,assignedToId,contacts,website,city:str(p.city,100),region:regionText,country:str(p.country,100),annualVolume,remarks:str(p.remarks,5000),products:refs(p.products||[],'products'),components:refs(p.components||[],'components')});
 }else if(type==='VMS_SAVE_EVALUATION'){
  ensure(manager,'Purchase Manager access required for evaluation.','FORBIDDEN');ensure(p.scores&&typeof p.scores==='object'&&!Array.isArray(p.scores),'Enter evaluation scores.');const scores={};for(const [k] of VMS_CRITERIA){const val=p.scores[k];if(val!==''&&val!=null){const n=Number(val);ensure(Number.isInteger(n)&&n>=1&&n<=5,'Each rating must be a whole number from 1 to 5.');scores[k]=n;}}crm.scores=scores;crm.evaluation=vmsEvaluation(scores);crm.evaluationRemarks=str(p.remarks,5000);crm.evaluatedAt=now;crm.evaluatedBy=user.name;
 }else if(type==='VMS_ADD_INTERACTION'){
  ensure(writer,'Purchase access required.','FORBIDDEN');ensure(VMS_INTERACTION_TYPES.includes(p.type),'Select an interaction type.');const fileIds=files(),notes=str(p.notes,10000);ensure(notes||fileIds.length,'Enter notes or attach evidence.');let dates;try{dates=vmsInteractionDates(p,now);}catch(e){ensure(false,e.message);}const {occurredAt,nextFollowUpAt}=dates;crm.interactions=crm.interactions||[];crm.interactions.push({id:id(),type:p.type,title:str(p.title,200),notes,occurredAt,nextFollowUpAt,fileIds,createdAt:now,createdBy:user.name,createdById:user.id,completedAt:null});
 }else if(type==='VMS_UPDATE_FOLLOWUP'){
  ensure(writer,'Purchase access required.','FORBIDDEN');const i=crm.interactions?.find(x=>x.id===p.interactionId);ensure(i&&!i.voidedAt,'Interaction unavailable.');ensure(manager||i.createdById===user.id||crm.assignedToId===user.id,'Only the owner or Purchase Manager can update this follow-up.','FORBIDDEN');ensure(str(p.remarks),'Explain the follow-up update.');const next=date(p.nextFollowUpAt,'next follow-up date',true);ensure(next>=i.occurredAt,'Follow-up cannot precede the interaction.');i.nextFollowUpAt=next;i.completedAt=p.completed===true?now:null;i.completionRemarks=str(p.remarks);i.updatedBy=user.name;
 }else if(type==='VMS_SAVE_SAMPLE'){
  ensure(manager,'Purchase Manager access required for samples.','FORBIDDEN');crm.samples=crm.samples||[];let sample=crm.samples.find(x=>x.id===p.id);ensure(!p.id||sample,'Sample not found.');const name=str(p.name,200);ensure(name,'Component / sample name is required.');ensure(VMS_SAMPLE_STATUSES.includes(p.status),'Select a sample status.');ensure(['USD','CNY','INR'].includes(p.currency),'Select a sample currency.');const priceMinor=p.price===''||p.price==null?null:toMinor(p.price);ensure(priceMinor===null||(Number.isSafeInteger(priceMinor)&&priceMinor>=0&&priceMinor<=1e12),'Invalid sample price.');const update={name,status:p.status,currency:p.currency,priceMinor,priceRemarks:str(p.priceRemarks),qualityRemarks:str(p.qualityRemarks),updatedAt:now,updatedBy:user.name};if(sample)Object.assign(sample,update);else{sample={id:id(),...update};crm.samples.push(sample);}
 }else if(type==='VMS_ADD_DOCUMENT'){
  ensure(writer,'Purchase access required.','FORBIDDEN');const fileIds=files();ensure(fileIds.length,'Choose at least one file.');const typeId=str(p.typeId,120);ensure(!typeId||cfg.photoTypes.some(t=>t.id===typeId),'Choose a valid photo type.');crm.documents=crm.documents||[];crm.documents.push({id:id(),fileIds,typeId,caption:str(p.caption,1000),at:now,by:user.name});
 }else{ensure(false,'Unsupported VMS command.');}
 if(type==='VMS_SAVE_PROFILE'){if(crm.countryId)crm.country=cfg.countries.find(x=>x.id===crm.countryId).name;if(crm.regionId)crm.region=cfg.regions.find(x=>x.id===crm.regionId).name;if(crm.districtId)crm.city=cfg.districts.find(x=>x.id===crm.districtId).name;}
 crm.updatedAt=now;crm.updatedBy=user.name;v.crm=crm;
 if(type==='VMS_SAVE_PROFILE'){const primary=crm.contacts[0]||{};v.contact=primary.name||'';v.email=primary.email||'';v.phone=primary.phone||'';v.wechat=primary.wechat||'';v.city=crm.city;v.country=crm.country;v.updatedAt=now;}
 // Keep audit changes focused: do not copy every previous interaction/file on each append.
 const keys=type==='VMS_SAVE_PROFILE'?['classificationId','countryId','regionId','districtId','stageId','expoId','assignedToId','contacts','website','city','region','country','annualVolume','remarks','products','components']:['scores','evaluation','evaluationRemarks','evaluatedAt','evaluatedBy'];
 const pick=value=>Object.fromEntries(keys.map(k=>[k,value[k]??null]));let oldValue=pick(previous),newValue=pick(crm);
 if(type==='VMS_ADD_INTERACTION'){oldValue=null;newValue=crm.interactions.at(-1);}else if(type==='VMS_ADD_DOCUMENT'){oldValue=null;newValue=crm.documents.at(-1);}else if(type==='VMS_UPDATE_FOLLOWUP'){oldValue=previous.interactions.find(i=>i.id===p.interactionId);newValue=crm.interactions.find(i=>i.id===p.interactionId);}else if(type==='VMS_SAVE_SAMPLE'){oldValue=previous.samples?.find(s=>s.id===p.id)||null;newValue=p.id?crm.samples.find(s=>s.id===p.id):crm.samples.at(-1);}
 if(type==='VMS_SAVE_PROFILE'){oldValue={profile:oldValue,primaryContact:primaryBefore};newValue={profile:newValue,primaryContact:Object.fromEntries(Object.keys(primaryBefore).map(k=>[k,v[k]??'']))};}
 event('vendor',v.id,type,'Vendor CRM updated; purchase identity and approvals unchanged.',oldValue,structuredClone(newValue));return {id:v.id};
}

/** Only editable CRM fields participate in offline conflict detection. */
export function vmsProfileSnapshot(v){const c=v.crm||{};return {stageId:c.stageId||'',expoId:c.expoId||'',assignedToId:c.assignedToId||'',classificationId:c.classificationId||'',countryId:c.countryId||'',regionId:c.regionId||'',districtId:c.districtId||'',contacts:(c.contacts?.length?c.contacts:[{name:v.contact,phone:v.phone,email:v.email,wechat:v.wechat}]).map(contact=>Object.fromEntries(['name','designation','phone','email','wechat'].map(k=>[k,contact[k]||'']))).filter(contact=>Object.values(contact).some(Boolean)),website:c.website||'',city:c.city??v.city??'',region:c.region||'',country:c.country??v.country??'',annualVolume:c.annualVolume||'',remarks:c.remarks||'',products:[...(c.products||[])],components:[...(c.components||[])]};}
export function vmsAnalytics(vendors,cfg){const counts=(kind)=>cfg[kind].map(t=>({...t,count:vendors.filter(v=>kind==='stages'?v.crm?.stageId===t.id:(v.crm?.[kind]||[]).includes(t.id)).length}));return {products:counts('products'),components:counts('components'),stages:counts('stages'),vendors:vendors.map(v=>({id:v.id,name:v.name,code:v.code,products:(v.crm?.products||[]).length,components:(v.crm?.components||[]).length})).sort((a,b)=>b.products-a.products||a.name.localeCompare(b.name))};}
