import {createNavigation,moduleDestination} from '/navigation.mjs';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>Number(v||0).toLocaleString('en-IN');
const paths={menu:'M4 6h16M4 12h16M4 18h16',box:'M3 7l9-4 9 4v11l-9 4-9-4zM3 7l9 4 9-4M12 11v11',clock:'M12 3a9 9 0 1 1 0 18 9 9 0 0 1 0-18M12 7v5l3 2',arrow:'M5 12h14M14 7l5 5-5 5',chevron:'M9 6l6 6-6 6',history:'M3 4v5h5M3 9a9 9 0 1 1 1 9',settings:'M12 3v3M12 18v3M3 12h3M18 12h3M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0'};
const icon=(n,size=20)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="${paths[n]||paths.box}"></path></svg>`;
const option=(v,label,current)=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(label)}</option>`;
const total=p=>Object.values(p||{}).reduce((n,q)=>n+Number(q),0),statuses={DRAFT:'Draft',PENDING:'Awaiting approval',APPROVED:'Approved',RETURNED:'Returned for changes'};
let state,record,draft,csrf='',busy=false,dirty=false,lastHash=location.hash,pendingHash=null,search='',series='',sku='yes',page='list',query=new URLSearchParams(),retryAttempt=null;
document.body.classList.add('bom-app','planning-app');
async function api(path,input){const res=await fetch('/api/planning/'+path,{method:input?'POST':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:input?JSON.stringify(input):undefined,cache:'no-store'});if(res.status===401){location.replace('/#/home');throw Error('Sign in to Farming Hub.');}const data=await res.json();if(!res.ok)throw Error(data.error||'Could not load monthly plans.');return data;}
const head=(title,sub,tools='')=>`<div class="page-head"><div><div class="eyebrow">Implements · Monthly planning</div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="actions">${tools}</div></div>`;
const button=(label,action,attrs='')=>`<button type="button" class="button ghost" data-action="${action}" ${attrs}>${esc(label)}</button>`;
function navigation(){return createNavigation({icon,esc,head,button,logo:'/assets/farming-hub-logo.png',context:()=>({user:state.user,ui:{view:'monthly-planning',orderId:['new','entry','edit'].includes(page)?'entry':'plans'}}),planningSections:[['plans','My plans / approvals','clock'],['entry','New monthly plan','box']]});}
function shell(body){const nav=navigation();$('#app').innerHTML=`<div class="shell">${nav.sidebar().replace('</aside>', '<button type="button" class="icon-button drawer-close" data-action="mobile" aria-label="Close navigation">×</button></aside>')}<div class="workspace module-shell"><header class="topbar"><button type="button" class="icon-button mobile-toggle" data-action="mobile" aria-label="Open navigation" aria-expanded="false">${icon('menu')}</button>${nav.breadcrumb('Monthly plans')}<div class="top-tools"><span class="technical-tag">PLAN ENTRY · NO COSTS</span><div class="account"><span class="small strong">${esc(state.user.name)}</span><small>${esc(state.user.role==='PLAN_OPERATOR'?'Monthly Planner':state.user.role)}</small><button class="button ghost" type="button" data-action="logout">Sign out</button></div></div></header><main class="content" id="main">${body}</main></div></div>`;if(matchMedia('(max-width:760px)').matches)$('.sidebar').inert=true;}
function table(headers,rows,label){return `<div class="table-wrap" role="region" tabindex="0" aria-label="${esc(label)}"><table class="plan-table"><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;}
function card(label,status){return `<a class="stat-card" href="#/plans?status=${status}"><span>${label} →</span><strong>${fmt(state.counts[status])}</strong><small>Open matching plans</small></a>`;}
function register(){const month=query.get('month')||'',status=query.get('status')||'';return head(state.canApprove?'Monthly plans & approvals':'Your monthly plans','Only approved plans enter purchasing and MRP.',state.canSubmit?`<a class="button primary" href="#/new?month=${state.month}">New monthly plan</a>`:'')+`<div class="stats">${card('Drafts','DRAFT')}${card('Awaiting approval','PENDING')}${card('Approved','APPROVED')}${card('Returned','RETURNED')}</div><section class="panel"><div class="filter-panel"><label>Month<input id="filter-month" type="month" value="${esc(month)}"></label><label>Status<select id="filter-status">${option('','All statuses',status)}${Object.entries(statuses).map(([v,l])=>option(v,l,status)).join('')}</select></label><a class="button ghost" href="#/plans">Reset filters</a>${button('Refresh','refresh')}</div>${state.requests.length?table(['Month / plan','Submitted by','Machines','Status','Last update','Action'],state.requests.map(r=>`<tr><td><strong>${r.month}</strong><small>${esc(r.id.slice(0,8))} · version ${r.version}</small></td><td>${esc(r.owner.name)}</td><td class="num">${fmt(total(r.plan))}</td><td class="plan-status">${statuses[r.status]}</td><td>${esc(new Date(r.updatedAt).toLocaleString('en-IN',{timeZone:'Asia/Calcutta'}))}</td><td><a class="button ghost" href="#/request?id=${r.id}">${r.status==='PENDING'&&state.canApprove?'Review & approve':'View plan'}</a></td></tr>`).join(''),'Monthly plan requests'):'<div class="empty"><h2>No plans in this view</h2><p>Create a plan or reset the filters.</p></div>'}<div class="panel-body actions">${state.total} plans ${query.get('before')?'<a class="button ghost" href="#/plans">First page</a>':''}${state.next?`<a class="button ghost" href="#/plans?month=${month}&status=${status}&before=${state.next}">Next page</a>`:''}</div></section><section class="panel plan-form"><h2>Approved quantities · ${state.month}</h2><p>${fmt(total(state.approvedPlan))} machines currently planned. New plans start with these quantities, including models hidden by filters. Approval replaces this month’s quantities with the reviewed totals.</p>${state.canApprove?`<a class="button ghost" href="/implements/#/plan?month=${state.month}">Open purchasing monthly planner</a>`:''}</section>`;}
function filters(){return `<div class="filter-panel plan-filter"><label>Find a model<input id="entry-search" type="search" value="${esc(search)}" placeholder="Model code, series or size"></label><label>Series<select id="entry-series">${option('','All series',series)}${[...new Set(state.models.map(m=>m.series))].sort().map(v=>option(v,v,series)).join('')}</select></label><label>SKU finalisation<select id="entry-sku">${option('','All models',sku)}${option('yes','Yes',sku)}${option('no','Not finalised',sku)}</select></label></div>`;}
function modelRows(){const matches=state.models.filter(m=>(!series||m.series===series)&&(!sku||(sku==='yes')===m.salesConfirmed)&&(!search||[m.id,m.configuration,m.series,m.size].join(' ').toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true}));let group='';const rows=matches.map(m=>{const heading=group!==m.series?`<tr class="plan-group"><th colspan="4" scope="rowgroup">${esc(m.series)}</th></tr>`:'';group=m.series;return heading+`<tr><td><strong>${esc(m.id)} · ${esc(m.series)}</strong><small>${esc(m.configuration)}</small></td><td>${m.salesConfirmed?'Yes':'Not finalised'}</td><td class="num">${fmt(state.approvedPlan[m.id])}</td><td class="num"><input type="number" data-model="${esc(m.id)}" aria-label="Machines planned for ${esc(m.id)}" min="0" max="100000" step="1" value="${esc(draft.plan[m.id]??0)}" required></td></tr>`;}).join('');const hidden=Object.keys(draft.plan).filter(id=>!matches.some(m=>m.id===id)).length;return `<p>${matches.length} models shown · ${hidden} planned models hidden by filters. Hidden quantities are retained.</p>`+table(['Model / specification','SKU finalisation','Approved machines','Proposed machines'],rows||'<tr><td colspan="4">No models match these filters.</td></tr>','Monthly plan quantities');}
function editor(){return head(record?.status==='RETURNED'?'Revise returned plan':'Enter monthly plan',`${draft.month} · Save a draft, then submit to Purchase Manager or Admin.`)+`<div class="plan-summary"><span><strong id="machine-total">${fmt(total(draft.plan))}</strong> machines</span><span id="model-total">${Object.keys(draft.plan).length} models</span><a class="button ghost" href="#/plans?month=${draft.month}">Back to monthly plans</a></div><section class="panel plan-form">${filters()}<form id="plan-editor"><div id="model-rows">${modelRows()}</div><label>Planning note / reason<textarea name="note" required maxlength="1200">${esc(draft.note||'')}</textarea></label><div class="actions"><button class="button ghost" type="submit" value="SAVE_DRAFT">Save draft</button><button class="button primary" type="submit" value="SUBMIT">Submit for approval</button></div><p class="form-error" role="alert" tabindex="-1"></p></form></section>`;}
function details(){const rows=Object.keys({...record.baselinePlan,...record.plan}).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(id=>{const m=state.models.find(m=>m.id===id);return `<tr><td><strong>${esc(id)} · ${esc(m?.series||'Model unavailable')}</strong><small>${esc(m?.configuration)}</small></td><td class="num">${fmt(record.baselinePlan[id])}</td><td class="num">${fmt(record.plan[id])}</td><td class="num">${fmt((record.plan[id]||0)-(record.baselinePlan[id]||0))}</td></tr>`;}).join('');const editable=record.owner.id===state.user.id&&['DRAFT','RETURNED'].includes(record.status);return head(record.month+' · '+statuses[record.status],`Submitted by ${record.owner.name} · ${fmt(total(record.plan))} machines`,`<a class="button ghost" href="#/plans">All plans</a>${editable?`<a class="button primary" href="#/edit?id=${record.id}">Edit plan</a>`:''}`)+`<section class="panel plan-form"><h2>Review model-wise quantities</h2><p>${esc(record.note)}</p>${record.status==='PENDING'?'<p class="notice">Approval replaces the selected month’s machine quantities. Pending plans do not affect material demand or stock.</p>':''}${table(['Model','At submission','Proposed / approved','Change'],rows,'Plan comparison')}${record.status==='PENDING'&&state.canApprove?'<form id="plan-approval"><label>Approval / return note<textarea name="note" required maxlength="1200"></textarea></label><div class="actions"><button class="button ghost" type="submit" value="RETURN">Return for changes</button><button class="button primary" type="submit" value="APPROVE">Approve monthly plan</button></div><p class="form-error" role="alert" tabindex="-1"></p></form>':''}${record.status==='APPROVED'&&state.canApprove?`<a class="button primary" href="/implements/#/plan?month=${record.month}">View approved purchasing plan</a>`:''}</section><section class="panel history-list"><h2>Plan history</h2><ol>${record.history.map(h=>`<li><strong>${esc(h.type.replaceAll('_',' '))}</strong> · ${esc(h.by.name)} · ${esc(new Date(h.at).toLocaleString('en-IN',{timeZone:'Asia/Calcutta'}))}<p>${esc(h.note)}</p></li>`).join('')}</ol></section>`;}
async function route(){const [path='plans',qs='']=location.hash.replace(/^#\/?/,'').split('?');page=path||'plans';query=new URLSearchParams(qs);record=null;draft=null;search='';series='';sku='yes';const month=query.get('month')||'';state=await api('workspace?'+new URLSearchParams({month,status:query.get('status')||'',...(query.get('before')?{before:query.get('before')}:{})}));csrf=state.csrf;
 if(['request','edit'].includes(page)){record=(await api('request?id='+encodeURIComponent(query.get('id')||''))).record;state=await api('workspace?month='+record.month);csrf=state.csrf;}
 if(page==='new'||page==='entry'||page==='edit'){if(!state.canSubmit)throw Error('Your account has view-only access.');if(record&&(record.owner.id!==state.user.id||!['DRAFT','RETURNED'].includes(record.status)))throw Error('This plan cannot be edited.');draft=record?structuredClone(record):{month:state.month,plan:structuredClone(state.approvedPlan),note:'',version:0};shell(editor());}else shell(page==='request'?details():register());lastHash=location.hash;dirty=false;}
async function safeRoute(){try{await route();}catch(e){$('#app').innerHTML=`<main class="shell-error"><h1>Monthly plan entry</h1><p role="alert">${esc(e.message)}</p><a class="button ghost" href="/#/home">Farming Hub home</a><a class="button ghost" href="/planning/">Reload plans</a></main>`;}}
const guard=$('#guard');$('#keep').onclick=()=>{pendingHash=null;guard.close();};$('#discard').onclick=async()=>{dirty=false;draft=null;guard.close();if(pendingHash==='logout'){await signout();}else if(pendingHash?.startsWith('external:'))location.href=pendingHash.slice(9);else{location.hash=pendingHash||'#/plans';if(location.hash===lastHash)safeRoute();}pendingHash=null;};guard.addEventListener('cancel',()=>pendingHash=null);
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',()=>{if(dirty||busy){pendingHash=location.hash;history.replaceState(null,'',lastHash||'#/plans');if(!busy)guard.showModal();return;}safeRoute();});
document.addEventListener('input',e=>{if(e.target.dataset.model){const v=Number(e.target.value);if(e.target.value===''||!Number.isSafeInteger(v)||v<0||v>100000){draft.plan[e.target.dataset.model]=e.target.value;dirty=true;return;}if(v)draft.plan[e.target.dataset.model]=v;else delete draft.plan[e.target.dataset.model];dirty=true;$('#machine-total').textContent=fmt(total(draft.plan));$('#model-total').textContent=Object.keys(draft.plan).length+' models';}else if(e.target.closest('#plan-editor')){draft.note=e.target.value;dirty=true;}else if(e.target.closest('#plan-approval'))dirty=true;if(e.target.id==='entry-search'){search=e.target.value;$('#model-rows').innerHTML=modelRows();}});
document.addEventListener('change',e=>{if(e.target.id==='entry-series'||e.target.id==='entry-sku'){if(e.target.id==='entry-series')series=e.target.value;else sku=e.target.value;$('#model-rows').innerHTML=modelRows();}if(['filter-month','filter-status'].includes(e.target.id))location.hash='#/plans?'+new URLSearchParams({month:$('#filter-month').value,status:$('#filter-status').value});if(e.target.id==='module-select')navigate(e.target.value);});
function navigate(to){if(to==='monthly-planning/entry'){location.hash='#/new?month='+state.month;return;}if(to==='monthly-planning/plans'){location.hash='#/plans';return;}const dest=['monthly-planning','implements-purchase','bom-management','production-stock'].includes(to)?moduleDestination(to):'/#/'+to;if(dirty){pendingHash='external:'+dest;guard.showModal();}else location.href=dest;}
document.addEventListener('click',async e=>{const link=e.target.closest('a[href]');if(dirty&&link&&!link.getAttribute('href').startsWith('#')){e.preventDefault();pendingHash='external:'+link.href;guard.showModal();return;}const el=e.target.closest('[data-action]');if(!el)return;try{const a=el.dataset.action;if(a==='nav')navigate(el.dataset.to);if(a==='mobile'){const side=$('.sidebar');const open=!side.classList.contains('open');side.classList.toggle('open',open);side.inert=!open;$('.workspace').inert=open;const toggle=$('[data-action=mobile]');toggle.setAttribute('aria-expanded',String(open));if(open)side.querySelector('.nav-link').focus();else toggle.focus();}if(a==='refresh'){if(dirty)throw Error('Save or discard your entries before refreshing.');await safeRoute();}if(a==='logout'){if(dirty){pendingHash='logout';guard.showModal();return;}await fetch('/api/logout',{method:'POST',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:'{}'});location.href='/#/home';}}catch(error){$('#toast-root').textContent=error.message;}});
document.addEventListener('submit',async e=>{if(!['plan-editor','plan-approval'].includes(e.target.id))return;e.preventDefault();if(busy)return;const form=e.target,error=form.querySelector('.form-error');error.textContent='';const type=e.submitter?.value,values=new FormData(form),input={type,requestId:crypto.randomUUID(),expectedVersion:record?.version||0,note:values.get('note'),...(record?{id:record.id}:{})};if(form.id==='plan-editor')Object.assign(input,{month:draft.month,plan:draft.plan});const fingerprint=JSON.stringify({...input,requestId:undefined});if(retryAttempt?.fingerprint===fingerprint)input.requestId=retryAttempt.id;else retryAttempt={fingerprint,id:input.requestId};busy=true;form.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=true);try{let out;for(let attempt=0;attempt<2;attempt++){try{out=await api('commands',input);break;}catch(err){if(!(err instanceof TypeError)||attempt)throw err;}}retryAttempt=null;dirty=false;busy=false;location.hash='#/request?id='+out.record.id;if(location.hash===lastHash)await safeRoute();$('#toast-root').textContent=type==='APPROVE'?'Monthly plan approved. Purchasing and MRP now use these quantities.':type==='SUBMIT'?'Plan submitted for approval.':type==='RETURN'?'Plan returned to its owner.':'Draft saved.';}catch(err){error.textContent=err.message;error.focus();}finally{busy=false;form.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=false);}});
await safeRoute();

async function signout(){await fetch('/api/logout',{method:'POST',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:'{}'});location.href='/#/home';}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('.sidebar.open')){const side=$('.sidebar');side.classList.remove('open');side.inert=true;$('.workspace').inert=false;$('[data-action=mobile]').focus();}});
