// Conflict recovery never re-renders an open form or submits its values automatically.
export function createSaveRecovery({context,fetchLatest,adopt,esc}){
 let pending=null;
 function clear(){pending=null;document.querySelector('#save-conflict')?.remove();}
 function show(error){if(error.status!==409)return;clear();const box=document.createElement('div');box.id='save-conflict';box.className='note-box warn';box.setAttribute('role','alert');box.innerHTML='<p>Your entries and selected files are still here.</p><button type="button" class="button small" data-action="review-save-conflict">Review latest changes</button>';const anchor=document.querySelector('#modal-error');if(anchor)anchor.after(box);else document.querySelector('main')?.prepend(box);}
 function changes(before,after){const result=[];for(const [key,label,route]of [['orders','Order','order'],['vendors','Supplier','vms'],['items','Item','items'],['bases','Product','product']]){const old=new Map((before[key]||[]).map(x=>[x.id,x]));for(const row of after[key]||[]){const prior=old.get(row.id);if(JSON.stringify(prior)===JSON.stringify(row))continue;const fields=prior?Object.keys(row).filter(k=>!['updatedAt','updatedBy','lastActivityAt'].includes(k)&&JSON.stringify(prior[k])!==JSON.stringify(row[k])):['new record'];const url=route==='items'?'#/items':'#/'+route+'/'+row.id;result.push('<li><b>'+esc(label+' '+(row.number||row.code||row.name||''))+'</b>: '+esc(fields.map(k=>k.replace(/([A-Z])/g,' $1').replace(/_/g,' ')).join(', '))+' <a target="_blank" rel="noopener" href="'+esc(url)+'">View latest saved record</a></li>');old.delete(row.id);}for(const row of old.values())if(!(after[key]||[]).some(x=>x.id===row.id))result.push('<li>'+esc(label+' '+(row.number||row.code||row.name||''))+' was removed.</li>');}for(const key of ['approvalControls','settings','users','priceLists','routes','templates','vms'])if(JSON.stringify(before[key])!==JSON.stringify(after[key]))result.push('<li>'+esc(key.replace(/([A-Z])/g,' $1'))+' changed. Review the relevant page before continuing.</li>');return result.length?'<ul>'+result.join('')+'</ul>':'<p>The saved view was refreshed. Review the latest record in another tab if needed.</p>';}
 async function action(name){if(name==='review-save-conflict'){const box=document.querySelector('#save-conflict'),before=context();if(!box)return true;const latest=await fetchLatest();if(context().user.id!==before.user.id||latest.user.id!==before.user.id)throw Error('The signed-in account changed. Sign in again before saving.');pending=latest;box.innerHTML='<b>Review before retrying</b>'+changes(before.state,latest.state)+'<p>Nothing has been submitted. Your form and selected files are unchanged.</p><label><input type="checkbox" data-review-save> I reviewed the latest changes and want to keep my entries.</label><p><button type="button" class="button small" data-action="continue-save-conflict">Continue editing with my entries</button></p>';return true;}
 if(name==='continue-save-conflict'){if(!pending||!document.querySelector('[data-review-save]')?.checked)throw Error('Review the latest changes and select the confirmation first.');adopt(pending);clear();const error=document.querySelector('#modal-error');if(error){error.textContent='Latest version loaded. Review your entries, then press Save when ready.';error.classList.add('visible');}return true;}return false;}
 return {show,clear,action};
}
