// Conflict recovery never re-renders an open form or submits its values automatically.
export function createSaveRecovery({context,fetchLatest,adopt,esc}){
 let pending=null;
 function clear(){pending=null;document.querySelector('#save-conflict')?.remove();}
 function show(error){if(error.status!==409)return;clear();const box=document.createElement('div');box.id='save-conflict';box.className='note-box warn';box.setAttribute('role','alert');box.innerHTML='<p>Your entries and selected files are still here.</p><button type="button" class="button small" data-action="review-save-conflict">Review latest changes</button>';const anchor=document.querySelector('#modal-error');if(anchor)anchor.after(box);else document.querySelector('main')?.prepend(box);}
 function changes(before,after){const result=[];for(const [key,label,route]of [['orders','Order','order'],['vendors','Supplier','vms'],['items','Item','items'],['bases','Product','product'],['domesticOrders','Domestic PO','domestic/orders'],['domesticBoms','Domestic BOM','domestic'],['domesticItems','Domestic item','domestic/items'],['domesticPriceLists','Domestic quotation','domestic/prices']]){const old=new Map((before[key]||[]).map(x=>[x.id,x]));for(const row of after[key]||[]){const prior=old.get(row.id);if(JSON.stringify(prior)===JSON.stringify(row))continue;const fields=prior?Object.keys(row).filter(k=>!['updatedAt','updatedBy','lastActivityAt'].includes(k)&&JSON.stringify(prior[k])!==JSON.stringify(row[k])):['new record'];const url=key==='domesticOrders'?'#/domestic/po-'+row.id:['items','domestic/items','domestic/prices'].includes(route)?'#/'+route:'#/'+route+'/'+row.id;result.push('<li><b>'+esc(label+' '+(row.number||row.code||row.name||''))+'</b>: '+esc(fields.map(k=>k.replace(/([A-Z])/g,' $1').replace(/_/g,' ')).join(', '))+' <a target="_blank" rel="noopener" href="'+esc(url)+'">View latest saved record</a></li>');old.delete(row.id);}for(const row of old.values())if(!(after[key]||[]).some(x=>x.id===row.id))result.push('<li>'+esc(label+' '+(row.number||row.code||row.name||''))+' was removed.</li>');}for(const key of ['approvalControls','settings','users','priceLists','routes','templates','vms'])if(JSON.stringify(before[key])!==JSON.stringify(after[key]))result.push('<li>'+esc(key.replace(/([A-Z])/g,' $1'))+' changed. Review the relevant page before continuing.</li>');return result.length?'<ul>'+result.join('')+'</ul>':'<p>The saved view was refreshed. Review the latest record in another tab if needed.</p>';}
 async function action(name){if(name==='review-save-conflict'){const box=document.querySelector('#save-conflict'),before=context();if(!box)return true;const latest=await fetchLatest();if(context().user.id!==before.user.id||latest.user.id!==before.user.id)throw Error('The signed-in account changed. Sign in again before saving.');pending=latest;box.innerHTML='<b>Review before retrying</b>'+changes(before.state,latest.state)+'<p>Nothing has been submitted. Your form and selected files are unchanged.</p><label><input type="checkbox" data-review-save> I reviewed the latest changes and want to keep my entries.</label><p><button type="button" class="button small" data-action="continue-save-conflict">Continue editing with my entries</button></p>';return true;}
 if(name==='continue-save-conflict'){if(!pending||!document.querySelector('[data-review-save]')?.checked)throw Error('Review the latest changes and select the confirmation first.');adopt(pending);clear();const error=document.querySelector('#modal-error');if(error){error.textContent='Latest version loaded. Review your entries, then press Save when ready.';error.classList.add('visible');}return true;}return false;}
 return {show,clear,action};
}

// Session recovery keeps the current DOM intact so typed values and File objects survive.
export function createSessionRecovery({context,reauthenticate,applySession,esc}){
 function clear(){document.querySelector('#session-recovery')?.remove();}
 function recoverable(error){return error?.status===401||(error?.status===403&&/session request token/i.test(error.message||''));}
 function show(error){if(!recoverable(error))return false;clear();const actor=context().user,box=document.createElement('div');box.id='session-recovery';box.className='note-box warn';box.setAttribute('role','alert');box.innerHTML='<b>Your sign-in expired</b><p>Your entries and selected files are still here. Sign in again as <b>'+esc(actor.name)+'</b>, then review and press Save.</p><div class="form-grid"><div class="field"><label>Email<input name="reauthEmail" type="email" autocomplete="username" required></label></div><div class="field"><label>Password<input name="reauthPassword" type="password" autocomplete="current-password" required></label></div></div><div class="form-error" data-reauth-error></div><button type="button" class="button small primary" data-action="reauthenticate-session">Sign in again</button>';const anchor=document.querySelector('#modal-error');if(anchor)anchor.after(box);else document.querySelector('main')?.prepend(box);box.querySelector('[name=reauthEmail]')?.focus();return true;}
 async function action(name){if(name!=='reauthenticate-session')return false;const box=document.querySelector('#session-recovery');if(!box)return true;const email=box.querySelector('[name=reauthEmail]'),password=box.querySelector('[name=reauthPassword]'),message=box.querySelector('[data-reauth-error]'),button=box.querySelector('[data-action=reauthenticate-session]');message.classList.remove('visible');if(!email.value.trim()||!password.value){message.textContent='Enter the email and password for '+context().user.name+'.';message.classList.add('visible');return true;}button.disabled=true;try{const expected=context().user,result=await reauthenticate(email.value,password.value);if(result.user.id!==expected.id)throw Error('Sign in as '+expected.name+' to continue this form.');applySession(result);password.value='';const requestError=document.querySelector('#modal-error');if(requestError){requestError.textContent='';requestError.classList.remove('visible');}box.innerHTML='<b>Signed in again</b><p>Your entries and selected files are unchanged. Review them, then press Save.</p>';return true;}catch(error){password.value='';message.textContent=error.message||'Sign-in failed.';message.classList.add('visible');password.focus();return true;}finally{if(button.isConnected)button.disabled=false;}}
 return {show,clear,action,recoverable};
}
