import {createDomesticPrices} from './domestic-prices.mjs';
import {latestDomesticPrices} from '../shared/domestic-prices.mjs';
import {DOMESTIC_SCOPE,DOMESTIC_SEGMENTS,DOMESTIC_UOMS,domesticCanEdit,domesticBomTotals,domesticAssemblyLine,DOMESTIC_ASSEMBLY_TYPES,domesticIsAssembly} from '../shared/domestic.mjs';
import {softwareReference} from '../shared/references.mjs';

export function createDomesticUI(host){
 const {context,esc,head,ph,button,badge,note,field,command,showDialog,renderModal,upload,getFile}=host;
 const money=n=>n==null?'Pending':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n/100);
 const value=n=>n==null?'':(n/100).toFixed(2),qty=n=>n==null?'':String(n/1000);
 const allowed=()=>{const {user}=context();return user?.role==='ADMIN'||user?.scopes?.includes(DOMESTIC_SCOPE);};
 const editable=()=>domesticCanEdit(context().user);
 const prices=createDomesticPrices({...host,money,editable});
 const assetSrc=name=>window.FH_DOMESTIC_IMAGES?.[name]||'/assets/domestic-bom/'+name;
 const fileUrls=new Map();let draft=null,pictureFocus=null;
 const items=()=>context().state.domesticItems||[],models=()=>context().state.domesticModels||[],boms=()=>context().state.domesticBoms||[];
 const ref=b=>softwareReference(context().state,'domesticBoms',b.id);
 const bomLabel=b=>b.code||models().find(m=>m.id===b.modelId)?.code||ref(b);
 function picture(item,large=false){
  if(!item.imageAsset&&!item.imageFileId)return '<span class="domestic-picture-empty">'+(item.assemblyId?'View assembly parts':'Picture pending')+'</span>';
  const src=item.imageAsset?assetSrc(item.imageAsset):context().sandbox?(fileUrls.get(item.imageFileId)||''):'/api/files/'+encodeURIComponent(item.imageFileId);
  return '<button type="button" class="domestic-picture '+(large?'large':'')+'" data-action="domestic-picture" data-asset="'+esc(item.imageAsset||'')+'" data-file="'+esc(item.imageFileId||'')+'" data-caption="'+esc(item.description||item.name||item.code)+'" aria-label="View picture '+esc(item.code||item.name)+'"><img '+(src?'src="'+esc(src)+'"':'')+(item.imageFileId?' data-dom-file="'+esc(item.imageFileId)+'"':'')+' alt="'+esc(item.description||item.name)+'" loading="lazy"></button>';
 }
 function hydrate(){if(!context().sandbox)return;for(const img of document.querySelectorAll('[data-dom-file]')){const id=img.dataset.domFile;if(fileUrls.has(id)){img.src=fileUrls.get(id);continue;}getFile(id).then(blob=>{if(blob){if(!fileUrls.has(id))fileUrls.set(id,URL.createObjectURL(blob));if(img.isConnected)img.src=fileUrls.get(id);}}).catch(()=>{});}}
 const headers=()=>'<thead><tr><th>S.No</th><th>segment</th><th>Item Description</th><th>UOM</th><th>Picture</th><th>Rate (before GST)</th></tr></thead>';
 function tabs(){const key=context().ui.orderId||'models';return '<div class="tabs domestic-tabs">'+[['models','Model BOMs'],['sets','Assembly BOMs'],['items','Item Master'],['vendors','Supplier master'],['prices','Price lists']].map(([to,label])=>'<a class="tab '+(key===to?'active':'')+'" href="#/domestic/'+to+'">'+label+'</a>').join('')+'</div>';}
 function totalsPanel(lines,confirmed=false){const t=domesticBomTotals(lines);return '<div class="domestic-total"><div><span>Total BOM · INR before GST</span><strong>'+(!confirmed||t.totalMinor===null?'Incomplete':money(t.totalMinor))+'</strong></div><p>'+(!confirmed?'Confirm the complete component selection. ': '')+(t.missing.length?t.missing.length+' row(s) need quantities, rates or a completed assembly.':'')+'</p>'+(t.missing.length&&t.knownMinor?'<small>Entered lines subtotal: '+money(t.knownMinor)+'</small>':'')+'</div>';}
 function modelCards(){return '<div class="domestic-models">'+models().map(m=>{const b=boms().find(b=>b.modelId===m.id);return '<article class="panel domestic-model">'+picture(m,true)+'<div class="panel-body"><div class="flex spread"><h2>'+esc(m.code)+'</h2>'+badge(b?.status==='COSTED'?'Costed':'Draft',b?.status==='COSTED'?'green':'amber')+'</div><p>'+esc(m.name)+'</p><div class="domestic-code">'+esc(b?ref(b):'')+'</div><p class="small muted">'+esc(b?.lines.find(l=>l.assemblyId&&(l.assemblyType==='CAN_SET'||!l.assemblyType))?.code||'Can set pending')+' · Model revision '+(b?.revision||1)+'</p><a class="button primary" href="#/domestic/'+esc(m.id)+'">Open BOM</a></div></article>';}).join('')+'</div>'+(models().length?'':note('The milking-machine catalogue has not been loaded in this workspace.'));}
 function setList(){return '<section class="panel">'+ph('Assembly BOMs','Each assembly contains the parts used to build it.',editable()?button('Add assembly BOM','domestic-set',{},'primary','plus'):'')+'<div class="panel-body domestic-models">'+boms().filter(domesticIsAssembly).map(b=>'<article class="domestic-assembly-card"><h2>'+esc(b.code)+'</h2><p>'+esc(b.name)+'</p><p>'+esc(DOMESTIC_ASSEMBLY_TYPES[b.assemblyType||'CAN_SET'])+' · '+b.lines.length+' assembly parts</p><p class="domestic-code">'+esc(ref(b))+' · Revision '+b.revision+'</p><a class="button" href="#/domestic/'+esc(b.id)+'">Open assembly</a></article>').join('')+'</div></section>';}
 function itemTable(){return '<div class="toolbar">'+field('domesticSearch','Find component','','search',{attrs:'id="domestic-search" placeholder="Item code or description"'})+field('domesticSegment','Segment','','select',{attrs:'id="domestic-segment"',options:[{value:'',label:'All segments'},...DOMESTIC_SEGMENTS]})+'<span class="muted">'+items().length+' items</span>'+(editable()?button('Add item','domestic-item',{},'primary','plus'):'')+'</div><div class="table-wrap domestic-table-wrap"><table class="domestic-table" aria-label="Domestic Item Master">'+headers()+'<tbody>'+items().map((i,n)=>'<tr data-domestic-row data-search="'+esc((i.code+' '+i.description+' '+i.segment).toLowerCase())+'" data-segment="'+esc(i.segment)+'"><td>'+(i.source?.row?i.source.row-1:n+1)+'</td><td>'+esc(i.segment)+'</td><td><b>'+esc(i.description)+'</b><div class="domestic-code">'+esc(i.code)+'</div>'+(editable()?button('Edit item','domestic-item',{id:i.id},'small ghost','edit'):'')+'</td><td>'+esc(i.uom)+'</td><td>'+picture(i)+'</td><td class="right">'+money(i.rateMinor)+'</td></tr>').join('')+'</tbody></table><p id="domestic-no-match" class="empty" hidden>No matching items.</p></div>';}
 const lineRate=l=>l.assemblyId?(l.assemblyConfirmed?domesticBomTotals(l.components).totalMinor:null):l.rateMinor;
 function readonlyTable(lines,source=null){return '<div class="table-wrap domestic-table-wrap"><table class="domestic-table" aria-label="BOM components">'+headers()+'<tbody>'+lines.map((l,n)=>'<tr><td>'+(n+1)+'</td><td>'+esc(l.segment)+'</td><td><b>'+esc(l.description)+'</b><div class="domestic-code">'+esc(l.code)+'</div>'+(l.priceSource?'<div class="sub">'+esc(l.priceSource.vendorCode+' · '+l.priceSource.quoteReference+' · '+l.priceSource.quoteDate)+'</div>':'')+(l.assemblyId?'<div class="sub">Assembly revision '+l.assemblyRevision+'</div>'+(source?button('View assembly parts','domestic-parts',{id:source.id,revision:source.revision,index:n},'small ghost','box'):''):'')+'</td><td>'+esc(l.uom)+'<div class="sub">Qty: '+(l.quantityMilli==null?'Pending':qty(l.quantityMilli))+'</div></td><td>'+picture(l)+'</td><td class="right">'+money(lineRate(l))+(domesticBomTotals([l]).totalMinor!=null?'<div class="sub">Line: '+money(domesticBomTotals([l]).totalMinor)+'</div>':'')+'</td></tr>').join('')+'</tbody></table></div>';}
 function bomView(b,model){const stale=b.lines.filter(l=>l.assemblyId&&boms().find(x=>x.id===l.assemblyId)?.revision!==l.assemblyRevision);return '<section class="panel domestic-bom-header"><div>'+(model?picture(model,true):'<h2>'+esc(b.code)+'</h2>')+'</div><div><h2>'+esc(model?.code||b.name)+'</h2><p>'+esc(model?.name||'Assembly parts used to build this component')+'</p><div class="domestic-code">'+esc(ref(b))+'</div><p>Revision '+b.revision+' · '+badge(b.status==='COSTED'?'Costed':'Draft',b.status==='COSTED'?'green':'amber')+'</p><div class="flex wrap">'+(editable()?button('Edit BOM','domestic-bom',{id:b.id},'primary','edit'):'')+button('Revision history','domestic-history',{id:b.id},'','history')+'</div></div></section>'+(stale.length?note('A linked assembly has a newer revision. Edit and save this model BOM to adopt it; the saved cost remains unchanged until then.','warn'):'')+'<div class="gap"></div><section class="panel">'+ph(b.kind==='MODEL'?'Major BOM':'Assembly parts',esc(b.notes||''))+readonlyTable(b.lines,b)+totalsPanel(b.lines,b.compositionConfirmed)+'</section>';}
 function page(){if(!allowed())return note('LAE Domestic access is required.','warn');const key=context().ui.orderId||'models',model=models().find(m=>m.id===key),bom=boms().find(b=>b.id===key||model&&b.modelId===model.id);queueMicrotask(hydrate);return head('LAE Domestic','Milking machines','Items and BOMs · INR before GST')+tabs()+(key==='prices'?prices.page():key==='vendors'?prices.vendorPage():key==='items'?'<section class="panel"><div class="panel-body">'+note('Workbook descriptions, units and pictures retained. Blank rates are pending, not zero.')+'</div>'+itemTable()+'</section>':key==='sets'?setList():bom?bomView(bom,model):modelCards());}
 function quoteChoices(l,n){const choices=latestDomesticPrices(context().state,l.itemId),saved=l.priceSource;return field('quote-'+n,'Supplier price',l.quoteId||saved?.quoteId||'','select',{attrs:'data-domestic-quote="'+n+'"',options:[{value:'',label:'Manual rate'},...choices.map(q=>({value:q.quoteId,label:q.vendorCode+' · '+money(q.rateMinor)+' · '+q.quoteDate})),...(saved&&!choices.some(q=>q.quoteId===saved.quoteId)?[{value:saved.quoteId,label:saved.vendorCode+' · Saved quote '+saved.quoteDate}]:[])]});}
 function syncDraft(){const form=document.getElementById('dialog-form');if(!draft||!form)return;draft.lines.forEach((l,n)=>{l.quantity=form.querySelector('[name="quantity-'+n+'"]')?.value??l.quantity;if(!l.assemblyId)l.rate=form.querySelector('[name="rate-'+n+'"]')?.value??l.rate;l.quoteId=form.querySelector('[name=quote-'+n+']')?.value||'';});draft.reason=form.querySelector('[name=reason]')?.value||'';draft.notes=form.querySelector('[name=notes]')?.value||'';draft.compositionConfirmed=!!form.querySelector('[name=compositionConfirmed]')?.checked;}
 function draftTotals(){if(!draft)return;syncDraft();const lines=draft.lines.map(l=>({...l,quantityMilli:l.quantity===''?null:Math.round(Number(l.quantity)*1000),rateMinor:l.rate===''?null:Math.round(Number(l.rate)*100)})),target=document.getElementById('domestic-bom-total');if(target){try{target.innerHTML=totalsPanel(lines,draft.compositionConfirmed);}catch(e){target.textContent=e.message;}}}
 function modal(t,d){
  if(t.startsWith('domestic-price-')||t==='domestic-vendor')return prices.modal(t,d);
  if(t==='domestic-picture'){const src=d.asset?assetSrc(d.asset):context().sandbox?fileUrls.get(d.file):'/api/files/'+encodeURIComponent(d.file);return {title:'Identification picture',sub:d.caption,body:'<img class="domestic-full-picture" src="'+esc(src||'')+'" alt="'+esc(d.caption)+'">',submit:null,wide:true};}
  if(t==='domestic-set')return {title:'Add assembly BOM',sub:'Parts used to build one major component',submit:'Create assembly',body:field('assemblyType','Assembly type','FRAME','select',{required:true,options:Object.entries(DOMESTIC_ASSEMBLY_TYPES).map(([value,label])=>({value,label}))})+field('code','Assembly code','','text',{hint:'Optional. A permanent BOM code is assigned if left blank.'})+field('name','Assembly name','','text',{required:true})};
  if(t==='domestic-parts'){const b=boms().find(x=>x.id===d.id),version=Number(d.revision)===b.revision?b:b.history.find(h=>h.revision===Number(d.revision)),line=version?.lines[Number(d.index)];if(!line?.assemblyId)return {title:'Assembly unavailable',body:note('Reopen the BOM to view its saved assembly.'),submit:null};return {title:'Assembly parts · '+line.code,sub:line.description+' · Saved revision '+line.assemblyRevision,wide:true,submit:null,body:note('Quantities below are per assembly. Major BOM quantity: '+(qty(line.quantityMilli)||'Pending')+' set(s) per machine.')+readonlyTable(line.components)+totalsPanel(line.components,line.assemblyConfirmed)+button('Open assembly BOM','nav',{to:'domestic/'+line.assemblyId},'primary','edit')};}
  if(t==='domestic-history'){const b=boms().find(x=>x.id===d.id);return {title:'BOM revision history',sub:ref(b),body:b.history.length?b.history.slice().reverse().map(r=>'<details class="domestic-history"><summary>Revision '+r.revision+' · '+esc(r.replacedBy)+' · '+esc(r.replacedAt.slice(0,10))+'</summary><p>'+esc(r.reason)+'</p>'+readonlyTable(r.lines,{id:b.id,revision:r.revision})+totalsPanel(r.lines,r.compositionConfirmed)+'</details>').join(''):note('No previous revisions. The next saved change will retain this version.'),submit:null,wide:true};}
  if(t==='domestic-item'){const i=items().find(x=>x.id===d.id);return {title:i?'Edit Domestic item':'Add Domestic item',sub:i?.code||'Permanent item code assigned when saved',wide:true,submit:'Save item',body:'<div class="form-grid">'+field('segment','segment',i?.segment||'ACCESSORIES','select',{options:DOMESTIC_SEGMENTS,required:true})+field('uom','UOM',i?.uom||'PCS','select',{options:DOMESTIC_UOMS,required:true})+field('description','Item Description',i?.description||'','textarea',{required:true,full:true,attrs:'maxlength="600"'})+field('rate','Rate (before GST) · INR',value(i?.rateMinor),'number',{attrs:'min="0" step="0.01"',hint:'Leave blank until the price is known.'})+field('picture','Identification picture','','file',{attrs:'accept="image/png,image/jpeg,image/webp"',hint:'Existing picture stays unless replaced.'})+(i?field('reason','Reason for change','','textarea',{required:true,full:true}):'')+'</div>'+(i?picture(i):'')};}
  const b=boms().find(x=>x.id===d.id),choices=items().filter(i=>i.active&&!draft.lines.some(l=>l.itemId===i.id)),sets=b.kind==='MODEL'?boms().filter(x=>domesticIsAssembly(x)&&!draft.lines.some(l=>l.assemblyId===x.id)):[];
  queueMicrotask(()=>{hydrate();draftTotals();});
  return {title:'Edit BOM · '+bomLabel(b),sub:ref(b)+' · Revision '+b.revision,wide:true,submit:'Save BOM revision',body:(draft.lines.some(l=>l.assemblyId)?note('This edit uses the latest assembly revisions. Saving retains the previous model BOM and its costs. Assembly cost is calculated from its parts.'):'')+'<div class="toolbar">'+field('component',b.kind==='MODEL'?'Add major component or assembly':'Add assembly part','','select',{attrs:'id="domestic-add-select"',options:[{value:'',label:b.kind==='MODEL'?'Select a major component or assembly':'Select an assembly part'},...sets.map(x=>({value:'set:'+x.id,label:x.code+' · '+x.name})),...choices.map(i=>({value:i.id,label:i.code+' · '+i.description}))]})+button('Add row','domestic-add-row',{},'','plus')+'</div><div class="table-wrap domestic-table-wrap"><table class="domestic-table">'+headers()+'<tbody>'+draft.lines.map((l,n)=>'<tr><td>'+(n+1)+button('Remove','domestic-remove-row',{index:n},'small ghost')+'</td><td>'+esc(l.segment)+'</td><td><b>'+esc(l.description)+'</b><div class="domestic-code">'+esc(l.code)+(l.assemblyId?' · Assembly revision '+l.assemblyRevision:'')+'</div></td><td>'+esc(l.uom)+field('quantity-'+n,'Qty per '+(b.kind==='MODEL'?'machine':'assembly'),l.quantity,'number',{attrs:'data-domestic-number min="'+(['PCS','SET'].includes(l.uom)?'1':'0.001')+'" max="1000000" step="'+(['PCS','SET'].includes(l.uom)?'1':'0.001')+'"'})+'</td><td>'+picture(l)+'</td><td>'+(l.assemblyId?money(lineRate(l)):quoteChoices(l,n)+field('rate-'+n,'INR / '+esc(l.uom),l.rate,'number',{attrs:'data-domestic-number min="0" step="0.01"'}))+'</td></tr>').join('')+'</tbody></table></div><label class="domestic-confirm"><input name="compositionConfirmed" type="checkbox" '+(draft.compositionConfirmed?'checked':'')+'> All required components for this '+(b.kind==='MODEL'?'machine':'assembly')+' are included.</label><div id="domestic-bom-total"></div>'+field('notes','BOM notes',draft.notes,'textarea',{full:true})+field('reason','Reason for this revision',draft.reason,'textarea',{required:true,full:true})};
 }
 async function action(a,d){
  if(!a.startsWith('domestic-'))return false;
  if(await prices.action(a,d))return true;
  // Keep a picture enlargement inside the open edit dialog so unsaved entries survive.
  if(a==='domestic-picture'&&context().ui.modal){const source=d.asset?assetSrc(d.asset):context().sandbox?fileUrls.get(d.file):'/api/files/'+encodeURIComponent(d.file);let viewer=document.getElementById('domestic-inline-picture');if(!viewer){viewer=document.createElement('div');viewer.id='domestic-inline-picture';viewer.className='domestic-picture-overlay';document.querySelector('#modal-root .modal-backdrop').append(viewer);viewer.setAttribute('role','dialog');viewer.setAttribute('aria-label','Identification picture');viewer.setAttribute('aria-modal','true');viewer.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();viewer.querySelector('button').click();}if(e.key==='Tab'){e.preventDefault();e.stopPropagation();viewer.querySelector('button').focus();}});}pictureFocus=document.activeElement;viewer.innerHTML=button('Close picture','domestic-close-picture')+'<img src="'+esc(source||'')+'" alt="'+esc(d.caption)+'">';viewer.querySelector('button').focus();return true;}
  if(a==='domestic-close-picture'){document.getElementById('domestic-inline-picture')?.remove();pictureFocus?.focus();return true;}
  if(a==='domestic-add-row'){syncDraft();const selected=document.getElementById('domestic-add-select').value;if(selected.startsWith('set:')){const b=boms().find(b=>b.id===selected.slice(4));if(b)draft.lines.push({...domesticAssemblyLine(b),quantity:'1',rate:''});}else{const i=items().find(i=>i.id===selected);if(i)draft.lines.push({...i,itemId:i.id,quantity:'',rate:value(i.rateMinor)});}renderModal();return true;}
  if(a==='domestic-remove-row'){syncDraft();draft.lines.splice(Number(d.index),1);renderModal();return true;}
  if(a==='domestic-bom'){const b=boms().find(x=>x.id===d.id);draft={...structuredClone(b),reason:'',lines:b.lines.map(l=>({...l,...(l.assemblyId?domesticAssemblyLine(boms().find(x=>x.id===l.assemblyId)):{}),quantity:qty(l.quantityMilli),rate:value(l.rateMinor)}))};}
  showDialog(a,{...d});queueMicrotask(hydrate);return true;
 }
 async function submit(t,d,form){if(t.startsWith('domestic-price-')||t==='domestic-vendor')return prices.submit(t,d,form);const f=Object.fromEntries(new FormData(form));
  if(t==='domestic-set')return command('DOMESTIC_CREATE_ASSEMBLY',{code:f.code,name:f.name,assemblyType:f.assemblyType},{message:'Assembly BOM created. Add its assembly parts.'});
  if(t==='domestic-item'){const old=items().find(i=>i.id===d.id),file=form.querySelector('[name=picture]').files[0];let imageFileId=old?.imageFileId||null;if(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Use a PNG, JPG or WebP picture.');imageFileId=await upload(file,[],DOMESTIC_SCOPE);}return command('DOMESTIC_SAVE_ITEM',{itemId:old?.id,segment:f.segment,description:f.description,uom:f.uom,rate:f.rate,imageAsset:old?.imageAsset||null,imageFileId,reason:f.reason},{message:'Domestic item saved.'});}
  syncDraft();return command('DOMESTIC_SAVE_BOM',{bomId:d.id,revision:draft.revision,lines:draft.lines.map(l=>({itemId:l.itemId,assemblyId:l.assemblyId,assemblyRevision:l.assemblyRevision,quoteId:l.quoteId,quantity:l.quantity,rate:l.assemblyId?null:l.rate})),notes:draft.notes,reason:draft.reason,compositionConfirmed:draft.compositionConfirmed},{message:'BOM revision saved. Previous version retained.'});
 }
 function change(el){if(context().ui.modal==='domestic-bom'&&el.hasAttribute('data-domestic-quote')){const n=Number(el.dataset.domesticQuote),l=draft.lines[n],q=(context().state.domesticPriceLists||[]).find(q=>q.id===el.value),line=q?.lines.find(i=>i.itemId===l.itemId);if(line){document.querySelector('[name="rate-'+n+'"]').value=value(line.rateMinor);}draftTotals();return true;}if(context().ui.modal==='domestic-bom'&&el.name?.startsWith('rate-')){const n=el.name.slice(5);document.querySelector('[name="quote-'+n+'"]').value='';draftTotals();return true;}if(el.id==='domestic-search'||el.id==='domestic-segment'){const query=document.getElementById('domestic-search')?.value.toLowerCase()||'',segment=document.getElementById('domestic-segment')?.value||'';let count=0;document.querySelectorAll('[data-domestic-row]').forEach(row=>{row.hidden=!(row.dataset.search.includes(query)&&(!segment||row.dataset.segment===segment));if(!row.hidden)count++;});const empty=document.getElementById('domestic-no-match');if(empty)empty.hidden=count>0;return true;}if(el.matches('[data-domestic-number],[name=compositionConfirmed]')&&context().ui.modal==='domestic-bom'){draftTotals();return true;}return false;}
 return {page,modal,action,submit,change,hydrate};
}


