import {latestDomesticPrices} from '../shared/domestic-prices.mjs';
import {domesticBomTotals,domesticIsAssembly} from '../shared/domestic.mjs';

export function createDomesticOrders(host){
 const {context,esc,button,field,note,badge,money,picture,hydrate,showDialog,renderModal,command,navigate}=host;
 let draft=null;
 const state=()=>context().state,orders=()=>state().domesticOrders||[],canIssue=()=>['ADMIN','MANAGER'].includes(context().user?.role),suppliers=()=>state().vendors.filter(v=>v.kind==='SUPPLIER'&&v.status==='ACTIVE'&&v.scopes?.includes('LAE_DOMESTIC'));
 const qty=n=>n==null?'Pending':(n/1000).toLocaleString('en-IN',{maximumFractionDigits:3});
 const status=o=>badge(o.status,o.status==='ISSUED'?'green':o.status==='CANCELLED'?'red':'amber');
 function list(){return '<section class="panel"><div class="panel-body flex spread wrap"><h2>Domestic purchase orders</h2>'+button('Create from assembly BOM','nav',{to:'domestic/sets'},'primary')+'</div>'+note('Create an order from a confirmed assembly BOM. Executives prepare drafts; Managers and Admins approve and issue. GST and freight are stated in the order terms.')+'<div class="table-wrap"><table aria-label="Domestic purchase orders"><thead><tr><th>PO number</th><th>Supplier</th><th>Assembly</th><th>Sets</th><th>Parts subtotal · INR</th><th>Status</th><th></th></tr></thead><tbody>'+orders().slice().reverse().map(o=>'<tr><td>'+esc(o.number)+'</td><td>'+esc(o.vendor.name)+'</td><td>'+esc(o.bom.code)+' · Rev '+o.bom.revision+'</td><td>'+o.assemblyQuantity+'</td><td>'+money(o.totalMinor)+'</td><td>'+status(o)+'</td><td>'+button('Open order','nav',{to:'domestic/po-'+o.id},'small')+'</td></tr>').join('')+'</tbody></table></div>'+(!orders().length?note('No Domestic purchase orders yet. Open an Assembly BOM and choose Create purchase order.'):'')+'</section>';}
 function orderDocument(o){const s=o.issuedSnapshot||o;return '<div class="domestic-po-document"><div class="domestic-po-brand"><img src="'+esc(window.FH_LOGO_URL||'/assets/farming-hub-logo.png')+'" alt="Farming Hub"><p>FARMING HUB PRIVATE LIMITED</p></div><div class="flex spread wrap"><div><h2>Purchase order · '+esc(s.number)+'</h2><p>LAE Domestic · INR</p></div>'+status(o)+'</div>'+(o.status==='DRAFT'?note('DRAFT — NOT ISSUED. Do not send this as an approved order.','warn'):o.status==='CANCELLED'?note('CANCELLED — DO NOT SUPPLY AGAINST THIS ORDER.','warn'):'')+'<div class="form-grid"><div><p class="muted">Supplier</p><b>'+esc(s.vendor.name)+'</b><p>'+esc(s.vendor.code)+'</p>'+(s.vendor.address?'<div class="domestic-po-text">'+esc(s.vendor.address)+'</div>':'')+(s.vendor.gstin?'<p>GSTIN: '+esc(s.vendor.gstin)+'</p>':'')+(s.vendor.pan?'<p>PAN: '+esc(s.vendor.pan)+'</p>':'')+'</div><div><p class="muted">Assembly reference</p><b>'+esc(s.bom.code+' · '+s.bom.name)+'</b><p>'+esc(s.bom.reference)+' · BOM revision '+s.bom.revision+'</p><p>'+s.assemblyQuantity+' assemblies · '+s.lines.length+' / '+s.bom.partCount+' parts included</p></div></div><div class="table-wrap"><table class="domestic-price-comparison" aria-label="Domestic purchase order parts"><thead><tr><th>Picture</th><th>Item code / description</th><th>Per assembly</th><th>Order quantity</th><th>Rate · INR</th><th>Amount · INR</th></tr></thead><tbody>'+s.lines.map(l=>'<tr><td>'+picture(l)+'</td><td><b>'+esc(l.code)+'</b><div>'+esc(l.description)+'</div></td><td>'+qty(l.perAssemblyMilli)+' '+esc(l.uom)+'</td><td>'+qty(l.quantityMilli)+' '+esc(l.uom)+'</td><td>'+money(l.rateMinor)+'</td><td>'+money(domesticBomTotals([l]).totalMinor)+'</td></tr>').join('')+'</tbody></table></div><h2 class="right">Parts subtotal before GST / freight: '+money(s.totalMinor)+'</h2><div class="form-grid">'+[['Required delivery',s.deliveryDate],['Delivery address',s.deliveryAddress],['Payment terms',s.paymentTerms],['GST / tax terms',s.taxTerms],['Freight terms',s.freightTerms],['Remarks',s.notes||'—']].map(([k,v])=>'<div><p class="muted">'+k+'</p><div class="domestic-po-text">'+esc(v)+'</div></div>').join('')+'</div><p class="small muted">Supply only the listed parts and quantities. Item codes and specifications identify the goods; photos are visual references.</p><p class="small">'+(s.issuedAt?'Issued by '+esc(s.issuedBy)+' · '+esc(s.issuedAt.slice(0,10)):'Prepared by '+esc(s.createdBy)+' · '+esc(s.createdAt.slice(0,10)))+'</p>'+(context().sandbox?note('REVIEW BUILD — demonstration document, not a live commercial order.','warn'):'')+'</div>';}
 function detail(id){const o=orders().find(o=>o.id===id);if(!o)return note('Domestic order not found.','warn');queueMicrotask(hydrate);return '<section class="panel"><div class="panel-body"><div class="flex wrap">'+button('All Domestic POs','nav',{to:'domestic/orders'})+(o.status==='DRAFT'&&host.editable()?button('Edit draft','domestic-po-edit',{id:o.id}):'')+(o.status==='DRAFT'&&canIssue()?button('Approve & issue','domestic-po-issue',{id:o.id},'primary'):'')+button('Print / Save PDF','domestic-po-print',{id:o.id})+(o.status!=='CANCELLED'&&canIssue()?button('Cancel order','domestic-po-cancel',{id:o.id},'danger'):'')+'</div>'+orderDocument(o)+'<details><summary>Order history ('+o.history.length+')</summary>'+o.history.slice().reverse().map(h=>'<p class="domestic-history"><b>'+esc(h.action)+'</b> · '+esc(h.actor)+' · '+esc(h.at)+'<br>'+esc(h.reason)+'</p>').join('')+'</details></div></section>';}
 function sync(){if(!draft)return;const form=document.querySelector('#dialog-form');if(!form)return;for(const name of ['vendorId','assemblyQuantity','deliveryDate','deliveryAddress','paymentTerms','taxTerms','freightTerms','notes','reason']){const el=form.elements.namedItem(name);if(el)draft[name]=el.value;}for(const [i,l]of draft.lines.entries()){const checked=form.querySelector('[data-po-part="'+i+'"]'),rate=form.elements.namedItem('po-rate-'+i);if(checked)l.selected=checked.checked;if(rate)l.rate=rate.value;}}
 function selectedTotals(){try{return domesticBomTotals(draft.lines.filter(l=>l.selected).map(l=>({...l,quantityMilli:l.perAssemblyMilli*Number(draft.assemblyQuantity),rateMinor:l.rate===''?null:Math.round(Number(l.rate)*100)}))).totalMinor;}catch{return null;}}
 function rows(){return '<div class="table-wrap"><table class="domestic-price-comparison" aria-label="Select Domestic PO parts"><thead><tr><th>Include</th><th>Picture</th><th>Assembly part</th><th>Order quantity</th><th>Unit rate · INR</th></tr></thead><tbody>'+draft.lines.map((l,i)=>'<tr><td><input type="checkbox" data-po-part="'+i+'" aria-label="Include '+esc(l.code)+'" '+(l.selected?'checked':'')+'></td><td>'+picture(l)+'</td><td><b>'+esc(l.code)+'</b><div>'+esc(l.description)+'</div><div class="sub">Per assembly: '+qty(l.perAssemblyMilli)+' '+esc(l.uom)+'</div></td><td>'+qty(l.perAssemblyMilli*Number(draft.assemblyQuantity))+' '+esc(l.uom)+'</td><td>'+field('po-rate-'+i,'Rate '+l.code,l.rate,'number',{required:l.selected,attrs:'min="0" step="0.01" '+(!l.selected?'disabled':'')})+'<div class="sub">'+esc(l.quoteId?'Supplier quote '+l.quoteLabel:'Manual agreed rate')+'</div></td></tr>').join('')+'</tbody></table></div><div class="domestic-total"><strong>Parts subtotal before GST / freight: <span id="domestic-po-total">'+money(selectedTotals())+'</span></strong></div>';}
 function modal(t,d){const o=orders().find(o=>o.id===d.id);
  if(t==='domestic-po-issue'||t==='domestic-po-cancel')return {title:t==='domestic-po-issue'?'Approve and issue Domestic PO':'Cancel Domestic PO',sub:o?.number,submit:t==='domestic-po-issue'?'Approve & issue':'Cancel order',body:note(t==='domestic-po-issue'?'Issuing freezes this BOM revision, photographs, supplier and prices. Review the order before approving.':'Cancellation preserves the issued document and order history. Notify the supplier separately if it was already sent.','warn')+(t==='domestic-po-issue'?'<label class="domestic-confirm"><input type="checkbox" name="confirm" required> I confirm the vendor, parts, quantities, rates and commercial terms.</label>':'')+field('reason','Reason','','textarea',{required:true,attrs:'maxlength="1500"'})};
  return {title:draft.orderId?'Edit Domestic purchase order':'Create purchase order from BOM',sub:draft.bom.code+' · '+draft.bom.name+' · Saved revision '+draft.bom.revision,wide:true,submit:'Save PO draft',body:note('Choose the parts for this supplier. Quantities come from the saved BOM × assembly count. Saving creates a draft; approval is a separate step.')+'<div class="form-grid">'+field('vendorId','Supplier',draft.vendorId,'select',{required:true,options:[{value:'',label:'Select Domestic supplier'},...suppliers().map(v=>({value:v.id,label:v.code+' · '+v.name}))]})+field('assemblyQuantity','Number of assemblies',draft.assemblyQuantity,'number',{required:true,attrs:'min="1" max="10000" step="1"'})+'</div><div id="domestic-po-rows">'+rows()+'</div><div class="form-grid">'+field('deliveryDate','Required delivery date',draft.deliveryDate,'date',{required:true})+field('deliveryAddress','Delivery address',draft.deliveryAddress,'textarea',{required:true,attrs:'maxlength="1500"'})+field('paymentTerms','Agreed payment terms',draft.paymentTerms,'textarea',{required:true,attrs:'maxlength="1500"'})+field('taxTerms','GST / tax terms',draft.taxTerms,'textarea',{required:true,attrs:'maxlength="1500"',hint:'State the agreed tax treatment. The displayed subtotal excludes GST.'})+field('freightTerms','Freight terms',draft.freightTerms,'textarea',{required:true,attrs:'maxlength="1500"'})+field('notes','Remarks',draft.notes,'textarea',{attrs:'maxlength="3000"'})+field('reason','Reason for this draft / change',draft.reason,'textarea',{required:true,attrs:'maxlength="1500"'})+'</div>'};
 }
 async function printOrder(o){document.querySelector('.print-sheet')?.remove();const sheet=document.createElement('div');sheet.className='print-sheet domestic-po-print';sheet.innerHTML=orderDocument(o);document.body.append(sheet);hydrate();for(const img of sheet.querySelectorAll('img')){img.loading='eager';if(!img.getAttribute('src')&&img.dataset.domFile&&context().sandbox){const blob=await host.getFile(img.dataset.domFile);img.src=URL.createObjectURL(blob);}await Promise.race([img.decode(),new Promise((_,reject)=>setTimeout(()=>reject(Error('An item photo could not load. Reopen the order and retry printing.')),10000))]);}window.print();}
 async function action(a,d){if(!a.startsWith('domestic-po-'))return false;
  const o=orders().find(o=>o.id===d.id);
  if(a==='domestic-po-print'){if(!o)throw Error('Order not found.');await printOrder(o);return true;}
  if(a==='domestic-po-create'||a==='domestic-po-edit'){
   if(!host.editable())throw Error('Purchase editing access is required.');
   const b=state().domesticBoms.find(b=>b.id===(o?.bom.id||d.id));if(!domesticIsAssembly(b)||!b.compositionConfirmed||!b.lines.length||b.lines.some(l=>!l.quantityMilli))throw Error('Save and confirm this assembly with all quantities before creating a purchase order.');
   if(o&&o.status!=='DRAFT')throw Error('Only drafts can be edited.');
   if(o&&o.bom.revision!==b.revision)throw Error('The BOM changed. Cancel this draft and create a new one from the current revision.');
   draft={orderId:o?.id,revision:o?.revision,bom:{id:b.id,code:b.code,name:b.name,revision:b.revision},vendorId:o?.vendorId||'',assemblyQuantity:String(o?.assemblyQuantity||1),deliveryDate:o?.deliveryDate||'',deliveryAddress:o?.deliveryAddress||'',paymentTerms:o?.paymentTerms||'',taxTerms:o?.taxTerms||'',freightTerms:o?.freightTerms||'',notes:o?.notes||'',reason:'',lines:b.lines.map(l=>{const saved=o?.lines.find(x=>x.itemId===l.itemId);return {...l,perAssemblyMilli:l.quantityMilli,selected:o?!!saved:true,rate:saved?(saved.rateMinor/100).toFixed(2):'',quoteId:saved?.quotation?.id||'',quoteLabel:saved?.quotation?.reference||''};})};
  }
  showDialog(a,{...d,revision:o?.revision});queueMicrotask(hydrate);return true;
 }
 function change(el){if(!['domestic-po-create','domestic-po-edit'].includes(context().ui.modal))return false;
  if(el.name==='vendorId'){sync();for(const l of draft.lines){const q=latestDomesticPrices(state(),l.itemId).find(q=>q.vendorId===draft.vendorId&&q.uom===l.uom);l.rate=q?(q.rateMinor/100).toFixed(2):'';l.quoteId=q?.quoteId||'';l.quoteLabel=q?.quoteReference||'';}draft.paymentTerms=suppliers().find(v=>v.id===draft.vendorId)?.paymentTermsText||'';renderModal();queueMicrotask(hydrate);return true;}
  if(el.name==='assemblyQuantity'||el.hasAttribute('data-po-part')){sync();document.getElementById('domestic-po-rows').innerHTML=rows();hydrate();return true;}
  if(el.name?.startsWith('po-rate-')){sync();const l=draft.lines[Number(el.name.slice(8))];if(l){l.quoteId='';l.quoteLabel='';}document.getElementById('domestic-po-total').textContent=money(selectedTotals());return true;}return false;
 }
 async function submit(t,d,form){const f=Object.fromEntries(new FormData(form));let result;
  if(t==='domestic-po-issue'||t==='domestic-po-cancel')result=await command(t==='domestic-po-issue'?'DOMESTIC_PO_ISSUE':'DOMESTIC_PO_CANCEL',{orderId:d.id,revision:d.revision,reason:f.reason,confirm:f.confirm==='on'},{message:t==='domestic-po-issue'?'Domestic PO issued. Print or save its PDF for the supplier.':'Domestic PO cancelled.'});
  else{sync();result=await command('DOMESTIC_PO_SAVE',{...draft,bomId:draft.bom.id,bomRevision:draft.bom.revision,lines:draft.lines.filter(l=>l.selected).map(l=>({itemId:l.itemId,rate:l.rate,quoteId:l.quoteId||null}))},{message:'Domestic PO draft saved. Review before approval.'});}
  if(result?.id)navigate('domestic/po-'+result.id);return result;
 }
 return {list,detail,modal,action,change,submit};
}
