import {DOMESTIC_PRICE_HEADERS,previewDomesticPrices,latestDomesticPrices} from '../shared/domestic-prices.mjs';
import {DOMESTIC_SEGMENTS} from '../shared/domestic.mjs';
export function createDomesticPrices(host){
 const {context,esc,button,note,field,showDialog,command,upload,readSheetWorkbook,download,money}=host;
 let review=null,reading=0,manual=null;
 const suppliers=()=>context().state.vendors.filter(v=>v.status==='ACTIVE'&&v.kind==='SUPPLIER');
 const quotes=()=>context().state.domesticPriceLists||[];
 const items=()=>context().state.domesticItems||[];
 const date=()=>new Date().toISOString().slice(0,10);
 function bomCodes(itemId){return (context().state.domesticBoms||[]).filter(b=>b.lines.some(l=>l.itemId===itemId||l.components?.some(p=>p.itemId===itemId))).map(b=>({label:host.bomLabel(b),reference:host.bomReference(b)}));}
 function identity(i){const codes=bomCodes(i.itemId||i.id);return '<b>'+esc(i.description)+'</b><div class="domestic-code">'+esc(i.code)+'</div><div class="sub">Used in BOM: '+(codes.length?codes.map(c=>'<span title="'+esc(c.reference)+'">'+esc(c.label)+'</span>').join(' · '):'Not assigned')+'</div>';}
 function quoteFields(values={}){return '<div class="form-grid">'+field('vendorId','Supplier',values.vendorId||'','select',{required:true,options:[{value:'',label:'Select supplier'},...suppliers().map(v=>({value:v.id,label:v.code+' · '+v.name}))]})+field('quoteDate','Supplier quote date',values.quoteDate||date(),'date',{required:true,attrs:'max="'+date()+'"'})+field('quoteReference','Supplier quote reference',values.quoteReference||'','text',{required:true})+field('reason','Reason / quote conditions',values.reason||'','textarea',{required:true,hint:'Record the source and any freight, quantity or payment conditions.'})+'</div>';}
 function manualTable(){return '<div class="domestic-picker-filters">'+field('priceSearch','Find item','','search',{attrs:'id="domestic-price-search" placeholder="Item name, item code or BOM code"'})+field('priceSegment','Segment','','select',{attrs:'id="domestic-price-segment"',options:[{value:'',label:'All segments'},...DOMESTIC_SEGMENTS]})+'</div><div class="table-wrap domestic-price-scroll"><table class="domestic-price-entry" aria-label="Manual supplier prices"><thead><tr><th>Picture</th><th>Item / BOM code</th><th>UOM</th><th>INR before GST</th></tr></thead><tbody>'+items().filter(i=>i.active).map(i=>'<tr data-price-item="'+esc(i.id)+'" data-search="'+esc([i.code,i.description,...bomCodes(i.id).flatMap(c=>[c.label,c.reference])].join(' ').toLowerCase())+'" data-segment="'+esc(i.segment)+'"><td>'+host.picture(i)+'</td><td>'+identity(i)+'</td><td>'+esc(i.uom)+'</td><td>'+field('price-'+i.id,'INR / '+i.uom,manual.rates[i.id]??'','number',{attrs:'data-domestic-price-rate="'+esc(i.id)+'" min="0" step="0.01" inputmode="decimal" aria-label="Rate for '+esc(i.code)+' in INR per '+esc(i.uom)+'"'})+'</td></tr>').join('')+'</tbody></table><p id="domestic-price-empty" class="empty" hidden>No matching items.</p></div><p id="domestic-price-count" class="small muted" role="status" aria-live="polite"></p>';}
 function page(){const latest=items().flatMap(i=>latestDomesticPrices(context().state,i.id).map((p,n)=>({...p,item:i,lowest:n===0})));
  return '<section class="panel"><div class="panel-body"><div class="flex spread wrap"><h2>Supplier price lists</h2><div class="flex wrap">'+button('Download template','domestic-price-template',{},'','download')+(host.editable()?button('Upload price list','domestic-price-upload',{},'','upload')+button('Enter prices','domestic-price-manual',{},'primary','edit'):'')+'</div></div>'+note('Type prices or upload a filled template, then review and save. INR before GST. Blank rates are skipped; saved BOM costs stay unchanged.')+'</div><div class="table-wrap"><table class="domestic-price-comparison" aria-label="Supplier price comparison"><thead><tr><th>Picture</th><th>Item / BOM code</th><th>Supplier</th><th>Quote / date</th><th>UOM</th><th>INR before GST</th></tr></thead><tbody>'+latest.map(p=>'<tr><td>'+host.picture(p.item)+'</td><td>'+identity(p.item)+'</td><td>'+esc(p.vendorCode+' · '+p.vendorName)+'</td><td>'+esc(p.quoteReference)+'<div class="sub">'+esc(p.quoteDate)+'</div></td><td>'+esc(p.uom)+'</td><td>'+money(p.rateMinor)+(p.lowest?'<div class="sub">Lowest quoted rate</div>':'')+'</td></tr>').join('')+'</tbody></table></div>'+(!latest.length?note('No supplier prices yet. Choose Enter prices or Download template.'):'')+'<div class="panel-body"><p class="small muted">Latest quote by date for each supplier and item. Earlier-dated quotes remain in history. Freight, GST, minimum quantities and other supplier conditions are excluded from this rate comparison. BOM labels show current saved usage.</p><details><summary>Quotation history ('+quotes().length+')</summary>'+quotes().slice().reverse().map(q=>'<p><b>'+esc(q.vendorCode+' · '+q.quoteReference)+'</b> · '+esc(q.quoteDate)+' · '+q.lines.length+' prices · '+esc(q.createdBy)+' · '+(q.entryMethod==='MANUAL'?'Manual entry':'File upload')+'<br><span class="small muted">'+esc(q.reason)+'</span> '+button('View prices','domestic-price-history',{id:q.id},'small ghost')+'</p>').join('')+'</details></div></section>';
 }
 function vendorPage(){return '<section class="panel"><div class="panel-body"><div class="flex spread"><h2>Supplier master</h2>'+(['ADMIN','MANAGER'].includes(context().user.role)?button('Add supplier','domestic-vendor',{},'primary','plus'):'')+'</div><p class="small muted">Shared supplier master. Existing suppliers in your assigned divisions can also quote Domestic items.</p></div><div class="table-wrap"><table><thead><tr><th>Supplier code</th><th>Name</th><th>Contact</th><th>Payment terms</th></tr></thead><tbody>'+suppliers().map(v=>'<tr><td>'+esc(v.code)+'</td><td>'+esc(v.name)+'</td><td>'+esc([v.contact,v.phone].filter(Boolean).join(' · '))+'</td><td>'+esc(v.paymentTermsText||'Not recorded')+'</td></tr>').join('')+'</tbody></table></div></section>';}
 function reviewTable(rows){return '<div class="table-wrap"><table class="domestic-price-comparison" aria-label="Supplier price review"><thead><tr><th>Row</th><th>Picture</th><th>Item / BOM code</th><th>UOM</th><th>INR before GST</th><th>Result</th></tr></thead><tbody>'+rows.map(r=>{const i=items().find(i=>i.id===r.itemId);return '<tr><td>'+r.row+'</td><td>'+(i?host.picture(i):'—')+'</td><td>'+identity(r)+'</td><td>'+esc(r.uom)+'</td><td>'+money(r.rateMinor)+'</td><td>'+esc(r.errors?.join('; ')||(r.result==='SKIP'?'Blank — skipped':r.rateMinor===0?'Save zero rate':'Ready to save'))+'</td></tr>';}).join('')+'</tbody></table></div>';}
 function modal(t,d){
  queueMicrotask(()=>{host.hydrate();filterManual();});
  if(t==='domestic-vendor')return {title:'Add Domestic supplier',submit:'Save supplier',body:field('code','Supplier code','','text',{required:true})+field('name','Supplier name','','text',{required:true})+field('country','Country','India','text',{required:true})+field('contact','Contact person','','text')+field('phone','Phone','','text')+field('paymentTermsText','Supplier payment terms','','textarea')};
  if(t==='domestic-price-history'){const q=quotes().find(q=>q.id===d.id);return {title:'Supplier quote · '+q.quoteReference,sub:q.vendorName+' · '+q.quoteDate,submit:null,wide:true,body:reviewTable(q.lines.map((l,n)=>({...l,row:n+1})))+note(q.reason)};}
  if(t==='domestic-price-review'){return {title:'Review supplier prices',sub:review.supplierName+' · '+review.quoteReference+' · '+review.quoteDate,wide:true,submit:review.preview.some(r=>r.result==='REJECTED')||!review.preview.some(r=>r.result==='SAVE')?null:'Save supplier prices',body:note(review.preview.filter(r=>r.result==='SAVE').length+' prices to save. '+review.preview.filter(r=>r.result==='SKIP').length+' blank rates skipped. Existing BOM costs are not changed.')+reviewTable(review.preview)+(review.entryMethod==='MANUAL'?button('Back to edit prices','domestic-price-back',{},'','edit'):note('If anything is incorrect, cancel, correct the file and upload again.'))};}
  if(t==='domestic-price-manual')return {title:'Enter supplier prices',sub:'Type INR rates beside the pictured items · before GST',wide:true,submit:'Review prices',body:quoteFields(manual.meta)+note('Leave unquoted items blank. Enter 0 only for a confirmed free item.')+manualTable()+(!suppliers().length?note('A Purchase Manager must add a supplier before saving prices.','warn'):'')};
  return {title:'Upload supplier price list',sub:'INR per item UOM · before GST',wide:true,submit:'Review prices',body:quoteFields()+field('priceFile','Completed template','','file',{required:true,full:true,attrs:'accept=".xlsx,.csv"',hint:'Up to 500 rows. Use values only; formulas are rejected. Maximum 50 MB.'})+(!suppliers().length?note('A Purchase Manager must add a supplier before uploading.','warn'):'')};
 }
 async function priceWorkbook(entries){
  const bytes=window.FH_DOMESTIC_PRICE_TEMPLATE?Uint8Array.from(atob(window.FH_DOMESTIC_PRICE_TEMPLATE),c=>c.charCodeAt(0)):await fetch('/templates/Domestic_Price_List_Template.xlsx').then(r=>{if(!r.ok)throw Error('Template could not be loaded.');return r.arrayBuffer();});
  const zip=await JSZip.loadAsync(bytes),xml=new DOMParser().parseFromString(await zip.file('xl/worksheets/sheet1.xml').async('string'),'application/xml'),ns=xml.documentElement.namespaceURI,rows=xml.getElementsByTagNameNS('*','sheetData')[0],prototype=rows.querySelector('row[r="2"]'),styles=['A','B','C','D'].map(c=>prototype?.querySelector('c[r="'+c+'2"]')?.getAttribute('s')||'0');
  // Keep the authored header and off-table instructions, replace only A:D body cells.
  for(const r of [...rows.children])if(Number(r.getAttribute('r'))>1){for(const c of [...r.children])if(/^[A-D]\d+$/.test(c.getAttribute('r')))c.remove();}
  entries.forEach((i,n)=>{const rn=n+2;let row=rows.querySelector('row[r="'+rn+'"]');if(!row){row=xml.createElementNS(ns,'row');row.setAttribute('r',rn);rows.append(row);}row.setAttribute('ht','44');row.setAttribute('customHeight','1');[i.code,i.description,i.uom,i.rate??''].forEach((v,j)=>{const c=xml.createElementNS(ns,'c');c.setAttribute('r','ABCD'[j]+rn);c.setAttribute('s',styles[j]);c.setAttribute('t','inlineStr');const is=xml.createElementNS(ns,'is'),t=xml.createElementNS(ns,'t');t.textContent=v;is.append(t);c.append(is);row.append(c);});[...row.children].sort((a,b)=>a.getAttribute('r').localeCompare(b.getAttribute('r'))).forEach(c=>row.append(c));});
  xml.getElementsByTagNameNS('*','dimension')[0]?.setAttribute('ref','A1:F'+Math.max(3,entries.length+1));
  // Fixed entry timestamp makes identical manual quotations produce the same retry fingerprint.
  zip.file('xl/worksheets/sheet1.xml',new XMLSerializer().serializeToString(xml),{date:new Date('2000-01-01T00:00:00Z'),createFolders:false});return zip.generateAsync({type:'blob'});
 }
 async function template(){if(!items().some(i=>i.active))throw Error('Add Domestic items before downloading their price template.');download(await priceWorkbook(items().filter(i=>i.active)),'FH_Domestic_Price_List_Template.xlsx');}
 function filterManual(){const query=document.getElementById('domestic-price-search')?.value.trim().toLowerCase()||'',segment=document.getElementById('domestic-price-segment')?.value||'';let count=0;document.querySelectorAll('[data-price-item]').forEach(row=>{row.hidden=!(row.dataset.search.includes(query)&&(!segment||row.dataset.segment===segment));if(!row.hidden)count++;});const empty=document.getElementById('domestic-price-empty');if(empty)empty.hidden=count>0;const status=document.getElementById('domestic-price-count');if(status)status.textContent=Object.values(manual?.rates||{}).filter(v=>v.trim()!=='').length+' prices entered · blank rates skipped';}
 function change(el){if(context().ui.modal!=='domestic-price-manual')return false;if(el.hasAttribute('data-domestic-price-rate')){manual.rates[el.dataset.domesticPriceRate]=el.value;filterManual();return true;}if(el.id==='domestic-price-search'||el.id==='domestic-price-segment'){filterManual();return true;}return false;}
 async function action(a,d){if(a==='domestic-price-template'){await template();return true;}if(a==='domestic-price-upload'||a==='domestic-price-manual'){if(!host.editable())throw Error('Purchase editing access is required.');reading++;review=null;manual=a==='domestic-price-manual'?{meta:{},rates:{}}:null;showDialog(a,{});return true;}if(a==='domestic-price-back'&&manual){reading++;review=null;showDialog('domestic-price-manual',{});return true;}if(a==='domestic-price-history'||a==='domestic-vendor'){showDialog(a,d);return true;}return false;}
 async function submit(t,d,form){
  const f=Object.fromEntries(new FormData(form));
  if(t==='domestic-vendor')return command('DOMESTIC_SAVE_VENDOR',f,{message:'Domestic supplier created.'});
  if(t==='domestic-price-manual'){
   const token=++reading;manual.meta={vendorId:f.vendorId,quoteDate:f.quoteDate,quoteReference:f.quoteReference,reason:f.reason};for(const input of form.querySelectorAll('[data-domestic-price-rate]'))manual.rates[input.dataset.domesticPriceRate]=input.value;
   const entries=items().filter(i=>i.active&&manual.rates[i.id]?.trim()!=='').filter(i=>manual.rates[i.id]!=null).map(i=>({...i,rate:manual.rates[i.id].trim()}));
   if(!entries.length)throw Error('Enter at least one price before reviewing.');if(entries.length>500)throw Error('Save up to 500 prices at a time.');
   const rows=entries.map(i=>Object.fromEntries(DOMESTIC_PRICE_HEADERS.map((h,n)=>[h,[i.code,i.description,i.uom,i.rate][n]]))),file=new File([await priceWorkbook(entries)],'Manual_Domestic_Prices.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),sourceHash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(n=>n.toString(16).padStart(2,'0')).join('');
   if(token!==reading||context().ui.modal!==t)return;review={...manual.meta,entryMethod:'MANUAL',file,rows,sourceHash,supplierName:suppliers().find(v=>v.id===f.vendorId)?.name,preview:previewDomesticPrices(context().state,rows)};showDialog('domestic-price-review',{});return {keepOpen:true};
  }
  if(t==='domestic-price-upload'){const token=++reading,file=form.querySelector('[name=priceFile]').files[0],rows=await readSheetWorkbook(file,DOMESTIC_PRICE_HEADERS,500,{rejectFormulas:true});if(rows.some(r=>!DOMESTIC_PRICE_HEADERS.every(h=>Object.hasOwn(r,h))))throw Error('Keep the exact headings from the downloaded template.');const bytes=await file.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');if(token!==reading||context().ui.modal!==t)return;review={...f,file,rows,sourceHash:hash,supplierName:suppliers().find(v=>v.id===f.vendorId)?.name,preview:previewDomesticPrices(context().state,rows)};showDialog('domestic-price-review',{});return {keepOpen:true};}
  if(!review)throw Error('Enter or upload the price list again.');
  review.fileId??=await upload(review.file,[],'LAE_DOMESTIC');return command('DOMESTIC_IMPORT_PRICES',{vendorId:review.vendorId,quoteDate:review.quoteDate,quoteReference:review.quoteReference,reason:review.reason,rows:review.rows,sourceHash:review.sourceHash,fileId:review.fileId,entryMethod:review.entryMethod||'UPLOAD'},{message:'Supplier prices saved. Existing BOMs retained.'});
 }
 return {page,vendorPage,modal,action,submit,change};
}
