import {DOMESTIC_PRICE_HEADERS,previewDomesticPrices,latestDomesticPrices} from '../shared/domestic-prices.mjs';
export function createDomesticPrices(host){
 const {context,esc,button,note,field,showDialog,command,upload,readSheetWorkbook,download,money}=host;
 let review=null,reading=0;
 const suppliers=()=>context().state.vendors.filter(v=>v.status==='ACTIVE'&&v.kind==='SUPPLIER');
 const quotes=()=>context().state.domesticPriceLists||[];
 const items=()=>context().state.domesticItems||[];
 const date=()=>new Date().toISOString().slice(0,10);
 function page(){const latest=items().flatMap(i=>latestDomesticPrices(context().state,i.id).map((p,n)=>({...p,item:i,lowest:n===0})));
  return '<section class="panel"><div class="panel-body"><div class="flex spread wrap"><h2>Supplier price lists</h2><div class="flex wrap">'+button('Download template','domestic-price-template',{},'','download')+(host.editable()?button('Upload price list','domestic-price-upload',{},'primary','upload'):'')+'</div></div>'+note('1. Download template · 2. Fill INR rates before GST · 3. Upload and review. Blank rates are skipped. Saved BOM costs stay unchanged.')+'</div><div class="table-wrap"><table aria-label="Supplier price comparison"><thead><tr><th>Item</th><th>Supplier</th><th>Quote / date</th><th>UOM</th><th>INR before GST</th></tr></thead><tbody>'+latest.map(p=>'<tr><td><b>'+esc(p.code)+'</b><div class="sub">'+esc(p.description)+'</div></td><td>'+esc(p.vendorCode+' · '+p.vendorName)+'</td><td>'+esc(p.quoteReference)+'<div class="sub">'+esc(p.quoteDate)+'</div></td><td>'+esc(p.uom)+'</td><td>'+money(p.rateMinor)+(p.lowest?'<div class="sub">Lowest quoted rate</div>':'')+'</td></tr>').join('')+'</tbody></table></div>'+(!latest.length?note('No prices uploaded yet. Start with Download template.'):'')+'<div class="panel-body"><p class="small muted">Latest quote by date for each supplier and item. Earlier-dated quotes remain in history. Freight, GST, minimum quantities and other supplier conditions are excluded from this rate comparison.</p><details><summary>Upload history ('+quotes().length+')</summary>'+quotes().slice().reverse().map(q=>'<p><b>'+esc(q.vendorCode+' · '+q.quoteReference)+'</b> · '+esc(q.quoteDate)+' · '+q.lines.length+' prices · '+esc(q.createdBy)+'<br><span class="small muted">'+esc(q.reason)+'</span> '+button('View prices','domestic-price-history',{id:q.id},'small ghost')+'</p>').join('')+'</details></div></section>';
 }
 function vendorPage(){return '<section class="panel"><div class="panel-body"><div class="flex spread"><h2>Supplier master</h2>'+(['ADMIN','MANAGER'].includes(context().user.role)?button('Add supplier','domestic-vendor',{},'primary','plus'):'')+'</div><p class="small muted">Shared supplier master. Existing suppliers in your assigned divisions can also quote Domestic items.</p></div><div class="table-wrap"><table><thead><tr><th>Supplier code</th><th>Name</th><th>Contact</th><th>Payment terms</th></tr></thead><tbody>'+suppliers().map(v=>'<tr><td>'+esc(v.code)+'</td><td>'+esc(v.name)+'</td><td>'+esc([v.contact,v.phone].filter(Boolean).join(' · '))+'</td><td>'+esc(v.paymentTermsText||'Not recorded')+'</td></tr>').join('')+'</tbody></table></div></section>';}
 function reviewTable(rows){return '<div class="table-wrap"><table aria-label="Price upload review"><thead><tr><th>Row</th><th>Item</th><th>UOM</th><th>INR before GST</th><th>Result</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+r.row+'</td><td>'+esc(r.code)+'<div class="sub">'+esc(r.description)+'</div></td><td>'+esc(r.uom)+'</td><td>'+money(r.rateMinor)+'</td><td>'+esc(r.errors?.join('; ')||(r.result==='SKIP'?'Blank — skipped':r.rateMinor===0?'Save zero rate':'Ready to save'))+'</td></tr>').join('')+'</tbody></table></div>';}
 function modal(t,d){
  if(t==='domestic-vendor')return {title:'Add Domestic supplier',submit:'Save supplier',body:field('code','Supplier code','','text',{required:true})+field('name','Supplier name','','text',{required:true})+field('country','Country','India','text',{required:true})+field('contact','Contact person','','text')+field('phone','Phone','','text')+field('paymentTermsText','Supplier payment terms','','textarea')};
  if(t==='domestic-price-history'){const q=quotes().find(q=>q.id===d.id);return {title:'Supplier quote · '+q.quoteReference,sub:q.vendorName+' · '+q.quoteDate,submit:null,wide:true,body:reviewTable(q.lines.map((l,n)=>({...l,row:n+1})))+note(q.reason)};}
  if(t==='domestic-price-review'){return {title:'Review supplier prices',sub:review.supplierName+' · '+review.quoteReference+' · '+review.quoteDate,wide:true,submit:review.preview.some(r=>r.result==='REJECTED')||!review.preview.some(r=>r.result==='SAVE')?null:'Save supplier prices',body:note(review.preview.filter(r=>r.result==='SAVE').length+' prices to save. '+review.preview.filter(r=>r.result==='SKIP').length+' blank rates skipped. Existing BOM costs are not changed.')+reviewTable(review.preview)+note('If anything is incorrect, cancel, correct the file and upload again.')};}
  return {title:'Upload supplier price list',sub:'INR per item UOM · before GST',wide:true,submit:'Review prices',body:'<div class="form-grid">'+field('vendorId','Supplier','','select',{required:true,options:[{value:'',label:'Select supplier'},...suppliers().map(v=>({value:v.id,label:v.code+' · '+v.name}))]})+field('quoteDate','Supplier quote date',date(),'date',{required:true,attrs:'max="'+date()+'"'})+field('quoteReference','Supplier quote reference','','text',{required:true})+field('reason','Reason / quote conditions','','textarea',{required:true,hint:'Record the source and any freight, quantity or payment conditions.'})+field('priceFile','Completed template','','file',{required:true,full:true,attrs:'accept=".xlsx,.csv"',hint:'Up to 500 rows. Use values only; formulas are rejected. Maximum 50 MB.'})+'</div>'+(!suppliers().length?note('A Purchase Manager must add a supplier before uploading.','warn'):'')};
 }
 async function template(){
  if(!items().length)throw Error('Add Domestic items before downloading their price template.');
  const bytes=window.FH_DOMESTIC_PRICE_TEMPLATE?Uint8Array.from(atob(window.FH_DOMESTIC_PRICE_TEMPLATE),c=>c.charCodeAt(0)):await fetch('/templates/Domestic_Price_List_Template.xlsx').then(r=>{if(!r.ok)throw Error('Template could not be loaded.');return r.arrayBuffer();});
  const zip=await JSZip.loadAsync(bytes),xml=new DOMParser().parseFromString(await zip.file('xl/worksheets/sheet1.xml').async('string'),'application/xml'),ns=xml.documentElement.namespaceURI,rows=xml.getElementsByTagNameNS('*','sheetData')[0],prototype=rows.querySelector('row[r="2"]'),styles=['A','B','C','D'].map(c=>prototype?.querySelector('c[r="'+c+'2"]')?.getAttribute('s')||'0');
  // Keep the authored header and off-table instructions, replace only A:D body cells.
  for(const r of [...rows.children])if(Number(r.getAttribute('r'))>1){for(const c of [...r.children])if(/^[A-D]\d+$/.test(c.getAttribute('r')))c.remove();}
  items().filter(i=>i.active).forEach((i,n)=>{const rn=n+2;let row=rows.querySelector('row[r="'+rn+'"]');if(!row){row=xml.createElementNS(ns,'row');row.setAttribute('r',rn);rows.append(row);}row.setAttribute('ht','44');row.setAttribute('customHeight','1');[i.code,i.description,i.uom,''].forEach((v,j)=>{const c=xml.createElementNS(ns,'c');c.setAttribute('r','ABCD'[j]+rn);c.setAttribute('s',styles[j]);c.setAttribute('t','inlineStr');const is=xml.createElementNS(ns,'is'),t=xml.createElementNS(ns,'t');t.textContent=v;is.append(t);c.append(is);row.append(c);});[...row.children].sort((a,b)=>a.getAttribute('r').localeCompare(b.getAttribute('r'))).forEach(c=>row.append(c));});
  xml.getElementsByTagNameNS('*','dimension')[0]?.setAttribute('ref','A1:F'+Math.max(3,items().filter(i=>i.active).length+1));
  zip.file('xl/worksheets/sheet1.xml',new XMLSerializer().serializeToString(xml));download(await zip.generateAsync({type:'blob'}),'FH_Domestic_Price_List_Template.xlsx');
 }
 async function action(a,d){if(a==='domestic-price-template'){await template();return true;}if(a==='domestic-price-upload'){reading++;review=null;showDialog(a,{});return true;}if(a==='domestic-price-history'||a==='domestic-vendor'){showDialog(a,d);return true;}return false;}
 async function submit(t,d,form){
  const f=Object.fromEntries(new FormData(form));
  if(t==='domestic-vendor')return command('DOMESTIC_SAVE_VENDOR',f,{message:'Domestic supplier created.'});
  if(t==='domestic-price-upload'){const token=++reading,file=form.querySelector('[name=priceFile]').files[0],rows=await readSheetWorkbook(file,DOMESTIC_PRICE_HEADERS,500,{rejectFormulas:true});if(rows.some(r=>!DOMESTIC_PRICE_HEADERS.every(h=>Object.hasOwn(r,h))))throw Error('Keep the exact headings from the downloaded template.');const bytes=await file.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');if(token!==reading||context().ui.modal!==t)return;review={...f,file,rows,sourceHash:hash,supplierName:suppliers().find(v=>v.id===f.vendorId)?.name,preview:previewDomesticPrices(context().state,rows)};showDialog('domestic-price-review',{});return {keepOpen:true};}
  if(!review)throw Error('Upload the price list again.');
  review.fileId??=await upload(review.file,[],'LAE_DOMESTIC');return command('DOMESTIC_IMPORT_PRICES',{vendorId:review.vendorId,quoteDate:review.quoteDate,quoteReference:review.quoteReference,reason:review.reason,rows:review.rows,sourceHash:review.sourceHash,fileId:review.fileId},{message:'Supplier prices saved. Existing BOMs retained.'});
 }
 return {page,vendorPage,modal,action,submit};
}
