import {pendingLoadingRows} from '../shared/shipping.mjs';

export function createLoadingUI(host){
 const {context,esc,head,ph,button,field,note,badge,visibleOrders,canCreate,canEdit,isoDay,addDays}=host;
 const modes=[{value:'SINGLE_ORDER',label:'Single order and single supplier'},{value:'MULTIPLE_ORDERS',label:'Multiple purchase orders · one supplier'},{value:'MULTIPLE_SUPPLIERS',label:'Multiple suppliers'}];
 const vendorName=id=>context().state.vendors.find(v=>v.id===id)?.name||id;
 const allRows=()=>pendingLoadingRows(visibleOrders());
 const eligible=()=>allRows().filter(r=>r.unallocated>0&&canEdit(context().user,r.o)&&r.o.productionStartedAt&&r.o.pi?.status==='APPROVED');
 const suppliers=rows=>[...new Set(rows.map(r=>r.o.vendorId))].map(id=>({value:id,label:vendorName(id)}));
 const orders=rows=>[...new Map(rows.map(r=>[r.o.id,r.o])).values()];
 const options=rows=>orders(rows).map(o=>({value:o.id,label:o.number+' · '+(o.pi?.number||'PI pending')}));
 const attrs=o=>' data-loading-vendor-id="'+esc(o.vendorId)+'" data-loading-order-id="'+esc(o.id)+'"';
 const searchText=(o,l)=>esc([vendorName(o.vendorId),o.number,o.pi?.number,l.code,l.name,l.description].join(' ').toLowerCase());
 const planned=()=>visibleOrders().flatMap(o=>o.shipments.filter(s=>s.status!=='CANCELLED'&&!s.actualDeparture&&!s.roGroupId&&!s.forwarderRef).map(s=>({o,s})));
 function page(){const rows=allRows(),can=canCreate(context().user),groups=new Map();for(const o of visibleOrders())for(const s of o.shipments)if(s.roGroupId){if(!groups.has(s.roGroupId))groups.set(s.roGroupId,[]);groups.get(s.roGroupId).push({o,s});}
  return head('LAE Import / Loading','Loading','Select items, save a loading plan, then assign an RO when ready.',button('Open flow map','nav',{to:'flow-map'},'small'))+
   '<div class="panel">'+ph('Items for loading','Available quantities exclude all active shipment reservations.',can?button('Loading plan','loading-plan',{},'small primary','plus'):'')+
   '<div class="panel-body"><div class="form-grid three">'+field('loadingVendor','Supplier','','select',{attrs:'data-loading-vendor',options:[{value:'',label:'All suppliers'},...suppliers(rows)]})+field('loadingOrder','Purchase order','','select',{attrs:'data-loading-order',options:[{value:'',label:'All orders'},...options(rows)]})+field('loadingStatus','Show','available','select',{attrs:'data-loading-status',options:[{value:'available',label:'Available to plan'},{value:'all',label:'All items · including allocated / shipped'}]})+field('loadingSearch','Find supplier, PO, PI or item','','search',{attrs:'data-loading-search'})+'</div></div><div class="table-wrap"><table><thead><tr><th>Supplier / PO / PI</th><th>Item</th><th>Ordered</th><th>Available to plan</th><th>Reserved · not loaded</th><th>Container loaded</th><th>On vessel / arrived</th></tr></thead><tbody>'+rows.map(r=>'<tr'+attrs(r.o)+' data-loading-available="'+r.unallocated+'" data-loading-row="'+searchText(r.o,r.l)+'"'+(r.unallocated<=0?' hidden':'')+'><td>'+esc(vendorName(r.o.vendorId))+'<div class="sub"><a href="#/order/'+r.o.id+'">'+esc(r.o.number)+'</a> · '+esc(r.o.pi?.number||'PI pending')+'</div></td><td>'+esc(r.l.code)+'<div class="sub">'+esc(r.l.description||r.l.name||'')+'</div></td><td>'+r.ordered+'</td><td><b>'+r.unallocated+'</b></td><td>'+r.reserved+'</td><td>'+r.containerLoaded+'</td><td>'+r.departed+'</td></tr>').join('')+'</tbody></table></div><p class="small muted" data-loading-empty'+(rows.some(r=>r.unallocated>0)?' hidden':'')+'>No items match this view. Choose All items to review allocations and shipping progress.</p></div><div class="gap"></div>'+
   '<div class="panel">'+ph('Saved plans · awaiting RO','Assign one plan to an RO or combine plans. Existing order-level approvals and documents remain required.',can&&planned().length?button('Assign / combine RO','ro-loading',{},'small'):'')+'<div class="table-wrap"><table><thead><tr><th>Supplier / PO</th><th>Plan</th><th>Quantity</th><th>Progress</th><th></th></tr></thead><tbody>'+planned().map(({o,s})=>'<tr><td>'+esc(vendorName(o.vendorId))+'<div class="sub">'+esc(o.number)+'</div></td><td>'+esc(s.number)+'</td><td>'+s.lines.reduce((n,l)=>n+l.quantity,0)+'</td><td>'+badge(s.status,'dark')+'</td><td>'+button('Open order','open-order',{id:o.id},'small ghost')+'</td></tr>').join('')+'</tbody></table></div></div><div class="gap"></div>'+
   [...groups.values()].map(m=>'<div class="panel">'+ph('RO '+esc(m[0].s.roNumber),new Set(m.map(x=>x.o.vendorId)).size+' suppliers · '+new Set(m.map(x=>x.o.id)).size+' orders')+'<div class="panel-body">'+m.map(({o,s})=>'<p><a href="#/order/'+o.id+'">'+esc(o.number)+'</a> · '+esc(vendorName(o.vendorId))+' · '+s.lines.reduce((n,l)=>n+l.quantity,0)+' units · '+badge(s.status,'dark')+'</p>').join('')+'</div></div>').join('');
 }
 function planForm(){const rows=eligible();context().ui.loadingRows=rows.map(({o,l})=>({orderId:o.id,lineId:l.id}));return note('1. Choose loading type and supplier/order. 2. Tick items and enter quantities. 3. Save the plan. Assign or combine an RO afterward.','blue')+'<div class="form-grid three">'+field('loadingMode','Loading type','SINGLE_ORDER','select',{required:true,attrs:'data-loading-mode',options:modes})+field('vendorId','Supplier','','select',{required:true,attrs:'data-loading-plan-vendor',options:[{value:'',label:'Select supplier'},...suppliers(rows)]})+field('orderId','Purchase order','','select',{required:true,attrs:'data-loading-plan-order',options:[{value:'',label:'Select supplier first'}]})+'</div>'+field('find','Find item, PO or PI','','search',{attrs:'data-loading-search'})+'<div class="table-wrap" style="max-height:400px;overflow:auto"><table><thead><tr><th>Select</th><th>Supplier / PO / PI</th><th>Item</th><th>Available</th><th>Load quantity</th></tr></thead><tbody>'+rows.map(({o,l,unallocated},i)=>'<tr hidden'+attrs(o)+' data-loading-row="'+searchText(o,l)+'"><td><input type="checkbox" name="pick-'+i+'" data-loading-pick="'+i+'" aria-label="Select '+esc(o.number+' '+l.code)+'"></td><td>'+esc(vendorName(o.vendorId))+'<div class="sub">'+esc(o.number)+' · '+esc(o.pi?.number)+'</div></td><td>'+esc(l.code)+'<div class="sub">'+esc(l.description||l.name||'')+'</div></td><td>'+unallocated+'</td><td>'+field('load-'+i,'Quantity for '+l.code,'','number',{attrs:'data-loading-quantity disabled min="1" max="'+unallocated+'" step="1"'})+'</td></tr>').join('')+'</tbody></table></div><p class="small" data-loading-selection>0 items selected</p>'+note('Only approved-PI orders with bulk production started are eligible. Search filters preserve your selected items. Untick an item to exclude it.','blue')+'<div class="form-grid three">'+field('etd','Planned ETD',isoDay(),'date',{required:true})+field('eta','Planned ETA',addDays(isoDay(),30),'date',{required:true})+field('containerType','Container type','40HC','select',{options:['20GP','40GP','40HC','LCL']})+field('origin','Origin','','text',{required:true})+field('destination','Destination','','text',{required:true})+'</div>'+field('remarks','Loading instructions / reason','','textarea',{required:true,full:true});}
 function roForm(){const members=planned().filter(({o})=>canEdit(context().user,o)&&o.pi?.status==='APPROVED');context().ui.roExisting=members;return note('Select saved plans for one RO. Choose one plan for a single load, or plans across orders and suppliers to combine. The destination and forwarding agent must match.','blue')+field('roNumber','RO number','','text',{required:true})+'<div class="table-wrap"><table><thead><tr><th>Select</th><th>Supplier / PO</th><th>Plan</th><th>Destination</th><th>Quantity</th></tr></thead><tbody>'+members.map(({o,s},i)=>'<tr><td><input type="checkbox" name="existing-'+i+'" aria-label="Select '+esc(s.number)+'"></td><td>'+esc(vendorName(o.vendorId))+'<div class="sub">'+esc(o.number)+'</div></td><td>'+esc(s.number)+'</td><td>'+esc(s.destination)+'</td><td>'+s.lines.reduce((n,l)=>n+l.quantity,0)+'</td></tr>').join('')+'</tbody></table></div>'+field('remarks','RO assignment reason / instructions','','textarea',{required:true,full:true});}
 function payload(form){const f=Object.fromEntries(new FormData(form));if(context().ui.modal==='ro-loading')return {type:'PLAN_RO_LOADING',payload:{roNumber:f.roNumber,remarks:f.remarks,orders:context().ui.roExisting.flatMap(({o,s},i)=>f['existing-'+i]?[{orderId:o.id,shipmentId:s.id}]:[])}};const grouped=new Map();context().ui.loadingRows.forEach((r,i)=>{if(f['pick-'+i]){if(!grouped.has(r.orderId))grouped.set(r.orderId,{orderId:r.orderId,lines:[]});grouped.get(r.orderId).lines.push({lineId:r.lineId,quantity:Number(f['load-'+i])});}});return {type:'PLAN_LOADING',payload:{...f,orders:[...grouped.values()]}};}
 function sync(el){const root=el.closest('form')||document.querySelector('#app'),mode=root.querySelector('[data-loading-mode]'),v=root.querySelector(mode?'[data-loading-plan-vendor]':'[data-loading-vendor]'),po=root.querySelector(mode?'[data-loading-plan-order]':'[data-loading-order]');if(!v||!po)return;
  const rows=mode?eligible():allRows();if(el===v||el===mode){const prev=po.value,filtered=rows.filter(r=>!v.value||r.o.vendorId===v.value);po.innerHTML='<option value="">'+(mode&&mode.value==='SINGLE_ORDER'?'Select purchase order':'All orders')+'</option>'+options(filtered).map(x=>'<option value="'+esc(x.value)+'">'+esc(x.label)+'</option>').join('');if([...po.options].some(x=>x.value===prev))po.value=prev;}
  if(mode){v.required=mode.value!=='MULTIPLE_SUPPLIERS';po.required=mode.value==='SINGLE_ORDER';v.options[0].textContent=v.required?'Select supplier':'All suppliers';v.closest('label').querySelector('span').hidden=!v.required;po.closest('label').querySelector('span').hidden=!po.required;if(mode.value==='SINGLE_ORDER'&&!v.value)po.value='';}
  const q=root.querySelector('[data-loading-search]')?.value.trim().toLowerCase()||'',status=root.querySelector('[data-loading-status]')?.value||'all';let shown=0;
  root.querySelectorAll('[data-loading-row]').forEach(row=>{const scopeOK=(!v.value||row.dataset.loadingVendorId===v.value)&&(!po.value||row.dataset.loadingOrderId===po.value)&&(!mode||mode.value==='MULTIPLE_SUPPLIERS'||!!v.value)&&( !mode||mode.value!=='SINGLE_ORDER'||!!po.value);row.hidden=!scopeOK||!row.dataset.loadingRow.includes(q)||(status==='available'&&Number(row.dataset.loadingAvailable)<=0);if(!row.hidden)shown++;});
  // A mode/supplier/order change never silently discards a selected quantity. Submission validates its scope.
  const selected=root.querySelectorAll('[data-loading-pick]:checked'),summary=root.querySelector('[data-loading-selection]');if(summary)summary.textContent=selected.length+' items selected'+([...selected].some(c=>c.closest('tr').hidden)?' · selected items remain included when filtered':'');const empty=root.querySelector('[data-loading-empty]');if(empty)empty.hidden=shown>0;
 }
 function change(el){if(el.matches('[data-loading-pick]')){const input=el.closest('tr').querySelector('[data-loading-quantity]');input.disabled=!el.checked;input.required=el.checked;if(el.checked&&!input.value)input.value=input.max;sync(el);return true;}if(el.matches('[data-loading-mode],[data-loading-plan-vendor],[data-loading-plan-order],[data-loading-vendor],[data-loading-order],[data-loading-status],[data-loading-search]')){sync(el);return true;}return false;}
 return {page,planForm,roForm,payload,change};
}
