/** Presentation hierarchy only. Existing routes and server scopes stay authoritative. */
export function createNavigation(host){
 const {icon,esc,head,button}=host,ctx=host.context;
 const divisions=[['lae-import','LAE Import','overview'],['lae-domestic','LAE Domestic'],['utility','Utility Division'],['implements','Implements Division']];
 const work=[['overview','Overview','grid'],['orders','Order pipeline','orders'],['tasks','Tasks & follow-ups','clock'],['payments','Payments','money'],['shipments','Shipping & freight','ship'],['documents','QC & documents','file']];
 const masters=[['vendors','Vendor master','users'],['items','Item master','orders'],['prices','Supplier price lists','money'],['plm','Product Lifecycle (PLM)','box']];
 const activeView=()=>ctx().ui.view==='order'?'orders':ctx().ui.view==='product'?'plm':ctx().ui.view;
 const area=()=>ctx().ui.view==='vms'?'vms':ctx().ui.view==='order-management'||[...work,...masters].some(([id])=>id===activeView())?'orders':'home';
 const nav=(to,label,ic,active=false)=>'<button type="button" class="nav-link '+(active?'active':'')+'" data-action="nav" data-to="'+to+'"'+(active?' aria-current="page"':'')+'>'+icon(ic,16)+'<span>'+esc(label)+'</span></button>';
 function sidebar(){const {ui}=ctx(),section=area();let inside='';
  if(section==='orders')inside=ui.view==='order-management'?'<div class="nav-label">Divisions</div>'+divisions.map(([id,label,to])=>nav(to||'order-management/'+id,label,to?'box':'clock',ui.orderId===id)).join(''):'<div class="nav-section-title">LAE Import</div>'+work.map(([to,label,ic])=>nav(to,label,ic,activeView()===to)).join('')+'<details class="nav-catalogues" '+(masters.some(([id])=>id===activeView())?'open':'')+'><summary>Master data & products</summary>'+masters.map(([to,label,ic])=>nav(to,label,ic,activeView()===to)).join('')+'</details>'+nav('order-management','All divisions','chevron');
  if(section==='vms')inside='<div class="nav-section-title">Vendor workspace</div>'+host.vmsNavigation();
  return '<aside class="sidebar module-sidebar '+(ui.mobile?'open':'')+'"><button type="button" class="brand brand-logo-block brand-home" data-action="nav" data-to="home" aria-label="Farming Hub home"><div class="brand-logo-shell"><img class="brand-logo" src="'+host.logo+'" alt="Farming Hub"></div></button><nav class="module-switcher" aria-label="Main modules">'+nav('order-management','Order Management','orders',section==='orders')+nav('vms','Vendor Management System','users',section==='vms')+'</nav><nav class="module-navigation" aria-label="'+(section==='vms'?'VMS sections':section==='orders'?'Order Management sections':'Workspace')+'">'+inside+'</nav><div class="sidebar-bottom">'+nav('home','Modules','grid',ui.view==='home')+nav('settings','Users & settings','settings',ui.view==='settings')+nav('versions','Version & edit log','history',ui.view==='versions')+'</div></aside>';
 }
 const card=(title,description,to,ic,pending=false)=>'<a class="module-card '+(pending?'pending':'')+'" href="#/'+to+'"><span class="module-card-icon">'+icon(ic,24)+'</span><span class="module-card-copy"><h2>'+esc(title)+'</h2><p>'+esc(description)+'</p><span class="module-card-state">'+(pending?'Pending development':'Open module '+icon('arrow',14))+'</span></span></a>';
 function home(){return head('Farming Hub','Your workspace','Choose a module to get started.')+'<div class="module-cards">'+card('Order Management','Orders, payments, shipping and product records.','order-management','orders')+card('Vendor Management System','Vendors, visit history, follow-ups and sourcing.','vms','users')+'</div>';}
 function orderHub(){const division=divisions.find(([id])=>id===ctx().ui.orderId);if(division&&division[0]!=='lae-import')return head('Order Management',division[1],'',button('All divisions','nav',{to:'order-management'},'ghost','arrow'))+'<div class="division-pending panel"><span class="module-card-icon">'+icon('clock',24)+'</span><h2>Pending development</h2><p>This division is not available yet.</p>'+button('Open LAE Import','nav',{to:'overview'},'primary','arrow')+'</div>';return head('Order Management','Order Management','Select a division.')+'<div class="module-cards division-cards">'+divisions.map(([id,label,to])=>card(label,to?'All current purchasing tools.':'',to||'order-management/'+id,to?'box':'clock',!to)).join('')+'</div>';}
 function breadcrumb(last){const section=area(),parts=[['home','Farming Hub']];if(section==='orders'){parts.push(['order-management','Order Management']);if(ctx().ui.view!=='order-management')parts.push(['overview','LAE Import']);}else if(section==='vms')parts.push(['vms','Vendor Management System']);if(ctx().ui.view==='order-management'&&ctx().ui.orderId)last=divisions.find(([id])=>id===ctx().ui.orderId)?.[1]||last;if(ctx().ui.view!=='home'&&last!==parts.at(-1)[1])parts.push([null,last]);return '<div class="breadcrumb">'+parts.map(([to,title],i)=>(i?icon('chevron',11):'')+(to&&i<parts.length-1?'<a href="#/'+to+'">'+esc(title)+'</a>':'<b>'+esc(title)+'</b>')).join('')+'</div>';}
 return {sidebar,home,orderHub,breadcrumb,area};
}
