/** Presentation hierarchy only. Existing routes and server scopes stay authoritative. */
export function moduleDestination(to){const path=to==='bom-management'?'/bom/':to==='production-stock'?'/production/':to==='monthly-planning'?'/planning/':to==='implements-purchase'?'/implements/#/models':'/#/'+to;return typeof location!=='undefined'&&location.protocol==='file:'?'https://purchase.dvjassociates.com'+path:path;}
export function createNavigation(host){
 const {icon,esc,head,button}=host,ctx=host.context;
 const divisions=[['lae-import','LAE Import','overview'],['lae-domestic','LAE Domestic','domestic/models'],['utility','Utility Division']];
 const work=[['overview','Overview','grid'],['orders','Order pipeline','orders'],['tasks','Tasks & follow-ups','clock'],['payments','Payments','money'],['loading','Loading','box'],['flow-map','Purchase flow map','grid'],['ro-costings','RO costings','money'],['landing-prices','Landing prices','money'],['shipments','Shipping & freight','ship'],['documents','QC & documents','file']];
 const masters=[['vendors','Vendor master','users'],['items','Item master','orders'],['prices','Supplier price lists','money'],['plm','Product Lifecycle (PLM)','box']];
 const activeView=()=>ctx().ui.view==='order'?'orders':ctx().ui.view==='product'?'plm':ctx().ui.view;
 const area=()=>['bom-management','production-stock'].includes(ctx().ui.view)?'production':ctx().ui.view==='vms'?'vms':ctx().ui.view==='implements'||ctx().ui.view==='domestic'||ctx().ui.view==='order-management'||[...work,...masters].some(([id])=>id===activeView())?'orders':'home';
 const productionOnly=()=>['BOM_REVIEWER','PRODUCTION_OPERATOR','PLAN_OPERATOR'].includes(ctx().user?.role);
 const bomAllowed=()=>ctx().user?.role==='ADMIN'||ctx().user?.role!=='PLAN_OPERATOR'&&ctx().user?.scopes?.includes('BOM_MANAGEMENT');
 const productionAllowed=()=>ctx().user?.role==='ADMIN'||!['BOM_REVIEWER','PLAN_OPERATOR'].includes(ctx().user?.role)&&ctx().user?.scopes?.includes('PRODUCTION_MANAGEMENT');
 const purchaseAllowed=()=>!productionOnly()&&(ctx().user?.role==='ADMIN'||ctx().user?.scopes?.includes('IMPLEMENTS_DOMESTIC'));
 const planningAllowed=()=>ctx().user?.role==='ADMIN'||ctx().user?.role==='MANAGER'&&purchaseAllowed()||ctx().user?.scopes?.includes('IMPLEMENTS_PLANNING')&&!['BOM_REVIEWER','PRODUCTION_OPERATOR'].includes(ctx().user?.role);
 const implementsAllowed=()=>purchaseAllowed()||bomAllowed()||productionAllowed()||planningAllowed();
 const nav=(to,label,ic,active=false)=>'<button type="button" class="nav-link '+(active?'active':'')+'" data-action="nav" data-to="'+to+'"'+(active?' aria-current="page"':'')+'>'+icon(ic,16)+'<span>'+esc(label)+'</span></button>';
 const divisionLinks=()=>'<div class="nav-label">Divisions</div>'+(!productionOnly()?nav('division/lae','LAE Division','box',ctx().ui.view==='division'&&ctx().ui.orderId==='lae'):'')+(implementsAllowed()?nav('division/implements','Implements Division','box',ctx().ui.view==='division'&&ctx().ui.orderId==='implements'):'');
 function sidebar(){const {ui}=ctx(),section=area();let inside=divisionLinks();
  if(section==='orders')inside=nav('division/lae','LAE Division','arrow')+(ui.view==='order-management'?'<div class="nav-label">Order Management</div>'+divisions.map(([id,label,to])=>nav(to||'order-management/'+id,label,to?'box':'clock',ui.orderId===id)).join(''):'<div class="nav-section-title">LAE Import</div>'+work.map(([to,label,ic])=>nav(to,label,ic,activeView()===to)).join('')+'<details class="nav-catalogues" '+(masters.some(([id])=>id===activeView())?'open':'')+'><summary>Master data & products</summary>'+masters.map(([to,label,ic])=>nav(to,label,ic,activeView()===to)).join('')+'</details>');
  if(ui.view==='order-management'&&ui.orderId==='implements')inside=divisionLinks();
  if(ui.view==='implements')inside=nav('division/implements','Implements Division','arrow')+'<div class="nav-section-title">Implements purchase</div>'+(host.implementsSections||[]).map(([to,label,ic])=>nav('implements/'+to,label,ic,ui.orderId===to)).join('');
  if(ui.view==='domestic')inside=nav('division/lae','LAE Division','arrow')+'<div class="nav-section-title">LAE Domestic</div>'+nav('domestic/models','Model BOMs','box',!['items','sets','vendors','prices','orders'].includes(ui.orderId)&&!ui.orderId?.startsWith('po-'))+nav('domestic/sets','Assembly BOMs','box',ui.orderId==='sets')+nav('domestic/items','Item Master','orders',ui.orderId==='items')+nav('domestic/vendors','Supplier master','users',ui.orderId==='vendors')+nav('domestic/prices','Price lists','money',ui.orderId==='prices')+nav('domestic/orders','Purchase orders','orders',ui.orderId==='orders'||ui.orderId?.startsWith('po-'));
  if(ui.view==='bom-management')inside=nav('division/implements','Implements Division','arrow')+'<div class="nav-section-title">BOM & Syntax</div>'+(host.bomSections||[]).map(([to,label,ic])=>nav('bom-management/'+to,label,ic,ui.orderId===to)).join('');
  if(ui.view==='production-stock')inside=nav('division/implements','Implements Division','arrow')+'<div class="nav-section-title">Production & Stock</div>'+(host.productionSections||[]).map(([to,label,ic])=>nav('production-stock/'+to,label,ic,ui.orderId===to)).join('');
  if(ui.view==='monthly-planning')inside=nav('division/implements','Implements Division','arrow')+'<div class="nav-section-title">Monthly plans</div>'+(host.planningSections||[]).map(([to,label,ic])=>nav('monthly-planning/'+to,label,ic,ui.orderId===to)).join('');
  if(section==='vms')inside=nav('division/lae','LAE Division','arrow')+'<div class="nav-section-title">Vendor workspace</div>'+host.vmsNavigation();
  const options=(!productionOnly()?'<optgroup label="LAE Division"><option value="division/lae">All LAE modules</option><option value="order-management">Order Management</option><option value="vms">Vendor Management System</option></optgroup>':'')+(implementsAllowed()?'<optgroup label="Implements Division"><option value="division/implements">All Implements modules</option>'+(purchaseAllowed()?'<option value="implements-purchase">Rotavator purchasing</option>':'')+(bomAllowed()?'<option value="bom-management">BOM &amp; Syntax</option>':'')+(productionAllowed()?'<option value="production-stock">Production &amp; Stock</option>':'')+(planningAllowed()?'<option value="monthly-planning">Monthly plan entry</option>':'')+'</optgroup>':'');
  return '<aside class="sidebar module-sidebar '+(ui.mobile?'open':'')+'"><button type="button" class="brand brand-logo-block brand-home" data-action="nav" data-to="home" aria-label="Farming Hub home"><div class="brand-logo-shell"><img class="brand-logo" src="'+host.logo+'" alt="Farming Hub"></div></button><nav class="module-navigation" aria-label="'+(ui.view==='implements'?'Implements sections':section==='vms'?'VMS sections':section==='orders'?'Order Management sections':'Workspace')+'">'+inside+'</nav><div class="sidebar-bottom">'+nav('settings','Users & settings','settings',ui.view==='settings')+nav('versions','Version & edit log','history',ui.view==='versions')+'<div class="module-switcher"><label for="module-select">Modules</label><select id="module-select"><option value="" selected disabled>Select module...</option>'+options+'</select></div></div></aside>';
 }
 const card=(title,description,to,ic,pending=false)=>'<a class="module-card '+(pending?'pending':'')+'" href="'+(['bom-management','production-stock','monthly-planning','implements-purchase'].includes(to)?moduleDestination(to):'#/'+to)+'"><span class="module-card-icon">'+icon(ic,24)+'</span><span class="module-card-copy"><h2>'+esc(title)+'</h2><p>'+esc(description)+'</p><span class="module-card-state">'+(pending?'Pending development':'Open '+(to.startsWith('division/')?'division':'module')+' '+icon('arrow',14))+'</span></span></a>';
 function home(){return head('Farming Hub','Your workspace','Choose a division to get started.')+'<div class="module-cards division-cards">'+(!productionOnly()?card('LAE Division','Order Management and Vendor Management.','division/lae','orders'):'')+(implementsAllowed()?card('Implements Division',[purchaseAllowed()?'Rotavator purchasing':'',bomAllowed()?'BOM & Syntax':'',productionAllowed()?'Production & Stock':'',planningAllowed()?'Monthly plan entry':''].filter(Boolean).join(', ')+'.','division/implements','box'):'')+'</div>';}
 function divisionHub(id=ctx().ui.orderId){const lae=id==='lae',allowed=lae?!productionOnly():id==='implements'&&implementsAllowed();if(!allowed)return head('Farming Hub','Division unavailable','Your account does not have access to this division.',button('Home','nav',{to:'home'},'ghost','arrow'));return head('Farming Hub',lae?'LAE Division':'Implements Division','Choose a module.')+'<div class="module-cards">'+(lae?card('Order Management','Orders, payments, shipping and product records.','order-management','orders')+card('Vendor Management System','Vendors, visit history, follow-ups and sourcing.','vms','users'):(purchaseAllowed()?card('Rotavator purchasing','Purchase prices, monthly MRP, costing and supplier purchase orders.','implements-purchase','money'):'')+(bomAllowed()?card('BOM & Syntax','Model definitions, component quantities and fabrication checks.','bom-management','box'):'')+(productionAllowed()?card('Production & Stock','Material issue, finished machines and serial tracking.','production-stock','box'):'')+(planningAllowed()?card('Monthly plan entry','Submit monthly machine plans and track purchase approval. No costs.','monthly-planning','clock'):''))+'</div>';}
 function orderHub(){if(ctx().ui.orderId==='implements')return divisionHub('implements');const division=divisions.find(([id])=>id===ctx().ui.orderId);if(division&&division[0]==='lae-domestic')return head('Order Management','LAE Domestic','')+card('Milking machines','Model BOMs and component Item Master.','domestic/models','box');if(division&&division[0]!=='lae-import')return head('Order Management',division[1],'',button('All categories','nav',{to:'order-management'},'ghost','arrow'))+'<div class="division-pending panel"><span class="module-card-icon">'+icon('clock',24)+'</span><h2>Pending development</h2><p>This division is not available yet.</p>'+button('Open LAE Import','nav',{to:'overview'},'primary','arrow')+'</div>';return head('LAE Division','Order Management','Select a category.')+'<div class="module-cards division-cards">'+divisions.map(([id,label,to])=>card(label,id==='lae-domestic'?'Milking machines - items & BOMs':to?'All current purchasing tools.':'',to||'order-management/'+id,to?'box':'clock',!to)).join('')+'</div>';}
 function breadcrumb(last){const {ui}=ctx(),section=area(),parts=[['home','Farming Hub']],implementsView=['implements','bom-management','production-stock','monthly-planning'].includes(ui.view)||ui.view==='order-management'&&ui.orderId==='implements';
  if(ui.view==='division')last=ui.orderId==='lae'?'LAE Division':'Implements Division';
  else if(implementsView){parts.push(['division/implements','Implements Division']);if(ui.view==='implements')parts.push(['implements-purchase','Rotavator purchasing']);else if(ui.view==='bom-management')parts.push(['bom-management','BOM & Syntax']);else if(ui.view==='production-stock')parts.push(['production-stock','Production & Stock']);else if(ui.view==='monthly-planning')parts.push(['monthly-planning','Monthly plan entry']);else last='Implements Division';}
  else if(section==='orders'){parts.push(['division/lae','LAE Division'],['order-management','Order Management']);if(ui.view==='domestic'){parts.push(['domestic/models','LAE Domestic']);last=ui.orderId==='items'?'Item Master':'Milking machines';}else if(ui.view!=='order-management')parts.push(['overview','LAE Import']);if(ui.view==='order-management'&&ui.orderId)last=divisions.find(([id])=>id===ui.orderId)?.[1]||last;}
  else if(section==='vms')parts.push(['division/lae','LAE Division'],['vms','Vendor Management System']);
  if(ui.view!=='home'&&last!==parts.at(-1)[1])parts.push([null,last]);const external=['implements','bom-management','production-stock','monthly-planning'].includes(ui.view);
  return '<div class="breadcrumb">'+parts.map(([to,title],i)=>(i?icon('chevron',11):'')+(to&&i<parts.length-1?'<a href="'+(['implements-purchase','bom-management','production-stock'].includes(to)?moduleDestination(to):(external?'/#/':'#/')+to)+'">'+esc(title)+'</a>':'<b>'+esc(title)+'</b>')).join('')+'</div>';
 }
 return {sidebar,home,divisionHub,orderHub,breadcrumb,area};
}
