import {REFERENCE_TYPES,referenceRecords,softwareReference,integrationSnapshot} from '../shared/references.mjs';
/** Readable identity register and manual mapping preparation; no live ERP transport. */
export function createReferencePages(host){const {esc,head,button,field}=host;let type='orders',query='',page=1,selected='',draft={system:'TALLY',companyKey:'',externalId:'',masterId:'',alterId:'',voucherNumber:''};
 const ctx=host.context,caption=(type,id,parentType='',parentId='')=>{const ref=softwareReference(ctx().state,type,id,parentType,parentId);return ref?'<div class="sub mono software-reference">'+esc(ref)+'</div>':'';};
 const detail=(type,id)=>'<div class="toolbar reference-detail"><span>Software reference <b class="mono">'+esc(softwareReference(ctx().state,type,id))+'</b></span>'+button('Reference register','nav',{to:'references'},'small ghost')+'</div>';
 const settingsLink=()=>'<div class="panel reference-settings"><div class="panel-head"><h2>Software references & ERP links</h2>'+button('Open register','nav',{to:'references'},'small')+'</div><div class="panel-body">Permanent record references for your ERP and Tally. Connection not configured.</div></div><div class="gap"></div>';
 const title=r=>r.record.number||r.record.code||r.record.reference||r.record.name||r.record.productName||r.record.summary||r.record.title||REFERENCE_TYPES[r.type].label;
 function render(){const {state,user}=ctx(),registry=state.recordReferences,all=referenceRecords(state),rows=all.filter(r=>(!type||r.type===type)&&(!query||[softwareReference(state,r.type,r.id,r.parentType,r.parentId),title(r),r.id].join(' ').toLowerCase().includes(query.toLowerCase())));page=Math.max(1,Math.min(page,Math.ceil(rows.length/25)));const row=all.find(r=>r.key===selected);
 const links=r=>(registry?.links||[]).filter(l=>l.recordKey===r.key).map(l=>'<div>'+esc(l.system)+' · '+esc(l.companyKey)+'<div class="sub mono">'+esc(l.externalId)+'</div></div>').join('')||'<span class="muted">Not linked</span>';
 return head('Users & settings','Software references','Permanent references for Farming Hub → ERP → Tally.',user.role==='ADMIN'?button('Export integration JSON','reference-export',{},'','download'):'')+'<div class="panel"><div class="toolbar"><div class="filters"><label>Record type <select id="reference-type"><option value="" '+(!type?'selected':'')+'>All records</option>'+Object.entries(REFERENCE_TYPES).map(([k,v])=>'<option value="'+k+'" '+(k===type?'selected':'')+'>'+esc(v.label)+'</option>').join('')+'</select></label><input id="reference-search" aria-label="Search software references" placeholder="Reference, code or name" value="'+esc(query)+'"></div><span class="muted">Not connected</span></div><div class="table-wrap"><table><thead><tr><th>Software reference</th><th>Record</th><th>ERP / Tally link</th>'+(user.role==='ADMIN'?'<th>Mapping</th>':'')+'</tr></thead><tbody>'+rows.slice((page-1)*25,page*25).map(r=>'<tr><td class="mono">'+esc(softwareReference(state,r.type,r.id,r.parentType,r.parentId))+'</td><td>'+esc(title(r))+'<div class="sub">'+esc(REFERENCE_TYPES[r.type].label)+(r.record.deletedAt?' · Deleted':'')+'</div></td><td>'+links(r)+'</td>'+(user.role==='ADMIN'?'<td>'+button('Link ID','reference-link',{ref:r.key},'small ghost')+'</td>':'')+'</tr>').join('')+(rows.length?'':'<tr><td colspan="4"><div class="empty">No matching records</div></td></tr>')+'</tbody></table></div><div class="pagination"><span>'+rows.length+' records · Page '+page+' of '+Math.max(1,Math.ceil(rows.length/25))+'</span><div>'+(page>1?button('Previous','reference-page',{delta:-1},'small ghost'):'')+(page*25<rows.length?button('Next','reference-page',{delta:1},'small ghost'):'')+'</div></div></div>'+(row&&user.role==='ADMIN'?'<div class="gap"></div><section class="panel" id="external-link-panel"><div class="panel-head"><h2>Link '+esc(softwareReference(state,row.type,row.id,row.parentType,row.parentId))+'</h2>'+button('Cancel','reference-cancel',{},'small ghost')+'</div><form id="external-link-form" class="panel-body"><p class="muted">Record an existing ERP or Tally identity. Saving a link does not send data or create a voucher.</p><div class="form-grid">'+field('system','System',draft.system,'select',{options:[{value:'ERP',label:'ERP frontend'},{value:'TALLY',label:'Tally'}]})+field('companyKey','Company key / GUID',draft.companyKey,'text',{required:true})+field('externalId','External ID / GUID',draft.externalId,'text',{required:true})+field('masterId','Tally Master ID (optional)',draft.masterId)+field('alterId','Tally Alter ID (optional)',draft.alterId)+field('voucherNumber','Voucher number (optional)',draft.voucherNumber)+'</div><button type="submit" class="button primary">Save link</button></form></section>':'')+'<p class="muted small" style="margin-top:16px">PO numbers, item codes and bank references remain separate. Software references never reset. Exported data uses its workspace namespace to distinguish environments.</p>';
 }
 async function action(a,d){if(!a.startsWith('reference-'))return false;if(a==='reference-link'){selected=d.ref;draft={system:'TALLY',companyKey:'',externalId:'',masterId:'',alterId:'',voucherNumber:''};}else if(a==='reference-cancel')selected='';else if(a==='reference-page')page+=Number(d.delta);else if(a==='reference-export'){if(ctx().user.role!=='ADMIN')return true;const payload={...integrationSnapshot(ctx().state),environment:ctx().sandbox?'standalone-review':'authenticated-workspace'},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='FarmingHub-Integration-v1.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return true;}host.navigate('references');if(selected)document.querySelector('#external-link-panel')?.scrollIntoView({block:'start'});return true;}
 function change(el){if(el.closest('#external-link-form')){draft[el.name]=el.value;return true;}if(el.id!=='reference-type')return false;type=el.value;page=1;selected='';host.navigate('references');return true;}
 function input(el){if(el.closest('#external-link-form')){draft[el.name]=el.value;return true;}if(el.id!=='reference-search')return false;query=el.value;page=1;const cursor=el.selectionStart;host.navigate('references');const input=document.querySelector('#reference-search');input?.focus();input?.setSelectionRange(cursor,cursor);return true;}
 async function submit(event){if(event.target.id!=='external-link-form')return false;event.preventDefault();const result=await host.command('LINK_EXTERNAL_REFERENCE',{recordKey:selected,...draft},{close:false,message:'External identity linked. No synchronization performed.'});if(result){selected='';host.navigate('references');}return true;}
 return {render,caption,detail,settingsLink,action,change,input,submit};
}
