import {importantRoDocuments,validateRoDriveUrl,roDrivePreviewUrl} from '../shared/ro-documents.mjs';
import {assertRoCostAccess,canWriteRoCosting,validateRoRecord,calculateRoCosting,RO_ACTUAL_FIELDS,worksheetComparisonSummary} from '../shared/ro-costing.mjs';

export function createRoCostingUI(host){
 const {context,api,esc,field,button,head,ph,note,badge,showDialog,render,closeModal,toast,csv}=host;
 let cache=null,cacheKey='',loading=false,error='',q='',status='',offset=0,importRows=null,request=null,openedRo='',drivePreview=null;
 const fmt=n=>n===null||n===undefined?'Pending':Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:4});
 const labels={supplierInr:'Actual supplier payment (INR, including invoice extras)',bankNet:'Bank charges before GST (INR)',forwarderNet:'Forwarder expenses before GST (INR)',otherNet:'Other landing expenses before GST (INR)',bcd:'Actual BCD (INR)',sws:'Actual SWS (INR)'};
 const key=()=>[context().user.id,context().ui.orderId||'',q,status,offset].join('|');
 const localKey=()=>host.reviewStore+':ro-costings:'+context().user.id;
 function localRead(){const raw=JSON.parse(localStorage.getItem(localKey())||'{}');return raw;}
 async function load(force=false){
  if(loading)return;loading=true;const expected=key();error='';
  try{
   const {user,ui,sandbox}=context();assertRoCostAccess(user);
   if(sandbox){const rows=localRead();if(ui.orderId){const r=rows[ui.orderId];if(!r)throw Error('RO costing not found in this isolated review.');const files=window.FH_RO_REVIEW_DOCUMENTS?.[r.record.ro]||[];cache={...r,cost:calculateRoCosting(r.record),importantDocuments:importantRoDocuments(r.record,files),documents:{rows:files.slice(0,100),total:files.length,offset:0},history:r.history||[]};}else{const found=Object.values(rows).filter(r=>(!q||(r.record.ro+' '+r.record.supplier).toLowerCase().includes(q.toLowerCase()))&&(!status||calculateRoCosting(r.record).status===status)).sort((a,b)=>a.record.ro.localeCompare(b.record.ro,undefined,{numeric:true}));cache={total:found.length,rows:found.slice(offset,offset+50).map(r=>({ro:r.record.ro,supplier:r.record.supplier,revision:r.revision,invoices:r.record.invoices.map(i=>i.invoice),inwardDate:r.record.inwardDate,boeDate:r.record.boeDate,documents:importantDocumentCount(r.record,window.FH_RO_REVIEW_DOCUMENTS?.[r.record.ro]||[]),...calculateRoCosting(r.record),worksheetComparison:worksheetComparisonSummary(r.record)}))};}}
   else cache=await api('/ro-costings'+(ui.orderId?'/record?ro='+encodeURIComponent(ui.orderId):'?q='+encodeURIComponent(q)+'&status='+status+'&offset='+offset));
   if(sandbox)cache.sourceLibrary=window.FH_RO_SOURCE_LIBRARY||null;
   if(expected!==key()){cache=null;cacheKey='';}else cacheKey=expected;
  }catch(e){cache=null;error=e.message;cacheKey=expected;}finally{loading=false;if(context().ui.view==='ro-costings')render();}
 }
 function working(c){return `<div class="arrival-results"><div><span>Goods invoice USD</span><strong>$${fmt(c.goodsUsd)}</strong></div><div><span>Entered actual costs before GST</span><strong>₹${fmt(c.enteredTotal)}</strong></div><div><span>Verified actual AI INR / USD</span><strong>${fmt(c.rate)}</strong></div><div><span>Suresh rate in actual record</span><strong>${fmt(c.sureshRate)}</strong></div></div>`;}
 function page(){
  const {user,ui,sandbox}=context();try{assertRoCostAccess(user);}catch(e){return head('LAE Import','RO costings','')+note(esc(e.message),'warn');}
  if(cacheKey!==key()&&!loading){cache=null;queueMicrotask(()=>load());}
  const title=head('LAE Import','RO costings','Worksheet AI and Suresh references, important documents and verified actual costs before GST.',button('Refresh','ro-refresh',{},'ghost'));
  if(loading||cacheKey!==key())return title+note('Loading RO costings…');
  if(error)return title+note(esc(error),'warn')+button('Try again','ro-refresh',{},'primary');
  const write=canWriteRoCosting(user),review=(sandbox?note('Isolated browser review. These records do not update the website. Evidence uploads are available on the authenticated server.'):'')+sourceLibraryPanel(cache.sourceLibrary);
  if(ui.orderId){const r=cache.record,c=cache.cost;if(openedRo!==r.ro){openedRo=r.ro;drivePreview=null;requestAnimationFrame(()=>{if(context().ui.view==='ro-costings'&&context().ui.orderId===r.ro){window.scrollTo(0,0);document.getElementById('ro-important-documents')?.focus({preventScroll:true});}});}return title+review+button('All RO costings','nav',{to:'ro-costings'},'ghost')+importantDocumentsPanel(cache.importantDocuments)+comparisonPanel(r.worksheetComparison)+`<section class="panel">${ph('RO '+esc(r.ro),esc(r.supplier),badge(c.status,c.rate===null?'amber':'green')+(write?button('Edit workings','ro-edit',{},'primary'):''))}<div class="panel-body">${working(c)}<p>Invoice face value: $${fmt(c.faceUsd)} · BOE ${esc(r.boe||'Pending')} · BOE date ${esc(r.boeDate||'Pending')} · Inward ${esc(r.inwardDate||'Pending')}</p><p>Customs FX ₹${fmt(r.customsFx)}/USD is a reference. Final landed rate = actual before-GST INR total ÷ unique goods invoice USD.</p>${c.pending.length?note(esc(c.pending.join(' ')),'warn'):''}${c.differencePercent!==null?note('AI / Suresh difference: '+fmt(c.differencePercent)+'%'):''}${r.notes?note(esc(r.notes)):''}<h3>Supplier invoices</h3>${table(['Supplier','Invoice','Currency','Goods','Extras','Face value','Basis / review'],r.invoices.map(i=>[esc(i.supplier),esc(i.invoice),esc(i.currency),fmt(i.goods),fmt(i.extras),fmt(i.face),esc([i.basis,i.review].filter(Boolean).join(' · '))]))}<h3>Actual cost workings</h3>${table(['Component','INR before GST'],RO_ACTUAL_FIELDS.map(k=>[esc(labels[k]),fmt(r.actuals[k])]))}<p>Coverage: ${esc(r.actuals.expenseCoverage)} · ${esc(r.actuals.confirmation||'Verification not recorded.')}</p><details><summary>Received expense documents — reference workings</summary><p>These amounts are retained as evidence; they do not automatically enter actual cost. Enter each verified allocated expense once in the actual workings.</p>${table(['Document','Component','Net','GST excluded','Basis / allocation','Status'],r.expenses.map(e=>[esc(e.document_no),esc(e.component),fmt(e.net)+' '+esc(e.currency),fmt(e.gst),esc(e.basis+' '+e.allocation),e.provisional?'Provisional':e.include?'Received — verify actual':'Excluded reference']))}</details><h3>Flags</h3>${r.issues.length?table(['Severity','Issue','Details'],r.issues.map(i=>[esc(i.severity),esc(i.topic),esc(i.detail)])):'<p>No imported flags.</p>'}</div></section><section class="panel">${ph('Costing history','Previous financial versions are retained.')}<div class="panel-body">${table(['Revision','Date','Reason'],cache.history.map(e=>[e.revision,esc(e.at),esc(e.reason)]))}${button('Export this RO','ro-export',{},'ghost')}</div></section>`;}
  openedRo='';drivePreview=null;
  return title+review+`<section class="panel"><div class="panel-body"><form id="ro-filter" class="toolbar">${field('q','Find RO / supplier',q)}${field('status','Actual costing status',status,'select',{options:[{value:'',label:'All'},'Pending','Complete']})}<button class="button" type="submit">Find</button></form><div class="flex wrap">${write?button('New RO costing','ro-new',{},'primary')+button('Import prepared costings','ro-import',{},'ghost'):''}<span>${cache.total} RO records</span></div></div>${table(['RO','Supplier / invoices','Inward / BOE date','Goods USD','Worksheet AI INR / USD','Worksheet Suresh INR / USD','Worksheet status','Verified actual AI INR / USD','Actual status','Important docs'],cache.rows.map(r=>['<a class="ro-costing-link" style="text-decoration:underline;font-weight:600" href="#/ro-costings/'+encodeURIComponent(r.ro)+'" title="Open RO '+esc(r.ro)+' — Commercial Invoice, Inward BOE and costing">'+esc(r.ro)+'</a>',esc(r.supplier)+'<div class="sub">'+esc(r.invoices.join('; '))+'</div>',esc(r.inwardDate||'Pending')+' / '+esc(r.boeDate||'Pending'),fmt(r.goodsUsd),fmt(r.worksheetComparison?.aiRate),fmt(r.worksheetComparison?.sureshRate),esc(r.worksheetComparison?.status||'Pending'),fmt(r.rate),badge(r.status,r.rate===null?'amber':'green'),r.documents]))}<div class="panel-body flex wrap">${offset?button('Previous','ro-page',{offset:Math.max(0,offset-50)},'ghost'):''}${offset+50<cache.total?button('Next','ro-page',{offset:offset+50},'ghost'):''}<span>Showing ${cache.total?offset+1:0}–${Math.min(cache.total,offset+50)} of ${cache.total}</span></div></section>`;
 }
 function comparisonPanel(comparison){
  if(!comparison)return '<section class="panel ro-reference-panel">'+ph('Worksheet AI / Suresh comparison','Before-GST worksheet references')+'<div class="panel-body">'+note('Worksheet references have not been supplied. Verified actual workings remain available below.')+'</div></section>';
  const summary=side=>'<div class="arrival-results"><div><span>Reference INR / USD</span><strong>'+fmt(side.rate)+'</strong></div><div><span>Reference INR total</span><strong>'+fmt(side.totalInr)+'</strong></div><div><span>Goods USD basis</span><strong>'+fmt(side.goodsUsd)+'</strong></div></div>'+(side.basis?'<p>'+esc(side.basis)+'</p>':'')+(side.formula?'<p>Source formula: <code>'+esc(side.formula)+'</code></p>':'');
  const sideTable=(label,side)=>'<h4>'+esc(label)+'</h4>'+summary(side)+table(['Named component / source label','Source value','Unit','Source cell','Source formula','Basis'],side.rows.map(row=>[esc(row.label),row.value===null?'Pending':typeof row.value==='number'?fmt(row.value):esc(row.value),esc(row.unit),esc(row.cell),'<code>'+esc(row.formula)+'</code>',esc(row.basis)]));
  return '<section class="panel ro-reference-panel">'+ph('Worksheet AI / Suresh comparison','Before-GST references; actual costs are verified separately.',badge(comparison.status,'amber'))+'<div class="panel-body"><p>'+esc(comparison.basis)+'</p><p>Reviewed '+esc(comparison.reviewedOn||'Pending')+' · '+esc(comparison.source)+'</p><h3>Worksheet AI</h3>'+summary(comparison.ai)+'<h3>Suresh worksheet</h3>'+summary(comparison.suresh)+note('These historical or provisional references do not complete missing actual payments or expenses. Source formulas are preserved independently; component rows are not automatically added into actual costs.')+comparison.workings.map(w=>'<details><summary>'+esc(w.invoice||'Invoice reference pending')+' · '+esc(w.supplier)+' · '+esc(w.status)+' · '+(comparison.selectedWorkingIds.includes(w.id)?'Selected headline source':'Retained alternative')+'</summary><p>'+esc(w.basis)+'</p><p>Source: '+esc(w.source.file)+' · Sheet: '+esc(w.source.sheet)+' · Working: '+esc(w.id)+'</p>'+(w.source.sha256?'<p style="overflow-wrap:anywhere">Source SHA-256: <code>'+esc(w.source.sha256)+'</code></p>':'')+sideTable('Worksheet AI workings',w.ai)+sideTable('Suresh original workings',w.suresh)+'</details>').join('')+'</div></section>';
 }
 function table(headers,rows){return '<div class="table-wrap" role="region" aria-label="RO costing table" tabindex="0"><table><thead><tr>'+headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.map(row=>'<tr>'+row.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+headers.length+'">No records</td></tr>')+'</tbody></table></div>';}
 function importantDocumentCount(record,files){const grouped=importantRoDocuments(record,files);return grouped.commercialInvoices.length+grouped.inwardBoe.length+grouped.importerCopies.length;}
 function driveLink(url,label,library=false){const link=validateRoDriveUrl(url,{library});return '<a class="button small ghost" href="'+esc(link.url)+'" target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">'+esc(label)+'</a>';}
 function sourceLibraryPanel(library){return library?'<section class="panel ro-reference-panel">'+ph('Costing learnings / source library','Private source references; Google Drive access is required.')+'<div class="panel-body"><p>'+esc(library.name)+'</p>'+driveLink(library.driveUrl,'Open source library in Google Drive',true)+'</div></section>':'';}
 function documentLink(file,view=false){const base=context().sandbox?'/__ro-review/files/':'/api/ro-costings/files/';return '<a class="button small ghost" href="'+base+encodeURIComponent(file.id)+(view?'?view=1':'')+'"'+(view?' target="_blank" rel="noopener"':'')+'>'+(/\.pdf$/i.test(file.name)&&view?'View PDF':'Download')+'</a>';}
 function importantAccess(file){const local=file.storage==='google-drive'?'':documentLink(file,true)+' '+documentLink(file);const references=file.driveReferences||(file.driveUrl?[{url:file.driveUrl}]:[]);return local+' '+references.map(r=>{const link=validateRoDriveUrl(r.url);return button('Preview document','ro-drive-preview',{file:link.fileId},'small ghost')+' '+driveLink(link.url,'Open in Google Drive');}).join(' ');}
 function drivePreviewPanel(){
  if(!drivePreview)return '';
  return '<section class="ro-drive-preview" aria-labelledby="ro-drive-preview-title"><div class="flex wrap"><h3 id="ro-drive-preview-title" tabindex="-1">'+esc(drivePreview.name)+'</h3>'+button('Close preview','ro-drive-close',{},'small ghost')+'</div><p>Use your permitted Google account to view this private document. If the preview is unavailable, open it in Google Drive.</p>'+driveLink(drivePreview.url,'Open preview in Google Drive')+'<iframe title="'+esc('RO '+cache.record.ro+' — '+drivePreview.name)+'" src="'+esc(roDrivePreviewUrl(drivePreview.url))+'" referrerpolicy="no-referrer" allow="fullscreen"></iframe></section>';
 }
 function importantDocumentsPanel(group={commercialInvoices:[],inwardBoe:[],importerCopies:[]}){
  const block=(label,files,agent=false)=>'<div><h3>'+esc(label)+'</h3>'+(agent?'<p>Issued by Yasuda, World Gates or Future Consol to Farming Hub.</p>':'')+(files.length?table(agent?['Forwarding agent','Document','Type','Open / download']:['Document','Type','Open / download'],files.map(f=>[...(agent?[esc(f.agent)]:[]),esc(f.name),esc(f.kind),importantAccess(f)])):note('Missing — '+label+' has not been provided or verified.','warn'))+'</div>';
  return '<section class="panel" id="ro-important-documents" tabindex="-1">'+ph('Important documents','Commercial invoice, inward/main Bill of Entry and verified importer copy',canWriteRoCosting(context().user)&&!context().sandbox?button('Upload documents','ro-upload',{},'primary'):'')+'<div class="panel-body"><div id="ro-drive-preview">'+drivePreviewPanel()+'</div>'+block('Commercial Invoice',group.commercialInvoices)+block('Inward BOE / Main BOE',group.inwardBoe)+block('Importer copy',group.importerCopies||[])+'<details><summary>Retained document archive</summary><div id="ro-document-list">'+documents(cache.documents)+'</div></details></div></section>';
 }
 function documents(d){return table(['Document','Type','Size','Open / download'],d.rows.map(f=>[esc(f.name),esc(f.kind),fmt(f.bytes/1024)+' KB',f.storage==='google-drive'?driveLink(f.driveUrl,'Open in Google Drive'):documentLink(f)]))+(d.offset+100<d.total?button('More documents','ro-doc-page',{offset:d.offset+100},'ghost'):'');}
 function invoiceFields(i={},index=0){return `<fieldset data-ro-invoice="${index}"><legend>Supplier invoice ${index+1}</legend><div class="form-grid">${field('supplier-'+index,'Supplier',i.supplier||'')}${field('invoice-'+index,'Supplier invoice number',i.invoice||'')}${field('currency-'+index,'Currency',i.currency||'USD','select',{options:['USD','CNY','UNKNOWN','CONFLICT']})}${field('goods-'+index,'Goods value',i.goods??'','number',{attrs:'min="0" step="0.01"'})}${field('extras-'+index,'Invoice extras',i.extras??'','number',{attrs:'min="0" step="0.01"'})}${field('face-'+index,'Invoice face value',i.face??'','number',{attrs:'min="0" step="0.01"'})}${field('basis-'+index,'Invoice evidence / value basis',i.basis||'','textarea',{full:true,hint:'Keep BOE-only evidence marked as reference until the original supplier invoice is verified.'})}</div></fieldset>`;}
 function modal(type){
  if(type==='ro-upload')return {title:'Upload RO documents',sub:'RO '+cache.record.ro,body:field('kind','Document type','','select',{required:true,options:[{value:'',label:'Select document type'},'Commercial invoice','Inward BOE','Importer copy']})+field('files','Supporting files','','file',{required:true,full:true,attrs:'multiple',hint:'Choose Importer copy only when the document explicitly identifies itself as that copy. Each original stays separate. Maximum 50 MB per file.'}),submit:'Upload documents'};
  if(type==='ro-import')return {title:'Import prepared RO costings',sub:'Existing RO versions are preserved.',body:note('Choose the prepared RO costing JSON. Review its RO list before importing. Maximum 30 records per batch.')+field('file','Prepared costing file','','file',{required:true,attrs:'accept=".json"'})+'<div id="ro-import-preview" role="status"></div>'+field('reason','Import reason','','textarea',{required:true,full:true})+field('confirm','I reviewed these RO records','','checkbox',{required:true}),submit:'Import costings'};
  const r=type==='ro-new'?{invoices:[],actuals:{}}:cache.record;
  return {title:type==='ro-new'?'New RO costing':'Edit RO '+r.ro,sub:'Blank amounts stay pending. Enter 0 only for a confirmed nil charge.',wide:true,body:'<div class="form-grid">'+field('ro','RO number',r.ro||'','text',{required:true,attrs:type==='ro-new'?'':'readonly'})+field('supplier','Supplier / joint loading suppliers',r.supplier||'')+field('inwardDate','RO inward date',r.inwardDate||'','date')+field('boeDate','BOE date',r.boeDate||'','date')+field('boe','BOE number',r.boe||'')+field('customsFx','BOE customs INR / USD (reference)',r.customsFx??'','number',{attrs:'min="0" step="0.0001"'})+'</div><h3>Supplier invoices</h3><div id="ro-invoice-fields">'+(r.invoices.length?r.invoices:[{}]).map(invoiceFields).join('')+'</div>'+button('Add supplier invoice','ro-add-invoice',{},'ghost')+'<h3>Actual workings before GST</h3><div class="form-grid">'+RO_ACTUAL_FIELDS.map(k=>field(k,labels[k],r.actuals[k]??'','number',{attrs:'min="0" step="0.01"'})).join('')+field('sureshRate','Suresh rate in actual record',r.actuals.sureshRate??'','number',{attrs:'min="0" step="0.0001"'})+field('expenseCoverage','Actual expense coverage',r.actuals.expenseCoverage||'Pending','select',{options:['Pending','Complete']})+field('currencyConfirmed','All invoice USD values verified',r.actuals.currencyConfirmed?'on':'','checkbox',{attrs:r.actuals.currencyConfirmed?'checked':''})+field('confirmation','Evidence / nil charge verification',r.actuals.confirmation||'','textarea',{full:true})+field('notes','Costing notes',r.notes||'','textarea',{full:true})+field('reason','Reason for saving this version','','textarea',{required:true,full:true})+'</div>',submit:'Save workings'};
 }
 function readEdit(form,type){const f=Object.fromEntries(new FormData(form)),old=type==='ro-new'?{}:cache.record;const value=k=>f[k]===''?null:Number(f[k]);return validateRoRecord({...old,ro:f.ro,supplier:f.supplier,inwardDate:f.inwardDate,boeDate:f.boeDate,boe:f.boe,customsFx:value('customsFx'),notes:f.notes,invoices:[...form.querySelectorAll('[data-ro-invoice]')].map((el,n)=>({...old.invoices?.[n],supplier:f['supplier-'+n],invoice:f['invoice-'+n],currency:f['currency-'+n],goods:value('goods-'+n),extras:value('extras-'+n),face:value('face-'+n),basis:f['basis-'+n]})).filter(i=>i.invoice||i.goods!==null),actuals:{...Object.fromEntries(RO_ACTUAL_FIELDS.map(k=>[k,value(k)])),sureshRate:value('sureshRate'),expenseCoverage:f.expenseCoverage,currencyConfirmed:form.querySelector('[name=currencyConfirmed]').checked,confirmation:f.confirmation}});}
 async function submit(type,data,form){
  const f=Object.fromEntries(new FormData(form));assertRoCostAccess(context().user,true);
  if(type==='ro-upload'){for(const file of form.querySelector('[name=files]').files){if(file.size>50*1024*1024)throw Error('Maximum file size is 50 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let n=0;n<bytes.length;n+=32768)binary+=String.fromCharCode(...bytes.subarray(n,n+32768));await api('/ro-costings/files',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({ro:cache.record.ro,name:file.name,kind:f.kind,base64:btoa(binary)})});}closeModal();cacheKey='';toast('RO documents uploaded.');render();return;}
  const records=type==='ro-import'?(importRows||[]):[{record:readEdit(form,type),expectedRevision:type==='ro-new'?0:cache.revision}];
  if(!records.length)throw Error('Choose and review the prepared costing file first.');
  const payload={records,reason:f.reason};const signature=JSON.stringify(payload);if(!request||request.signature!==signature)request={signature,id:crypto.randomUUID()};
  if(context().sandbox){const saved=localRead(),next=structuredClone(saved);for(const entry of records){let r=validateRoRecord(entry.record);const old=saved[r.ro];if(old?.record.worksheetComparison&&!Object.hasOwn(entry.record,'worksheetComparison'))r=validateRoRecord({...r,worksheetComparison:old.record.worksheetComparison});if((old?.revision||0)!==entry.expectedRevision)throw Error('RO '+r.ro+' changed. Refresh before saving.');next[r.ro]={record:r,revision:(old?.revision||0)+1,history:[...(old?.history||[]),{revision:(old?.revision||0)+1,at:new Date().toISOString(),reason:f.reason}]};}localStorage.setItem(localKey(),JSON.stringify(next));}
  else await api('/ro-costings/import',{method:'POST',headers:{'Idempotency-Key':request.id},body:JSON.stringify(payload)});
  request=null;closeModal();cacheKey='';toast('RO costing versions saved. Missing actuals remain pending.');render();
 }
 async function action(a,d){if(!a.startsWith('ro-'))return false;
  if(a==='ro-drive-preview'){
   assertRoCostAccess(context().user);
   const groups=cache?.importantDocuments,files=groups?['commercialInvoices','inwardBoe','importerCopies'].flatMap(k=>groups[k]||[]):[];
   const match=files.flatMap(file=>(file.driveReferences||(file.driveUrl?[{url:file.driveUrl}]:[])).map(ref=>({file,link:validateRoDriveUrl(ref.url)}))).find(entry=>entry.link.fileId===d.file);
   if(!match)throw Error('Document is not available in this RO. Refresh before trying again.');
   drivePreview={name:match.file.name,url:match.link.url,fileId:match.link.fileId};
   document.getElementById('ro-drive-preview').innerHTML=drivePreviewPanel();document.getElementById('ro-drive-preview-title').focus();
  }
  if(a==='ro-drive-close'){
   const fileId=drivePreview?.fileId;drivePreview=null;document.getElementById('ro-drive-preview').replaceChildren();
   if(fileId)document.querySelector('[data-action="ro-drive-preview"][data-file="'+fileId+'"]')?.focus();
  }
  if(a==='ro-refresh'){drivePreview=null;cacheKey='';cache=null;await load(true);}
  if(a==='ro-page'){offset=Number(d.offset);cacheKey='';render();}
  if(a==='ro-edit'||a==='ro-new'||a==='ro-import'||a==='ro-upload'){request=null;importRows=null;showDialog(a);}
  if(a==='ro-add-invoice'){const target=document.getElementById('ro-invoice-fields'),n=target.children.length;if(n>=100)throw Error('Maximum 100 supplier invoices per RO.');target.insertAdjacentHTML('beforeend',invoiceFields({},n));}
  if(a==='ro-doc-page'){const start=Number(d.offset);if(!Number.isSafeInteger(start)||start<0)throw Error('Invalid document page.');const files=context().sandbox?(window.FH_RO_REVIEW_DOCUMENTS?.[cache.record.ro]||[]):null;const docs=files?{rows:files.slice(start,start+100),total:files.length,offset:start}:await api('/ro-costings/documents?ro='+encodeURIComponent(cache.record.ro)+'&offset='+start);document.getElementById('ro-document-list').innerHTML=documents(docs);}
  if(a==='ro-export'){const r=cache.record,c=cache.cost;csv('RO-'+r.ro+'-Costings.csv',['RO','Supplier','Invoices','Goods USD','Invoice face USD',...RO_ACTUAL_FIELDS.map(k=>labels[k]),'Actual coverage','Verified actual AI INR / USD','Suresh rate in actual record','Actual status','Pending','Worksheet AI INR / USD','Worksheet Suresh INR / USD','Worksheet status','Worksheet basis'],[[r.ro,r.supplier,r.invoices.map(i=>i.invoice).join('; '),c.goodsUsd,c.faceUsd,...RO_ACTUAL_FIELDS.map(k=>r.actuals[k]??''),r.actuals.expenseCoverage,c.rate??'',c.sureshRate??'',c.status,c.pending.join('; '),r.worksheetComparison?.ai.rate??'',r.worksheetComparison?.suresh.rate??'',r.worksheetComparison?.status||'Pending',r.worksheetComparison?.basis||'']]);}
  return true;
 }
 async function formSubmit(event){if(event.target.id!=='ro-filter')return false;const f=Object.fromEntries(new FormData(event.target));q=f.q;status=f.status;offset=0;cacheKey='';render();return true;}
 async function change(el){if(context().ui.modal!=='ro-import'||el.name!=='file')return false;importRows=null;document.getElementById('ro-import-preview').textContent='';const file=el.files[0];if(!file)return true;if(file.size>5e6)throw Error('Prepared import maximum is 5 MB.');const input=JSON.parse(await file.text());if(!Array.isArray(input.records)||!input.records.length||input.records.length>30)throw Error('Import 1–30 prepared RO records at a time.');importRows=input.records.map(e=>({record:validateRoRecord(e.record),expectedRevision:e.expectedRevision}));document.getElementById('ro-import-preview').textContent='Review '+importRows.length+' ROs: '+importRows.map(e=>e.record.ro).join(', ')+'. Existing RO versions require matching revisions.';return true;}
 return {page,modal,submit,action,formSubmit,change};
}
