import {importantRoDocuments,RO_FORWARDING_AGENTS,RO_AGENT_DOCUMENT_TYPES} from '../shared/ro-documents.mjs';
import {assertRoCostAccess,canWriteRoCosting,validateRoRecord,calculateRoCosting,RO_ACTUAL_FIELDS} from '../shared/ro-costing.mjs';

export function createRoCostingUI(host){
 const {context,api,esc,field,button,head,ph,note,badge,showDialog,render,closeModal,toast,csv}=host;
 let cache=null,cacheKey='',loading=false,error='',q='',status='',offset=0,importRows=null,request=null,openedRo='';
 const fmt=n=>n===null||n===undefined?'Pending':Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:4});
 const labels={supplierInr:'Actual supplier payment (INR, including invoice extras)',bankNet:'Bank charges before GST (INR)',forwarderNet:'Forwarder expenses before GST (INR)',otherNet:'Other landing expenses before GST (INR)',bcd:'Actual BCD (INR)',sws:'Actual SWS (INR)'};
 const key=()=>[context().user.id,context().ui.orderId||'',q,status,offset].join('|');
 const localKey=()=>host.reviewStore+':ro-costings:'+context().user.id;
 function localRead(){const raw=JSON.parse(localStorage.getItem(localKey())||'{}');return raw;}
 async function load(force=false){
  if(loading)return;loading=true;const expected=key();error='';
  try{
   const {user,ui,sandbox}=context();assertRoCostAccess(user);
   if(sandbox){const rows=localRead();if(ui.orderId){const r=rows[ui.orderId];if(!r)throw Error('RO costing not found in this isolated review.');const files=window.FH_RO_REVIEW_DOCUMENTS?.[r.record.ro]||[];cache={...r,cost:calculateRoCosting(r.record),importantDocuments:importantRoDocuments(r.record,files),documents:{rows:files.slice(0,100),total:files.length,offset:0},history:r.history||[]};}else{const found=Object.values(rows).filter(r=>(!q||(r.record.ro+' '+r.record.supplier).toLowerCase().includes(q.toLowerCase()))&&(!status||calculateRoCosting(r.record).status===status)).sort((a,b)=>a.record.ro.localeCompare(b.record.ro,undefined,{numeric:true}));cache={total:found.length,rows:found.slice(offset,offset+50).map(r=>({ro:r.record.ro,supplier:r.record.supplier,revision:r.revision,invoices:r.record.invoices.map(i=>i.invoice),inwardDate:r.record.inwardDate,boeDate:r.record.boeDate,documents:importantDocumentCount(r.record,window.FH_RO_REVIEW_DOCUMENTS?.[r.record.ro]||[]),...calculateRoCosting(r.record)}))};}}
   else cache=await api('/ro-costings'+(ui.orderId?'/record?ro='+encodeURIComponent(ui.orderId):'?q='+encodeURIComponent(q)+'&status='+status+'&offset='+offset));
   if(expected!==key()){cache=null;cacheKey='';}else cacheKey=expected;
  }catch(e){cache=null;error=e.message;cacheKey=expected;}finally{loading=false;if(context().ui.view==='ro-costings')render();}
 }
 function working(c){return `<div class="arrival-results"><div><span>Goods invoice USD</span><strong>$${fmt(c.goodsUsd)}</strong></div><div><span>Entered actual costs before GST</span><strong>₹${fmt(c.enteredTotal)}</strong></div><div><span>AI calculated INR / USD</span><strong>${fmt(c.rate)}</strong></div><div><span>Suresh calculated INR / USD</span><strong>${fmt(c.sureshRate)}</strong></div></div>`;}
 function page(){
  const {user,ui,sandbox}=context();try{assertRoCostAccess(user);}catch(e){return head('LAE Import','RO costings','')+note(esc(e.message),'warn');}
  if(cacheKey!==key()&&!loading){cache=null;queueMicrotask(()=>load());}
  const title=head('LAE Import','RO costings','Invoice documents, actual expenses and landed INR cost per USD before GST.',button('Refresh','ro-refresh',{},'ghost'));
  if(loading||cacheKey!==key())return title+note('Loading RO costings…');
  if(error)return title+note(esc(error),'warn')+button('Try again','ro-refresh',{},'primary');
  const write=canWriteRoCosting(user),review=sandbox?note('Isolated browser review. These records do not update the website. Evidence uploads are available on the authenticated server.'):'';
  if(ui.orderId){const r=cache.record,c=cache.cost;if(openedRo!==r.ro){openedRo=r.ro;requestAnimationFrame(()=>{if(context().ui.view==='ro-costings'&&context().ui.orderId===r.ro){window.scrollTo(0,0);document.getElementById('ro-important-documents')?.focus({preventScroll:true});}});}return title+review+button('All RO costings','nav',{to:'ro-costings'},'ghost')+importantDocumentsPanel(cache.importantDocuments)+`<section class="panel">${ph('RO '+esc(r.ro),esc(r.supplier),badge(c.status,c.rate===null?'amber':'green')+(write?button('Edit workings','ro-edit',{},'primary'):''))}<div class="panel-body">${working(c)}<p>Invoice face value: $${fmt(c.faceUsd)} · BOE ${esc(r.boe||'Pending')} · BOE date ${esc(r.boeDate||'Pending')} · Inward ${esc(r.inwardDate||'Pending')}</p><p>Customs FX ₹${fmt(r.customsFx)}/USD is a reference. Final landed rate = actual before-GST INR total ÷ unique goods invoice USD.</p>${c.pending.length?note(esc(c.pending.join(' ')),'warn'):''}${c.differencePercent!==null?note('AI / Suresh difference: '+fmt(c.differencePercent)+'%'):''}${r.notes?note(esc(r.notes)):''}<h3>Supplier invoices</h3>${table(['Supplier','Invoice','Currency','Goods','Extras','Face value','Basis / review'],r.invoices.map(i=>[esc(i.supplier),esc(i.invoice),esc(i.currency),fmt(i.goods),fmt(i.extras),fmt(i.face),esc([i.basis,i.review].filter(Boolean).join(' · '))]))}<h3>Actual cost workings</h3>${table(['Component','INR before GST'],RO_ACTUAL_FIELDS.map(k=>[esc(labels[k]),fmt(r.actuals[k])]))}<p>Coverage: ${esc(r.actuals.expenseCoverage)} · ${esc(r.actuals.confirmation||'Verification not recorded.')}</p><details><summary>Received expense documents — reference workings</summary><p>These amounts are retained as evidence; they do not automatically enter actual cost. Enter each verified allocated expense once in the actual workings.</p>${table(['Document','Component','Net','GST excluded','Basis / allocation','Status'],r.expenses.map(e=>[esc(e.document_no),esc(e.component),fmt(e.net)+' '+esc(e.currency),fmt(e.gst),esc(e.basis+' '+e.allocation),e.provisional?'Provisional':e.include?'Received — verify actual':'Excluded reference']))}</details><h3>Flags</h3>${r.issues.length?table(['Severity','Issue','Details'],r.issues.map(i=>[esc(i.severity),esc(i.topic),esc(i.detail)])):'<p>No imported flags.</p>'}</div></section><section class="panel">${ph('Costing history','Previous financial versions are retained.')}<div class="panel-body">${table(['Revision','Date','Reason'],cache.history.map(e=>[e.revision,esc(e.at),esc(e.reason)]))}${button('Export this RO','ro-export',{},'ghost')}</div></section>`;}
  openedRo='';
  return title+review+`<section class="panel"><div class="panel-body"><form id="ro-filter" class="toolbar">${field('q','Find RO / supplier',q)}${field('status','Costing status',status,'select',{options:[{value:'',label:'All'},'Pending','Complete']})}<button class="button" type="submit">Find</button></form><div class="flex wrap">${write?button('New RO costing','ro-new',{},'primary')+button('Import prepared costings','ro-import',{},'ghost'):''}<span>${cache.total} RO records</span></div></div>${table(['RO','Supplier / invoices','Inward / BOE date','Goods USD','AI INR / USD','Suresh INR / USD','Status','Important docs'],cache.rows.map(r=>['<a class="ro-costing-link" style="text-decoration:underline;font-weight:600" href="#/ro-costings/'+encodeURIComponent(r.ro)+'" title="Open RO '+esc(r.ro)+' — Commercial Invoice, Inward BOE and costing">'+esc(r.ro)+'</a>',esc(r.supplier)+'<div class="sub">'+esc(r.invoices.join('; '))+'</div>',esc(r.inwardDate||'Pending')+' / '+esc(r.boeDate||'Pending'),fmt(r.goodsUsd),fmt(r.rate),fmt(r.sureshRate),badge(r.status,r.rate===null?'amber':'green'),r.documents]))}<div class="panel-body flex wrap">${offset?button('Previous','ro-page',{offset:Math.max(0,offset-50)},'ghost'):''}${offset+50<cache.total?button('Next','ro-page',{offset:offset+50},'ghost'):''}<span>Showing ${cache.total?offset+1:0}–${Math.min(cache.total,offset+50)} of ${cache.total}</span></div></section>`;
 }
 function table(headers,rows){return '<div class="table-wrap" role="region" aria-label="RO costing table" tabindex="0"><table><thead><tr>'+headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.map(row=>'<tr>'+row.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+headers.length+'">No records</td></tr>')+'</tbody></table></div>';}
 function importantDocumentCount(record,files){const grouped=importantRoDocuments(record,files);return grouped.commercialInvoices.length+grouped.forwarderInvoices.length+grouped.inwardBoe.length;}
 function documentLink(file,view=false){const base=context().sandbox?'/__ro-review/files/':'/api/ro-costings/files/';return '<a class="button small ghost" href="'+base+encodeURIComponent(file.id)+(view?'?view=1':'')+'"'+(view?' target="_blank" rel="noopener"':'')+'>'+(/\.pdf$/i.test(file.name)&&view?'View PDF':'Download')+'</a>';}
 function importantDocumentsPanel(group={commercialInvoices:[],forwarderInvoices:[],inwardBoe:[],otherBoe:[]}){
  const block=(label,files,agent=false)=>'<div><h3>'+esc(label)+'</h3>'+(agent?'<p>Issued by Yasuda, World Gates or Future Consol to Farming Hub.</p>':'')+(files.length?table(agent?['Forwarding agent','Document','Type','Open / download']:['Document','Type','Open / download'],files.map(f=>[...(agent?[esc(f.agent)]:[]),esc(f.name),esc(f.kind),documentLink(f,true)+' '+documentLink(f)])):note('Missing — '+label+' has not been provided or verified.','warn'))+'</div>';
  return '<section class="panel" id="ro-important-documents" tabindex="-1">'+ph('Important documents','Commercial invoice, forwarding agent invoice and inward/main Bill of Entry',canWriteRoCosting(context().user)&&!context().sandbox?button('Upload documents','ro-upload',{},'primary'):'')+'<div class="panel-body">'+block('Commercial Invoice',group.commercialInvoices)+block('Forwarding Agent Invoice',group.forwarderInvoices||[],true)+block('Inward BOE / Main BOE',group.inwardBoe)+'</div></section>';
 }
 function documents(d){return table(['Document','Type','Size','Download'],d.rows.map(f=>[esc(f.name),esc(f.kind),fmt(f.bytes/1024)+' KB',documentLink(f)]))+(d.offset+100<d.total?button('More documents','ro-doc-page',{offset:d.offset+100},'ghost'):'');}
 function invoiceFields(i={},index=0){return `<fieldset data-ro-invoice="${index}"><legend>Supplier invoice ${index+1}</legend><div class="form-grid">${field('supplier-'+index,'Supplier',i.supplier||'')}${field('invoice-'+index,'Supplier invoice number',i.invoice||'')}${field('currency-'+index,'Currency',i.currency||'USD','select',{options:['USD','CNY','UNKNOWN','CONFLICT']})}${field('goods-'+index,'Goods value',i.goods??'','number',{attrs:'min="0" step="0.01"'})}${field('extras-'+index,'Invoice extras',i.extras??'','number',{attrs:'min="0" step="0.01"'})}${field('face-'+index,'Invoice face value',i.face??'','number',{attrs:'min="0" step="0.01"'})}${field('basis-'+index,'Invoice evidence / value basis',i.basis||'','textarea',{full:true,hint:'Keep BOE-only evidence marked as reference until the original supplier invoice is verified.'})}</div></fieldset>`;}
 function modal(type){
  if(type==='ro-upload')return {title:'Upload RO documents',sub:'RO '+cache.record.ro,body:field('kind','Document type','','select',{required:true,options:[{value:'',label:'Select document type'},'Commercial invoice',...RO_FORWARDING_AGENTS.flatMap(agent=>RO_AGENT_DOCUMENT_TYPES.map(type=>`${type} — ${agent}`)),'Inward BOE']})+field('files','Supporting files','','file',{required:true,full:true,attrs:'multiple',hint:'For agent bills, verify the selected agent is the issuer and Farming Hub is the billed customer. Each file stays separate. Maximum 50 MB per file.'}),submit:'Upload documents'};
  if(type==='ro-import')return {title:'Import prepared RO costings',sub:'Existing RO versions are preserved.',body:note('Choose the prepared RO costing JSON. Review its RO list before importing. Maximum 30 records per batch.')+field('file','Prepared costing file','','file',{required:true,attrs:'accept=".json"'})+'<div id="ro-import-preview" role="status"></div>'+field('reason','Import reason','','textarea',{required:true,full:true})+field('confirm','I reviewed these RO records','','checkbox',{required:true}),submit:'Import costings'};
  const r=type==='ro-new'?{invoices:[],actuals:{}}:cache.record;
  return {title:type==='ro-new'?'New RO costing':'Edit RO '+r.ro,sub:'Blank amounts stay pending. Enter 0 only for a confirmed nil charge.',wide:true,body:'<div class="form-grid">'+field('ro','RO number',r.ro||'','text',{required:true,attrs:type==='ro-new'?'':'readonly'})+field('supplier','Supplier / joint loading suppliers',r.supplier||'')+field('inwardDate','RO inward date',r.inwardDate||'','date')+field('boeDate','BOE date',r.boeDate||'','date')+field('boe','BOE number',r.boe||'')+field('customsFx','BOE customs INR / USD (reference)',r.customsFx??'','number',{attrs:'min="0" step="0.0001"'})+'</div><h3>Supplier invoices</h3><div id="ro-invoice-fields">'+(r.invoices.length?r.invoices:[{}]).map(invoiceFields).join('')+'</div>'+button('Add supplier invoice','ro-add-invoice',{},'ghost')+'<h3>Actual workings before GST</h3><div class="form-grid">'+RO_ACTUAL_FIELDS.map(k=>field(k,labels[k],r.actuals[k]??'','number',{attrs:'min="0" step="0.01"'})).join('')+field('sureshRate','Suresh calculated INR / USD',r.actuals.sureshRate??'','number',{attrs:'min="0" step="0.0001"'})+field('expenseCoverage','Actual expense coverage',r.actuals.expenseCoverage||'Pending','select',{options:['Pending','Complete']})+field('currencyConfirmed','All invoice USD values verified',r.actuals.currencyConfirmed?'on':'','checkbox',{attrs:r.actuals.currencyConfirmed?'checked':''})+field('confirmation','Evidence / nil charge verification',r.actuals.confirmation||'','textarea',{full:true})+field('notes','Costing notes',r.notes||'','textarea',{full:true})+field('reason','Reason for saving this version','','textarea',{required:true,full:true})+'</div>',submit:'Save workings'};
 }
 function readEdit(form,type){const f=Object.fromEntries(new FormData(form)),old=type==='ro-new'?{}:cache.record;const value=k=>f[k]===''?null:Number(f[k]);return validateRoRecord({...old,ro:f.ro,supplier:f.supplier,inwardDate:f.inwardDate,boeDate:f.boeDate,boe:f.boe,customsFx:value('customsFx'),notes:f.notes,invoices:[...form.querySelectorAll('[data-ro-invoice]')].map((el,n)=>({...old.invoices?.[n],supplier:f['supplier-'+n],invoice:f['invoice-'+n],currency:f['currency-'+n],goods:value('goods-'+n),extras:value('extras-'+n),face:value('face-'+n),basis:f['basis-'+n]})).filter(i=>i.invoice||i.goods!==null),actuals:{...Object.fromEntries(RO_ACTUAL_FIELDS.map(k=>[k,value(k)])),sureshRate:value('sureshRate'),expenseCoverage:f.expenseCoverage,currencyConfirmed:form.querySelector('[name=currencyConfirmed]').checked,confirmation:f.confirmation}});}
 async function submit(type,data,form){
  const f=Object.fromEntries(new FormData(form));assertRoCostAccess(context().user,true);
  if(type==='ro-upload'){for(const file of form.querySelector('[name=files]').files){if(file.size>50*1024*1024)throw Error('Maximum file size is 50 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let n=0;n<bytes.length;n+=32768)binary+=String.fromCharCode(...bytes.subarray(n,n+32768));await api('/ro-costings/files',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({ro:cache.record.ro,name:file.name,kind:f.kind,base64:btoa(binary)})});}closeModal();cacheKey='';toast('RO documents uploaded.');render();return;}
  const records=type==='ro-import'?(importRows||[]):[{record:readEdit(form,type),expectedRevision:type==='ro-new'?0:cache.revision}];
  if(!records.length)throw Error('Choose and review the prepared costing file first.');
  const payload={records,reason:f.reason};const signature=JSON.stringify(payload);if(!request||request.signature!==signature)request={signature,id:crypto.randomUUID()};
  if(context().sandbox){const saved=localRead(),next=structuredClone(saved);for(const entry of records){const r=validateRoRecord(entry.record),old=saved[r.ro];if((old?.revision||0)!==entry.expectedRevision)throw Error('RO '+r.ro+' changed. Refresh before saving.');next[r.ro]={record:r,revision:(old?.revision||0)+1,history:[...(old?.history||[]),{revision:(old?.revision||0)+1,at:new Date().toISOString(),reason:f.reason}]};}localStorage.setItem(localKey(),JSON.stringify(next));}
  else await api('/ro-costings/import',{method:'POST',headers:{'Idempotency-Key':request.id},body:JSON.stringify(payload)});
  request=null;closeModal();cacheKey='';toast('RO costing versions saved. Missing actuals remain pending.');render();
 }
 async function action(a,d){if(!a.startsWith('ro-'))return false;
  if(a==='ro-refresh'){cacheKey='';cache=null;await load(true);}
  if(a==='ro-page'){offset=Number(d.offset);cacheKey='';render();}
  if(a==='ro-edit'||a==='ro-new'||a==='ro-import'||a==='ro-upload'){request=null;importRows=null;showDialog(a);}
  if(a==='ro-add-invoice'){const target=document.getElementById('ro-invoice-fields'),n=target.children.length;if(n>=100)throw Error('Maximum 100 supplier invoices per RO.');target.insertAdjacentHTML('beforeend',invoiceFields({},n));}
  if(a==='ro-doc-page'){const docs=await api('/ro-costings/documents?ro='+encodeURIComponent(cache.record.ro)+'&offset='+Number(d.offset));document.getElementById('ro-document-list').innerHTML=documents(docs);}
  if(a==='ro-export'){const r=cache.record,c=cache.cost;csv('RO-'+r.ro+'-Costings.csv',['RO','Supplier','Invoices','Goods USD','Invoice face USD',...RO_ACTUAL_FIELDS.map(k=>labels[k]),'Actual coverage','AI INR / USD','Suresh INR / USD','Status','Pending'],[[r.ro,r.supplier,r.invoices.map(i=>i.invoice).join('; '),c.goodsUsd,c.faceUsd,...RO_ACTUAL_FIELDS.map(k=>r.actuals[k]??''),r.actuals.expenseCoverage,c.rate??'',c.sureshRate??'',c.status,c.pending.join('; ')]]);}
  return true;
 }
 async function formSubmit(event){if(event.target.id!=='ro-filter')return false;const f=Object.fromEntries(new FormData(event.target));q=f.q;status=f.status;offset=0;cacheKey='';render();return true;}
 async function change(el){if(context().ui.modal!=='ro-import'||el.name!=='file')return false;importRows=null;document.getElementById('ro-import-preview').textContent='';const file=el.files[0];if(!file)return true;if(file.size>5e6)throw Error('Prepared import maximum is 5 MB.');const input=JSON.parse(await file.text());if(!Array.isArray(input.records)||!input.records.length||input.records.length>30)throw Error('Import 1–30 prepared RO records at a time.');importRows=input.records.map(e=>({record:validateRoRecord(e.record),expectedRevision:e.expectedRevision}));document.getElementById('ro-import-preview').textContent='Review '+importRows.length+' ROs: '+importRows.map(e=>e.record.ro).join(', ')+'. Existing RO versions require matching revisions.';return true;}
 return {page,modal,submit,action,formSubmit,change};
}
