import {vmsConfig,vmsAnalytics,vmsProfileSnapshot} from '../shared/vms.mjs';
import {createVmsOutbox} from './vms-outbox.mjs';

export function createVmsPages(host,utils){
 const {esc,button,field,head,ph,kpi,note,dt,badge}=host,{table,row,link,vendors,opts}=utils;
 const modules=[['dashboard','Dashboard'],['followups','Vendor Follow-up'],['vendors','Vendors'],['analytics','Analytics'],['expos','Expos & Fairs'],['products','Product Lines'],['components','Component Tags'],['risk','Sourcing Risk'],['pending','Pending Sync'],['app','Get the App'],['users','Users & Roles'],['settings','Settings']];
 const outbox=createVmsOutbox(host),ctx=host.context,manager=()=>host.canApprove(ctx().user);
 let catalog='stages';
 const current=()=>ctx().ui.vmsPage||'dashboard';
 function navigation(){return '<nav class="vms-nav" aria-label="Vendor Management modules">'+modules.map(([key,label])=>button(label,'vms-tab',{tab:key},current()===key&&!ctx().ui.orderId?'primary':'ghost')).join('')+'</nav>';}
 function header(){return head('Vendor Management (VMS)',modules.find(([key])=>key===current())?.[1]||'Settings','',manager()&&['dashboard','vendors'].includes(current())?button('Add vendor','vendor-edit',{},'primary','plus')+(current()==='vendors'?button('Vendor master / import','nav',{to:'vendors'},'ghost'):''):'')+'<div class="toolbar vms-module-toolbar">'+field('vms-module','VMS module',current(),'select',{options:modules.map(([value,label])=>({value,label})),attrs:'id="vms-module"'})+(!['pending','app','users'].includes(current())?button('Export view','vms-export',{},'small ghost','download'):'')+'</div>';}
 const labels={stages:'Vendor Stages',photoTypes:'Photo Types',classifications:'Product classifications',countries:'Countries',regions:'States / Regions',districts:'Districts / Cities',currencies:'Currency references',groups:'Product groups',products:'Product Lines',components:'Component Tags',expos:'Expos & Fairs'};
 function catalogView(kind,selector=false){const cfg=vmsConfig(ctx().state),rows=cfg[kind]||[];
  const details=t=>kind==='expos'?[t.edition,t.year,t.city,t.country,t.startDate&&dt(t.startDate),t.endDate&&dt(t.endDate)].filter(Boolean).join(' · '):kind==='products'?(cfg.groups.find(g=>g.id===t.groupId)?.name||'Ungrouped'):kind==='stages'?(t.countsInSourcing?'Counts in sourcing':'Outside sourcing pool'):kind==='currencies'?'1 '+(t.code==='CNY'?'RMB':t.code)+' = INR '+t.inrPerUnit+' · '+dt(t.rateDate):['regions','districts'].includes(kind)?cfg[kind==='regions'?'countries':'regions'].find(x=>x.id===t.parentId)?.name||'':t.description||'';
  const linked=t=>vendors().filter(v=>kind==='expos'?v.crm?.expoId===t.id:(v.crm?.[kind]||[]).includes(t.id)).length;
  return '<div class="gap"></div><div class="panel">'+ph(labels[kind]||'Catalogues','',manager()?button('Add '+(kind==='groups'?'group':'entry'),'vms-catalog-edit',{kind},'primary','plus'):'')+(selector?'<div class="toolbar">'+field('vms-catalog','Settings section',kind,'select',{options:Object.entries(labels).map(([value,label])=>({value,label})),attrs:'id="vms-catalog"'})+'</div>':'')+(kind==='currencies'?note('Optional manual reference rates for VMS only. PO/PI pricing uses its own supplier-agreed rate; these references never reprice an order.'):'')+table(['Name','Details','Availability',...(['products','components','expos'].includes(kind)?['Vendors']:[]),''],rows.map(t=>row([esc(t.name),esc(details(t)),badge(t.active===false?'Inactive':'Active'),...(['products','components','expos'].includes(kind)?[button(String(linked(t)),'vms-filter',{kind,id:t.id},'small ghost')]:[]),manager()?button('Edit','vms-catalog-edit',{kind,id:t.id},'small ghost'):''])))+'</div>';
 }
 function analytics(){const cfg=vmsConfig(ctx().state),vs=vendors(),data=vmsAnalytics(vs,cfg),bars=(rows,kind)=>table(['Name','Vendors','Coverage'],rows.map(t=>row([button(esc(t.name),'vms-filter',{kind,id:t.id},'small ghost'),t.count,'<progress aria-label="'+esc(t.name+' vendor coverage')+'" max="'+Math.max(1,vs.length)+'" value="'+t.count+'"></progress>'])));
  return '<div class="kpi-grid">'+kpi('Vendors',vs.length,'Current division','users')+kpi('Product lines',cfg.products.length,'Including inactive linked lines','box')+kpi('Component tags',cfg.components.length,'Supplier coverage','grid')+'</div>'+cfg.groups.map(g=>'<div class="panel">'+ph(esc(g.name))+bars(data.products.filter(t=>t.groupId===g.id),'products')+'</div><div class="gap"></div>').join('')+'<div class="panel">'+ph('Ungrouped product lines')+bars(data.products.filter(t=>!t.groupId),'products')+'</div><div class="gap"></div><div class="grid-two"><div class="panel">'+ph('Vendors per component')+bars(data.components,'components')+'</div><div class="panel">'+ph('Vendors per stage')+bars(data.stages,'stages')+'</div></div><div class="gap"></div><div class="panel">'+ph('Product lines per vendor')+table(['Supplier','Product lines','Components'],data.vendors.map(v=>row([link(v),v.products,v.components])))+'</div>';
 }
 function pending(){return '<div class="panel">'+ph('Pending Sync',navigator.onLine?'Non-conflicting edits sync automatically while you are signed in.':'Offline — queued edits stay on this browser.',button(outbox.isSyncing()?'Syncing…':'Sync now','vms-sync',{},'primary'))+note('Vendor profile edits and text interactions can queue from an open workspace. Attachments, new vendors, purchase approvals and payments require a connection. Keep this browser’s site data until synced.')+table(['Supplier','Change','Saved locally','Status',''],outbox.list().map(x=>row([esc(x.vendorName),x.commandType==='VMS_SAVE_PROFILE'?'Profile edit':'Interaction',dt(x.createdAt),badge(x.status,x.status==='Conflict'?'red':'amber')+'<p class="vms-wrap">'+esc(x.error)+'</p>',button('Review','vms-sync-review',{id:x.id},'small ghost')+button('Discard','vms-sync-discard',{id:x.id},'small ghost')])) )+'</div>';}
 function appView(){return '<div class="panel">'+ph('Get the App')+'<div class="panel-body">'+(outbox.canInstall()?button('Install Farming Hub','vms-install',{},'primary','download'):note('On Chrome or Edge, open the browser menu and choose Install app when available. On iPhone or iPad, use Safari → Share → Add to Home Screen.'))+'<p>Use the same Purchase login. Open VMS before going offline to queue vendor profile edits and text interactions. Reconnect while signed in to sync automatically.</p><p>Offline reload shows a reconnect screen; business records and sign-in sessions are not cached by the app. A native Android APK was not supplied with the recovered VMS source.</p></div></div>';}
 function render(tab){if(tab==='analytics')return analytics();if(tab==='pending')return pending();if(tab==='app')return appView();if(tab==='users')return host.usersPanel();if(tab==='settings'||tab==='catalog')return host.preferencesPanel()+catalogView(catalog,true);if(['expos','products','components'].includes(tab))return (tab==='products'?catalogView('groups'):'')+catalogView(tab);return null;}
 function catalogFields(d,t,cfg){let body='';if(d.kind==='products')body+=field('groupId','Product group',t.groupId||'','select',{options:opts(cfg.groups,'Ungrouped')})+field('description','Description',t.description||'','textarea');if(['regions','districts'].includes(d.kind))body+=field('parentId',d.kind==='regions'?'Country':'State / region',t.parentId||'','select',{options:opts(cfg[d.kind==='regions'?'countries':'regions']),required:true});if(d.kind==='currencies')body+=field('code','Currency',t.code||'USD','select',{options:[{value:'USD',label:'USD'},{value:'CNY',label:'RMB'},{value:'INR',label:'INR'}]})+field('inrPerUnit','INR per currency unit',t.inrPerUnit||'','number',{required:true,attrs:'min="0.000001" max="1000000" step="0.000001"'})+field('rateDate','Reference rate date',t.rateDate||host.isoDay(),'date',{required:true});return body;}
 function profileFields(c,cfg){return field('classificationId','Product classification',c.classificationId||'','select',{options:opts(cfg.classifications)})+field('countryId','Country catalogue',c.countryId||'','select',{options:opts(cfg.countries),attrs:'data-vms-location="country"'})+field('regionId','Region catalogue',c.regionId||'','select',{options:opts(cfg.regions.filter(x=>x.parentId===c.countryId)),attrs:'data-vms-location="region"'})+field('districtId','District catalogue',c.districtId||'','select',{options:opts(cfg.districts.filter(x=>x.parentId===c.regionId))});}
 function modal(type,d){if(!['vms-sync-review','vms-sync-discard'].includes(type))return null;const item=outbox.list().find(x=>x.id===d.id);if(!item)return {title:'Edit unavailable',body:'Already synced or discarded.',submit:null};const latest=vendors().find(x=>x.id===item.vendorId),current=latest?vmsProfileSnapshot(latest):{};return {title:type==='vms-sync-discard'?'Discard queued edit?':'Review queued edit',body:note(esc(item.vendorName))+(type==='vms-sync-discard'?'<p>This removes only this browser’s unsynced change. Saved server records remain.</p>':table(['Field','Current saved value','Your proposed value'],Object.keys(item.payload).filter(k=>k!=='vendorId'&&(item.commandType!=='VMS_SAVE_PROFILE'||JSON.stringify(item.payload[k])!==JSON.stringify(item.base[k]))).map(k=>row([esc(k),'<pre class="vms-wrap">'+esc(JSON.stringify(current[k]??'',null,2))+'</pre>','<pre class="vms-wrap">'+esc(JSON.stringify(item.payload[k],null,2))+'</pre>'])))),wide:true,submit:type==='vms-sync-discard'?'Discard unsynced edit':item.status==='Conflict'?'Apply my reviewed changes':'Retry sync'};}
 async function submit(type,d){if(type==='vms-sync-discard'){outbox.discard(d.id);}else if(type==='vms-sync-review'){const item=outbox.list().find(x=>x.id===d.id);if(item){const v=vendors().find(v=>v.id===item.vendorId);await outbox.retry(item.id,item.status==='Conflict'&&v?vmsProfileSnapshot(v):null);}}else return false;host.closeModal();host.render();return true;}
 async function action(a,d){if(a==='vms-export'&&['analytics','expos','products','components','settings','catalog'].includes(current())){const cfg=vmsConfig(ctx().state),kind=['settings','catalog'].includes(current())?catalog:current();if(kind==='analytics'){const data=vmsAnalytics(vendors(),cfg);host.csv('VMS-analytics.csv',['Type','Name','Vendors'],['products','components','stages'].flatMap(k=>data[k].map(t=>[k,t.name,t.count])));}else{const rows=cfg[kind],keys=[...new Set(rows.flatMap(Object.keys))];host.csv('VMS-'+kind+'.csv',keys,rows.map(t=>keys.map(k=>t[k]??'')));}}else if(a==='vms-sync')await outbox.sync();else if(a==='vms-install')await outbox.install();else if(a==='vms-sync-review'){if(navigator.onLine&&!ctx().sandbox)await host.refresh();host.showDialog(a,d);}else return false;return true;}
 function change(target){if(target.id==='vms-catalog'){catalog=target.value;host.render();return true;}if(target.dataset.vmsLocation){const form=target.form,cfg=vmsConfig(ctx().state),region=form.elements.regionId,district=form.elements.districtId,fill=(el,rows)=>{el.innerHTML=opts(rows).map(x=>'<option value="'+esc(x.value)+'">'+esc(x.label)+'</option>').join('');};if(target.dataset.vmsLocation==='country')fill(region,cfg.regions.filter(x=>x.parentId===target.value));fill(district,cfg.districts.filter(x=>x.parentId===region.value));return true;}return false;}
 return {render,navigation,header,catalogFields,profileFields,modal,submit,action,change,outbox};
}
